### ISSUE TITLE
Please add the pkg-config support

### ISSUE THREAD

**Issue by lu-zero** [Intel-Media-SDK/MediaSDK#1]
Having a pkg-config file simplifies a lot supporting in the a large number of build systems.

**Comment by amaslenn** [comment]
Are you going to integrate MediaSDK library somewhere? Could you please share where exactly? :)
Will address your request. May I ask you to review/verify implementation when it is ready?

**Comment by lu-zero** [comment]
I'm using it for [Libav](http://github.com/libav/libav) and the [rust bindings](https://github.com/rust-av/mfx_dispatch-rs), currently I'm using [this](https://github.com/lu-zero/mfx_dispatch/) packaging of it and I'd rather converge the effort on your tree instead of having to maintain it.

I can volunteer to maintain the autotools build system if it is deemed useful.

**Comment by amaslenn** [comment]
Would it be enough to add just `pkg-config` file similar to [yours](https://github.com/lu-zero/mfx_dispatch/blob/master/libmfx.pc.in) for `mfx` library, or you want fully functional `autotools` build system for entire MediaSDK?

**Comment by lu-zero** [comment]
I know that some people in distributions would welcome having the build system since it would mean less changes on their side (and autotools came since it is low impact on distributions to begin with).

Overall my packaging has those two features some want:
- autotools and bare cmake build system including pkg-config files.
- some glue-code to make the library have a default device on linux as it does on windows.

For my use cases the pkg-config file is the minimum requirement to keep my code working w/out special changes (in libav the non-minimal configuration already depends on having explicit vaapi and dx usage to enable full-hw transcoding, filters and some other interoperability).

**Comment by amaslenn** [comment]
Adding pkg-config file for `mfx` library looks reasonable.
Two build systems will create confusion and at this point doesn't provide much value.

Will you create PR for adding pkg-config file?

**Comment by lu-zero** [comment]
I do not know enough of the system to find the information needed in a minute, if you have time to do that or tell me where to find the version number, the include/libs path and link-line would be great =)

**Comment by amaslenn** [comment]
OK, I will follow up it.

**Comment by amaslenn** [comment]
@lu-zero pkg-config file (`mfx.pc`) will be like following:
```
prefix=/opt/intel/mediasdk
libdir=/opt/intel/mediasdk/lib/lin_x64
includedir=/opt/intel/mediasdk/include

Name: mfx
Description: Intel(R) Media SDK Dispatcher
Version: 1.21
Libs: -L${libdir} -lmfx
Cflags: -I${includedir}
```
File content including `prefix`, `libdir` and `includedir` will be generated by Cmake.

Does it work for you?

**Comment by amaslenn** [comment]
`mfx` itself doesn't depend on `va` (and friends :)).
