### ISSUE TITLE
vp9 hw acceleration

### ISSUE THREAD

**Issue by WeiChihChern** [Intel-Media-SDK/MediaSDK#1005]
I've implemented vp9 encoding process with ffmpeg + libvpx.   Would like to further accelerate the encoding process of vp9 (realtime encoding).

Will using Intel Media SDK require me to redesign the system that I currently have? Or would it be easier to use intel quick sync video?

**Comment by onabiull** [comment]
Media SDK is SDK which expose Quick Sync Sync video HW features to programmer. I anticipate that at most you'll need to rebuild ffmpeg with qsv support and probably adjust some command-line parameters. But you'll need Icelake system to get VP9e support. see readme in https://github.com/intel/media-driver.

**Comment by WeiChihChern** [comment]
@onabiull Thanks, looking into it.

**Comment by dmitryermilov** [comment]
ICL support VP9 encode

**Comment by syjml** [comment]
> ICL support VP9 encode

Does Ice Lake support the hardware acceleration of vp9 encoder?

**Comment by dmitryermilov** [comment]
Hi @syjml ,
yes

**Comment by syjml** [comment]
> Hi @syjml ,
> yes

Does the processor code-named Comet Lake support VP9 encoder hardware acceleration?

**Comment by dmitryermilov** [comment]
No. It's Gen9. VP9 VDEnc (aka LowPower) is not supported there.

**Comment by syjml** [comment]
> No. It's Gen9. VP9 VDEnc (aka LowPower) is not supported there.

Are you saying that the processor code-named Comet Lake does not support VP9 encoder hardware acceleration?
