### ISSUE TITLE
Possible cmake missprint

### ISSUE THREAD

**Issue by adydychk** [Intel-Media-SDK/MediaSDK#1014]
I tried to build latest MediaSDK on CentOS 7.4 **without** OpenCL and was surprised with output:

```
...
No package 'libmfx' found
Intel OpenCL SDK was not found (optional). The following will not be built: rotate_opencl plugin. <- !!!
...
Enable:
ENABLE_OPENCL : ON <- !!!
ENABLE_X11_DRI3 : OFF
ENABLE_WAYLAND : OFF
ENABLE_ITT : OFF
ENABLE_TEXTLOG : OFF
ENABLE_STAT : OFF
...
Build:
BUILD_RUNTIME : ON
BUILD_DISPATCHER : ON
BUILD_SAMPLES : ON
BUILD_TESTS : OFF
BUILD_TOOLS : OFF
BUILD_KERNELS : OFF
...
```
I surprised that cmake wrote that "OpenCL not found" (which is fully correct) but in section "Enable" I see "ENABLE_OPENCL : ON". That is very strange.
It seems that cmake has a misprint...

@onabiull Can you take a look on it? :)

**Comment by onabiull** [comment]
This option enabled by default. 
https://github.com/Intel-Media-SDK/MediaSDK/blob/f7145a6b7bbea73dc37bc0b4e7a825a1b6ccbe8d/CMakeLists.txt#L46
And thus generate error, as dependency missed.
You should explicitly turn if OFF. 
`cmake3 ../MediaSDK -DENABLE_OPENCL=OFF`

**Comment by adydychk** [comment]
Oh, thanks, understood the logic but it is unclear if the user see only only output of cmake...   
Maybe it is better to change "enable" to "Enabled project configuration (by default or parameters)"

**Comment by dvrogozh** [comment]
The plan is to use the rule for all the enable options: if option is explicitly enabled and required prerequisites are missing - error out. This behavior was not simply yet implemented for OCL.
