### ISSUE TITLE
HEVCe: replacing macro MFX_DESTROY_VABUFFER to function CheckAndDestroyVAbuffer

### ISSUE THREAD

**Issue by dmenshov** [Intel-Media-SDK/MediaSDK#1065]

**Comment by mgonchar** [comment]
Mostly it means changing ```MFX_DESTROY_VABUFFER``` macro to something like https://github.com/Intel-Media-SDK/MediaSDK/blob/master/_studio/mfx_lib/shared/include/mfx_h264_encode_vaapi.h#L53 The main issue - absence of returned from ```vaDestroyBuffer``` status check

**Comment by DenWolf** [comment]
Agree with @mgonchar - this replacing macro without checking returning status to function with checking returning status - as already presented in AVCe, word "Refactoring" is very strong and loud for this task, so I suggest to rename the issue

**Comment by dmenshov** [comment]
[PR#1084](https://github.com/Intel-Media-SDK/MediaSDK/pull/1084) is on review
