### ISSUE TITLE
Is there a way of decoding only I-frames for h.264 

### ISSUE THREAD

**Issue by boxerab** [Intel-Media-SDK/MediaSDK#1069]

**Comment by dmitryermilov** [comment]
You can leverage SetSkipMode API function:
**Description**
> This function sets the decoder skip mode. The application may use it to increase decoding performance by sacrificing output quality. The rising of skip level firstly results in skipping of some decoding  operations like deblocking and then leads to frame skipping; firstly, B then P. Particular details are platform dependent.

**Comment by artem-shaporenko** [comment]
Right, but noticeable moment - it doesn't allow you to control skipped steps, so for example if you want to skip all frames except I, but want to kip deblocking - it won't allow you to perform right way, we are working on new functionality to allow skip level selection
