### ISSUE TITLE
[gstreamer-msdk][avc encode cbr]the encode file has garbage and mosaic with low bitrate

### ISSUE THREAD

**Issue by wangzj0601** [Intel-Media-SDK/MediaSDK#1076]
System Environment
=======
Platform: KBL
Arch: x86_64
Kernel: 4.18.0+
libva commit 566a1388b4e5961fb73d0fd03058d50c5965a7f4

media_driver commit 8968471978818839fed845ce918843a9ef3210c9

mediasdk commit 750cfb4776023fb5a9b2481c1bf1956ab5568651

gstreamer master branch 74b9e72ec6b0963661c5c370e634f6fc9444057f

repo: https://gitlab.freedesktop.org/gstreamer/gstreamer.git

gst-plugin-bad commit 2f05ee9ba9a7bbdde761c8da1fe330a58b1c4687

repo: https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad.git

Regression?
=======

Bug detailed description 
=======

the encoded file has garbage and mosaic with low bitrate

Reproduce Steps
==============
1. build enc as above lists
2. gst-launch-1.0 -vf filesrc location=/media_stream/assets/yuv/MOBILE_352x288_30_orig_01_352x288_I420.yuv num-buffers=300 ! rawvideoparse format=i420 width=352 height=288 framerate=25 ! videoconvert ! video/x-raw,format=NV12 ! msdkh264enc rate-control=cbr bitrate=100 gop-size=12 num-slices=1 b-frames=0 hardware=true ! video/x-h264,profile=main ! h264parse ! filesink location=./test.h264
3.  gst-launch-1.0 -vf filesrc location=./test.h264 ! h264parse ! msdkh264dec hardware=true ! videoconvert ! ximagesink

some failed cases:

"test/gst-msdk/encode/avc.py:test_cbr(bframes=0,bitrate=100,case=mobile,fps=25,gop=12,profile=high,slices=1)": {
"test/gst-msdk/encode/avc.py:test_cbr(bframes=0,bitrate=100,case=mobile,fps=25,gop=12,profile=high,slices=4)": {
"test/gst-msdk/encode/avc.py:test_cbr(bframes=0,bitrate=100,case=mobile,fps=25,gop=12,profile=main,slices=1)": {
"test/gst-msdk/encode/avc.py:test_cbr(bframes=0,bitrate=100,case=mobile,fps=25,gop=12,profile=main,slices=4)": {
"test/gst-msdk/encode/avc.py:test_cbr(bframes=0,bitrate=100,case=mobile,fps=25,gop=30,profile=high,slices=1)": {
"test/gst-msdk/encode/avc.py:test_cbr(bframes=0,bitrate=100,case=mobile,fps=25,gop=30,profile=high,slices=4)": {
"test/gst-msdk/encode/avc.py:test_cbr(bframes=0,bitrate=100,case=mobile,fps=25,gop=30,profile=main,slices=1)": {

test/gst-msdk/encode/avc.py:test_cbr(bframes=3,bitrate=150,case=mobile,fps=25,gop=12,profile=high,slices=1)": {
"test/gst-msdk/encode/avc.py:test_cbr(bframes=3,bitrate=150,case=mobile,fps=25,gop=12,profile=high,slices=4)": {
"test/gst-msdk/encode/avc.py:test_cbr(bframes=3,bitrate=150,case=mobile,fps=25,gop=12,profile=main,slices=1)": {
"test/gst-msdk/encode/avc.py:test_cbr(bframes=3,bitrate=150,case=mobile,fps=25,gop=12,profile=main,slices=4)": {
"test/gst-msdk/encode/avc.py:test_cbr(bframes=3,bitrate=150,case=soccer,fps=25,gop=12,profile=high,slices=1)": {
"test/gst-msdk/encode/avc.py:test_cbr(bframes=3,bitrate=150,case=soccer,fps=25,gop=12,profile=main,slices=1)": {
"test/gst-msdk/encode/avc.py:test_cbr(bframes=3,bitrate=150,case=soccer,fps=25,gop=30,profile=high,slices=1)": {
"test/gst-msdk/encode/avc.py:test_cbr(bframes=3,bitrate=150,case=soccer,fps=25,gop=30,profile=main,slices=1)": {

Expected Result
=============
can view the content of the picture clearly at low bitrate.

Actual Result
===========
the encoded file has garbage and mosaic with low bitrate

**Comment by wangzj0601** [comment]
use sample_encode instead of gst-msdk, this issue also can be duplicated.

cmdline as below:

sample_encode h264 -i /media_stream/assets/yuv/MOBILE_352x288_30_orig_01_352x288_I420.yuv -o ./test.h264 -w 352 -h 288 -n 300 -f 25 -nv12 -cbr -b 100 -g 12 -num_slice 1 -r 1 -CodecProfile 77 -hw

**Comment by egorovdanil** [comment]
I-frames are difficult to encode, so when using a low bitrate in combination with a small gop size, the dynamic stream will look like this. I tried to increase the gop size to 150 and the stream became much better without increasing the output stream size much.

**Comment by daleksan** [comment]
Hi @wangzj0601 approach suggested by @egorovdanil is suitable for you?
