### ISSUE TITLE
i7-8559U MaxSliceSize problem

### ISSUE THREAD

**Issue by Warpmh** [Intel-Media-SDK/MediaSDK#1077]
Hi,

I have problem on i7-8559U with max slice size option(ctx->m_coding_option2.MaxSliceSize = 1000;) MFXVideoENCODE_Query return MFX_ERR_UNSUPPORTED. Same configuration work fine on i7-8700k. Where can be problem? That cpu really not supported that parameter or need update drivers?

Best Regards,
Alexey.

**Comment by onabiull** [comment]
Could you please check if #1088 fix the issue? Looks like device id for i7-8559U was missed from our whitelist.

**Comment by Warpmh** [comment]
Thanks. Will try later.
