### ISSUE TITLE
field_copy: stale shader in the msdk sources

### ISSUE THREAD

**Issue by dvrogozh** [Intel-Media-SDK/MediaSDK#1098]
https://github.com/Intel-Media-SDK/MediaSDK/blob/5b266943cf274c0540f5e6a6b90674d1a3277f3c/_studio/mfx_lib/genx/field_copy/isa/genx_fcopy_cmcode_isa.cpp#L21

**Comment by dvrogozh** [comment]
```
# ls -1 *.cpp
genx_fcopy_cmcode_isa.cpp
genx_fcopy_gen10_isa.cpp
genx_fcopy_gen11_isa.cpp
genx_fcopy_gen11lp_isa.cpp
genx_fcopy_gen7_5_isa.cpp
genx_fcopy_gen8_isa.cpp
genx_fcopy_gen9_isa.cpp
```

@onabiull : let's decide whether we keep gen7_5 or consider it a stale one as well. If we keep it, we need a build support of it as well.

**Comment by onabiull** [comment]
I'd prefer to remove it.

**Comment by dvrogozh** [comment]
@dsoroki: please, consider gen7_5 as a stale kernel as well. Remove it.

**Comment by dvrogozh** [comment]
Partially fixed by: https://github.com/Intel-Media-SDK/MediaSDK/pull/1097 (genx_fcopy_gen7_5_isa.cpp removed).
