### ISSUE TITLE
Deinterlacing output framerate: Clarification needed 

### ISSUE THREAD

**Issue by sreerenjb** [Intel-Media-SDK/MediaSDK#111]
If I understood correctly BOB and Advanced deinterlace should double the framerate and weave should just keep the same framerate.
Q1)  Is that the expected output for MediaSDK deinterlace?
Q2)  Does the user-space suppose to provide "mfxExtVPPFrameRateConversion" in order to double the framerate after deinterlacing?

**Comment by dmitryermilov** [comment]
Right, there are two modes for Bob and Advanced DI:
* Xi->Xp
* Xi->2Xp

where X is some framerate like 30 or 29,97.

A decision which mode to use is done based on difference between par->In.FrameRateExtN/par->In.FrameRateExtD and par->out.FrameRateExtN/par->out.FrameRateExtD. 
mfxExtVPPFrameRateConversion is not necessary.

**Comment by sreerenjb** [comment]
Do those two modes only available for BOB and ADI? 
Usually, BOB double the fps (I mean, input field rate == output frame rate), Does the first mode(Xi->Xp) just drop the frames? 
How about other modes of deinterlacing; Does the Field Weave only support the same frame-rate at i/p and o/p?

One more question: Does the FrameRate conversion is implemented in software? If so, it will impact the deinterlace performance, isn't it?

**Comment by Jister** [comment]
Yes, Xi->Xp and Xi->2Xp only available for BOB and ADI. Xi->Xp mode just drop one of the field. Both of these two modes are done by HW, so i think there should be no performance issue. For Field Weave, the input is provided field by field, and two separate fields will be weaved into one interleaved frame.

**Comment by FurongZhang** [comment]
Since we have clarified this issue and no further questions/opens, close it.

**Comment by FurongZhang** [comment]
Please feel free to open it if any more further questions.
