### ISSUE TITLE
SKL HEVC 10-bit Decode

### ISSUE THREAD

**Issue by shtirlic** [Intel-Media-SDK/MediaSDK#1112]
Hi, on the Intel forum I found the answer that HEVC 10-bit should work on Intel E3-1585L v5 with C236 
by  Artem S. (Intel) https://software.intel.com/en-us/forums/intel-media-sdk/topic/737824

> Any Skylake based processor with integrated graphics support hardware accelerated HEVC encode, e.g. any Intel(R) Xeon Processor E3-15* v5 any 6th generation Intel Core, So if your target OS is windows - MSS will work at any of them. Linux is limited almost to Xeon only(validated).Please note that to get integrated graphics support with Xeon Processors you need specific C236 chipset, so pay attention to the motherboard specs. KBL processors(e.g 7th Generation Core) supports 10 bit HW accelerated encode.

As I see in my `vainfo` there is no VAProfileHEVCMain10 in features:

```shell
/opt/intel/mediasdk/bin/vainfo --display drm
libva info: VA-API version 1.3.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /opt/intel/mediasdk/lib64/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_3
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.3 (libva 2.3.0)
vainfo: Driver version: Intel iHD driver - 16.9.git_00f9ae_2018-10-01
vainfo: Supported profile and entrypoints
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileNone                   :	VAEntrypointStats
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointFEI
      VAProfileH264Main               :	VAEntrypointEncSliceLP
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointFEI
      VAProfileH264High               :	VAEntrypointEncSliceLP
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointFEI
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointFEI`
```
CPU: Intel(R) Xeon(R) CPU E3-1585L v5
Server: HPE ProLiant m710x Server Cartridge with C236 chipset

Also I see in media driver features in https://github.com/intel/media-driver/blob/master/media_driver/linux/gen9/ddi/media_sku_wa_g9.cpp#L35
There is no `  .hevc10Decoding     = 1,` for SKL

What is the correct information about the state of Hardware/GPU SKL 10bit HEVC Decoding?

**Comment by eero-t** [comment]
This is issue tracker for MediaSDK, not for the underlying media HW driver / libva backend: https://github.com/intel/media-driver/

(According to table on that page, driver supports 8bit HEVC encoding from SKL forward, 10bit from CNL forward, but as you noticed from the sources, it can encode 10bit HEVC already on KBL.  I just checked that it works without giving any errors.)

**Comment by shtirlic** [comment]
Actually I am interested only in decoding 10 bit HEVC myabe it's possible on SLK with GPU accelerated?

**Comment by artem-shaporenko** [comment]
Hi @shtirlic, no, it is not possible to get gpu accelerated decoding on SKL processor, only starting KBL. There is support for GPU accelerated decoding(auto enabled) on windows, but not recommended to use due to big number of stability issues.

**Comment by shtirlic** [comment]
Thx for the info, closing this.
