### ISSUE TITLE
Query: Confirm support for Intel's VCA

### ISSUE THREAD

**Issue by Brainiarc7** [Intel-Media-SDK/MediaSDK#1136]
Hello there,

I came across this kit, the Intel Visual Computing Accelerator: https://ark.intel.com/products/98092/Intel-Visual-Compute-Accelerator-VCA1585LMV

Whose specifications are as shown in the link above.

Is this SKU supported by this version of the Media SDK?

From the product brief, its' composed of three Skylake-based mobile Xeon E3 1585L v5s: https://en.wikichip.org/wiki/intel/xeon_e3/e3-1585l_v5

**Comment by dmitryermilov** [comment]
Hello,

It's supported.

**Comment by Brainiarc7** [comment]
Thank you.
I'll be building a test bed solution based on the above implementation.

**Comment by dmitryermilov** [comment]
You're welcome.
