### ISSUE TITLE
build error on 32bit

### ISSUE THREAD

**Issue by tjaalton** [Intel-Media-SDK/MediaSDK#1195]
fails to build on i386, full log here:
https://launchpad.net/~canonical-x/+archive/ubuntu/x-staging/+build/16387424

the failing part:
cd /<<PKGBUILDDIR>>/build/samples/sample_common && /usr/bin/c++  -DLINUX -DLINUX32 -DMFX_FILE_VERSION=\"0.19.2.13\" -DMFX_PRODUCT_VERSION=\"0.0.000.0000\" -DMSDK_BUILD=\"\" -DUNIX -D_FILE_OFFSET_BITS=64 -D__USE_LARGEFILE64 -I/<<PKGBUILDDIR>>/api/mediasdk_structures -I/<<PKGBUILDDIR>>/api/include -I/<<PKGBUILDDIR>>/build -I/<<PKGBUILDDIR>>/samples/sample_common/include -I/<<PKGBUILDDIR>>/samples/sample_common/../sample_misc/wayland/include  -DMFX_TRACE_ENABLE_STAT -DMFX_TRACE_ENABLE_TEXTLOG -msse4.2 -std=c++11 -m32 -g -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -pipe -fPIC -Wall -Wformat -Wformat-security -Wnon-virtual-dtor -Wno-deprecated-declarations -Wno-unknown-pragmas -Wno-unused   -I/usr/include/libdrm     -DMFX_VA -DLIBVA_SUPPORT -DLIBVA_DRM_SUPPORT -DLIBVA_X11_SUPPORT   -I/usr/include/libdrm    -DLIBVA_SUPPORT -DLIBVA_DRM_SUPPORT -DLIBVA_X11_SUPPORT  -DX11_DRI3_SUPPORT -DLIBVA_WAYLAND_SUPPORT -fno-devirtualize-speculatively  -o CMakeFiles/sample_common.dir/src/vaapi_utils_drm.cpp.o -c /<<PKGBUILDDIR>>/samples/sample_common/src/vaapi_utils_drm.cpp
/<<PKGBUILDDIR>>/samples/sample_common/src/vaapi_utils.cpp: In member function ‘VAStatus CLibVA::AcquireVASurface(void**, VADisplay, VASurfaceID, VADisplay, VASurfaceID*)’:
/<<PKGBUILDDIR>>/samples/sample_common/src/vaapi_utils.cpp:386:22: error: invalid conversion from ‘long unsigned int*’ to ‘uintptr_t*’ {aka ‘unsigned int*’} [-fpermissive]
     extsrf.buffers = &handle;
                      ^~~~~~~
make[3]: *** [samples/sample_common/CMakeFiles/sample_common.dir/build.make:313: samples/sample_common/CMakeFiles/sample_common.dir/src/vaapi_utils.cpp.o] Error 1

**Comment by dvrogozh** [comment]
I believe we have fixed 32-bit build those few months ago. And we have clarified that 64-bit configuration is the only one fully supported: https://github.com/Intel-Media-SDK/MediaSDK#system-requirements. I am closing the bug and let us know if there are any other build issues and/or 32-bit configuration is anywhere required for Linux.
