### ISSUE TITLE
[KBL] VPP mirroring: segmentation fault  in ffmpeg-qsv

### ISSUE THREAD

**Issue by fulinjie** [Intel-Media-SDK/MediaSDK#1223]
Segmentation fault happens while enabling QSV mirror, and it happens in Video memory -> Sys memory:

Reproduce:
1. apply the qsv transpose patch:
https://github.com/intel-media-ci/ffmpeg/pull/23
2. cmdline:
ffmpeg -init_hw_device qsv=foo -filter_hw_device foo -v verbose -f rawvideo -pix_fmt nv12 -s:v 384x288 -i ./input.yuv -vf 'hwupload=extra_hw_frames=64,format=qsv,vpp_qsv=mirror=1' -f rawvideo -pix_fmt nv12 -an -vframes 5 -y ./transpose.yuv
3. error message:
rotation works, but mirror causes segmentation fault, gdb shows various results during the experiments
corrupted size vs. prev_size or invalid chunk size, or normal memory issue message.

Experimental info:
1. it happens when the mirroring.position == MIRROR_OUTPUT,:

if I use Video memory -> Video memory, by using qsv transcoding pipeline:
ffmpeg  -hwaccel qsv -v verbose -c:v h264_qsv -i input.h264 -vf 'format=qsv,vpp_qsv=mirror=1' -c:v h264_qsv -vframes 50 out.h264
Mirroring VPP works.
or modify the mirroringPosition:
case MFX_IOPATTERN_IN_VIDEO_MEMORY  | MFX_IOPATTERN_OUT_SYSTEM_MEMORY:
executeParams.mirroringPosition = MIRROR_WO_EXEC;

The pipeline works and generates correct output.

2. It was caused by EnqueueCopyMirrorNV12GPUtoCPU:
https://github.com/Intel-Media-SDK/MediaSDK/blob/b63529b39796e13614e16455f16a92491e2d09cb/_studio/shared/src/cm_mem_copy.cpp#L3011
If i  return MFX_ERR_NONE directly, the segmentation fault is gone. 

3. sample_vpp works on video->sys mem situation, but it doesn't act the same way like ffmpeg-qsv vpp:
absence of a hwupload thread (SYS_TO_D3D == m_ioMode).

Summary:
Segmentation issue is caused by VPP Mirroring (D3D_TO_SYS) together with hwupload (SYS_TO_D3D), and I suspect maybe it's something to do with the multi-thread (I tried to set scheduler-locking to trace this issue, but it happens when one thread task is all finished and jump to another.)

**Comment by dvrogozh** [comment]
SIGBUS happens. Indeed it will go away if EnqueueCopyMirrorNV12GPUtoCPU() will be commented out.

I don't think that this is mediasdk issue. Issue is in ffmpeg which allocates output system memory non-continuously. Mediasdk then calls CMRT to copy from video to system memory, but CMRT requires memory to be continuously allocated across Y and UV. So, you need to make a patch to ffmpeg similar to this one: https://github.com/FFmpeg/FFmpeg/commit/325aa63dd1a3abc2453914d0bc111d297833d725. However, I would recommend to try avoid memory copy and allocate output memory correctly right away. @fulinjie : can you, please, make a change?

@onabiull : can we, please, introduce a change to mediasdk which will check whether memory is allocated correctly to prevent SIGBUS and simply error out? This will save a lot of time debugging such issues.

**Comment by lizhong1008** [comment]
@dvrogozh , you are correct, currently ffmpeg can't make sure memory continuously for NV12. 
There are too solutions:
1. Apply a similar fix as FFmpeg/FFmpeg@325aa63 to ffmpeg-qsv vpp. But this the best solution.
2. Allocate a continuous memory at the beginning of frame allocation for NV12 (P010 should be same I believe).   Thus is not only required for Intel HW, MSDK or iHD driver, but also a part of spec definition:  see : https://www.fourcc.org/pixel-format/yuv-nv12/, 
 "A format in which all Y samples are found first in memory as an array of unsigned char with an even number of lines (possibly with a larger stride for memory alignment), **followed immediately** by an array of unsigned char containing interleaved Cb and Cr samples (such that if addressed as a little-endian WORD type, Cb would be in the LSBs and Cr would be in the MSBs) with the same total stride as the Y samples. This is the preferred 4:2:0 pixel format."

**Comment by fulinjie** [comment]
@dvrogozh thanks, it's true that segmentation fault was caused by non-continuously allocated system memory. And I work out a patch to allocate output memory continuously if out memory mode is sysem memory in QSV VPP:
https://github.com/intel-media-ci/ffmpeg/pull/25
And it fixes this issue.
@lizhong1008 will it be more acceptable for community to allocate continuous memory just in QSV?

**Comment by ruiling** [comment]
I think the restriction should come from CMRT software, right? i don't think GPU hardware have such kind of requirement. can we ask CMRT to remove such kind of restriction in the future? Now that FFmpeg allocate like this, I think most people just think Y and UV are separate planes. It's better we could allow users allocating these two planes separately and can still benefit from hardware accelerated copy.

**Comment by fulinjie** [comment]
Hi @dvrogozh ,

I'm thinking of eliminate the gap for memory allocation between ffmpeg and MSDK:
- ffmpeg allocate surface memory separately for each plane, and it's a common usage for each filter/decoder/encoder. 
- MSDK requires memory to be continuous between Y and UV.

If we have to modify this in ffmpeg side to suite the constraints in MSDK, memory reallocate is required, and it does harm to the performance.

Another way we could have a try in ffmpeg is to fake NV12 surface into two single plane surface (8bit MFX_FOUCC_P8) and call Cm copy twice. 
But it seems to be a work around solution more likely.


I checked the code and found that padding is allowed in Cm kernel:
height_stride is calculated by  the offset of mfxFrameSurface1::Data::Y and mfxFrameSurface1::Data::UV,
And i guess padding is allowed and offset is taken into consideration for Cm kernel.

But in CanUseCmCopy:
https://github.com/Intel-Media-SDK/MediaSDK/blob/563aea228ac4738f06c64ec1859c0dcddd2a1136/_studio/shared/src/cm_mem_copy.cpp#L3171
when Padding % pSrc->Data.Pitch == 0, cm_copy is allowed, too.


I'm not quite familiar with the MSDK code, would you please offer some advice on possible solutions in MSDK to get rid off the continuous memory constraint?

Thanks in advance.

**Comment by dmitryermilov** [comment]
@fulinjie , is it still actual? I know this commit https://github.com/FFmpeg/FFmpeg/commit/5345965b3f088ad5acd5151bec421c97470675a4 might have fixed the issue.

**Comment by fulinjie** [comment]
Hi, @dmitryermilov , I believe not.
IIRC, this patch is to fix the the continuous memory allocation issue:
https://patchwork.ffmpeg.org/patch/13594/

**Comment by dmitryermilov** [comment]
Great. Thank you!

**Comment by fulinjie** [comment]
FYI, it's not merged into ffmpeg mainline yet.
