### ISSUE TITLE
6% drop in MediaSDK AVC transcode performance on GEN8/9 Core devices

### ISSUE THREAD

**Issue by eero-t** [Intel-Media-SDK/MediaSDK#1232]
Test setup:
* drm-tip v4.19 kernel
* Git versions of the libva, gmmlib, media-driver and mediasdk
* GEN8/9 Core device

*Summary*

There's 4-6% performance drop in single- and multi-process AVC transcoding with MediaSDK between following commits:
* 2019-01-16 17-53-01 0554371c8d07ba7f  Clean up obsololete code from LA kernels(failing kernels build)
* 2019-01-17 17-29-07 22c5f65acab544e5  genx/la: add kernels build support

How to reproduce:
* ffmpeg -hwaccel qsv -qsv_device /dev/dri/renderD128 -c:v h264_qsv -i 1280x720p_29.97_10mb_h264_cabac.264 -c:v h264_qsv -b:v 2000K -compression_level 4 0027_HD20_1.0.h264
* ffmpeg -hwaccel qsv -qsv_device /dev/dri/renderD128 -c:v h264_qsv -i 720x480p_30.00_4mb_h264_cabac_180s.264 -c:v h264_qsv -b:v 2000K -compression_level 4 0038_SD03_1.0.h264

I've isolated the regression to the libmfxhw64.so.1.28 library, switching between old and new versions of that changes the performance.

Regression is visible in all BDW, SKL, KBL and CFL devices I've tested.  Slightly more in GT3e, than in GT2 devices.  It's not visible on BXT/APL (too much variance).

Of the few other tests we run, during same time frame there's also ~1% improvement on GT3/GT4 devices (but not on GT2 ones) in *multi-process* performance of following (but not with single stream/process):
* ffmpeg -hwaccel qsv -qsv_device /dev/dri/renderD128 -c:v mpeg2_qsv -i 1920x1080i_29.97_20mb_mpeg2_high.mpv -c:v h264_qsv -low_power 1 -qscale:v 26 -compression_level 7 0024_HD17i7_1.0.h264

There was no change in PSNR / SSIM in the above listed tests.

**Comment by dvrogozh** [comment]
History between these commits is:
```
22c5f65 genx/la: add kernels build support
0b0b0b8 [AVCe] Fix for SW BRC Reset, LA Bpyr is on
58835b0 [AVCe] Fix for slice header packing
d537b27 vp8d: Fixed incorrect computation of 1st partition size
919418e Fix CODEOWNERS for hevc component
afea2a0 mjpege: drop unused code
0d6f30b vp8: Fixed vp8 playback
99743da h264e: Rework check MaxFrameSize
9b5e8d9 genx: simplify cmc and GenX_IR detection
5977d41 genx: fix typo in add_cmc_target
72124fd [VPP] depricated platfrorm-dependent code removed
ae8f993 [VPP] Format for YUV2 and UYVY was enabled.
6bfbcb0 Remove vm_mutex at all
3e1989a clExtTasks: remove vm_mutex
0554371 Clean up obsololete code from LA kernels(failing kernels build)
```

Suspicious commit would be this one: "0b0b0b8 [AVCe] Fix for SW BRC Reset, LA Bpyr is on". But in this case we could improve quality which came with the dropped performance. @eero-t: can you, please, try further bisect?

**Comment by eero-t** [comment]
Ok.  Are you able to reproduce the drop between these commits in your setup?

Note that these are results with power management enabled, I don't use fixed GPU or CPU frequencies (because I'm tracking separately both kernel and media stack changes, and I want to see also impact of CPU vs GPU usage changes with power management, TDP limits etc).   There were no noticeable changes in CPU or GPU power usage (as reported by RAPL). Kernel used in tests is drm-tip v4.19.

Also, that drop is visible only when using MediaSDK with FFmpeg, I don't see a drop in any of the tests when doing them through MediaSDK sample application, e.g:
* sample_multi_transcode -i::h264 1280x720p_29.97_10mb_h264_cabac.264 -o::h264 0027_HD20_1.0.h264 -b 2000 -u 4 -n 1200 -async 1 -hw
* sample_multi_transcode -i::h264 720x480p_30.00_4mb_h264_cabac_180s.264 -o::h264 0038_SD03_1.0.h264 -b 2000 -u 4 -n 1200  -async 1 -hw

(FFmpeg QSV has nearly 2x perf in single stream/process case than sample app, but about same in multiprocess case, former is due to power management.   For MSDK, I have also data with drm-tip git head, that combo didn't show changes either.)

Any idea why / what differs between how sample app and FFmpeg QSV backend use MediaSDK in these test-cases?

PS: there's even larger regression in FFmpeg VAAPI handling, few days after this: https://trac.ffmpeg.org/ticket/7706

**Comment by dvrogozh** [comment]
> Are you able to reproduce the drop between these commits in your setup?

I did not try yet. 0b0b0b8 commit is a guess looking into the history.

> Any idea why / what differs between how sample app and FFmpeg QSV backend use MediaSDK in these test-cases?

1. Async depth differs for sure. You run smt with `-async 1` and I believe that ffmpeg-qsv uses async=4 by default. This most definitively will give better performance on single stream, but will behave approximately the same on multistreams since here you naturally have parallel tasks to execute without any async. For this reason, on multistreams it is usually better to force -async 1 since this allow to save some memory. ffmpeg-qsv should have such option as well, I think it is called -async_depth - check help, please.
2. I was just noted that ffmpeg-qsv enables look ahead by default (I did not know that). If that's so, this probably explains why you don't see perf. drop on smt which don't have look ahead by default. You can try to force disable la in ffmpeg-qsv and try again on same commits.

**Comment by lizhong1008** [comment]
> 1. Async depth differs for sure. You run smt with `-async 1` and I believe that ffmpeg-qsv uses async=4 by default. This most definitively will give better performance on single stream, but will behave approximately the same on multistreams since here you naturally have parallel tasks to execute without any async. For this reason, on multistreams it is usually better to force -async 1 since this allow to save some memory. ffmpeg-qsv should have such option as well, I think it is called -async_depth - check help, please.

Thus correct.  ffmpeg-qsv default async_depth is 4. and you can use option  -async_depth to specify another you want.  IMHO,  would better to set async_depth=4  for sample_decode too. 

>I was just noted that ffmpeg-qsv enables look ahead by default (I did not know that). If that's so, this probably explains why you don't see perf. drop on smt which don't have look ahead by default. You can try to force disable la in ffmpeg-qsv and try again on same commits.
 
Thus not true, look_ahead is disabled now by default (see https://patchwork.ffmpeg.org/patch/7771/).

**Comment by eero-t** [comment]
Perf bisected:
* 0b0b0b8 [AVCe] Fix for SW BRC Reset, LA Bpyr is on => BAD
* 58835b0 [AVCe] Fix for slice header packing => GOOD

=> As you expected, 0b0b0b8 was the commit regressing perf

I'll try async_depth next, to see whether I can reproduce the drop also with sample_multi_transcode.

**Comment by eero-t** [comment]
"-async 4" option doubles single process/stream performance for the HD20 case.  With multi-process, perf is about same as with "-async 1"  => I will switch our test-cases to "-async 4".

However, I'm not seeing the regression with sample_multi_transcode even when using "-async 4":
* sample_multi_transcode -i::h264 1280x720p_29.97_10mb_h264_cabac.264 -o::h264 0027_HD20_1.0.h264 -b 2000 -u 4 -n 2400 -async 4 -hw

Any other ideas what could cause the difference between FFmpeg QSV and that?

**Comment by eero-t** [comment]
Closing this as:
* Regressing commit was a fix for some issue ("Fix for SW BRC Reset, LA Bpyr is on")
* Issue isn't visible with MSDK samples when using async option, only with FFmpeg
* In multi-process case kernel was scheduling things badly, so multi-process results were not reliable (calculating the results wasn't then as good either), only single process ones
* No action/interest in the bug for >1/2 year
