### ISSUE TITLE
Whether the MediaSDK support FFmpeg3.3.9？

### ISSUE THREAD

**Issue by MrCool1508** [Intel-Media-SDK/MediaSDK#1243]
Hello,

My CPU is Intel Pentium GT4400T.

I have downloaded Media Server Studio SDK2018Production 16.9, and completed installed. The sample test also has passed. I followed "Intel Quick Sync Video and FFmpeg Installation and Validation Guide" to install  FFmpeg3.3.9. 

All configuration I have checked are right. And FFmpeg installation was successed. I'm sure that because of using command "ffmpeg -codecs | grep 'qsv'"  has the right result. And then, I used the comand 'ffmpeg -i input.mp4 -vcodec h264_qsv out_qsv.mp4' as "Intel Quick Sync Video and FFmpeg Installation and Validation Guide" wrote, always got the error like: “Selected ratecontrol mode is not supported by the QSV run time. Choose a different mode. Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height”.
I have looked up many solutions but have none can help.

Whether the MediaSDK support FFmpeg3.3.9??

**Comment by AntonGrishin** [comment]
Hi @MrCool1508,
AFAIK, FFmpeg runs with a bit more complexity cmd - you can check it here: [Build and use FFmpeg with MediaSDK
](https://github.com/Intel-Media-SDK/MediaSDK/wiki/Build-and-use-ffmpeg-with-MediaSDK)

BTW, you also can find more examples on [FFmpeg QSV wiki page](https://trac.ffmpeg.org/wiki/Hardware/QuickSync)
