### ISSUE TITLE
sample_vpp doesn't support ayuv on Linux

### ISSUE THREAD

**Issue by xhaihao** [Intel-Media-SDK/MediaSDK#1258]
MediSDK (master): a1c009490ec5a64da4097aac82780cdef9af4e58
media-driver (master): ceb486ff396869f3f30118f652eeb754363baf4d
gmmlib (master): ac68e2cebf9774b17bc8a4057d30959117222127
libva (2.4.0):  25b33076849e68bebae87771fb482c5ab929e18b

Command line:
/usr/share/mfx/samples/sample_vpp -lib hw  -sw 352 -sh 288 -scc nv12 -dcc ayuv -i input.nv12.352x288.yuv -o output.yuv

Error message:
[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), InitMemoryAllocator, pProcessor->pmfxVPP->Query failed at /home/xhh/graphics/ex/gstreamer/MediaSDK/samples/sample_vpp/src/sample_vpp_utils.cpp:643

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), InitResources, InitMemoryAllocator failed at /home/xhh/graphics/ex/gstreamer/MediaSDK/samples/sample_vpp/src/sample_vpp_utils.cpp:690

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), main, InitResources failed at /home/xhh/graphics/ex/gstreamer/MediaSDK/samples/sample_vpp/src/sample_vpp.cpp:532

**Comment by dvrogozh** [comment]
Did https://github.com/Intel-Media-SDK/MediaSDK/pull/1259 fixed that?

**Comment by xhaihao** [comment]
Yes. https://github.com/Intel-Media-SDK/MediaSDK/pull/1259 fixed this issue, I forgot to mention it in the commit log.
