### ISSUE TITLE
VP9 decoder reports resolution change differently than avc,hevc decoders

### ISSUE THREAD

**Issue by dulayev** [Intel-Media-SDK/MediaSDK#1260]
VP9 decoder returned MFX_ERR_INCOMPATIBLE_VIDEO_PARAM on decreasing resolution before the change:
https://github.com/Intel-Media-SDK/MediaSDK/commit/98ccf9044d8d66b6d18f7180faacfa22a4669291
It returns MFX_ERR_NONE now.

From the one side this change is interesting and good since it performs to avoid some operations which are usually done by application on resolution change, like Reset. However, concerns are:
1. You have changed behavior of VP9 decoder, other decoders still return MFX_ERR_INCOMPATIBLE_VIDEO_PARAM. It is not correct thing to do to step into different behavior on the same operation from different codecs 
2. Why MFX_WRN_INCOMPATIBLE_PARAM was not returned?

**Comment by dmitry-gurulev** [comment]
>other decoders still return MFX_ERR_INCOMPATIBLE_VIDEO_PARAM
They shouldn't. Could u please share a stream w/ such behavior?

**Comment by dulayev** [comment]
Sure, 
[stream_nv12_352x288_176x144.h264.zip](https://github.com/Intel-Media-SDK/MediaSDK/files/2965783/stream_nv12_352x288_176x144.h264.zip)
And I forgot to mention that discussed behavior takes place on Android.

**Comment by dmitry-gurulev** [comment]
@dulayev, thanks, you're right. Need to adjust VP9 decoder behavior when DRC is turned off.

**Comment by Gvence** [comment]
I tried  VP9 / h264 DRC cases (included Dulayev's case)  I found it has same behavior. All return ERROR: MFX_ERR_NONE != MFX_ERR_INCOMPATIBLE_VIDEO_PARAM.  I think there is no this issue in recently MSDK

**Comment by wangyan-intel** [comment]
@dulayev Based on @Gvence's comments, this issue is gone. I will close it. If you still have this issue, feel free to reopen it. Thanks.
