### ISSUE TITLE
allow build with system gtest

### ISSUE THREAD

**Issue by tjaalton** [Intel-Media-SDK/MediaSDK#1285]
It seems the embedded copy of googletest is built if tests are enabled, please allow using gtest from the system.

**Comment by onabiull** [comment]
We was convinced that gtest are natural exception to regular dependency handling practices. Unfortunately it tend to change API in non-portable ways. And we faced binary incompatibilities between subsequent minor releases when tried to use it as shared library. Google itself recommends embedding in https://github.com/google/googletest/tree/master/googletest/README.md. We can provide build option which would try to utilize system-provided gtest, but this would became a moving target.

**Comment by tjaalton** [comment]
Having an option to use a system installed one is good enough, at least for my use-case packaging this for Debian/Ubuntu Linux

**Comment by dvrogozh** [comment]
@tjaalton : #1288 adds "blind" (no checks of the version, no support of gtest from custom location) build against system installed gtest via `-DUSE_SYSTEM_GTEST=ON`. Would that be enough as a short term solution? PR is for master branch, may not apply clean against 18.4.1.
