### ISSUE TITLE
Vpp scaling mode does not work

### ISSUE THREAD

**Issue by 3703liu** [Intel-Media-SDK/MediaSDK#1289]
I am using the  sample_multi_transcode in MediaSdk to transcode  a  h264  file from 1080p to 720p. I want to try  different  scaling mode. so the scaling mode  is configured  with a mfxExtVppScaling  structure   in   function "CTranscodingPipeline::InitVppMfxParams(sInputParams *pInParams)" in pipeline_transcode.cpp  as described in the mediasdk  manual . And  the scaling mode  value is  printed in function VideoVPPHW::SyncTaskSubmission(DdiTask* pTask)",   which shows the scaling mode  has been set successfully, but the final  result makes no difference.  So  I am wondering   how to configure the  scaling mode.

**Comment by FurongZhang** [comment]
I have a sample code in the tutorial.

**Comment by FurongZhang** [comment]
https://github.com/Intel-Media-SDK/MediaSDK/pull/2308

**Comment by FurongZhang** [comment]
https://github.com/Intel-Media-SDK/MediaSDK/pull/2308 is the sample code. Will merge it ASAP. Please refer to the sample code firstly.
