### ISSUE TITLE
dispatcher: are paths handled correctly?

### ISSUE THREAD

**Issue by onabiull** [Intel-Media-SDK/MediaSDK#1307]
```
#define MAX_PLUGIN_PATH 4096
#define MAX_PLUGIN_NAME 4096
```
Windows MAX_PATH is 260, the exception is extended-length path which permits 32767 but requires "\\?\" prefix, see details at https://docs.microsoft.com/en-us/windows/desktop/FileIO/naming-a-file.
Do we really use prefixes for constructing plugins' path names?

**Comment by npletnev** [comment]
The issue has been fixed in mentioned pr.
