### ISSUE TITLE
[hevc 8/10bit dec] Incompatible video parameters detected.

### ISSUE THREAD

**Issue by feiwan1** [Intel-Media-SDK/MediaSDK#1311]
When decode some stream by using sample_decode, "Incompatible video parameters detected" is shown.

Example:
10bit:
sample_decode h265 -i Allegro_HEVC_Main10_MT51_BITDEPTHRND_00_1920x1080@60Hz_1.8.bin -o test.yuv

8bit
sample_decode h265 -i RAP_B_Bossen_1.bin -o a.yuv -hw -vaapi

**Comment by dmitry-gurulev** [comment]
At RAP_B_Bossen_2.bin (RAP_B_Bossen_1.bin is not a part of conformance) there are [SPS :: pic_width/height_in_luma_samples] changes from 448x265 -> 416x240 -> 448x265. When size is changed from bigger size to smaller one - it is enough to reset decoder, no surface reallocation is required.

**Comment by dmitry-gurulev** [comment]
Behavior is expected
