### ISSUE TITLE
Document MediaSDK sample applications low-power mode option

### ISSUE THREAD

**Issue by eero-t** [Intel-Media-SDK/MediaSDK#1315]
Unlike FFmpeg, MediaSDK sample applications don't have option for using low-power mode (HW encoding) instead shader encoding.  This would be useful in testing them against FFmpeg.

**Comment by dmitryermilov** [comment]
Sample_encode has "-qsv-ff" which actives low power encoders.

**Comment by eero-t** [comment]
Thanks! I  guess FF stands for Fixed Function.

Please describe it in the help output so that one knows what the option actually stands, and that one can grep the (very long) help output for it.  Something like:
` -qsv-ff       Enable QuickSync Fixed Function (low-power HW) encoding mode`
