### ISSUE TITLE
metrics_monitor don't work

### ISSUE THREAD

**Issue by zhuqingliang** [Intel-Media-SDK/MediaSDK#1321]
run  /opt/intel/mediasdk/share/mfx/samples/metrics_monitor :
ERROR: Failed to initialize metrics monitor, error code -10

env
platform: skl/kbl
kernel :4.15.0
system: 16.04
Mediasdk commit :6bbc73701388e0a33df7bc1bf736c9c58e75a8f5 
i915 driver: c4dbce5fd7637502b0332dd157d722d3560f4197

**Comment by lizhong1008** [comment]
I have same issue on KBL

**Comment by dmitryermilov** [comment]
@andreyor , can you please comment?

**Comment by dvrogozh** [comment]
I believe this is not a bug.

metrics monitor requires support to be available in Linux kernel. It can work on 2 types of kernel:
1. If it is coming from one of MSS releases
2. On Linux kernels from kernel.org starting from 4.16

For upstream kernel compare:
* https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/include/uapi/drm/i915_drm.h?h=v4.16 - search PMU perf events
* https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/include/uapi/drm/i915_drm.h?h=v4.15 - no PMU events

This all is documented in metrics monitor readme: https://github.com/Intel-Media-SDK/MediaSDK/blob/master/doc/samples/readme-metrics_monitor_linux.pdf. Please, pay attention that you may need to setup privileges correctly to be able to access PMU metrics (basically, running under root should work).

**Comment by zhuqingliang** [comment]
replace my kernel to 4.19.5 , now metrics monitor can work.  Thanks for your information.
