### ISSUE TITLE
MSDK scaling modes don't take effect

### ISSUE THREAD

**Issue by lizhong1008** [Intel-Media-SDK/MediaSDK#1327]
Summary: 
    When set different scaling modes: MFX_SCALING_MODE_DEFAULT, MFX_SCALING_MODE_LOWPOWER or MFX_SCALING_MODE_QUALITY, the output result is totally same, no matter scaling output data, render engine usage, and performance.   

How to reproduce:
1. Apply the patch: https://patchwork.ffmpeg.org/patch/11768/
2. Run: 
  a. ffmpeg -hwaccel qsv -c:v h264_qsv -i /root/Videos/bbb_sunflower_1080p_30fps_normal.mp4 -vframes 1000 -vf scale_qsv=w=1280:h=720 -c:v h264_qsv -low_power 1 -q 25 test_scale_default.mp4 -y
  b. ffmpeg -hwaccel qsv -c:v h264_qsv -i /root/Videos/bbb_sunflower_1080p_30fps_normal.mp4 -vframes 1000 -vf scale_qsv=w=1280:h=720:mode=hq -c:v h264_qsv -low_power 1 -q 25 test_scale_hq.mp4 -y
 c. ffmpeg -hwaccel qsv -c:v h264_qsv -i /root/Videos/bbb_sunflower_1080p_30fps_normal.mp4 -vframes 1000 -vf scale_qsv=w=1280:h=720:mode=low_power -c:v h264_qsv -low_power 1 -q 25 test_scale_lp.mp4 -y

   All results are same.  Tested on both KBL and SKL.

Probably relative issue: https://github.com/intel/media-driver/issues/582 , but I noted that in MSDK, MFX_SCALING_MODE_DEFAULT is map to VA_FILTER_SCALING_DEFAULT

**Comment by lizhong1008** [comment]
Ping again.

**Comment by Alexandr-Konovalov** [comment]
@lizhong1008 , in current sources for non-APL systems I see such mapping.

```
MFX_SCALING_MODE_LOWPOWER -> VA_FILTER_SCALING_DEFAULT -> VPHAL_SCALING_PREFER_SFC
MFX_SCALING_MODE_QUALITY -> VA_FILTER_SCALING_HQ -> VPHAL_SCALING_PREFER_COMP
MFX_SCALING_MODE_DEFAULT -> VA_FILTER_SCALING_HQ
```
I enabled logging in the driver and see that low_power/hq from ffmpeg command line is definitely passed to the driver level. And I reproduced your results on SKL, output streams are bit-to-bit equal. In combination with intel/media-driver#582 , it points out to a problem in the driver.

**Comment by Alexandr-Konovalov** [comment]
@lizhong1008 Can it be closed, then?

**Comment by lizhong1008** [comment]
@Alexandr-Konovalov Sorry for late reply. 
As comment on https://github.com/intel/media-driver/issues/582#issuecomment-490142360,  set VA_FILTER_SCALING_DEFAULT  will enable SFC (And I can confirm that if ffmpeg-vaapi set VA_FILTER_SCALING_DEFAULT , SFC works).  So my question is still open: why set MFX_SCALING_MODE_LOWPOWER can't enable SFC?

**Comment by Alexandr-Konovalov** [comment]
@lizhong1008 Thank you for the clarification. I see that for ffmpeg/vaapi results for mode=fast/hq are bit2bit equal, but for mode=default the result is different. So at this point SFC is probably at work.

For ffmpeg/qsv, I see that results for mode=hq and mode=low_power are bit2bit equal and this is the problem. One difference with vaapi that I see is that MSDK sets output_color_standard to VAProcColorStandardBT601 while vaapi uses VAProcColorStandardNone. It can be that or something different.  How can I explicitly check that SFC works?

**Comment by Alexandr-Konovalov** [comment]
@lizhong1008  As far as I can understand, SFC for ffmpeg/qsv in mode=low_power during resize to 1280x720 is not enabled in Intel media driver because 
```
    bColorFill = (pcRenderParams->pColorFillParams &&
                  (!RECT1_CONTAINS_RECT2(pSrc->rcDst, pRenderTarget->rcDst))) ?
                 true : false;

```
gets true in `VphalSfcState::GetOutputPipe()`. I.e., `pSrc->rcDst` is 1280x720, while `pRenderTarget->rcDst` is 1280x736. And `pRenderTarget->rcDst.bottom == 736` because in ffmpeg/qsv `init_out_pool()` (see libavfilter/vf_scale_qsv.c) calls
```   
    out_frames_ctx->width             = FFALIGN(out_width,  32);
    out_frames_ctx->height            = FFALIGN(out_height, 32);
```
Why are they aligned to 32? Looks like overkill.

**Comment by lizhong1008** [comment]
> How can I explicitly check that SFC works?
SFC is using a fixed HW function to do scaling,  non-SFC mode (mostly it is AVS mode) is using EU (3D render engine) to do scaling.  So you can check Render usage to make sure SFC is working or not. If Render usage is close to zero, it is SFC (please see bug report description of https://github.com/intel/media-driver/issues/582)

**Comment by lizhong1008** [comment]
> How can I explicitly check that SFC works?

SFC is using a fixed HW function to do scaling, non-SFC mode (mostly it is AVS mode) is using EU (3D render engine) to do scaling. So you can check Render usage to make sure SFC is working or not. If Render usage is close to zero, it is SFC (please see bug report description of intel/media-driver#582)

**Comment by lizhong1008** [comment]
@Alexandr-Konovalov Good point, if I scale it to be 1280x736 instead of 1280x720, render usage is zero, thus mean SFC works. 

>Why are they aligned to 32? Looks like overkill.

I not not the initialized author of vf_scale_qsv.c, but I know MSDK alignment requirement is tricky, sometimes it is required to be 16bytes , sometimes to be 32 bytes, this is probably a reason.

**Comment by dmitryermilov** [comment]
is it actual yet?

**Comment by Alexandr-Konovalov** [comment]
@lizhong1008  I hope this is clarified, can we close the issue?

**Comment by lizhong1008** [comment]
@Alexandr-Konovalov @dmitryermilov sorry for late reply. Yes it is clear now ,though I need to check more details of ColorFill in iHD driver.
