### ISSUE TITLE
The usage of the flag MFX_BITSTREAM_COMPLETE_FRAME

### ISSUE THREAD

**Issue by fuweitax** [Intel-Media-SDK/MediaSDK#1332]
Is this flag supported only for H264 and JPEG codec? What happens if I set it for other codecs?

**Comment by fuweitax** [comment]
Any comment about this issue?

**Comment by dmitryermilov** [comment]
It's supported for AVC/HEVC/MPEG2/JPEG. 
If you set it for decoder which doesn't support the flag, nothing will happen. the flag will be ignored.

**Comment by fuweitax** [comment]
Thank you very much, @dmitryermilov. I wonder if it's better to always set this flag. If not, in which use cases, need to set it, and in which use cases, don't?

**Comment by dmitryermilov** [comment]
You can set it to reduce latency(just by 1 frame). In case of MFX_BITSTREAM_COMPLETE_FRAME MSDK decoders won't wait for beginning of next frame to "complete" current frame. However, if on some frame application is mistaken and passed more/less than the whole frame, then it will cause artifacts.

**Comment by fuweitax** [comment]
Ok, got it. Thank you very much!
