### ISSUE TITLE
Movie file parser

### ISSUE THREAD

**Issue by mofo7777** [Intel-Media-SDK/MediaSDK#1343]
Hello.

It seems Intel-Media-SDK needs some Movie file parsers. For example, we need to provide raw video data to use sample_decode.

If you agree, i can integrate some parsers i've made (.mp4/.mov, mpeg1-2, flv), See [https://github.com/mofo7777](https://github.com/mofo7777)

**Comment by onabiull** [comment]
Sorry but muxers and demuxers out of current project scope. We was unable to justify ROI of maintaining our own version. So current approach is to use ffmpeg or gstreamer with QSV acceleration.
