### ISSUE TITLE
Regression: 4-6% AVC transcoding perf drop in sample_multi_transcode

### ISSUE THREAD

**Issue by eero-t** [Intel-Media-SDK/MediaSDK#1348]
"sample_multi_transcode" performance regressed for AVC by 4-6%, at least on BXT/BDW/SKL/KBL/CFL GT2/GT3e/GT4e, in following cases:
* `sample_multi_transcode -i::h264 1280x720p_29.97_10mb_h264_cabac.264 -o::h264 output.h264 -b 2000 -u 4 -async 4 -hw`
* `sample_multi_transcode -i::h264 720x480p_30.00_4mb_h264_cabac_180s.264 -o::h264 output.h264 -b 2000 -u 4 -async 4 -hw`

I'm not seeing perf drop in couple of other AVC cases I'm running (HD17i & HD22), but no improvements either. If one changes encoding in latter case to MPEG-2, there's no regression, so it's AVC encoding issue.

I bisected this regression to the following (huge) commit:
```
commit 897ea5aabd1fca5c5ef3a31ff0aec21488da1192
Author:     fzhar <Fedor.Zharinov@intel.com>
AuthorDate: Tue Feb 26 16:08:06 2019 +0300
Commit:     Oleg Nabiullin <oleg.nabiullin@intel.com>
CommitDate: Mon Apr 1 15:18:55 2019 +0300

    Windows samples and projects are merged in
...
177 files changed, 298 insertions(+), 255 deletions(-)
```

**Comment by eero-t** [comment]
I do see 1-2% improvement in PSNR for above mentioned test-cases, and <1% improvement for SSIM.

If this indeed is just a defaults change, perf drop is be acceptable compromise for increased quality, and this can be closed.

However, I couldn't check what options were changed, so that I could verify whether they explain all of the performance drop:
```
$ sample_multi_transcode -pp
Multi Transcoding Sample Version 8.4.27.1705

ERROR: Source file name not found
```

Could you tell me what options I should use to get the same default AVC encoding quality settings as with the earlier defaults?  Thanks!

**Comment by Alexandr-Konovalov** [comment]
I found no such options, because current logic of `sample_multi_transcode` doesn't allow setting 0 as values of parameter, but that was defaults in the version you compare against. 

With an attached patch and command line 
```sample_multi_transcode -i::h264 1280x720p_29.97_10mb_h264_cabac.264 -o::h264 curr1.h264 -b 2000 -u 4 -async 4 -hw  -cbr``` I get transcoded stream bit-to-bit equal to transcoded by previous version (pre-897ea5) of sample_multi_transcode.

Is it resolve performance difference on your machine?

[sample_multi_transcode-restore-prev-defaults.txt](https://github.com/Intel-Media-SDK/MediaSDK/files/3131636/sample_multi_transcode-restore-prev-defaults.txt)

**Comment by eero-t** [comment]
Thanks, applying that patch on top of the latest MediaSDK git restores the earlier (better) performance and (marginally worse) quality which verifies that given encode options change were the cause.

I'm assuming this is acceptable quality vs. performance compromise => closing
