### ISSUE TITLE
sample_multi_transcode fails with 10-bit -> 8-bit conversion

### ISSUE THREAD

**Issue by eero-t** [Intel-Media-SDK/MediaSDK#1353]
Setup:
- KBL GT2
- Ubuntu 18.04
- Latest drm-tip kernel
- git versions of media-driver/MediaSDK/etc

Test-case:
- Transcode 10-bit 4K HEVC content to 8-bit FullHD HEVC:
`sample_multi_transcode -hw -dc::nv12 -i::h265 Netflix_FoodMarket_4096x2160_10bit_420_100mbs_600.h265 -w 1920 -h 1080 -b 10000 -ec::nv12 -o::h265 output.h265`

Output:
```
[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), EncodePreInit, m_pmfxENC->Query failed at /opt/builder/source1/media-sdk/samples/sample_multi_transcode/src/pipeline_transcode.cpp:537

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), Init, EncodePreInit failed at /opt/builder/source1/media-sdk/samples/sample_multi_transcode/src/pipeline_transcode.cpp:3778

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), Init, pThreadPipeline->pPipeline->Init failed at /opt/builder/source1/media-sdk/samples/sample_multi_transcode/src/sample_multi_transcode.cpp:305

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), main, transcode.Init failed at /opt/builder/source1/media-sdk/samples/sample_multi_transcode/src/sample_multi_transcode.cpp:908
```
This happens regardless of whether I specify the transcode result format for decode (-dc::nv12) or encode (-ec::nv12).  Only removing both gets the command working, but then there's no output conversion.  None of the other documented output formats worked either.

This isn't related to regression #1344, it was broken already before.

**Comment by Alexandr-Konovalov** [comment]
According to my understanding, call only with `-ec::nv12 ` (without `-dc::nv12`) is correct, as we set a parameter for encoder.

**Comment by eero-t** [comment]
Thanks, I can verify that by using just the -ec option the command works now, and the resulting output looks OK.

Btw. What the encode & decode side conversion actually means, isn't the conversion actually done in-between them (decode with FF HW and compute based encode in KBL case), using the  SFC (scale & format conversion) HW block?
