### ISSUE TITLE
make step on building MediaSDK fails with error: ‘VAEncMiscParameterBufferMultiPassFrameSize’ was not declared 

### ISSUE THREAD

**Issue by skyline220** [Intel-Media-SDK/MediaSDK#1355]
Hi,

OS: Ubuntu 16.04 LTS
CPU: i5-7260U
Kernel 4.14.16

I have tried building the Media-SDK with the following:

https://github.com/Intel-Media-SDK/MediaSDK/wiki/Build-Media-SDK-on-Ubuntu

After successfully installing libva, the make step fails on building the media SDK with:

[ 74%] Building CXX object _studio/mfx_lib/plugin/CMakeFiles/mfx_h264la_hw64.dir//shared/src/libmfxsw_enc.cpp.o
/home/test/working_dir/msdk/_studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp: In function ‘mfxStatus SetMultiPassFrameSize(const MfxHwH264Encode::DdiTask&, mfxU32, VADisplay, VAContextID, VABufferID&)’:
/home/test/working_dir/msdk/_studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp:340:5: error: ‘VAEncMiscParameterBufferMultiPassFrameSize’ was not declared in this scope
VAEncMiscParameterBufferMultiPassFrameSize *p_multiPassFrameSize;
^
/home/test/working_dir/msdk/_studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp:340:49: error: ‘p_multiPassFrameSize’ was not declared in this scope
VAEncMiscParameterBufferMultiPassFrameSize *p_multiPassFrameSize;
^
/home/test/working_dir/msdk/_studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp:359:24: error: ‘VAEncMiscParameterTypeMultiPassFrameSize’ was not declared in this scope
misc_param->type = VAEncMiscParameterTypeMultiPassFrameSize;
^
/home/test/working_dir/msdk/_studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp:360:73: error: expected primary-expression before ‘)’ token
p_multiPassFrameSize = (VAEncMiscParameterBufferMultiPassFrameSize *)misc_param->data;
^
[ 75%] Building CXX object _studio/mfx_lib/plugin/CMakeFiles/mfx_h264la_hw64.dir//encode_hw/h264/src/mfx_h264_encode_cm.cpp.o
_studio/mfx_lib/plugin/CMakeFiles/mfx_h264la_hw64.dir/build.make:400: recipe for target '_studio/mfx_lib/plugin/CMakeFiles/mfx_h264la_hw64.dir//shared/src/mfx_h264_encode_vaapi.cpp.o' failed
make[2]: *** [_studio/mfx_lib/plugin/CMakeFiles/mfx_h264la_hw64.dir//shared/src/mfx_h264_encode_vaapi.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:2790: recipe for target '_studio/mfx_lib/plugin/CMakeFiles/mfx_h264la_hw64.dir/all' failed
make[1]: *** [_studio/mfx_lib/plugin/CMakeFiles/mfx_h264la_hw64.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

I was wondering if any assistance could be provided on how to resolve this? I need this to install the gstreamer mediasdk plugins.

Thanks

**Comment by dmitryermilov** [comment]
Please update libva.
Latest libva version has [VAEncMiscParameterTypeMultiPassFrameSize](https://github.com/intel/libva/blob/c98b06d2b8c00dc4df628488b672711b3f0eb118/va/va.h#L1757) and [VAEncMiscParameterBufferMultiPassFrameSize ](https://github.com/intel/libva/blob/c98b06d2b8c00dc4df628488b672711b3f0eb118/va/va.h#L2134)

**Comment by skyline220** [comment]
This worked, thanks. Please update the instructions when possible, closing this issue
