### ISSUE TITLE
[KBL][FFmpeg-qsv]HW decode + nv12->rgb32 + hwdownload performance poor when enabling gpu_copy 

### ISSUE THREAD

**Issue by fulinjie** [Intel-Media-SDK/MediaSDK#1380]
CMD line:
ffmpeg -hwaccel qsv -c:v h264_qsv -i bbb_sunflower_1080p_30fps_normal.mp4 -vf "scale_qsv=format=rgb32,hwdownload,format=rgb32" -f rawvideo -pix_fmt rgb32 /dev/null

Apply patch to enable gpu_copy for hwdownload by default:
https://github.com/fulinjie/ffmpeg/commit/cefed3e301f8997662d7fe8b49a08023ebcf1d52

gpu_copy off: 133 fps
gpu_copy on: 163 fps

For hwdownload rgb32, gpu_copy can accelerate on APL, but got poor perfs on KBL.

For hwdownload nv12,  gpu copy can improve performance as expected for both APL and KBL.

**Comment by fulinjie** [comment]
Update the performance, previous description should corrected: 
- gpu_copy off: 163 fps
- gpu_copy on: 133 fps
Enable gpu_copy but found performance drop.
       |  nv12->rg32  |  nv12->rgb32  gpu_copy |       nv12     | nv12 gpu_copy 
APL |         14          |                61                      |         32       |       139
KBL |         163        |               133                     |        319      |        361

**Comment by gsilva2016** [comment]
Hi Linjie, do we know why HW color conversion with GPU_COPY is causing a drop?

**Comment by fulinjie** [comment]
Hi gsilva, I could't tell the difference from APL and KBL for both FFmpeg level log and Media SDK level call stack (mfxlib.log) when enabling gpu_copy, they all showed CmCopy is used:

/home/linjiefu/data/Documents/git/msdk/_studio/mfx_lib/decode/h264/src/mfx_h264_dec_decode.cpp: 1570: DecodeFrame                             : VideoDECODEH264::DecodeFrame: ENTER
/home/linjiefu/data/Documents/git/msdk/_studio/mfx_lib/decode/h264/src/mfx_h264_dec_decode.cpp: 1570: DecodeFrame                             : VideoDECODEH264::DecodeFrame: EXIT
/home/linjiefu/data/Documents/git/msdk/_studio/mfx_lib/decode/h264/src/mfx_h264_dec_decode.cpp: 1045: RunThread                               : VideoDECODEH264::RunThread: EXIT
/home/linjiefu/data/Documents/git/msdk/_studio/mfx_lib/decode/h264/src/mfx_h264_dec_decode.cpp: 1022: AVCDECODERoutine                        : AVCDECODERoutine: EXIT
/home/linjiefu/data/Documents/git/msdk/_studio/mfx_lib/scheduler/include/mfx_scheduler_core.h:  479: call_pRoutine                           : mfxRes = 0
/home/linjiefu/data/Documents/git/msdk/_studio/mfx_lib/scheduler/include/mfx_scheduler_core.h:  451: call_pRoutine                           : MFX Async Task: EXIT
/home/linjiefu/data/Documents/git/msdk/_studio/mfx_lib/scheduler/src/mfx_scheduler_core_task_management.cpp:  617: MarkTaskCompleted                       : ^Completed^268435468
/home/linjiefu/data/Documents/git/msdk/_studio/mfx_lib/scheduler/src/mfx_scheduler_core_thread.cpp:   66: ThreadProc                              : thread_proc: EXIT
/home/linjiefu/data/Documents/git/msdk/_studio/mfx_lib/scheduler/src/mfx_scheduler_core_thread.cpp:   66: ThreadProc                              : thread_proc: ENTER
/home/linjiefu/data/Documents/git/msdk/_studio/mfx_lib/shared/src/libmfxsw_vpp.cpp:  255: MFXVideoVPP_RunFrameVPPAsync            : MFX_RunFrameVPPAsync: ENTER
/home/linjiefu/data/Documents/git/msdk/_studio/mfx_lib/shared/src/libmfxsw_vpp.cpp:  257: MFXVideoVPP_RunFrameVPPAsync            : in0x55bc65babd88[184]
/home/linjiefu/data/Documents/git/msdk/_studio/mfx_lib/scheduler/src/mfx_scheduler_core_ischeduler.cpp:  538: AddTask                                 : ^Enqueue^536870927
/home/linjiefu/data/Documents/git/msdk/_studio/mfx_lib/shared/src/libmfxsw_vpp.cpp:  443: MFXVideoVPP_RunFrameVPPAsync            : out0x7fff7ff945d0[184]
/home/linjiefu/data/Documents/git/msdk/_studio/mfx_lib/shared/src/libmfxsw_vpp.cpp:  446: MFXVideoVPP_RunFrameVPPAsync            : *syncp = 0x55bc00000c00
/home/linjiefu/data/Documents/git/msdk/_studio/mfx_lib/shared/src/libmfxsw_vpp.cpp:  448: MFXVideoVPP_RunFrameVPPAsync            : mfxRes = 0
/home/linjiefu/data/Documents/git/msdk/_studio/mfx_lib/shared/src/libmfxsw_vpp.cpp:  255: MFXVideoVPP_RunFrameVPPAsync            : MFX_RunFrameVPPAsync: EXIT
/home/linjiefu/data/Documents/git/msdk/_studio/mfx_lib/shared/src/libmfxsw_async.cpp:   28: MFXVideoCORE_SyncOperation              : MFX_SyncOperation: ENTER
/home/linjiefu/data/Documents/git/msdk/_studio/mfx_lib/shared/src/libmfxsw_async.cpp:   34: MFXVideoCORE_SyncOperation              : wait = 1000
/home/linjiefu/data/Documents/git/msdk/_studio/mfx_lib/scheduler/src/mfx_scheduler_core_ischeduler.cpp:  269: Synchronize                             : Scheduler::Wait: ENTER
/home/linjiefu/data/Documents/git/msdk/_studio/mfx_lib/scheduler/src/mfx_scheduler_core_ischeduler.cpp:  270: Synchronize                             : ^Depends^on15
/home/linjiefu/data/Documents/git/msdk/_studio/mfx_lib/scheduler/src/mfx_scheduler_core_ischeduler.cpp:  271: Synchronize                             : timeToWait = 1000
/home/linjiefu/data/Documents/git/msdk/_studio/mfx_lib/scheduler/src/mfx_scheduler_core_thread.cpp:   66: ThreadProc                              : thread_proc: EXIT
/home/linjiefu/data/Documents/git/msdk/_studio/mfx_lib/scheduler/src/mfx_scheduler_core_thread.cpp:   66: ThreadProc                              : thread_proc: ENTER
/home/linjiefu/data/Documents/git/msdk/_studio/mfx_lib/scheduler/include/mfx_scheduler_core.h:  451: call_pRoutine                           : VPP Submit: ENTER
/home/linjiefu/data/Documents/git/msdk/_studio/mfx_lib/scheduler/include/mfx_scheduler_core.h:  452: call_pRoutine                           : ^Child^of15
/home/linjiefu/data/Documents/git/msdk/_studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp: 4374: AsyncTaskSubmission                     : VideoVPPHW::AsyncTaskSubmission: ENTER
/home/linjiefu/data/Documents/git/msdk/_studio/shared/src/libmfx_core_vaapi.cpp:  931: DoFastCopyWrapper                       : VAAPIVideoCORE::DoFastCopyWrapper: ENTER
/home/linjiefu/data/Documents/git/msdk/_studio/shared/src/cm_mem_copy.cpp: 2962: **CopyVideoToSystemMemory                 : CmCopyWrapper::CopyVideoToSystemMemory: ENTER**
/home/linjiefu/data/Documents/git/msdk/_studio/shared/src/cm_mem_copy.cpp: 2962: **CopyVideoToSystemMemory                 : CmCopyWrapper::CopyVideoToSystemMemory: EXIT**
/home/linjiefu/data/Documents/git/msdk/_studio/shared/src/libmfx_core_vaapi.cpp:  931: DoFastCopyWrapper                       : VAAPIVideoCORE::DoFastCopyWrapper: EXIT
/home/linjiefu/data/Documents/git/msdk/_studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp: 4374: AsyncTaskSubmission                     : VideoVPPHW::AsyncTaskSubmission: EXIT
/home/linjiefu/data/Documents/git/msdk/_studio/mfx_lib/scheduler/include/mfx_scheduler_core.h:  479: call_pRoutine                           : mfxRes = 0
/home/linjiefu/data/Documents/git/msdk/_studio/mfx_lib/scheduler/include/mfx_scheduler_core.h:  451: call_pRoutine                           : VPP Submit: EXIT
/home/linjiefu/data/Documents/git/msdk/_studio/mfx_lib/scheduler/src/mfx_scheduler_core_task_management.cpp:  617: MarkTaskCompleted                       : ^Completed^536870927
/home/linjiefu/data/Documents/git/msdk/_studio/mfx_lib/scheduler/src/mfx_scheduler_core_thread.cpp:   66: ThreadProc                              : thread_proc: EXIT
/home/linjiefu/data/Documents/git/msdk/_studio/mfx_lib/scheduler/src/mfx_scheduler_core_thread.cpp:   66: ThreadProc                              : thread_proc: ENTER
/home/linjiefu/data/Documents/git/msdk/_studio/mfx_lib/scheduler/src/mfx_scheduler_core_ischeduler.cpp:  269: Synchronize                             : Scheduler::Wait: EXIT
/home/linjiefu/data/Documents/git/msdk/_studio/mfx_lib/shared/src/libmfxsw_async.cpp:   44: MFXVideoCORE_SyncOperation              : mfxRes = 0
/home/linjiefu/data/Documents/git/msdk/_studio/mfx_lib/shared/src/libmfxsw_async.cpp:   28: MFXVideoCORE_SyncOperation              : MFX_SyncOperation: EXIT


One thing is weird from my point:
        - CRITICAL error in driver when enabling gpu_copy
[MOS]:  CRITICAL - Mos_Specific_GetMemoryCompressionMode:5488: Invalid (nullptr) Pointer.
(but it seems that this message can also be triggered by sample_vpp when set -gpu_copy 1)

**Comment by fulinjie** [comment]
@gsilva2016 
Hi gsilva, is there any constraints we should follow for single plane format using CmCopy?
(As far as i know, nv12 like format needs:
1. continuous memory between Y and UV;
2. 128 x 64 alignment;
)

**Comment by fulinjie** [comment]
Update:
RGB32 surface is a linear surface on KBL, so cmcopy can't benefit it:
https://github.com/intel/media-driver/blob/e710df0edb0fecfcffe503f639a437cdacb59649/media_driver/linux/common/ddi/media_libva_util.cpp#L316-L327

But on APL, driver always uses mapgtt on the atom(APL). 
See https://github.com/intel/media-driver/issues/620.

That's the root cause.
Closed.
