### ISSUE TITLE
sample decode on-screen rendering fails under ubuntu 19.04

### ISSUE THREAD

**Issue by dvrogozh** [Intel-Media-SDK/MediaSDK#1396]
Install Ubuntu 19.04 and mediasdk coming from the OS:
```
sudo apt-get install libmfx1 libmfx-tools
sudo apt-get install libva-drm2 libva-x11-2
```

And run the following sample decode rendering command which will fail:
```
export LIBVA_DRIVER_NAME=iHD
wget https://fate-suite.libav.org/h264-conformance/AUD_MW_E.264
/usr/share/mfx/samples/sample_decode h264 -i AUD_MW_E.264 -r -f 30

X Error of failed request:  BadAlloc (insufficient resources for operation)
        Major opcode of failed request:  149 ()
        Minor opcode of failed request:  2
        Serial number of failed request:  19
        Current serial number in output stream:  22
```

**Comment by dvrogozh** [comment]
This is a bad error reporting issue from sample_decode. Effectively sample tried to render NV12 frames via XCB pixmaps. For that it exports DMA file descriptor handle from NV12 frames and creates pixmap. The problem is that not all color formats can be used for rendering scanout. NV12 usually can not, hence pixmap creation just fails. PR #1297 improves error reporting and transforms the above error to:
```
Failed to create xcb pixmap from the NV12 surface: try another color format (e.g. RGB4)
DeliverOutput return error = -6
```

As implied by the error message, NV12 simply can not be rendered and color conversion is required. Since this is a sample application, I don't think it is needed to be handled automatically. For the successful rendering we need to run:
```
/usr/share/mfx/samples/sample_decode h264 -i AUD_MW_E.264 -r -f 30 -rgb4
```

Mind that NV12->RGB4 color conversion should be supported by underlying VAAPI driver. In case of iHD it is definitely supported by `intel-media-va-driver-non-free`, but it might not be supported by `intel-media-va-driver` for some platforms (basically, VP are supported by this driver for ICL+, on BDW, SKL, KBL it is not supported). Hence, before running the above command line, make sure to install `intel-media-va-driver-non-free`:
```
sudo apt-get install intel-media-va-driver-non-free
/usr/share/mfx/samples/sample_decode h264 -i AUD_MW_E.264 -r -f 30 -rgb4
```

`intel-media-va-driver-non-free` and `intel-media-va-driver` are distributed under the same license. The difference between them is that the first one includes binary EU shaders while the later one includes EU shaders with available source code.

**Comment by dvrogozh** [comment]
As clarified above, that's bad error reporting behavior of sample decode. It was improved and fix is available in Ubuntu 19.10. Please, consider switching from Ubuntu 19.04 to Ubuntu 19.10 if you are affected by this issue.

**Comment by dmitryermilov** [comment]
> PR #1297 improves error reporting and transforms the above error to:

@dvrogozh , #1297 is about gtest

**Comment by dvrogozh** [comment]
It should be #1397. I'll fix a comment above. Thx.
