### ISSUE TITLE
mctf VPP don't work with HEVC 10bit encoding

### ISSUE THREAD

**Issue by thx4ever** [Intel-Media-SDK/MediaSDK#1418]
Why Motion Compensated Temporal filter VPP don't work with sample_multi_transcode in 10bit encoding?
If i add to command line -mctf 0 it says not supported but if i encode HEVC 8bit it works with -hw
Maybe its because the -sys command line options needed to encode 10bit HEVC?

**Comment by spossos** [comment]
Hi, currently MCTF works for 8bit content only, in future update we will extended MCTF to be able to process 10bit content.

**Comment by daleksan** [comment]
@spossos Any updates?

**Comment by FurongZhang** [comment]
MCTF does not have 10bit support unless there is a major customer requirement.

**Comment by FurongZhang** [comment]
@thx4ever , @spossos  is MCTF expert. Please let us know if there is a major business impact for 10bit MCTF enabling. Thanks a lot in advance!
