### ISSUE TITLE
HEVC FEI API requirement is inconsistent

### ISSUE THREAD

**Issue by dvrogozh** [Intel-Media-SDK/MediaSDK#142]
Compare:
https://github.com/Intel-Media-SDK/MediaSDK/blob/0e50c533fc57f06af703ed41614d170972ed10a5/_studio/shared/include/mfx_common_linux_bdw.h#L154
with:
https://github.com/Intel-Media-SDK/MediaSDK/blob/0e50c533fc57f06af703ed41614d170972ed10a5/_studio/shared/include/mfx_common_linux_cfl.h#L195

What is MFX_ENABLE_HEVC_VIDEO_FEI_ENCODE API requirement?

**Comment by dvrogozh** [comment]
And looking into this line:
https://github.com/Intel-Media-SDK/MediaSDK/blob/0e50c533fc57f06af703ed41614d170972ed10a5/api/include/mfxfeihevc.h#L29

I completely don't understand in which API version HEVC FEI did/will appear? Moreover, mfxfeihevc.h has some abnormal number of MFX_VERSION_NEXT defines which make no sense!

**Comment by mgonchar** [comment]
AFAIK 1.26 should be correct version of API for HEVC FEI. @onabiull can you confirm it? 

HEVC FEI API should be delivered in two passes that is what folded MFX_VERSION_NEXT macro in mfxfeihevc.h means. Maybe there should be MFX_VERSION_NEXT+1 for such clearness in such situations.

**Comment by dvrogozh** [comment]
MFX_VERSION_NEXT covers the whole mfxfeihevc.h! It looks like HEVC FEI API is still not published at all.

**Comment by dvrogozh** [comment]
Moreover, if anyone will configure mediasdk build by default as:
`perl tools/builder/build_mfx.pl --cmake=intel64.make.release`
he will not get HEVC FEI because of that line:
https://github.com/Intel-Media-SDK/MediaSDK/blob/0e50c533fc57f06af703ed41614d170972ed10a5/_studio/hevc_fei/CMakeLists.txt#L21
