### ISSUE TITLE
Question (Disable SAO filter)

### ISSUE THREAD

**Issue by thx4ever** [Intel-Media-SDK/MediaSDK#1421]
HI, i want to know how i can disable SAO filter because even at high bitrates it smooth the vídeo Picture, i tryed with 15Mbit and 20 Mbit but Picture looks too much smooth, is there a way to disable SAO filter completely on sample_multi_transcode? I encoded the vídeo with 10bit but it looks too much smooth, i think the encoder have same problem as x265 does, no são the Picture looks more natural and have better detail retention.

Thanks

**Comment by dmitryermilov** [comment]
Hi,

MSDK HEVC encode support [SAO](https://github.com/Intel-Media-SDK/MediaSDK/search?q=SampleAdaptiveOffset&unscoped_q=SampleAdaptiveOffset) but this API handle is not enabled on samples level.
