### ISSUE TITLE
[sample_encode][Tile][Question] How to use Tile encode

### ISSUE THREAD

**Issue by fulinjie** [Intel-Media-SDK/MediaSDK#1422]
CMD line:
./sample_encode h265 -i 1080p_blue_sky.yuv -trows 2 -tcols 2 -o tile_encode.h265 -w 1920 -h 1080 -n 30

Error message:
[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), AllocFrames, Query (for encoder) failed at /root/build/MediaSDK/samples/sample_encode/src/pipeline_encode.cpp:903
[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), ResetMFXComponents, AllocFrames failed at /root/build/MediaSDK/samples/sample_encode/src/pipeline_encode.cpp:1828
[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), Init, ResetMFXComponents failed at /root/build/MediaSDK/samples/sample_encode/src/pipeline_encode.cpp:1572
[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), main, pPipeline->Init failed at /root/build/MediaSDK/samples/sample_encode/src/sample_encode.cpp:1559

Some attempts:
1. -trows 1 -tcols 1 can make the pipeline work, but i didn't find the difference between tile_encode.h265 and non_tile_encode.h265
2.  I see some code in https://github.com/Intel-Media-SDK/MediaSDK/blob/98ff579a9c4f70c1483d253eb1a045068149300b/_studio/mfx_lib/encode_hw/h265/src/mfx_h265_encode_hw_par.cpp#L497
Are there any constraints for slice num and trows/tcols?

**Comment by dmitryermilov** [comment]
HEVC tile support appears since ICL.

**Comment by fulinjie** [comment]
@dmitryermilov Thanks for this info, and i'm currently working on ICL with MSDK version b1c624e14660e3fa33302f98f84915cef4fee4e3

**Comment by Xiaogangli-intel** [comment]
Currently the tile mode is not supported, because some KMD features don't upstream.

**Comment by fulinjie** [comment]
@Xiaogangli-intel  thanks for the info.

**Comment by fulinjie** [comment]
Update:
Following cmdline works for me now:
./sample_encode h265 -i 1080p_blue_sky.yuv -trows 2 -tcols 2 -o tile_encode.h265 -w 1920 -h 1080 -n 30 -num_slice 2

However, there seems to be some issues with "-trows" option, only one rows of tile is encoded even if it is set to a bigger value(2 for example).
