### ISSUE TITLE
Question (HEVC CQP HRD encoding)

### ISSUE THREAD

**Issue by thx4ever** [Intel-Media-SDK/MediaSDK#1427]
Hi, how can i encode hevc CQP mode with HRD on sample_multi_transcode?

**Comment by adegtyar** [comment]
CQP HRD mode encoding is not supported for HEVC encoder. 
MFXVideoENCODE_Query() will return MFX_WRN_INCOMPATIBLE_VIDEO_PARAM when input parameters contain both RateControlMethod=MFX_RATECONTROL_CQP and VuiNalHrdParameters=MFX_CODINGOPTION_ON followed by reset of VuiNalHrdParameters to 0 in the out parameters.
So sample_multi_transcode will return 'Configuration changed' on passing parameters '-cqp -NalHrdConformance:off -VuiNalHrdParameters:on' to enable CQP HRD mode for HEVCe.

**Comment by thomasli21801** [comment]
May I know why there is such request for CQP HRD?
I think BRC HRD is more common request.
But as last comment, CQP HRD mode is not supported for HEVC encoder.
