### ISSUE TITLE
Possible Correct vpp output bit depth according to FourCC in sample_encode?

### ISSUE THREAD

**Issue by thx4ever** [Intel-Media-SDK/MediaSDK#1428]
Hi its possible to apply this patch to sample_encode?
Correct vpp output bit depth according to FourCC 
this patch fix green screen when using vpp sys memory for 10 bit hevc encoding on sample_encode application

**Comment by dmitryermilov** [comment]
Which patch? Did you mean to attach something?

**Comment by thx4ever** [comment]
pull request closed #1416
