### ISSUE TITLE
[MediaSDK/tools] metrics_monitor build failed on Ubuntu 16.04.06

### ISSUE THREAD

**Issue by zhoujd** [Intel-Media-SDK/MediaSDK#1446]
It looks like following commits may cause MSDK build failed on Ubuntu 16.04.6
https://github.com/Intel-Media-SDK/MediaSDK/commit/11a171e6b4efd9675a845691e0756e13eee6496f 
https://github.com/Intel-Media-SDK/MediaSDK/commit/846c00ab3490d88b5421b8ed82fd614d22999afb

The libdrm version is **2.4.0** on Ubuntu 16.04.6 with 'apt install', but from the comments
Use PMU definitions from libdrm

libdrm >= **2.4.92** is required

**DMFX_BUILD_INFO="\"Linux-4.15.0-47-generic 4.15.0-47-generic | GNU 5.4.0 | glibc 2.23\""**
Following is build log - 

18:45:46,081 INFO  - cd /opt/media/build/msdk/__cmake_build/samples/metrics_monitor && /usr/bin/c++ -DLINUX -DLINUX32 -DLINUX64 -DMFX_API_VERSION=\"1.30\" -DMFX_BUILD_INFO="\"Linux-4.15.0-47-generic 4.15.0-47-generic | GNU 5.4.0 | glibc 2.23\"" -DMFX_GIT_COMMIT=\"\" -DMSDK_BUILD=\"\" -DUNIX -D_FILE_OFFSET_BITS=64 -D__USE_LARGEFILE64 -Dcttmetrics_EXPORTS -I/opt/media/build/msdk/api/mediasdk_structures -I/opt/media/build/msdk/api/include -I/opt/media/build/msdk/__cmake_build -I/opt/media/build/msdk/samples/metrics_monitor/include -msse4.2 -std=c++11 -m64 -g -g3 -pipe -fPIC -Wall -Wformat -Wformat-security -Wnon-virtual-dtor -Wno-deprecated-declarations -Wno-unknown-pragmas -Wno-unused -O3 -DNDEBUG -fPIC -I/opt/media/install/include -I/usr/include/libdrm -o CMakeFiles/cttmetrics.dir/src/cttmetrics_i915_pmu.cpp.o -c /opt/media/build/msdk/samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp
18:45:46,225 INFO  - /opt/media/build/msdk/samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp: In function 'bool is_engine_config(uint64_t)':
18:45:46,226 INFO  - /opt/media/build/msdk/samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp:64:39: error: '__I915_PMU_OTHER' was not declared in this scope
18:45:46,227 INFO  - return config < __I915_PMU_OTHER(0);
18:45:46,227 INFO  - ^
18:45:46,228 INFO  - /opt/media/build/msdk/samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp: In function 'uint8_t get_engine_sample(uint64_t)':
18:45:46,228 INFO  - /opt/media/build/msdk/samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp:69:21: error: 'I915_PMU_SAMPLE_MASK' was not declared in this scope
18:45:46,228 INFO  - return config & I915_PMU_SAMPLE_MASK;
18:45:46,229 INFO  - ^
18:45:46,229 INFO  - /opt/media/build/msdk/samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp: At global scope:
18:45:46,231 INFO  - /opt/media/build/msdk/samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp:152:35: error: 'I915_SAMPLE_SEMA' was not declared in this scope
18:45:46,232 INFO  - #define I915_ENGINE_SAMPLE_COUNT (I915_SAMPLE_SEMA + 1)
18:45:46,232 INFO  - ^
18:45:46,233 INFO  - /opt/media/build/msdk/samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp:155:21: note: in expansion of macro 'I915_ENGINE_SAMPLE_COUNT'
18:45:46,235 INFO  - metric metrics[I915_ENGINE_SAMPLE_COUNT]; /* 0 - I915_SAMPLE_BUSY/Global PMU, 1 - I915_SAMPLE_WAIT, 2 - I915_SAMPLE_SEMA */
18:45:46,235 INFO  - ^
18:45:46,236 INFO  - /opt/media/build/msdk/samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp: In function 'int perf_init(i915_pmu_collector_ctx_t*, int, int*)':
18:45:46,237 INFO  - /opt/media/build/msdk/samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp:211:72: error: 'I915_SAMPLE_BUSY' was not declared in this scope
18:45:46,237 INFO  - bool is_sema_or_wait_config = is_engine_config(configs[i]) && (I915_SAMPLE_BUSY != get_engine_sample(configs[i]));
18:45:46,237 INFO  - ^
18:45:46,237 INFO  - /opt/media/build/msdk/samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp:228:35: error: 'I915_PMU_SAMPLE_MASK' was not declared in this scope
18:45:46,237 INFO  - int sample_type = I915_PMU_SAMPLE_MASK & configs[i];
18:45:46,238 INFO  - ^
18:45:46,238 INFO  - /opt/media/build/msdk/samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp:230:52: error: 'struct metrics_group' has no member named 'metrics'
18:45:46,238 INFO  - ctx->pm.groups[ctx->pm.num_groups].metrics[sample_type].config = configs[i];
18:45:46,238 INFO  - ^
18:45:46,238 INFO  - /opt/media/build/msdk/samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp:234:52: error: 'struct metrics_group' has no member named 'metrics'
18:45:46,239 INFO  - ctx->pm.groups[ctx->pm.num_groups].metrics[0].config = configs[i]; // For global, let's use metrics[0] field
18:45:46,239 INFO  - ^
18:45:46,239 INFO  - /opt/media/build/msdk/samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp: In function 'int perf_read(pmu_metrics*)':
18:45:46,239 INFO  - /opt/media/build/msdk/samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp:286:27: error: 'struct metrics_group' has no member named 'metrics'
18:45:46,239 INFO  - pm->groups[i].metrics[j].start.value = pm->groups[i].metrics[j].end.value;
18:45:46,239 INFO  - ^
18:45:46,240 INFO  - /opt/media/build/msdk/samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp:286:66: error: 'struct metrics_group' has no member named 'metrics'
18:45:46,240 INFO  - pm->groups[i].metrics[j].start.value = pm->groups[i].metrics[j].end.value;
18:45:46,240 INFO  - ^
18:45:46,240 INFO  - /opt/media/build/msdk/samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp:287:27: error: 'struct metrics_group' has no member named 'metrics'
18:45:46,240 INFO  - pm->groups[i].metrics[j].start.time = pm->groups[i].metrics[j].end.time;
18:45:46,241 INFO  - ^
18:45:46,241 INFO  - /opt/media/build/msdk/samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp:287:65: error: 'struct metrics_group' has no member named 'metrics'
18:45:46,241 INFO  - pm->groups[i].metrics[j].start.time = pm->groups[i].metrics[j].end.time;
18:45:46,241 INFO  - ^
18:45:46,241 INFO  - /opt/media/build/msdk/samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp:288:27: error: 'struct metrics_group' has no member named 'metrics'
18:45:46,242 INFO  - pm->groups[i].metrics[j].end.value = data.values[k++].value;
18:45:46,242 INFO  - ^
18:45:46,242 INFO  - /opt/media/build/msdk/samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp:289:27: error: 'struct metrics_group' has no member named 'metrics'
18:45:46,242 INFO  - pm->groups[i].metrics[j].end.time = data.time_enabled;
18:45:46,242 INFO  - ^
18:45:46,242 INFO  - /opt/media/build/msdk/samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp: In function 'cttStatus CTTMetrics_PMU_Init()':
18:45:46,243 INFO  - /opt/media/build/msdk/samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp:316:30: error: 'I915_ENGINE_CLASS_RENDER' was not declared in this scope
18:45:46,243 INFO  - I915_PMU_ENGINE_BUSY(I915_ENGINE_CLASS_RENDER, 0),
18:45:46,243 INFO  - ^
18:45:46,243 INFO  - /opt/media/build/msdk/samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp:316:57: error: 'I915_PMU_ENGINE_BUSY' was not declared in this scope
18:45:46,243 INFO  - I915_PMU_ENGINE_BUSY(I915_ENGINE_CLASS_RENDER, 0),
18:45:46,243 INFO  - ^
18:45:46,244 INFO  - /opt/media/build/msdk/samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp:317:57: error: 'I915_PMU_ENGINE_WAIT' was not declared in this scope
18:45:46,244 INFO  - I915_PMU_ENGINE_WAIT(I915_ENGINE_CLASS_RENDER, 0),
18:45:46,244 INFO  - ^
18:45:46,245 INFO  - /opt/media/build/msdk/samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp:318:57: error: 'I915_PMU_ENGINE_SEMA' was not declared in this scope
18:45:46,245 INFO  - I915_PMU_ENGINE_SEMA(I915_ENGINE_CLASS_RENDER, 0),
18:45:46,245 INFO  - ^
18:45:46,245 INFO  - /opt/media/build/msdk/samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp:320:30: error: 'I915_ENGINE_CLASS_VIDEO' was not declared in this scope
18:45:46,245 INFO  - I915_PMU_ENGINE_BUSY(I915_ENGINE_CLASS_VIDEO, 0),
18:45:46,245 INFO  - ^
18:45:46,246 INFO  - /opt/media/build/msdk/samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp:328:30: error: 'I915_ENGINE_CLASS_COPY' was not declared in this scope
18:45:46,246 INFO  - I915_PMU_ENGINE_BUSY(I915_ENGINE_CLASS_COPY, 0),
18:45:46,246 INFO  - ^
18:45:46,246 INFO  - /opt/media/build/msdk/samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp:332:30: error: 'I915_ENGINE_CLASS_VIDEO_ENHANCE' was not declared in this scope
18:45:46,246 INFO  - I915_PMU_ENGINE_BUSY(I915_ENGINE_CLASS_VIDEO_ENHANCE, 0),
18:45:46,246 INFO  - ^
18:45:46,247 INFO  - /opt/media/build/msdk/samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp:336:9: error: 'I915_PMU_ACTUAL_FREQUENCY' was not declared in this scope
18:45:46,247 INFO  - I915_PMU_ACTUAL_FREQUENCY,
18:45:46,247 INFO  - ^
18:45:46,247 INFO  - /opt/media/build/msdk/samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp:353:56: error: 'I915_SCHEDULER_CAP_PREEMPTION' was not declared in this scope
18:45:46,247 INFO  - g_ctx.has_preemption = has_param(g_ctx.gem_fd, I915_SCHEDULER_CAP_PREEMPTION);
18:45:46,247 INFO  - ^
18:45:46,248 INFO  - /opt/media/build/msdk/samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp:360:40: error: 'struct metrics_group' has no member named 'metrics'
18:45:46,248 INFO  - switch (g_ctx.pm.groups[i].metrics[0].config) {
18:45:46,248 INFO  - ^
18:45:46,248 INFO  - /opt/media/build/msdk/samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp:376:22: error: the value of 'I915_PMU_ACTUAL_FREQUENCY' is not usable in a constant expression
18:45:46,248 INFO  - case I915_PMU_ACTUAL_FREQUENCY:
18:45:46,248 INFO  - ^
18:45:46,249 INFO  - /opt/media/build/msdk/samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp:336:9: note: 'I915_PMU_ACTUAL_FREQUENCY' was not declared 'constexpr'
18:45:46,249 INFO  - I915_PMU_ACTUAL_FREQUENCY,
18:45:46,249 INFO  - ^
18:45:46,249 INFO  - /opt/media/build/msdk/samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp: In function 'cttStatus CTTMetrics_PMU_GetValue(unsigned int, float*)':
18:45:46,250 INFO  - /opt/media/build/msdk/samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp:533:42: error: 'struct metrics_group' has no member named 'metrics'
18:45:46,250 INFO  - value = perf_elapsed(&group->metrics[I915_SAMPLE_BUSY]);
18:45:46,250 INFO  - ^
18:45:46,250 INFO  - /opt/media/build/msdk/samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp:533:50: error: 'I915_SAMPLE_BUSY' was not declared in this scope
18:45:46,250 INFO  - value = perf_elapsed(&group->metrics[I915_SAMPLE_BUSY]);
18:45:46,250 INFO  - ^
18:45:46,251 INFO  - /opt/media/build/msdk/samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp:534:54: error: 'struct metrics_group' has no member named 'metrics'
18:45:46,251 INFO  - time = (double)perf_elapsed_time(&group->metrics[I915_SAMPLE_BUSY]);
18:45:46,251 INFO  - ^
18:45:46,251 INFO  - /opt/media/build/msdk/samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp:538:71: error: 'struct metrics_group' has no member named 'metrics'
18:45:46,252 INFO  - bool is_sema_and_wait_available = is_engine_config(group->metrics[I915_SAMPLE_BUSY].config) && (3 == group->num_metrics);
18:45:46,252 INFO  - ^
18:45:46,252 INFO  - /opt/media/build/msdk/samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp:541:51: error: 'struct metrics_group' has no member named 'metrics'
18:45:46,252 INFO  - value_sema = perf_elapsed(&group->metrics[I915_SAMPLE_SEMA]);
18:45:46,252 INFO  - ^
18:45:46,252 INFO  - /opt/media/build/msdk/samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp:541:59: error: 'I915_SAMPLE_SEMA' was not declared in this scope
18:45:46,253 INFO  - value_sema = perf_elapsed(&group->metrics[I915_SAMPLE_SEMA]);
18:45:46,253 INFO  - ^
18:45:46,253 INFO  - /opt/media/build/msdk/samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp:542:63: error: 'struct metrics_group' has no member named 'metrics'
18:45:46,253 INFO  - time_sema = (double)perf_elapsed_time(&group->metrics[I915_SAMPLE_SEMA]);
18:45:46,253 INFO  - ^
18:45:46,254 INFO  - /opt/media/build/msdk/samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp:544:51: error: 'struct metrics_group' has no member named 'metrics'
18:45:46,254 INFO  - value_wait = perf_elapsed(&group->metrics[I915_SAMPLE_WAIT]);
18:45:46,254 INFO  - ^
18:45:46,254 INFO  - /opt/media/build/msdk/samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp:544:59: error: 'I915_SAMPLE_WAIT' was not declared in this scope
18:45:46,254 INFO  - value_wait = perf_elapsed(&group->metrics[I915_SAMPLE_WAIT]);
18:45:46,254 INFO  - ^
18:45:46,255 INFO  - /opt/media/build/msdk/samples/metrics_monitor/src/cttmetrics_i915_pmu.cpp:545:63: error: 'struct metrics_group' has no member named 'metrics'
18:45:46,255 INFO  - time_wait = (double)perf_elapsed_time(&group->metrics[I915_SAMPLE_WAIT]);
18:45:46,255 INFO  - ^
18:45:46,255 INFO  - samples/metrics_monitor/CMakeFiles/cttmetrics.dir/build.make:110: recipe for target 'samples/metrics_monitor/CMakeFiles/cttmetrics.dir/src/cttmetrics_i915_pmu.cpp.o' failed
18:45:46,255 INFO  - make[2]: *** [samples/metrics_monitor/CMakeFiles/cttmetrics.dir/src/cttmetrics_i915_pmu.cpp.o] Error 1
18:45:46,256 INFO  - make[2]: Leaving directory '/opt/media/build/msdk/__cmake_build'
18:45:46,256 INFO  - CMakeFiles/Makefile2:906: recipe for target 'samples/metrics_monitor/CMakeFiles/cttmetrics.dir/all' failed
18:45:46,256 INFO  - make[1]: *** [samples/metrics_monitor/CMakeFiles/cttmetrics.dir/all] Error 2

**Comment by dvrogozh** [comment]
@zhoujd : did you somehow manually bypass libdrm version check or you see these errors with unmodified code?

i915 pmu requires Linux kernel version >=4.16. Looks like Ubuntu 16.04 uses 4.15, so i915 pmu won't be functional in any case. However, build of the whole mediasdk should not fail but rather metrics monitor should be excluded from the build..

**Comment by dmitryermilov** [comment]
>@zhoujd : did you somehow manually bypass libdrm version check or you see these errors with unmodified code?

I have the same question.

**Comment by zhoujd** [comment]
Thank you for quick reply, I didn't do any change on source code of MSDK.
I use following comand line to build MSDK.

cmake -DCMAKE_INSTALL_PREFIX="/opt/media/install" -DCMAKE_INSTALL_LIBDIR="/opt/media/install/lib" --no-warn-unused-cli -Wno-dev -DENABLE_OPENCL=NO -DCMAKE_BUILD_TYPE=release -G "Unix Makefiles" /opt/media/build/msdk

I can share more details info via email.

**Comment by dmitryermilov** [comment]
@zhoujd , please try https://github.com/Intel-Media-SDK/MediaSDK/pull/1450

**Comment by zhoujd** [comment]
@dmitryermilov , The patch #1450 does fix the issue.
