### ISSUE TITLE
Copy VASurface or VAImage to mfxFrameSurface at Encoding Directly

### ISSUE THREAD

**Issue by zhoub** [Intel-Media-SDK/MediaSDK#1460]
Hi !

Is that possible to copy the external **VASurface** or **VAImage** to the **mfxFrameSurface** to be encoded directly ? So there is no extra memory copy with host memory.

Thank you very much !

**Comment by dmitryermilov** [comment]
Hi,

Yes, it's possible to use externally provided vaSurfaceID in mfxFrameSurface but it will require special changes (hacks) in msdk vaapi memory allocator. Actually we did it for OMX plug-ins e.g. where encoder got externally provided gralloc buffer(which you may treat as vaSurfaceID) from camera. Similar story was for decoder cases where surface was allocated by let's call it "screen" component.
Please look at https://github.com/Intel-Media-SDK/MediaSDK_OMX_IL/blob/master/omx_utils/src/mfx_omx_vaapi_allocator.cpp 

Regards,
Dmtiry
