### ISSUE TITLE
[qsv_vpp][mirror]garbage in chroma occurs if there are paddings between Y and UV

### ISSUE THREAD

**Issue by fulinjie** [Intel-Media-SDK/MediaSDK#1497]
Apply patch in ffmpeg:
1. allocate continuous memory for qsv vpp:
https://patchwork.ffmpeg.org/patch/13405/
2. add support for transpose:
https://patchwork.ffmpeg.org/patch/13595/

Run cmdline:
ffmpeg -init_hw_device qsv=foo -filter_hw_device foo -v debug -f rawvideo -pix_fmt yuv420p -s:v 352x288 -i MOBILE_352x288_30_orig_01.yuv -vf 'hwupload=extra_hw_frames=64,format=qsv,vpp_qsv=transpose=vflip' -vframes 10 -f rawvideo -pix_fmt yuv420p -y ./transpose.yuv

if we modify in the patch and don't remove the plane_padding, there will be garbage in chroma field.
With plane_padding removed in this hard-coded way, the output image is good.

 /* remove plane_padding introduced by av_frame_get_buffer */
+        for (i = 1; i < 4; i++) {
+            if (out_frame->frame->data[i])
+                out_frame->frame->data[i] -= i * 128;
+        }

Analysis:

For vpp/mirror, CmCopy is used.

For the garbage caused by paddings, the UVOffset in MSDK is calculated by UV-Y, and then it will be calculated  based on pitch
height_stride = (Data.UV – Data.Y) /Data.Pitch,
https://github.com/Intel-Media-SDK/MediaSDK/blob/8fc7b41eaa0a8a20d55ac06438def8dbe1a1df86/_studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp#L3468
MSDK passed row based (pitch based) UVOffset to CM.
https://github.com/Intel-Media-SDK/MediaSDK/blob/8fc7b41eaa0a8a20d55ac06438def8dbe1a1df86/_studio/shared/src/cm_mem_copy.cpp#L1528

Summary:
So if padding is introduced, it won’t break the pipeline, but will assign the **incorrect address** to the pointer of Data.UV.
And that’s the reason for garbage in chroma filed in mirror.

**Comment by fulinjie** [comment]
any comments for this?@dmitryermilov

**Comment by dmitryermilov** [comment]
Hi @fulinjie ,

Thanks for analysis. Yes, AFAIR CM works only for cases when planes are allocated as one chunk of memory. I vaguely recall we had a check for it. Perhaps not for mirroring but for video->system CM based memory copy.. @AntonGrishin , can you please continue investigation?

BTW, @fulinjie I didn't get, why do you need this padding?

**Comment by fulinjie** [comment]
@dmitryermilov padding is a requirement in ffmpeg, and we would like to match the behavior of qsvenc and qsvvpp.
Currently, the padding bytes introduced in ffmpeg don't break qsvenc, but seem to cause troubles in qsv vpp. 
Former discussion can be shared to provide more details.

**Comment by dvrogozh** [comment]
@dmitryermilov, if I understand correctly the situation is that memory was allocated as a single chunk, but there is additional offset between Y and UV planes (these offset bytes are also managed by the allocation). If that's the case then this is actually valid situation. I saw other cases when applications behave in this was. The most recent example was in ChromeOS.

**Comment by dmitryermilov** [comment]
> @dmitryermilov, if I understand correctly the situation is that memory was allocated as a single chunk, but there is additional offset between Y and UV planes (these offset bytes are also managed by the allocation). If that's the case then this is actually valid situation. I saw other cases when applications behave in this was. The most recent example was in ChromeOS.

Ok

**Comment by AntonGrishin** [comment]
Hi @fulinjie 
I investigated your problem, and got following conclusion:
1) MediaSDK (CM) support padding between Y and UV, but need to align this padding with pitch (width variable in ffmpeg code).
I tested on 352x288 stream (pitch = 384). As you mentioned ffmpeg set padding in [get_video_buffer()](https://github.com/FFmpeg/FFmpeg/blob/806ac7da6927c1a9db2d6bc7af272733078964a0/libavutil/frame.c#L257).

>  for (i = 1; i < 4; i++) {
>        if (frame->data[i])
>             frame->data[i] += i * plane_padding;
>     }

I aligned this value on pitch and streams had no garbage (tried 384/3840 offset values).
2) MediaSDK must return not supported status in not aligned situation.

**Comment by fulinjie** [comment]
Hi @AntonGrishin,

Thanks for the effort.

1. Yes, I've verified that if padding are aligned the output is good. 
pitch aligned padding would allow cm passing the height stride based on row.

However, it's not the key point. Application (like ffmpeg qsv) may introduce plane padding in some specific size which is designed for all functions in app. The alignment requirement is not reasonable.
If your input clips is 4K, the alignment for padding will be huge waste.

2. IMHO, a check in MSDK is needed but not enough.
Since app has allocated continuous memory, there can be some possible solutions to cope with the random padding since the UV offset is passed to msdk directly.

Maybe do cm copy for Y plane and UV plane separately to be more robust for padding introduced by app?

**Comment by dmitryermilov** [comment]
> Application (like ffmpeg qsv) may introduce plane padding in some specific size which is designed for all functions in app. 
Padding is okay. But it must be stride aligned.

> The alignment requirement is not reasonable.
I assume almost any hardware processing has limitations related to alignment. The requirements might be e.g. width/height multiple to 16 or stride aligned to some value. Why do you think it's not reasonable? 

> If your input clips is 4K, the alignment for padding will be huge waste.
As far as I understand max "waste" will be (4096-1) bytes. No?

**Comment by dmitryermilov** [comment]
>Maybe do cm copy for Y plane and UV plane separately to be more robust for padding introduced by app?

It will require significant efforts to re-write the CM kernel. I don't think it's reasonable to do it while there is a simple solution on app side - align pointer to UV to pitch.

**Comment by fulinjie** [comment]
>  Why do you think it's not reasonable

@dmitryermilov 
My words may be a little confusing, and above opinion is based on **we insist in using get_video_buffer()**.

I agreed that it's reasonable for hardware processing. However since get_video_buffer() is used for both software and hardware, the alignment is not good for software. 

> As far as I understand max "waste" will be (4096-1) bytes.

It's based on calling get_video_buffer( ) with the "align = 4096" to set the plane_padding to stride.
Previously 128 aligned requirement for width is enough, but now we have 4096 aligned requirement if we intend to use this function for memory allocation in ffmpeg.

And this is the main reason for the patch: I modified to use a separate patch without padding introduced:
https://patchwork.ffmpeg.org/patch/13594/

> It will require significant efforts to re-write the CM kernel. I don't think it's reasonable to do it while there is a simple solution on app side - align pointer to UV to pitch.

It's true CM modification needs much effort and I didn't insist on this. 
And UV pointer alignment is acceptable. IMHO, this seems more like a trade off between
" reuse the function but redundant memory"
and
"no extra padding introduced but a new function" 

If we choose to rely on a separate function (like get_continuous_buffer in the patch) for memory allocation, this issue can be addressed.

Thanks.

**Comment by dmitryermilov** [comment]
Hi @fulinjie ,

Let's keep the current issue open. Anton only added a check which will return an error. 
I understand the problem but to tell you truth don't think we'll be able to rewrite the CM kernel in a short time to support the case when UV planes are not aligned to pitch size. Actually this discussion brings another question: on ffmpeg side, is it possible to implement a flexible memory allocator which will allocate system memory based on some external requirements parameters? This will definitely be suitable not only for msdk ffmpeg integration but other cases as well (e.g. MDF/OCL).

**Comment by fulinjie** [comment]
> Hi @fulinjie ,
> 
> Let's keep the current issue open. Anton only added a check which will return an error.
> I understand the problem but to tell you truth don't think we'll be able to rewrite the CM kernel in a short time to support the case when UV planes are not aligned to pitch size. Actually this discussion brings another question: on ffmpeg side, is it possible to implement a flexible memory allocator which will allocate system memory based on some external requirements parameters? This will definitely be suitable not only for msdk ffmpeg integration but other cases as well (e.g. MDF/OCL).

Agree, thanks for the efforts and analysis. @dmitryermilov @AntonGrishin

**Comment by daleksan** [comment]
Currently not planned to implement
