### ISSUE TITLE
[HEVC_ENCODE][LOOK AHEAD][QSV][SAMPLE_ENCODE]bit rate lose control in LA_EXT

### ISSUE THREAD

**Issue by fulinjie** [Intel-Media-SDK/MediaSDK#1511]
Try sample_encode to verify look_ahead for hevc and found:
1. only LA_EXT is supported for hevc look_ahead;
2. sample_encode seems not allowed setting for LA_EXT;

Enabled in ffmpeg_qsv and try to verify:
https://github.com/fulinjie/ffmpeg/commit/398f123b61736818d445f8a81c1d1848e1d57ddb

CMD:
ffmpeg -init_hw_device qsv=qsv:hw -hwaccel qsv -filter_hw_device qsv -v debug -f rawvideo -pix_fmt yuv420p -s:v 1920x1080 -i ./1080p_blue_sky.yuv -vf 'format=yuv420p,hwupload=extra_hw_frames=64' -an -c:v hevc_qsv -g 30 -bf 0 -look_ahead 1 -extbrc 1 -b:v 3M -vframes 100 -y out.h265

result:
when setting  3M in VBR (-b:v 3M), the output bitrate is 5M:
frame=  100 fps= 34 q=-0.0 Lsize=    2713kB time=00:00:04.00 bitrate=5557.0kbits/s speed=1.36x    
video:2713kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%

Actually,  no matter what we set in -b:v, the average bit rate is constant, and we loose the control for bit rate in LA_EXT mode.

**Comment by thx4ever** [comment]
Can u help me out? I added this patch to sample_multi_transcode, it Works but the problem are that it Always dont use target bitrate, a full movie come with 1GB size, how can i use target bitrate with your patch? If i set target bitrate 6000 i get 1-2000 bitrate, how can i control target bitrate with look-ahead?

**Comment by ogolikov** [comment]
Hi! could you share command line for sample_multi_transcode?

**Comment by thx4ever** [comment]
set -o::h265 e5400a06c74d41f5b12d430bbaa23d0b
-lad 100 -i::h264 input.264 -join -la_ext -hw -async 1 -n 300 -o::sink
-h 1080 -w 1920 -o::h265 output.hevc -b 3000 -join -async 1 -hw -i::source -l 1 -u 4 -n 300

sample_multi_transcode -par 1.par
Multi Transcoding Sample Version 8.4.27.0

Par file is: 1.par

Session 0:
plugin_loader.h :186 [INFO] Plugin was loaded from GUID: { 0x58, 0x8f, 0x11, 0x85, 0xd4, 0x7b, 0x42, 0x96, 0x8d, 0xea, 0x37, 0x7b, 0xb5, 0xd0, 0xdc, 0xb4 } (Intel (R) Media SDK plugin for LA ENC)
MFX HARDWARE Session 0 API ver 1.29 parameters:
Input video: AVC
Output video: To child session
MFX dll: C:\WINDOWS\SYSTEM32\libmfxhw64.dll

Session 1:
plugin_loader.h :186 [INFO] Plugin was loaded from GUID: { 0xe5, 0x40, 0x0a, 0x06, 0xc7, 0x4d, 0x41, 0xf5, 0xb1, 0x2d, 0x43, 0x0b, 0xba, 0xa2, 0x3d, 0x0b } (Intel (R) Media SDK GPU-Accelerated plugin for HEVC ENCODE)
MFX HARDWARE Session 1 API ver 1.29 parameters:
Input video: From parent session
Output video: HEVC
MFX dll: C:\WINDOWS\SYSTEM32\libmfxhw64.dll

Pipeline surfaces number (DecPool): 117
Session 0 was joined with other sessions
Session 1 was joined with other sessions

Transcoding started

[ERROR], sts=MFX_ERR_INVALID_VIDEO_PARAM(-15), TranscodingSample::CTranscodingPipeline::Encode, <EncodeOneFrame|Surface2BS> failed at C:\Users\thx4ever\source\repos\MediaSDK\samples\sample_multi_transcode\src\pipeline_transcode.cpp:1451

[ERROR], sts=MFX_ERR_INVALID_VIDEO_PARAM(-15), TranscodingSample::CTranscodingPipeline::Run, CTranscodingPipeline::Run::Encode() [000001905B5B9490]. failed at C:\Users\thx4ever\source\repos\MediaSDK\samples\sample_multi_transcode\src\pipeline_transcode.cpp:4591

session 1 [000001905B5B9490] failed with status MFX_ERR_INVALID_VIDEO_PARAM shutting down the application...

session [000001905BA056A0] m_bForceStop is set
session [000001905B5B9490] m_bForceStop is set
WARNING: m_bForceStop is set, returning NULL ptr from GetFreeSurface

Transcoding finished
Common transcoding time is 0.342123 sec

*** session 0 [000001905BA056A0] PASSED (MFX_ERR_NONE) 0.341098 sec, 8 frames, 23.454 fps
set -o::h265 e5400a06c74d41f5b12d430bbaa23d0b

*** session 1 [000001905B5B9490] FAILED (MFX_ERR_INVALID_VIDEO_PARAM) 0.306223 sec, 1 frames, 3.266 fps
-lad 100 -i::h264 input.264 -join -la_ext -hw -async 1 -n 300 -o::sink

The test FAILED

[ERROR], sts=MFX_ERR_INVALID_VIDEO_PARAM(-15), wmain, transcode.ProcessResult failed at C:\Users\thx4ever\source\repos\MediaSDK\samples\sample_multi_transcode\src\sample_multi_transcode.cpp:984
plugin_loader.h :212 [INFO] MFXBaseUSER_UnLoad(session=0x000001905B5B9490), sts=0
plugin_loader.h :212 [INFO] MFXBaseUSER_UnLoad(session=0x000001905BA056A0), sts=0

**Comment by ogolikov** [comment]
Hi! Thanks for parfile. 
GACC HEVC encoder is used in this case ("set -o::h265 e5400a06c74d41f5b12d430bbaa23d0b"). It isn't compatible with LA plugin. 
As I know GACC HEVC encoder has short LA by default. So it is no need to set LA parameters at all

**Comment by thx4ever** [comment]
Thanks for report ogolikov, can u show me how to encode HEVC 10 bit with par file with Intel Media SDK HEVC HW plugin and with LA enabled?

**Comment by ogolikov** [comment]
which platform?

**Comment by thx4ever** [comment]
Linux

**Comment by thx4ever** [comment]
ogolikov can u help me out? Look this
ffmpeg -v verbose -hide_banner -init_hw_device qsv=qsv:hw -hwaccel qsv -filter_hw_device qsv -f rawvideo -pix_fmt p010le -s:v 1440x1080 -i D:\IN.yuv -vf format=p010le,hwupload=extra_hw_frames=64 -c:v hevc_qsv -load_plugin hevc_sw -profile:v main10 -preset:v slower -look_ahead 1 -look_ahead_depth 100 -g 240 -refs:v 4 -bf:v 3 -flags -cgop -gpb 0 -b:v 6000k -extbrc 1 -bsf:v hevc_metadata=colour_primaries=1:transfer_characteristics=1:matrix_coefficients=1:sample_aspect_ratio=1440/1080 -aspect 16:9 C:\Users\thx4ever\Desktop\OUT.hevc

I can't control the ouptut target bitrate, i have 6000 bitrate but come with 1-2000 only
I'm using ffmpeg.

**Comment by ogolikov** [comment]
Hi! LA plugin functionality is limited by 8-bit  in current implementation. LA support will be added in HEVC encoder in future releases.
