### ISSUE TITLE
sample_encode V4L2 issues if VPP is not used

### ISSUE THREAD

**Issue by Sepsu** [Intel-Media-SDK/MediaSDK#1513]
Hello,

I'm trying to run the sample_encode application on Ubuntu 18.04 where I have complied MediaSDK together with the other necessary parts from their respective git repositories. I have the sample_enconde working well when using .yuv formatted example files and encoding them to H264.

I have ran into issues when using V4L2 UVC video device. I currently get image to the output file only if VPP is used (the image slices/blocks are still somewhat misindexed as you can see from the attached picture)
![h264 output](https://user-images.githubusercontent.com/11488870/60663523-25d4c800-9e68-11e9-96b1-976f5180b485.png) 

From looking at the code, the number of buffers to initialize and queue from v4l2_utils.cpp is defined from m_VppResponse.NumFrameActual which is only defined if VPP is used. If I don't define dstw/h from command line, the number of buffers is always zero and the ioctl for STREAMON return EBUSY error. I have manually played around to define the number of buffers which causes the V4L2 device correctly to work, but the encode_pipeline doesn't of course queue or read those buffers without further modifications.

Am I missing something here, would anyone be able to help getting V4L2 capture + h264 encoding to work properly without the VPP. Of if VPP is the only option to go, help with the misformed video frames (see the picture) is appriciated.
.

**Comment by salimerko** [comment]
Same problem reported in #1874

**Comment by daleksan** [comment]
closed by #1987

**Comment by daleksan** [comment]
Hi @Sepsu feel free to re-open if issue still relevant to you
