### ISSUE TITLE
Reset of VPP composition falsely outputs picture in picture

### ISSUE THREAD

**Issue by HermanMolinder** [Intel-Media-SDK/MediaSDK#152]
Steps to reproduce:
1: Composite an OSD on a video through VPP
2: Call MFXVideoVPP_Reset without composition params (to remove OSD)
3: Keep running the video through the VPP block. By doing this there will be a PiP at the output where the OSD previously was located.

Calling MFXVideoVPP_Reset again with new composition params will remove the PiP.

Replacing MFXVideoVPP_Reset with MFXVideoVPP_Close + MFXVideoVPP_Init will work as expected. However this solution leaks memory as reported in Issue #105.

Additional info:
Video memory is used through vaapi.
Tested on Apollolake with embedded Linux and Intel Media SDK version 1.26

**Comment by HermanMolinder** [comment]
I still have this problem and have been investigating it some more.

Now I've reproduced the issue with open source msdk, from the following commits:

libva: b3be72a5a110880f70626d7c3bed953cdde124b2
media-driver: 1c2b0615d749c45c07f9aee6586774816989c5b3
gmmlib: 247673f8e487d62b818876dc1905036e477986c1
MediaSDK: 7c2b069dce7bed268806f680412a2f3b09a52ce9

It seems like the composition params are still active when resetting the VPP, because every second input frame is composited where the OSD used to be instead of being rendered on the whole output surface.

**Comment by HermanMolinder** [comment]
I can confirm above observation about composition params still being active after reset. When the VPP is reset without composition params the MFXVideoVPP_RunFrameVPPAsync still returns MFX_ERR_MORE_DATA every second frame.

I was also able to reproduce this with resizing/scaling the output frame, to exclude the bug was connected to a passthrough of the surfaces.

**Comment by dmitryermilov** [comment]
Hi @HermanMolinder ,

Thank you for details. I'll take a look at this.

**Comment by dmitryermilov** [comment]
Hi @HermanMolinder ,

> I can confirm above observation about composition params still being active after reset. When the VPP is reset without composition params the MFXVideoVPP_RunFrameVPPAsync still returns MFX_ERR_MORE_DATA every second frame.
> 
> I was also able to reproduce this with resizing/scaling the output frame, to exclude the bug was connected to a passthrough of the surfaces.

I confirm it's a bug on our side. However I can't promise a quick fix because this usage model- application resetting a filters lists (list of filters, not parameters of a particular filter) via Reset is not very often usage case. On the other hand, of course MSDK library should not pretend that something works while it's broken. Here, of course we need to add a check in Reset() function and return an error. It will be added soon. 
From application point of view, I'd recommend to have two VPP instances: one is for composition, the other one is for scaling.  Calls of Close/Init of course also can help but it will introduce a big latency since Close/Init is usually an expensive operation.

**Comment by HermanMolinder** [comment]
Hi @dmitryermilov ,
Thank you for the info.

If you add an error on return; a quick work-around could be a fallback to close+init when reset() returns error. I think this work-around will be ok for now, as the number of composition inputs won't be updated very often thus it won't have much impact on the performance.

**Comment by HermanMolinder** [comment]
Hi,
Any news about this? When can I expect a fix? A check in reset() would be enough for now.

**Comment by dmitryermilov** [comment]
Sorry, no progress on a proper fix. However a check is Reset() is easy to implement.  I'll add it soon.

**Comment by dmitryermilov** [comment]
https://github.com/Intel-Media-SDK/MediaSDK/pull/702 introduces a check to return an error when composition is enabled/disabled via Reset().

**Comment by HermanMolinder** [comment]
Thanks @dmitryermilov,
I have verified that the check works after my small modification in fe23a07fdb6b8f731c841deee5b839e0d8d92262.
