### ISSUE TITLE
[VC1 Decode] sample_decode fails with MFX_ERR_UNDEFINED_BEHAVIOR

### ISSUE THREAD

**Issue by NaveenKumar-Intel** [Intel-Media-SDK/MediaSDK#1528]
[big_buck_bunny_720p_VC1_WMA3_25fps_4200K_short.zip](https://github.com/Intel-Media-SDK/MediaSDK/files/3372209/big_buck_bunny_720p_VC1_WMA3_25fps_4200K_short.zip)

sample_decode fails with MFX_ERR_UNDEFINED_BEHAVIOR for few VC1 video playback, however following referenced VC1 elementary streams works with VLC player.

**CMDLINE**
./sample_decode vc1 -i vantage.vc1 
./sample_decode vc1 -i vantage.vc1 –vaapi -hw
./sample_decode vc1 -i vantage.vc1 -o output.yuv –vaapi -hw

**RESULT:**
pretending that aspect ratio is 1:1
libva info: VA-API version 1.5.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /usr/lib64/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_4
libva info: va_openDriver() returns 0
Decoding Sample Version 8.4.27.

Input video     VC1
Output format   NV12
Input:
  Resolution    1280x720
  Crop X,Y,W,H  0,0,1280,720
Output:
  Resolution    1280x720
Frame rate      30.00
Memory type             vaapi
MediaSDK impl           hw
MediaSDK version        1.29

Decoding started

[ERROR], sts=MFX_ERR_UNDEFINED_BEHAVIOR(-16), RunDecoding, DecodeFrameAsync returned error status at /home/nkumar/workspace/MediaSDK/samples/sample_decode/src/pipeline_decode.cpp:1900
Frame number:    0, fps: 0.000, fread_fps: 0.000, fwrite_fps: 0.000
[ERROR], sts=MFX_ERR_UNDEFINED_BEHAVIOR(-16), RunDecoding, Unexpected error!! at /home/nkumar/workspace/MediaSDK/samples/sample_decode/src/pipeline_decode.cpp:2010

[ERROR], sts=MFX_ERR_UNDEFINED_BEHAVIOR(-16), main, Pipeline.RunDecoding failed at /home/nkumar/workspace/MediaSDK/samples/sample_decode/src/sample_decode.cpp:740

**Comment by Alexandr-Konovalov** [comment]
@NaveenKumar-Intel  The stream that you attached contains ASF container. Currently sample_decode doesn't support ASF. 

Is vantage.vc1 some different stream? Could you share it with us?

**Comment by Alexandr-Konovalov** [comment]
@NaveenKumar-Intel Is that issue still relevant?

**Comment by NaveenKumar-Intel** [comment]
VC1 playback fix is provided by @Haihao Xiang @ [https://gitlab.freedesktop.org/haihao/gst-plugins-bad.git](url) under ‘msdk-for-testing’ branch.
