### ISSUE TITLE
Dual GPU system on Ubuntu - Intel and Nvidia

### ISSUE THREAD

**Issue by e-dul-xb** [Intel-Media-SDK/MediaSDK#153]
Hi all,
I would like to use Intel Media SDK to decode JPEGs and in same time use Nvidia Cuda for other applications. Is this possible on Linux operating system(Ubuntu 16.04)?
I found info that this SDK supports all HW 5th Generation and higher, please correct me if I'm wrong.
Thank you.

**Comment by avbelova** [comment]
Hi Emil, 

Using 2 graphics on Ubuntu is possible. I don't see here any problem here.
Now the master supports Intel CPUs from 5th to 8th generations.

Best wishes,
Anna

**Comment by adydychk** [comment]
Hi @e-dul-xb ,
do you satisfied with the answer? Can we close the issue?
