### ISSUE TITLE
After some time create and delete, the SDK crashed

### ISSUE THREAD

**Issue by JackXu2** [Intel-Media-SDK/MediaSDK#1531]
Version: Media SDK 2019 Q1
CPU Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz

#3  <signal handler called>
#4  0x00007ff53a6faa5d in _mm_loadu_si128 (__P=0x436a3ff8) at /home/user/gcc/lib/gcc/x86_64-unknown-linux-gnu/5.4.0/include/emmintrin.h:698
#5  ns_asc::ME_VAR_8x8_Block (
    pSrc=0x436a3c78 "/210110/\221\215\217\223\220\222\223\222\221\222\223\222\220\220\216\222\220\221\221\222\222\224\224\226\231\233\240\241\247\252\255\256\260\260\262\261\255\255\244\244\236\226\221|\203\202\210\215\220\233\243\276\245\221\201pe`[\f\034\036 \037\"\"\037$\"\"&#%(%'''(()'.\017+*+)+.,(+++,../-+-,,,-1--..\016-//.///,....1/,-\214\214\216\223\220\221\221\216\220\220\216\220\220\216\216\215\217\220\215\216\217\220\227\224\230\231\231\240\243\245\251\250\255\251\254\250\247\241\232\233\224\213\203sz}~\204\212\215\225\260\231\207wjb]`\b\036\035\037!"..., 
    pRef=0x371bfc78 ".3100/0/\221\215\217\223\220\222\223\222\221\222\223\222\220\220\216\222\220\221\221\222\222\224\224\226\231\233\240\241\247\252\255\256\260\260\262\261\255\255\244\244\236\226\221|\203\202\210\215\220\233\243\276\245\221\201pe`[\f\033\037!\037\"\"\036#!!'#%(%'&'((*'.\016+*,),.+&)++,////+--,+,2-,.,\f.00,000-0/..1/+-\214\214\216\223\220\221\221\216\220\220\216\220\220\216\216\215\217\220\215\216\217\220\227\224\230\231\231\240\243\245\251\250\255\251\254\250\247\241\232\233\224\213\203sz}~\204\212\215\225\260\231\207wjb]`\b\037\035\037!"..., 
    pMCref=0x371bfc78 ".3100/0/\221\215\217\223\220\222\223\222\221\222\223\222\220\220\216\222\220\221\221\222\222\224\224\226\231\233\240\241\247\252\255\256\260\260\262\261\255\255\244\244\236\226\221|\203\202\210\215\220\233\243\276\245\221\201pe`[\f\033\037!\037\"\"\036#!!'#%(%'&'((*'.\016+*,),.+&)++,////+--,+,2-,.,\f.00,000-0/..1/+-\214\214\216\223\220\221\221\216\220\220\216\220\220\216\216\215\217\220\215\216\217\220\227\224\230\231\231\240\243\245\251\250\255\251\254\250\247\241\232\233\224\213\203sz}~\204\212\215\225\260\231\207wjb]`\b\037\035\037!"..., srcAvgVal=97, refAvgVal=97, srcPitch=128, refPitch=128, var=@0x1048f9b8: 14463736, jtvar=@0x1048f9bc: 14406027, 
    jtMCvar=@0x1048f9c0: 14406027) at /home/user/h5s/3rdparty/msdk/intel_linux/MediaSDK/_studio/shared/asc/src/../include/me_asc.h:94
#6  0x00007ff53a6fdce4 in ns_asc::MVcalcVar8x8 (MV=..., 
    curY=0x436a3c78 "/210110/\221\215\217\223\220\222\223\222\221\222\223\222\220\220\216\222\220\221\221\222\222\224\224\226\231\233\240\241\247\252\255\256\260\260\262\261\255\255\244\244\236\226\221|\203\202\210\215\220\233\243\276\245\221\201pe`[\f\034\036 \037\"\"\037$\"\"&#%(%'''(()'.\017+*+)+.,(+++,../-+-,,,-1--..\016-//.///,....1/,-\214\214\216\223\220\221\221\216\220\220\216\220\220\216\216\215\217\220\215\216\217\220\227\224\230\231\231\240\243\245\251\250\255\251\254\250\247\241\232\233\224\213\203sz}~\204\212\215\225\260\231\207wjb]`\b\036\035\037!"..., 
    refY=0x371bfc78 ".3100/0/\221\215\217\223\220\222\223\222\221\222\223\222\220\220\216\222\220\221\221\222\222\224\224\226\231\233\240\241\247\252\255\256\260\260\262\261\255\255\244\244\236\226\221|\203\202\210\215\220\233\243\276\245\221\201pe`[\f\033\037!\037\"\"\036#!!'#%(%'&'((*'.\016+*,),.+&)++,////+--,+,2-,.,\f.00,000-0/..1/+-\214\214\216\223\220\221\221\216\220\220\216\220\220\216\216\215\217\220\215\216\217\220\227\224\230\231\231\240\243\245\251\250\255\251\254\250\247\241\232\233\224\213\203sz}~\204\212\215\225\260\231\207wjb]`\b\037\035\037!"..., curAvg=97, refAvg=97, var=@0x1048f9b8: 14463736, jtvar=@0x1048f9bc: 14406027, jtMCvar=@0x1048f9c0: 14406027, dataIn=0x10382ac0)
    at /home/user/h5s/3rdparty/msdk/intel_linux/MediaSDK/_studio/shared/asc/src/motion_estimation_engine.cpp:110
#7  0x00007ff53a6fee28 in ns_asc::ME_simple (videoIn=0x28df85b0, fPos=127, dataIn=0x10382ac0, scale=0x1048f970, scaleRef=0x1048e630, limits=0x1048f290, ME_SAD_8x8_Block_Search=
    0x7ff53a6f3a63 <ME_SAD_8x8_Block_Search_SSE4(unsigned char*, unsigned char*, int, int, int, unsigned short*, int*, int*)>) at /home/user/h5s/3rdparty/msdk/intel_linux/MediaSDK/_studio/shared/asc/src/motion_estimation_engine.cpp:356
#8  0x00007ff53a6eef29 in ns_asc::ASC::MotionAnalysis (this=0x3c17c008, videoIn=0x1048f970, videoRef=0x1048e630, TSC=0x1048f380, AFD=0x1048f3a4, MVdiffVal=0x1048f390, AbsMVSize=0x1048f394, AbsMVHSize=0x1048f398, AbsMVVSize=0x1048f39c, 
    lyrIdx=ns_asc::ASCFull_Size) at /home/user/h5s/3rdparty/msdk/intel_linux/MediaSDK/_studio/shared/asc/src/asc.cpp:1011
#9  0x00007ff53a6efb41 in ns_asc::ASC::DetectShotChangeFrame (this=0x3c17c008) at /home/user/h5s/3rdparty/msdk/intel_linux/MediaSDK/_studio/shared/asc/src/asc.cpp:1146
#10 0x00007ff53a6f0597 in ns_asc::ASC::AscFrameAnalysis (this=0x3c17c008) at /home/user/h5s/3rdparty/msdk/intel_linux/MediaSDK/_studio/shared/asc/src/asc.cpp:1355
#11 0x00007ff53a6f069b in ns_asc::ASC::ProcessQueuedFrame (this=0x3c17c008, subSamplingEv=0x2fc46b60, subSamplingTask=0x2fc46b68, inputFrame=0x2fc46b70, pixelData=0x2fc46b80)
    at /home/user/h5s/3rdparty/msdk/intel_linux/MediaSDK/_studio/shared/asc/src/asc.cpp:1376
#12 0x00007ff53a63bc6f in MfxHwH264Encode::ImplementationAvc::Prd_LTR_Operation (this=0x3c17c000, task=...) at /home/user/h5s/3rdparty/msdk/intel_linux/MediaSDK/_studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp:2075
#13 0x00007ff53a63d07d in MfxHwH264Encode::ImplementationAvc::AsyncRoutine (this=0x3c17c000, bs=0x3bbd1220) at /home/user/h5s/3rdparty/msdk/intel_linux/MediaSDK/_studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp:2408
#14 0x00007ff53a6416c4 in MfxHwH264Encode::ImplementationAvc::AsyncRoutineHelper (state=0x3c17c000, param=0x3bbd1220) at /home/user/h5s/3rdparty/msdk/intel_linux/MediaSDK/_studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp:3160
#15 0x00007ff53a3dabec in mfxSchedulerCore::call_pRoutine (this=0xe974f00, call=...) at /home/user/h5s/3rdparty/msdk/intel_linux/MediaSDK/_studio/mfx_lib/scheduler/include/mfx_scheduler_core.h:467
#16 0x00007ff53a3da926 in mfxSchedulerCore::ThreadProc (this=0xe974f00, pContext=0xe8e7528) at /home/user/h5s/3rdparty/msdk/intel_linux/MediaSDK/_studio/mfx_lib/scheduler/src/mfx_scheduler_core_thread.cpp:80
#17 0x00007ff53a3d8b74 in std::_Mem_fn_base<void (mfxSchedulerCore::*)(MFX_SCHEDULER_THREAD_CONTEXT*), true>::operator()<MFX_SCHEDULER_THREAD_CONTEXT*&, void> (this=0x103fa578, __object=0xe974f00)
    at /home/user/gcc/include/c++/5.4.0/functional:600

**Comment by dmitryermilov** [comment]
Could you share a reproducer?
