### ISSUE TITLE
[vc1 decode] MFXVideoDECODE_DecodeFrameAsync returns unnavailable surface.

### ISSUE THREAD

**Issue by feiwan1** [Intel-Media-SDK/MediaSDK#1532]
Hi,
I am using gstreamer-msdk(https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/tree/master/sys/msdk) to decode and playback vc1 stream but it got a error: Couldn't find the cached MSDK surface.

Gst-msdk cmdline: gst-launch-1.0 filesrc location=FlightSimX_720p60_51_15Mbps.wmv ! asfdemux ! vc1parse ! msdkvc1dec ! "video/x-raw(memory:DMABuf)" !  glimagesink

When it calls MFXVideoDECODE_DecodeFrameAsync several times, the returned surface is not in list of which I put.

The process steps is:
round1: MFXVideoDECODE_DecodeFrameAsync(.., surface_work=surface1, surface_out=NULL, ..)
status = MFX_ERR_MORE_DATA;
surface1.Data.Locked = 0;
surface_out = NULL;

round2: MFXVideoDECODE_DecodeFrameAsync(.., surface_work=surface1, surface_out=NULL, ..)
status = MFX_ERR_MORE_SURFACE;
surface_out = NULL;

round3: MFXVideoDECODE_DecodeFrameAsync(.., surface_work=surface2, surface_out=NULL, ..)
status = MFX_ERR_MORE_DATA;
surface_out = NULL;

round4: MFXVideoDECODE_DecodeFrameAsync(.., surface_work=surface2, surface_out=NULL, ..)
suface2.Data.Locked = 0;
status = MFX_ERR_NONE;
surface_out = surface1;

round5: MFXVideoDECODE_DecodeFrameAsync(.., surface_work=surface3, surface_out=NULL, ..)
suface3.Data.Locked = 0;
status = MFX_ERR_MORE_DATA;
surface_out = NULL;

round6: MFXVideoDECODE_DecodeFrameAsync(.., surface_work=surface3, surface_out=NULL, ..)
status = MFX_ERR_NONE;
surface_out = surface1;

The issue appeared in round6, the surface_out should not be surface1 which already outputted in round4, and then never set it in.

And I took a sightly look, it seems when the vc1 frame type is SKIP, the indexes in vc1 context will be something wrong, which will lead to get a wrong memID and then the wrong surface. I tried to force return UMC_ERR_NOT_ENOUGH_DATA instead of update the indexes of context when the frame type is SKIP, the issue will gone. But this should not be a good solution: 
https://github.com/Intel-Media-SDK/MediaSDK/blob/4108fee8f7dd2afa51310ee7f1d327d065f1a24b/_studio/shared/umc/codec/vc1_dec/src/umc_vc1_dec_frame_descr.cpp#L273

The stream I tested can be found in:
http://samples.mplayerhq.hu/V-codecs/WVC1/

**Comment by dmitryermilov** [comment]
@Dmi3shin , please find an owner

**Comment by feiwan1** [comment]
Hi, I have synced with @xhaihao , msdk will re-use the previous surface instead of using a new one when it meets a SKIP type frame. This should not be a issue, and may benefits performance. While in gst-msdk side, once the surface returned, we will move it from decoded surface list. So in next round, same surface will be return but gst-msdk couldn't find it in its decoded surface list, then return error. And we will try to fix this in gst-msdk side. So close this one. 

And thanks @dmitryermilov @Dmi3shin for your support.
