### ISSUE TITLE
IO Wait is high when run 9 channel 1080 H265 to H264

### ISSUE THREAD

**Issue by JackXu2** [Intel-Media-SDK/MediaSDK#1535]
IO Wait is high when run 9 channel 1080 H265 to H264, and kernel wa is high. 
MediaSDK version: Media SDK 19.2.0
OS: Ubuntu 16.04
CPU: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
![image](https://user-images.githubusercontent.com/30012551/61339111-d7172d00-a86e-11e9-970e-0899cca003f3.png)

is there some wrong for the configuration?

**Comment by daleksan** [comment]
is it still actual on the latest media stack?
If so, could you provide us the reproducer?

**Comment by daleksan** [comment]
@JackXu2 feel free to re-open if it is still actual
