### ISSUE TITLE
Internal allocator and samples don't align pointers to page size

### ISSUE THREAD

**Issue by dmitryermilov** [Intel-Media-SDK/MediaSDK#1546]
MSDK internal allocator and samples don't align pointers to page size. Basically this is requirement of I915_GEM_USERPTR which is needed to make video memory from system memory. Another USERPTR requirement is memory size shall be page aligned.

**Comment by dmitryermilov** [comment]
+ @dvrogozh

**Comment by alariono** [comment]
@alariono
