### ISSUE TITLE
[FFmpeg][QSV][HEVC][DECODE] choose the best matched profile for profile-missing clips

### ISSUE THREAD

**Issue by fulinjie** [Intel-Media-SDK/MediaSDK#1576]
Currently, unknown profile (parsed profile == 0) will cause the decode failure directly in
ffmpeg qsv.

1. cmdline:
$ ffmpeg -hwaccel qsv -hwaccel_device /dev/dri/renderD128 -v verbose -c:v hevc_qsv -i /root/media/testing/assets/hevc/id_main_SlideEditing_1280x720_30_qp22.bin -vf 'hwdownload,format=nv12' -pix_fmt yuv420p -f rawvideo -vsync passthrough -vframes 300 -y  test.yuv

(this clips could be shared internally if needed)

2. error message

Error while decoding stream #0:0: Invalid argument
[hevc_qsv @ 0x1ad0a00] video_get_buffer: image parameters invalid
[hevc_qsv @ 0x1ad0a00] get_buffer() failed
Error while decoding stream #0:0: Invalid argument

3. In msdk, UMC_HEVC_DECODER::MFX_Utility::CheckVideoParam_H265() returned an error directly if the profile is unexpected:
https://github.com/Intel-Media-SDK/MediaSDK/blob/5b23796ab993771718fec3b997c3f4a5c98c6c4c/_studio/shared/umc/codec/h265_dec/src/umc_h265_mfx_utils.cpp#L987

4. After some discussion in https://github.com/intel-media-ci/ffmpeg/pull/66,  we thought there is one possible solution to choose the best matched profile for these profile-missing cases. And this will make msdk more robust for all kinds of possible clips. (it seems in sample_decode, some default profile type will be chosen if the profile info is missing, I thought it would be good to step a little bit further)

**Comment by IlyaTikhanov** [comment]
Hi,

To resolve this issue i think you can use the function below
https://github.com/Intel-Media-SDK/MediaSDK/blob/5b23796ab993771718fec3b997c3f4a5c98c6c4c/_studio/mfx_lib/decode/h265/src/mfx_h265_dec_decode.cpp#L562
It should find best-matching codec profile too with this function
https://github.com/Intel-Media-SDK/MediaSDK/blob/5b23796ab993771718fec3b997c3f4a5c98c6c4c/_studio/mfx_lib/decode/h265/src/mfx_h265_dec_decode.cpp#L587

Also i would like you to share clips with me, so i can reproduce this issue

**Comment by fulinjie** [comment]
Hi@IlyaTikhanov , clips is shared internally.

**Comment by dmitry-gurulev** [comment]
The problem is broader than just selection of profile basing on given _fourcc_, because profiles like _Rext\SCC_ allow 8\10b 420 streams (like main\main10) but requires special tools to be used for decoding, therefore requiring decoder to be initialized w/ certain `VAProfile`. So, in common, we can't properly initialize decoder basing on _fourcc_ (_bit depth_, _chroma format_) only and can't guarantee correct output.

To somehow cope this we may initialize decoder w/ max supported (on certain platform) profile.

**Comment by lizhong1008** [comment]
FFmepg qsv has swicted to MSDK parser, so it is not an issue now.

**Comment by fulinjie** [comment]
Closed, thanks for the support.
