### ISSUE TITLE
mctf in samples is disabled for 1.26 build

### ISSUE THREAD

**Issue by dvrogozh** [Intel-Media-SDK/MediaSDK#159]
https://github.com/Intel-Media-SDK/MediaSDK/blob/c885e1a6583d203ca2c6f844daf3a8ed70d468a9/samples/sample_common/include/sample_defs.h#L42-L50

Here is why having multiple pieces of code doing the same is evil.... Do we really need separate configs for samples and library?

**Comment by onabiull** [comment]
+ @fzhar As we provide samples as separate package, without MediaSDK code separate configs are reasonable. Still we may think about some safety checks.

**Comment by dvrogozh** [comment]
We can think about a safety checks or shared config, but let's fix MCTF enabling in samples first.
