### ISSUE TITLE
How to select the specified Graphic Adapter to encode when with multi intel Graphic Adaters?

### ISSUE THREAD

**Issue by dongyuhai** [Intel-Media-SDK/MediaSDK#1595]
How to select the specified Graphic Adapter to encode when with multi intel Graphic Adaters?

**Comment by onabiull** [comment]
This functionality is WIP, but https://github.com/Intel-Media-SDK/MediaSDK/pull/1566 may shed some lite on the topic.

**Comment by dmitryermilov** [comment]
Please refer to https://github.com/Intel-Media-SDK/MediaSDK/pull/1759
