### ISSUE TITLE
Add a default if MFX_HOME is not set

### ISSUE THREAD

**Issue by uartie** [Intel-Media-SDK/MediaSDK#16]
MFX_HOME should not be required since it usually just points to the same directory as is being configured by cmake (i.e. the top of source tree).  Consider setting the default to CMAKE_HOME_DIRECTORY when MFX_HOME is not defined in the environment.

**Comment by onabiull** [comment]
We can make MFX_HOME optional but for majority of users of this script it should be /opt/intel/mediasdk. Since MSS 2017 R3 this script reused in Samples development package.

**Comment by lizhong1008** [comment]
/opt/intel/mediasdk is the installation directory of MSS 2017 R3. But here MFX_HOME is to indicate the source code directory.
