### ISSUE TITLE
Xeon E-2176G (Coffeelake 3x8 GT2)

### ISSUE THREAD

**Issue by aungthetnaing** [Intel-Media-SDK/MediaSDK#1626]
We are having issues with : 
Xeon E-2176G (Coffeelake 3x8 GT2)

Is it officially supported? Init itself is failing for now.

**Comment by aungthetnaing** [comment]
Filed by error

**Comment by dmitryermilov** [comment]
Yes, CFL is supported. 
What is 'vainfo' output?
