### ISSUE TITLE
Cmake .. failed with error: Intel(R) Media SDK was not found (required)! Set/check MFX_HOME environment

### ISSUE THREAD

**Issue by rickffoliveira** [Intel-Media-SDK/MediaSDK#1638]
I did set up the environment variables and the Intel Media SDK folder is located in /opt/intel. I am using Ubuntu 18.04 and Intel CORE i7 7th Gen. I'm struggling to find out the solution. I put in attachment the error found. 
![Screenshot from 2019-09-12 15-28-35](https://user-images.githubusercontent.com/55255355/64812918-90943500-d576-11e9-84b8-2047a629d706.png)
Any help is appreciated!

**Comment by AntonGrishin** [comment]
I think `export MFX_HOME=/path/to/mediasdk` shall resolve this issue. Also based on cmake list of your project, you can you can use `cmake -DCMAKE_MFX_HOME=/path/to/mediasdk ..` for specify path where Media SDK installed.

**Comment by dmitryermilov** [comment]
Hi @rickffoliveira 

Was it solved?
