### ISSUE TITLE
vainfo fails when I run /opt/intel/mediasdk/bin/vainfo, which is extracted from MediaStack.tar.gz

### ISSUE THREAD

**Issue by wqdun** [Intel-Media-SDK/MediaSDK#1677]
Hi there, run **vainfo** failed:
![image](https://user-images.githubusercontent.com/24860235/65667523-7aa46b00-e072-11e9-92e5-4b595cda1612.png)
**The OS is:**
Ubuntu 16.04, with kernel 4.15.0-64-generic #73~16.04.1-Ubuntu SMP Fri Sep 13 09:56:18 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
**CPU:**
Model name:            Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz

**Error shows:**
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Is the hardware unsupported?
Thank you.

**Comment by onabiull** [comment]
Probably your system have two GPUs and /dev/dri/card0 (or /dev/dri/renderD128) mapped to the discrete one. Could you please try to run something like 
`sudo LIBVA_DRIVER_NAME=iHD LIBVA_DRIVERS_PATH=/opt/intel/mediasdk/lib64  /opt/intel/mediasdk/bin/vainfo --display drm --device /dev/dri/renderD128`
and change renderD128 to other render node available on your system. Most likely it would be renderD129.

**Comment by wqdun** [comment]
Hi @onabiull , thank you for the reply.
You were right, and it did work after I renamed card1 to card0, renderD129 to renderD128, the intel_gpu* command also showed the GPU usage. But is there a better way to assign the right Graphics Card when run commands like "sample_encode", if 2 cards are installed on PC?

But the PC crashed (the login loop problem) when reboot, I think the reason might be I have run "apt autoremove" command.
I didn't fix the crash problem, I just reinstalled the OS, this time I disabled the discrete Graphics Card. Then I installed SDK according to https://github.com/Intel-Media-SDK/MediaSDK/wiki/Build-Media-SDK-on-Ubuntu , after solving the below problems:
1. fatal error: CL/cl_va_api_media_sharing_intel.h: No such file or directory；
Found it on https://github.com/KhronosGroup/OpenCL-Headers ;
2. fatal error: CL/cl.hpp: No such file or directory;
Found it on opencv-3.3.0;
Finally I compiled SDK successfully.

Since libva is tags/2.1.1.pre1-20180601 (as https://github.com/Intel-Media-SDK/MediaSDK/wiki/Build-Media-SDK-on-Ubuntu ), so I try to find a corresponding intel/media-driver （on https://github.com/Intel-Media-SDK/MediaSDK/releases ）, failed. So I compiled https://github.com/intel/media-driver/releases/tag/intel-media-19.3.pre4 , didn't success until I "make install"ed https://github.com/intel/libva/releases/tag/2.5.0 .

I am still working on it, and thank you again.

**Comment by daleksan** [comment]
feel free to re-open if still actual
