### ISSUE TITLE
tracer for linux

### ISSUE THREAD

**Issue by aungthetnaing** [Intel-Media-SDK/MediaSDK#1686]
How to install Media SDK tracer for Linux?

**Comment by NaveenKumar-Intel** [comment]
Hi @aungthetnaing,

To install Media SDK tracer for Linux: Found some references, hope this helps.

Please find libmfx-tracer.so which is a part of MSDK close source packages. You can find it in /opt/intel/mediasdk/tools/tracer/. You can follow the readme file under this path.

Alternatively, you can also try the following steps to install Media SDK tracer for Linux: Reference @ [(How to use the Media SDK Tracer on Linux ?)](https://software.intel.com/en-us/forums/intel-media-sdk/topic/596058)

Step1 –
cd /opt/intel/mediasdk/lib64/
rm libmfxhw64.so
mv libmfxhw64-p.so.1.30 libmfxhw64-p-REAL.so.1.30

Step 2-  
export LD_LIBRARY_PATH=/opt/intel/mediasdk/tools/tracer:$LD_LIBRARY_PATH

Step3 - 
cd /opt/intel/mediasdk/tools/tracer/
ln -s libmfx-tracer.so libmfxhw64.so

Step4 – 
/opt/intel/mediasdk/tools/tracer/mfx-tracer-config --default            
/opt/intel/mediasdk/tools/tracer/mfx-tracer-config core.type file
/opt/intel/mediasdk/tools/tracer/mfx-tracer-config core.log ~/mfxtracer.log
/opt/intel/mediasdk/tools/tracer/mfx-tracer-config core.lib /opt/intel/mediasdk/lib64/libmfxhw64-p-REAL.so.1.30

Step5 - 
Run the sample application and you will see the output in the folder with above steps.
/usr/share/mfx/samples/sample_decode h264 -i content/test_stream.264.h264 -o out.yuv

**Comment by dvrogozh** [comment]
Plan was to improve/simplify tracer support on Linux with LD_PRELOAD mechanism, especially after a switch to dynamic dispatcher, but this effort never got investments:(. We will appreciate help in this direction.

**Comment by aungthetnaing** [comment]
Do you know where to get close source package? Whenever I use software.intel.com; I was redirected to this repo for Linux.

**Comment by liumark** [comment]
Hi Aung,
The public website at Intel Developer Zone(IDZ) is http://mediasdk.intel.com/, this is a general site, this one will guide you to Media SDK product site: https://software.intel.com/en-us/media-sdk
Let me know if you have any feedback.
Mark

**Comment by dmitryermilov** [comment]
@onabiull , @dvrogozh , @vvkalinin24 , any objection to opensource the tracer?

**Comment by onabiull** [comment]
It was already made available as part of MSS release https://github.com/Intel-Media-SDK/MediaSDK/releases/tag/MSS-2018-R2.2 see
https://github.com/Intel-Media-SDK/MediaSDK/tree/d07f8526c28e8579606ea086c99e9073f86d77af/tools/tracer
Still it need some refactoring and cleaning to land in master.
