### ISSUE TITLE
-dc::rgb4 in sample_multi_transcode error 

### ISSUE THREAD

**Issue by aungthetnaing** [Intel-Media-SDK/MediaSDK#1692]
I would like my decode pipeline to have rgb out and so I set up parfile as below: (ignore the composition, currently filling only 1 tile).

-i::h265 file.h265  -hw -vpp_comp_dst_x 0 -vpp_comp_dst_y 0 -vpp_comp_dst_w 1920 -vpp_comp_dst_h 1080  -dc::rgb4  -vpp_comp_tile_id 0   -join -o::sink
-vpp_comp_only 1 -vpp_comp_num_tiles 1 -rx11     -fps 10   -ext_allocator   -join -i::source

The error is:

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), CalculateNumberOfReqFrames, m_pmfxDEC.get failed at /home/movidius/mdk/examples/refApps/AICamera_generic/pc/decode_process/sample_multi_transcode/src/pipeline_transcode.cpp:3387

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), AllocFrames, CalculateNumberOfReqFrames failed at /home/movidius/mdk/examples/refApps/AICamera_generic/pc/decode_process/sample_multi_transcode/src/pipeline_transcode.cpp:3273

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), CompleteInit, AllocFrames failed at /home/movidius/mdk/examples/refApps/AICamera_generic/pc/decode_process/sample_multi_transcode/src/pipeline_transcode.cpp:3971

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), Init, m_pThreadContextArray[i]->pPipeline->CompleteInit failed at /home/movidius/mdk/examples/refApps/AICamera_generic/pc/decode_process/sample_multi_transcode/src/sample_multi_tran

**Comment by dmitryermilov** [comment]
Hi @aungthetnaing ,

does other pipelines(i mean e.g. single decode or encode) work on your side? I'm trying to understand if it's a composition specif issue.

**Comment by aungthetnaing** [comment]
I tried this:
**-i::h265 mbnet_videoStream4kHevc.h265    -dc::rgb4 -hw  -o::h264 out_transcode.264** 

Now, problem is moved to encoder:

libva info: va_openDriver() returns 0
plugin_loader.h :186 [INFO] Plugin was loaded from GUID: { 0x33, 0xa6, 0x1c, 0x0b, 0x4c, 0x27, 0x45, 0x4c, 0xa8, 0xd8, 0x5d, 0xde, 0x75, 0x7c, 0x6f, 0x8e } (Intel (R) Media SDK HW plugin for HEVC DECODE)

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), EncodePreInit, m_pmfxENC->Query failed at /home/movidius/mdk/examples/refApps/AICamera_generic/pc/decode_process/sample_multi_transcode/src/pipeline_transcode.cpp:542

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), Init, EncodePreInit failed at /home/movidius/mdk/examples/refApps/AICamera_generic/pc/decode_process/sample_multi_transcode/src/pipeline_transcode.cpp:3825

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), Init, pThreadPipeline->pPipeline->Init failed at /home/movidius/mdk/examples/refApps/AICamera_generic/pc/decode_process/sample_multi_transcode/src/sample_multi_transcode.cpp:305
plugin_loader.h :212 [INFO] MFXBaseUSER_UnLoad(session=0x0x55fd195e9750), sts=0

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), main, transcode.Init failed at /home/movidius/mdk/examples/refApps/AICamera_generic/pc/decode_process/sample_multi_transcode/src/sample_multi_transcode.cpp:908

**Comment by aungthetnaing** [comment]
what's I'm trying: 
I would like to overlay texts using openCV in decoded streams before composition into video wall. 

For single stream, I got it working in sample_decode when I passed -r -rgb4 options. So, I would need the rgb4 as decode out to be able to do that. 

-------------------------------------------------------------------------------------------------------------------------
  sts = m_pMFXAllocator->LockFrame(pmfxSurface->Data.MemId, &pmfxSurface->Data);
               MSDK_CHECK_STATUS(sts, "m_pMFXAllocator->LockFrame failed");
               // Do OSD here
               std::string framecnt = std::to_string((int)500);
               cv::Mat outgoing_img = cv::Mat(pmfxSurface->Info.Height, pmfxSurface->Info.Width ,
                       CV_8UC4, MSDK_MIN( MSDK_MIN(pmfxSurface->Data.R, pmfxSurface->Data.G), pmfxSurface->Data.B), pmfxSurface->Data.Pitch);
               cv::putText(outgoing_img, "I'm the overlay 44444", cv::Point(500,500), 0, 9, cv::Scalar(255, 0, 0, 255), 5, 8, false );
               // assert(0);
               sts = m_pMFXAllocator->UnlockFrame(pmfxSurface->Data.MemId, &pmfxSurface->Data);

**Comment by dmitryermilov** [comment]
> I tried this:
> -i::h265 mbnet_videoStream4kHevc.h265 -dc::rgb4 -hw -o::h264 out_transcode.264

This one won't work for sure because on Linux encoders don't accept RGB (while I recall on Windows it may work). 

> what's I'm trying:
> I would like to overlay texts using openCV in decoded streams before composition into video wall.

Ok, I got it. 

The main question to be on the same page: do I understand it correctly that eventually you'd like to have pipeline like below?
```
decode №1 -> openCV based text overlay ->
                                         |
                                         | -> composition "N to 1" -> encode
                                         |
decode №N -> openCV based text overlay ->
```

**Comment by aungthetnaing** [comment]
Yes, your pipeline diagram is correct. Text overlay is dynamic. We do need RGB for other purpose. (to connect to OpenVINO processes, etc) in the future. At this point, Text overlay is a good placeholder.

**Comment by dmitryermilov** [comment]
Good. Am I right that you strongly need **planar**  RGB (not merged)?
Decoder can output _planar_ RGB (which is actually done by internal color convention right after decoding from NV12 to RGB using HW SFC block.) But I'm not sure if composition supports planar RGB. I'll check.
Encoders, as I mentioned, can directly work _only_ with different forms of YCbCr but it can be solved by color conversion back from RGB to NV12/P010 (just before encode).

I'll debug what is wrong with parfile you originally posted.

**Comment by aungthetnaing** [comment]
OpenCV needs **interleave** RGB (that's what -dc::rgb4) correct? Which flag to try for dc:: for planar RGB?

**Comment by liumark** [comment]
@DmitryMalishev I tried the par file and I can reproduce the issue, the only thing I found is error message was little bit different.

By removing "-dc::rgb4" and "-rx11" from the par file, it works.

Since I didn't quite understand @aungthetnaing's scenario, I thought he was trying to output raw stream without encoding, so I add "-o::raw", this one has the same result--I have to remove both "-dc::rgb4" and "-rx11".

I can't find "-rx11" in our document, so I think that was wrong.

**Comment by dmitryermilov** [comment]
Hi Mark,

Probably you meant me not Dmitry Malishev :). 
Anyway, Aung got (we chatted a bit) a workable prototype of desired pipeline with some code changes. 
So _probably_ the current issue is not actual anymore.
**BUT** it would be great to have an example of interoperability with OpenCV as a part of sample_multi_transcode. From a good design perspective such OpenCV logic, IMO, should be located in a plug-in (examples are [here](https://github.com/Intel-Media-SDK/MediaSDK/tree/master/samples/sample_plugins/rotate_cpu) and [here ](https://github.com/Intel-Media-SDK/MediaSDK/tree/master/samples/sample_plugins/rotate_opencl)).

**Comment by aungthetnaing** [comment]
Added new options to force a decoder side VPP. I'm closing the issue for now. Once I have code cleaned up, I'll try to create a pull request.

**Comment by aungthetnaing** [comment]
"I can't find "-rx11" in our document, so I think that was wrong."

That's in pdf document. Required -rdrm OR -rx11 in Linux.

**Comment by aungthetnaing** [comment]
Please ignore my above comment. https://github.com/Intel-Media-SDK/MediaSDK/blob/master/doc/samples/readme-multi-transcode_linux.md seems incomplete. I was referring to PDF shipped with OpenVINO installed MediaSDK. I think we should correct it in https://github.com/Intel-Media-SDK/MediaSDK/blob/master/doc/samples/readme-multi-transcode_linux.md
