### ISSUE TITLE
using MediaSDK on centos 7.7

### ISSUE THREAD

**Issue by AvnerGidron305** [Intel-Media-SDK/MediaSDK#1702]
Hi,
I would like to use MediaSDK on Centos 7.7.
Is this possible?
I have this guide that using 7.5: https://01.org/node/30758
Thanks,
Avner

**Comment by onabiull** [comment]
Given compatible kernel (i915 kernel mode driver in the first hand) yes. This guide should work just well https://github.com/Intel-Media-SDK/MediaSDK/wiki/Build-Media-SDK-on-CentOS.

**Comment by dvrogozh** [comment]
It should be possible. While centos kernel is nominally 3.10, i915 driver is actually forklifted to at least 4.14 level (I looked ~a year ago). By now I suspect it correspond to 4.19.

**Comment by liumark** [comment]
From @dvrogozh's message, CentOS 7.7 has kernel 3.10 which requires kernel patch. The guide from @onabiull should cover this.
Is this correct?

**Comment by onabiull** [comment]
@liumark, actually vice versa. CentOS have 3.10 kernel, which contain i915 patches from newer kernels. There are chances that media stack would just work w/o patching. Wiki article is a guide how to build Media SDK.

**Comment by liumark** [comment]
Got it, I will work with @AvnerGidron305 assume the patch was applied.

**Comment by AvnerGidron305** [comment]
Hi, I've tried using the guide in: https://github.com/Intel-Media-SDK/MediaSDK/wiki/Build-Media-SDK-on-CentOS.
I'm failing to compile while using "make" command after the "./autogen.bash"
make output in here:
[make_result.txt](https://github.com/Intel-Media-SDK/MediaSDK/files/3694275/make_result.txt)

**Comment by AvnerGidron305** [comment]
Hi,
Iv'e finished the wiki guide successfully though i had to make some changes.
Now it seems i lack the required driver.
Here's a snapshot of "vainfo":
![Screenshot from 2019-10-07 14-07-58](https://user-images.githubusercontent.com/17855767/66307198-7ac32700-e90c-11e9-9780-02576e04377a.png)
This also happens when trying to use: https://01.org/node/30758   
Any thoughts?
thanks, Avner

**Comment by dmitryermilov** [comment]
Hi Avner,

Please try to set LIBVA_DRIVERS_PATH and LIBVA_DRIVER_NAME:
```
export LIBVA_DRIVERS_PATH="/opt/intel/mediasdk/lib64"
export LIBVA_DRIVER_NAME="iHD"
```

Regards,
Dmitry

**Comment by dmitryermilov** [comment]
Hi @AvnerGidron305 ,

Any news?
