### ISSUE TITLE
chroma_siting feature doesn't work for sample_vpp in Linux

### ISSUE THREAD

**Issue by liumark** [Intel-Media-SDK/MediaSDK#1737]
I knew this feature was fixed on Windows and I can confirm with following command:
sample_vpp.exe -sw 960 -sh 540 -scc rgb4 -dw 960 -dh 540 -dcc nv12 -chroma_siting vcen hcen -i test.rgb -o output.nv12

But the same command line doesn't work on Linux.
Mark

**Comment by NaveenKumar-Intel** [comment]
Hi @liumark,
I tried following command on CL & Linux and it works fine for me. 

**/usr/share/mfx/samples/sample_vpp -sw 1280 -sh 720 -scc rgb4 -dw 1280 -dh 720 -dcc nv12 -chroma_siting vcen hcen -i out_sintel_1280x720.rgb -o output_sintel.nv12 -n 100**

Please find following output file generated with above command:
[output_sintel.zip](https://github.com/Intel-Media-SDK/MediaSDK/files/3751631/output_sintel.zip)

ias@clr-d3c8ee47e70e45ce8e7c0b93146f7b97 /mnt/Video_Content/RGB $ /usr/share/mfx/samples/sample_vpp -sw 1280 -sh 720 -scc rgb4 -dw 1280 -dh 720 -dcc nv12 -chroma_siting vcen hcen -i out_sintel_1280x720.rgb -o output_sintel.nv12 -n 100

VPP_WRN: some filter(s) skipped
Input format    RGB4
Resolution      1280x720
Crop X,Y,W,H    0,0,1280,720
Frame rate      30.00
PicStruct       progressive
Output format   NV12
Resolution      1280x720
Crop X,Y,W,H    0,0,1280,720
Frame rate      30.00
PicStruct       progressive

Video Enhancement Algorithms
Deinterlace     OFF
Signal info     OFF
Scaling         OFF
CromaSiting             ON
Denoise         OFF
MCTF            OFF
ProcAmp         OFF
DetailEnh       OFF
GamutMapping    OFF
ColorSaturation OFF
ContrastEnh     OFF
SkinToneEnh     OFF
MVC mode        OFF
ImgStab         OFF

IOpattern type                  sys_to_sys
Number of asynchronious tasks   1
Time stamps checking            OFF
ROI checking                    OFF

MediaSDK impl   hw
HW accelaration is enabled
MediaSDK ver    1.28
VPP started
Frame number: 100
VPP finished

Total frames 100
Total time 2.82 sec
Frames per second 35.423 fps
ias@clr-d3c8ee47e70e45ce8e7c0b93146f7b97 /mnt/Video_Content/RGB $

Is your result different then the above?

**Comment by liumark** [comment]
Hi Kumar,
I check the zip file but I can't tell which pattern you are using.
I used a specific pattern to check.
Mark

**Comment by NaveenKumar-Intel** [comment]
Hi @liumark,
Can you please tell the pattern you are using? We will verify here and let you know the result.

**Comment by AntonGrishin** [comment]
Hi @liumark,
Currently, I can`t reproduced you issue (I tried different pattern).
If you have any additional  information, please feel free to send email to me.

**Comment by liumark** [comment]
Hi @AntonGrishin ,
Let's move to internal issue ticket to continue.
Mark
