### ISSUE TITLE
Performance of Kabylake encoding, how to optimize

### ISSUE THREAD

**Issue by tracy626** [Intel-Media-SDK/MediaSDK#174]
I have tested performance of encoding on my Kabylake machine, kernel and cpu info:
```
3.10.0-693.el7.x86_64
Intel(R) Core(TM) m3-7Y30 CPU @ 1.00GHz
```
Encoding test details, the raw yuv file is 1920x1080 and 60 fps 
```
$ time ./sample_encode h264 -hw -i TransStream_full60.yuv -w 1920 -h 1080 -nv12 -u veryslow -f 60 -o test.h264
libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /opt/intel/mediasdk/lib64/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_1
libva info: va_openDriver() returns 0
Encoding Sample Version 8.3.26.

Input file format	NV12
Output video		AVC 
Source picture:
	Resolution	1920x1088
	Crop X,Y,W,H	0,0,1920,1080
Destination picture:
	Resolution	1920x1088
	Crop X,Y,W,H	0,0,1920,1080
Frame rate	60.00
Bit rate(Kbps)	6271
Gop size	0
Ref dist	0
Ref number	0
Idr Interval	0
Target usage	quality
Memory type	system
Media SDK impl		hw
Media SDK version	1.26

Processing started
Frame number: 2418

Processing finished

real	0m19.053s
user	0m12.184s
sys	0m8.287s



$ time ./sample_encode h265 -hw -i TransStream_full60.yuv -w 1920 -h 1080 -nv12 -u veryslow -f 60 -o test.h265
plugin_loader.h :178 [INFO] Plugin was loaded from GUID: { 0x6f, 0xad, 0xc7, 0x91, 0xa0, 0xc2, 0xeb, 0x47, 0x9a, 0xb6, 0xdc, 0xd5, 0xea, 0x9d, 0xa3, 0x47 } (Intel (R) Media SDK HW plugin for HEVC ENCODE)
libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /opt/intel/mediasdk/lib64/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_1
libva info: va_openDriver() returns 0
Encoding Sample Version 8.3.26.

Input file format	NV12
Output video		HEVC
Source picture:
	Resolution	1920x1088
	Crop X,Y,W,H	0,0,1920,1080
Destination picture:
	Resolution	1920x1088
	Crop X,Y,W,H	0,0,1920,1080
Frame rate	60.00
Bit rate(Kbps)	54464
Gop size	0
Ref dist	0
Ref number	0
Idr Interval	0
Target usage	quality
Memory type	system
Media SDK impl		hw
Media SDK version	1.26

Processing started
Frame number: 2418
plugin_loader.h :204 [INFO] MFXBaseUSER_UnLoad(session=0x0x19f2330), sts=0

Processing finished

real	1m36.095s
user	0m20.358s
sys	0m15.423s
```

As you can see, fps of avc encoding is about 130 but for hevc only can do 25 fps.
My expectation fps for hevc encoding is above 60 fps.

Do you have any suggestions for me to optimize the encoding performance?

**Comment by tracy626** [comment]
Here is the outout specifying bitrate and usage, it looks that there is not very large change on hevc.
```
$ time ./sample_encode h264 -hw -i TransStream_full60.yuv -w 1920 -h 1080 -nv12 -u veryslow -f 60 -b 6000 -o test.h264
libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /opt/intel/mediasdk/lib64/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_1
libva info: va_openDriver() returns 0
Encoding Sample Version 8.3.26.

Input file format	NV12
Output video		AVC 
Source picture:
	Resolution	1920x1088
	Crop X,Y,W,H	0,0,1920,1080
Destination picture:
	Resolution	1920x1088
	Crop X,Y,W,H	0,0,1920,1080
Frame rate	60.00
Bit rate(Kbps)	6000
Gop size	0
Ref dist	0
Ref number	0
Idr Interval	0
Target usage	quality
Memory type	system
Media SDK impl		hw
Media SDK version	1.26

Processing started
Frame number: 2418

Processing finished

real	0m17.734s
user	0m10.477s
sys	0m7.041s


$ time ./sample_encode h265 -hw -i TransStream_full60.yuv -w 1920 -h 1080 -nv12 -u veryslow -f 60 -b 6000 -o test.h265
plugin_loader.h :178 [INFO] Plugin was loaded from GUID: { 0x6f, 0xad, 0xc7, 0x91, 0xa0, 0xc2, 0xeb, 0x47, 0x9a, 0xb6, 0xdc, 0xd5, 0xea, 0x9d, 0xa3, 0x47 } (Intel (R) Media SDK HW plugin for HEVC ENCODE)
libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /opt/intel/mediasdk/lib64/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_1
libva info: va_openDriver() returns 0
Encoding Sample Version 8.3.26.

Input file format	NV12
Output video		HEVC
Source picture:
	Resolution	1920x1088
	Crop X,Y,W,H	0,0,1920,1080
Destination picture:
	Resolution	1920x1088
	Crop X,Y,W,H	0,0,1920,1080
Frame rate	60.00
Bit rate(Kbps)	6000
Gop size	0
Ref dist	0
Ref number	0
Idr Interval	0
Target usage	quality
Memory type	system
Media SDK impl		hw
Media SDK version	1.26

Processing started
Frame number: 2418
plugin_loader.h :204 [INFO] MFXBaseUSER_UnLoad(session=0x0xbb1330), sts=0

Processing finished

real	1m30.313s
user	0m21.154s
sys	0m15.796s
```

**Comment by DavidMarec** [comment]
I am facing a similar situation on a APL based architecture (HD-Graphics 505/E3950):
About 25' to encode 100 frames (4096x2160). - _On another architecture it takes less than 7'_ . - 

I notice the huge difference between the `user+sys` time and the elapsed time.
That means than from the process side, the main part of the job is done **off-cpu**. The process is waiting most of the time.
I replaced the `fread` accesses by direct memory accesses using `mmap`, what makes  sys time decrease (a lot) and user time increase (a bit).
But, the _waiting_ duration remains  at the same level.
What may cause that delay ? encoding computations done by the chipset ?
How to measure it or how to understand the latency issue ?
Does the test results from the installer process may help in any way ?

**Comment by dvrogozh** [comment]
MediaSDK offloads tasks to GPU, hence you will see CPU waiting for these tasks to be finished. If you don't do much on the CPU, you will see just few % of CPU usage. If you want to monitor what GPU is doing, your best chance is to install 4.16+ linux kernel which has enabled i915 performance counters. Use like:
`perf stat -a -e i915/bcs0-busy/,i915/rcs0-busy/,i915/vcs0-busy/,i915/vcs1-busy/,i915/vecs0-busy/ <your_workload>.sh
`
This command will give you time during which each GPU engine was busy (you may need to drop i915/vcs1-busy/ if your HW does not support 2nd VDBOX). Option -a is a must since i915 supports only global counters. Better to run under root since running under general user will require special privileges. For encoding workloads you should expect to see the load on RCS0 and VCS0. You may always have some load on BCS0 and RCS0 if you run under some GUI (X Windows for example).

> Here is the output specifying bitrate and usage, it looks that there is not very large change on hevc.

Changing bitrate may give some impact on the performance, but I think it will be pretty small. That's because of Intel GPU architecture specifics. What should give a real difference is usage. Could you, please, try the following variants: -u 1, -u 4, -u 7? For what I see at the moment you have tried only -u 1 (veryslow).

Also, running encoding, please, make sure to dismiss results from the very first run since it will be significantly impacted by the time loading YUV into the memory. On the 2+ runs you should get benefits from the OS caching...

**Comment by adydychk** [comment]
@tracy626 Can we close this issue if you are satisfied with the answers?

**Comment by adydychk** [comment]
Feel free to reopen it or create new one.
