### ISSUE TITLE
Some function may occurred “divide by zero” when specially illegal input stream (generated by AFL)

### ISSUE THREAD

**Issue by jianbingzhu** [Intel-Media-SDK/MediaSDK#1741]
I am using AFL for SMTA fuzzing  security vulnerability checking. SMTA used MSDK libs for video decode/encode/vpp…

Now we found 2 MSDK FloatingPointException ( “divided by zero” may occurred in some functions when using specially illegal input streams) when testing SMTA. 

The source file mfx_h264_enc_common_hw.cpp is at https://github.com/Intel-Media-SDK/MediaSDK/blob/master/_studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp. Line 532 in function GetMaxNumRefFrame and line 971 in function calculateMfeTimeout, which are highlight.

mfxU16 GetMaxNumRefFrame(mfxU16 level, mfxU16 width, mfxU16 height)
    {
        mfxU32 maxDpbSize = 0;
        ……
        mfxU32 frameSize = width * height * 3 / 2;
        return mfx::clamp<mfxU16>(maxDpbSize / **frameSize**, 1, 16);
    }

mfxU32 calculateMfeTimeout(const mfxFrameInfo& info)
    {
        //Just calculate based on latency expectation from framerate in microsecond now, can be changed in future
        return mfxU32((mfxU64)info.FrameRateExtD * 1000000 / **info.FrameRateExtN**);
}

**Comment by jianbingzhu** [comment]
SMTA source code is at https://github.com/VCDP/SMTA. please refer 7.2 for SMTA building in https://github.com/VCDP/SMTA/blob/master/doc/SMTA_User_Guide.pdf.
bug reproduce SMTA command-line: 
      StreamingMediaTranscoder -params -i::h264  <crash_input>  -o::h264 -w 480 -h 720 /dev/null

**Comment by jianbingzhu** [comment]
please give me a link to upload the crash_inputs?

**Comment by xiajin-2007** [comment]
Update input files for this issue.
[crash_inputs.zip](https://github.com/Intel-Media-SDK/MediaSDK/files/3812033/crash_inputs.zip)
