### ISSUE TITLE
how to encode h265 video file  in lookahead  bitrate mode?

### ISSUE THREAD

**Issue by 3703liu** [Intel-Media-SDK/MediaSDK#1743]
when encoding H264  video, the lookahead rate control method  can improve the encoding quality . So I want to encode h265 video file in lookahead mode too.
I don't know how to use the LA mode for h265 encoding. I think the la_ext is  the implementation for  h265 LA mode., so my command line is :
./sample_multi_transcode -i::h265 input.265 -o::h265  out.hevc -b 3000 -w 1920 -h 1080 -u 4   -lad 100 -la_ext

The result is:
---------------------------------------------------------------------------------------------------
Multi Transcoding Sample Version 8.4.27.

libva info: VA-API version 1.0.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /opt/intel/mediasdk/lib64/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_0
libva info: va_openDriver() returns 0
Session 0:
plugin_loader.h :185 [INFO] Plugin was loaded from GUID: { 0x58, 0x8f, 0x11, 0x85, 0xd4, 0x7b, 0x42, 0x96, 0x8d, 0xea, 0x37, 0x7b, 0xb5, 0xd0, 0xdc, 0xb4 } (Intel (R) Media SDK plugin for LA ENC)

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), EncodePreInit, m_pmfxENC->Query failed at /home/lpb/git_hub/MediaSDK/samples/sample_multi_transcode/src/pipeline_transcode.cpp:461

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), Init, EncodePreInit failed at /home/lpb/git_hub/MediaSDK/samples/sample_multi_transcode/src/pipeline_transcode.cpp:3721

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), Init, pThreadPipeline->pPipeline->Init failed at /home/lpb/git_hub/MediaSDK/samples/sample_multi_transcode/src/sample_multi_transcode.cpp:442
plugin_loader.h :211 [INFO] MFXBaseUSER_UnLoad(session=0x0x56331c850c50), sts=0

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), main, transcode.Init failed at /home/lpb/git_hub/MediaSDK/samples/sample_multi_transcode/src/sample_multi_transcode.cpp:1169

- -------------------------------------------------------------------------------------------------
My CPU is i7-6700HQ.  API version is 1.28. Libva version is 1.0
So how to encode h265 in lookahead mode?  And whether my CPU and the driver  version support the h265 LA mode?

**Comment by NaveenKumar-Intel** [comment]
Hi @3703liu,
I can reproduce the above issue on CL. 
Found that currently it does not have support for HEVC encode lookahead bitrate mode. 

Verified above logs and observed that It tries to load **h264 lookahead plugin instead of hevc**. 
[ERROR], sts=MFX_ERR_NULL_PTR(-2), Init, m_fSource pointer is NULL at /builddir/build/BUILD/MediaSDK-intel-mediasdk-19.2.0/samples/sample_common/src/sample_utils.cpp:478
**plugin_loader.h :185 [INFO] Plugin was loaded from GUID: { 0x58, 0x8f, 0x11, 0x85, 0xd4, 0x7b, 0x42, 0x96, 0x8d, 0xea, 0x37, 0x7b, 0xb5, 0xd0, 0xdc, 0xb4 } (Intel (R) Media SDK plugin for LA ENC)**

You can find above GUID reference in the source code: @ ~/MediaSDK/api/include/mfxplugin.h
static const mfxPluginUID  **MFX_PLUGINID_H264LA_HW**       = {{0x58, 0x8f, 0x11, 0x85, 0xd4, 0x7b, 0x42, 0x96, 0x8d, 0xea, 0x37, 0x7b, 0xb5, 0xd0, 0xdc, 0xb4}};

**Comment by 3703liu** [comment]
Hi, @NaveenKumar-Intel,Thanks for your reply.
I am now confused about the lookahead  bitrate mode for  hevc. Can you help me?

1.  In the descriptions of options  of the sample_multi_transcode, which can be got by ./sample_multi_transcode -?.  There is a description as follows:
-la_ext       Use external LA plugin (compatible with h264 & hevc encoders)
Previously  I think the LA plugin can be used for  both h264 & hevc encoders.  
So in fact  is the  MFX_PLUGINID_H264LA_HW plugin  only works for h264 encoders and it cann't be used for hevc encoders?

2. I find a Class named VMEBrc in the file mfx_h265_encode_hw_brc.cpp. The class seems to be the  implementation of hevc lookahead bitrate mode. And it seems the VMEBrc can be used when initialing the hevc encoder.
So is the VMEBrc designed for LA mode or it is for some other bit rate method?

Appreciate  for your help!

**Comment by NaveenKumar-Intel** [comment]
Hi @3703liu,
With the info provided by @**Kulakov, Timofei A**, I was able to run the following **lookahead for HEVC encode**.
 
To use lookahead for HEVC encode, you need to have h264 LA plugin and the HEVC HW encode plugin, run in separate sessions. Please use the attached **hevc_la.par** file as an example.
[hevc_la.zip](https://github.com/Intel-Media-SDK/MediaSDK/files/3796740/hevc_la.zip)

ias@clr-733ea8e3fa524aa587f789b379ab855d/tmp $ **/usr/share/mfx/samples/sample_multi_transcode -par hevc_la.par**
Multi Transcoding Sample Version 8.4.27.

Par file is: hevc_la.par

libva info: VA-API version 1.5.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /usr/lib64/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_5
libva info: va_openDriver() returns 0
Session 0:
plugin_loader.h :186 [INFO] Plugin was loaded from GUID: { 0x58, 0x8f, 0x11, 0x85, 0xd4, 0x7b, 0x42, 0x96, 0x8d, 0xea, 0x37, 0x7b, 0xb5, 0xd0, 0xdc, 0xb4 } (Intel (R) Media SDK plugin for LA ENC)
MFX HARDWARE Session 0 API ver 1.30 parameters:
Input  video: HEVC
Output video: To child session

Session 1:
[WARNING] Configuration changed on the Query() call
mfx.LowPower:0 changed to mfx.LowPower:32
mfx.BRCParamMultiplier:0 changed to mfx.BRCParamMultiplier:1
mfx.NumSlice:0 changed to mfx.NumSlice:1
ext.265P.PicHeightInLumaSamples:1080 changed to ext.265P.PicHeightInLumaSamples:1088
MFX HARDWARE Session 1 API ver 1.30 parameters:
Input  video: From parent session
Output video: HEVC

Pipeline surfaces number (DecPool): 62
Session 0 was joined with other sessions
Session 1 was joined with other sessions

Transcoding started
......
Transcoding finished

Common transcoding time is 23.169 sec
-------------------------------------------------------------------------------
*** session 0 [0x5589ecd1bf00] PASSED (MFX_ERR_NONE) 23.1022 sec, 600 frames
-i::h265 /tmp/hevc_1080p.h265 -o::sink -hw -async 1 -la -la_ext -bpyr -dist 8 -join

*** session 1 [0x5589ecd470e0] PASSED (MFX_ERR_NONE) 23.1686 sec, 600 frames
-i::source -o::h265 /tmp/out_new.265 -u 4 -hw -b 500 -async 1 -bpyr -dist 8 -join

-------------------------------------------------------------------------------

The test PASSED
plugin_loader.h :212 [INFO] MFXBaseUSER_UnLoad(session=0x0x5589ecd1bf00), sts=0
ias@clr-733ea8e3fa524aa587f789b379ab855d/tmp $

Please verify and let us know if it works for you as well.

**Comment by 3703liu** [comment]
Hi @NaveenKumar-Intel.
It works for me too! Thanks very much ~
