### ISSUE TITLE
Getting Error when git clone MediaSDK wiht git-lfs

### ISSUE THREAD

**Issue by LukeZheZhu** [Intel-Media-SDK/MediaSDK#1761]
Clone MediaSDK with the command: git clone https://github.com/Intel-Media-SDK/MediaSDK.git

**Result:** 
Cloning into 'MediaSDK'...
remote: Enumerating objects: 65, done.
remote: Counting objects: 100% (65/65), done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 20459 (delta 18), reused 26 (delta 10), pack-reused 20394
Receiving objects: 100% (20459/20459), 33.81 MiB | 3.72 MiB/s, done.
Resolving deltas: 100% (12012/12012), done.
Checking connectivity... done.
Downloading doc/HEVC_FEI_overview.pdf (8.3 MB)
Error downloading object: doc/HEVC_FEI_overview.pdf (eef7dc4): Smudge error: Error downloading doc/HEVC_FEI_overview.pdf (eef7dc466b868b254f0e7a39acee7aa87623a293dee9615adced86a550c52e79): batch response: Post https://github.com/Intel-Media-SDK/MediaSDK.git/info/lfs/objects/batch: proxyconnect tcp: EOF

Errors logged to /home/lukezhu/MediaSDK/.git/lfs/logs/20191112T191953.180265949.log
Use `git lfs logs last` to view the log.
error: external filter git-lfs smudge -- %f failed 2
error: external filter git-lfs smudge -- %f failed
fatal: doc/HEVC_FEI_overview.pdf: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

**Comment by onabiull** [comment]
Looks like proxy configuration issue. Please check if you have correct [http] and [https] sections in your ~/.gitconfig
I've just checked that regular ```git clone/git lfs install/git lfs fetch/git lfs`checkout``` sequence works as expected on CentOS 7.
