### ISSUE TITLE
ffmpeg 1:N transcoding failed with different framerate setting for different output

### ISSUE THREAD

**Issue by paulli2017** [Intel-Media-SDK/MediaSDK#1768]
Hi,
I followed the instruction below for ffmpeg 1:N transcoding test:
https://github.com/Intel-Media-SDK/MediaSDK/wiki/Build-and-use-ffmpeg-with-MediaSDK

I don't have any issue with the example in the instruction, but I do have issue with the test case
I created and it won't even start to do trans-coding.  Here is the test cases that won't work: 

ffmpeg -hwaccel qsv -c:v hevc_qsv -i CrowdRun_3840x2160_40Mbps_50fps_500f.hevc -filter_complex "split=2[s1][s2]; [s1]scale_qsv=1920:1080, vpp_qsv=framerate=60[o1]; [s2]scale_qsv=1920:1080,vpp_qsv=framerate=30[o2]" -map [o1] -c:v h264_qsv -b:v 20M 1920x1080_60fps_20M.mp4 -map [o2] -c:v h264_qsv -b:v 10M 1920x1080_30fps_10M.mp4

Could anyone please help take a look at this?

Thanks.
Paul

**Comment by AntonGrishin** [comment]
Hi Paul,

I checked you cmd (but with another stream), and seems that all works.
cmd:

Log:  [ffmpeg.log](https://github.com/Intel-Media-SDK/MediaSDK/files/3879123/ffmpeg.log)
Note: `-y` in cmd is for overwrite output files.

Regards,
Anton

**Comment by paulli2017** [comment]
> Hi Paul,
> 
> I checked your cmd on my SKL machine (but with another stream), and seems that all works.
> Log: [ffmpeg.log](https://github.com/Intel-Media-SDK/MediaSDK/files/3879131/ffmpeg.log)
> 
> Note: `-y` in cmd is for overwrite output files.
> 
> Regards,
> Anton

Hi Anton,

Thanks for your response!  Please use the file as in the input. Here is the fie link:
\\smakramu-desk1\Shared\Media_Delivery
if you still can't access the file, please try another input file at 50fps.
We have reproduced this issue from another team. Please let me know your update.

Thanks.
Paul

**Comment by AntonGrishin** [comment]
Hi @paulli2017,

Can you please try with an updated guide?
```
ffmpeg -hwaccel qsv -c:v h264_qsv -i AUD_MW_60FPS.264  \
       -filter_complex "split=2[s1][s2];               \
                        [s1]scale_qsv=1280:720[o1];    \
                        [s2]fps=fps=30[o2]"            \
       -map -[o1] -c:v h264_qsv -b:v 5M 5M.mp4         \
       -map -[o2] -c:v h264_qsv -b:v 4M 4M60FPS.h264
```
**Note:** here we are using "fps" option to FRC.

**Comment by IsoaSFlus** [comment]
@AntonGrishin  I found that vpp_qsv=framerate seems not work when changing fps to a number less than original fps (eg 60 fps to 30fps). Is it a bug or just a limitation? What's the correct way to reduce fps with qsv acceleration? Thanks!

**Comment by dvrogozh** [comment]
> I found that vpp_qsv=framerate seems not work when changing fps to a number less than original fps

That's a bug in ffmpeg-qsv framerate conversion. However, ffmpeg maintainers decision is to avoid fixing it and stick with ffmpeg usual fps filter. So, correct way is to go with fps filter as in example which was posted by @AntonGrishin. See details here: https://patchwork.ffmpeg.org/project/ffmpeg/patch/1582903831-20063-1-git-send-email-linjie.fu@intel.com/

**Comment by daleksan** [comment]
Wiki was updated, closing the issue
