### ISSUE TITLE
MFXVideoUSER_Load and a few symbols are missing in libmfxsw64.dll

### ISSUE THREAD

**Issue by seungha-yang** [Intel-Media-SDK/MediaSDK#1779]
I tried to drop build-time MediaSDK dependency for upstream gstreamer msdk plugin to be easier use of Intel MediaSDK (+ easier shipping/packaging). This is working branch https://gitlab.freedesktop.org/seungha.yang/gst-plugins-bad/commits/msdk-dynamic-loading

The issue there is some symbols `MFXVideoUSER_Load`, `MFXVideoUSER_LoadByPath` and `MFXVideoUSER_UnLoad` are missing in `libmfxsw64.dll`. But `libmfx.so.1` has them on linux. Is it by design or can be fixed by Intel MediaSDK side?

**Comment by onabiull** [comment]
This considered an implementation detail. ``libmfx.so.1`` is a so called dispatcher library, which would load libmfx**hw**64.so or (deprecated, absent in open source libmfx**sw**64.so) see https://github.com/Intel-Media-SDK/MediaSDK/blob/master/doc/mediasdk-man.md#architecture. It is possible, although not recommended, to bypass dispatcher. But in this case you'll have to provide correct flags to ``MFXInit`` and call ``MFXVideoUSER_Register`` and ``MFXVideoUSER_Unregister`` manually. Essentially implement Dispatcher functionality in your gst plugin.

**Comment by dmitryermilov** [comment]
>It is possible, although not recommended, to bypass dispatcher 

@onabiull , hold on, I'd like to ask for more details from @pudding8757. While there is an **official** way to load MSDK via the dispatcher, why where is a need to bypass it by using some workarounds?

**Comment by pudding8757** [comment]
@dmitryermilov The primary goal of mine is removing build-time MediaSDK dependency, so if we can use the dispatcher in some other ways, bypassing would not be required I guess.

One of reason for removing the build-time dependency is, it would make it possible to official gstreamer release include the msdk plugin. For now, most hardware dependent plugins were not part of official gstreamer release, since they require build-time dependent stuff. Recently, we've removed all build-time dependency of nvidia encoder/decoder plugin from gstreamer side. That means nvidia encoder/decoder plugin would be candidate of official gstreamer release. In this context, I want to make msdk also be released together if possible.

**Comment by dmitryermilov** [comment]
Thanks for reply . What do you mean by "build-time MediaSDK dependency"?
Generally app, which uses MSDK, needs :
1. **MSDK headers** for compilation
2.  a library (static or shared) which would expose exported API functions. 

How are you going to remove headers dependencies? 

Generally, what you'tr trying to do here: https://gitlab.freedesktop.org/seungha.yang/gst-plugins-bad/commit/14f4fb64de0202b0d115e9681980b85b61e1feb8#595b6accb61b00608ab3c2671533417f00b34e32 is **already** done here https://github.com/Intel-Media-SDK/MediaSDK/tree/master/api/mfx_dispatch/linux

MSDK is distributed with a pkg-config file. So I assume at gst build system you simply need to check if MSDK is available on the system and if so, you should use headers path and required linkage library (i mean libmfx.so)  which pkg-config tells to use.

**Comment by pudding8757** [comment]
> How are you going to remove headers dependencies?

Possibly, gstreamer can ship MSDK headers for compilation without system installation of MSDK bits. 
Note that, there are some plugins which are shipping SDK headers for compilation as far as I know.

 > MSDK is distributed with a pkg-config file. So I assume at gst build system you simply need to check if MSDK is available on the system and if so, you should use headers path and required linkage library (i mean libmfx.so) which pkg-config tells to use.

gstreamer build system already uses the pkg-config for compilation :) But releasing/distribution is a little different story IMHO. One (my) use case is, I could not install MSDK stuff for some reasons on my application build machine, but my target system required the MSDK encoder/decoder.

The best for my use case I think is that MSDK provides a structure of function table like x264 or nvdia encoder. For example

1. MSDK provides a method for API function table load
2. Users load `entry point` library using dlopen
3. Load the symbol from `entry point` library then load an API function table from that
and so on..

**Comment by xhaihao** [comment]
> Possibly, gstreamer can ship MSDK headers for compilation without system installation of MSDK bits.
> Note that, there are some plugins which are shipping SDK headers for compilation as far as I know.

AFAIK MediaSDK has been integrated into some distribution, e.g. https://packages.ubuntu.com/source/eoan/intel-mediasdk.  Is it still required to ship MSDK headers in gstreamer?

**Comment by pudding8757** [comment]
@xhaihao Considering the case of Windows, shipping still seems worthwhile.

**Comment by dmitryermilov** [comment]
Hi @pudding8757 ,

Yes, I understand your point about building and distribution (which may need less dependencies).
And I see your point regarding headers. 
Coming back to the original issue, can you use the dispatcher I referred to ? You may borrow at and build _statically_ if you wish.

**Comment by dmitryermilov** [comment]
Hi @pudding8757 , do you have any news?
