### ISSUE TITLE
Excessive Memory Usage when decoding using MediaSDK

### ISSUE THREAD

**Issue by smrowe4** [Intel-Media-SDK/MediaSDK#1789]
MediaSDK requires >500 MB of memory when decoding h264 clips.  For example, sample_decode h264 -i input.h264 -hw -vaapi will require >500 MBs of memory.  Centos doesn't seem to show this issue requiring only ~60 MB's of memory/stream.  Not clear why Centos is requiring less than Ubuntu 18.

**Comment by dmitryermilov** [comment]
Can you please describe:

- CentOS version
- kernel version
- MSDK/UMD/libgmm versions

and attach a video clip
?

**Comment by smrowe4** [comment]
Release builds use the expected amount of memory, roughly 50 MB for 1080p decode.  Release-internal and debug builds use roughly 10x.  Since release builds use the expected amount of memory, this is not an issue.

**Comment by dmitryermilov** [comment]
Thank you for confirmation!
