### ISSUE TITLE
commit 444ecb4 caused regression in vp9 decoder

### ISSUE THREAD

**Issue by xhaihao** [Intel-Media-SDK/MediaSDK#1790]
The output Shift is not set since commit commit 444ecb4, which results in regression when running a gst-msdk pipeline:

https://github.com/Intel-Media-SDK/MediaSDK/commit/444ecb480a3918cc6faeb7662ca7492fd564f301#diff-d8bc9fb5bc14276fa6b733fff663ba7aL151-L153

gst-launch-1.0 filesrc location=input.10bit.ivf ! ivfparse ! msdkvp9dec ! fakesink

Redistribute latency...
0:00:00.021322781 15413 0x557733521050 ERROR                msdkdec gstmsdkdec.c:396:gst_msdkdec_init_decoder:<msdkvp9dec0> Init failed (invalid video parameters)
    0:00:00.021337017 15413 0x557733521050 ERROR                msdkdec gstmsdkdec.c:868:gst_msdkdec_negotiate:<msdkvp9dec0> Failed to re-negotiate

**Comment by xhaihao** [comment]
BTW for HEVC decoder, the output Shift is still equal to the input Shift. I think both VP9 and HEVC encoder should keep consistency for 10bit decoding

**Comment by dvrogozh** [comment]
@xhaihao : do you use MFX_VERSION>=MFX_VERSION_NEXT path to build mediasdk or you see regression when this condition is not true?

**Comment by xhaihao** [comment]
@dvrogozh I see the regression no matter this condition is true or not.
