### ISSUE TITLE
MFX_ERR_UNSUPPORTED. Failed on HD Graphics 4400, but work on HD Graphics 530

### ISSUE THREAD

**Issue by Jackson-256** [Intel-Media-SDK/MediaSDK#1791]
when I run sample_decode for decoding the video in h264, it work well on HD Graphics 530, but get the error of unsupported on HD Graphics 4400. I wonder what is going wrong?

 I have already set up opencl driver , sdk and hd graphics driver. 

when I debug the code , it indicated the libmfxhw64.dll load successfully, but when it tried to init the parameters (line 249 in api/mfx_dispatch/windows/src/mfx_dispatcher.cpp )，it return "MFX_ERR_UNSUPPORTED" error.

![image](https://user-images.githubusercontent.com/57104213/70013494-cfa0b800-15b2-11ea-88a5-efa8cc3aa12f.png)

**Comment by dmitryermilov** [comment]
@npletnev , would you like to request additional details?

**Comment by npletnev** [comment]
@Jackson-256, could you please provide Windows version, build and graphics driver version from your machine with HD Graphics 4400?
Did you take dispatcher lib and sample from SDK release? What its version?
Also, share cmd that you use to run sample_decode.

**Comment by dmitryermilov** [comment]
@Jackson-256 , could you reply?

**Comment by dmitryermilov** [comment]
@Jackson-256 , feel free to re-open
