### ISSUE TITLE
How to Use AvcTemporalLayers ?

### ISSUE THREAD

**Issue by zhoub** [Intel-Media-SDK/MediaSDK#1802]
Hi !

It seems that the example program sample_encode supports option AvcTemporalLayers, but how to use it ? How does input specify the parameter for SVC encoding ? Thanks in advance !

**Comment by dmitryermilov** [comment]
Hi!

This is an example:
`-AvcTemporalLayers "0 1 2 4 0 0 0 0 0"`

But please note that our H264 encoder doesn't support real SVC. These temporal layers functionality just builds special ref list when higher layers can be dropped on decoder side without artifacts.

**Comment by dmitryermilov** [comment]
@zhoub , can we close the issue?
