### ISSUE TITLE
Add support for MFX_FOURCC_BGR4 in vpp

### ISSUE THREAD

**Issue by CapOM** [Intel-Media-SDK/MediaSDK#1803]
Following https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/issues/1133 it would be great to add support for MFX_FOURCC_BGR4 so that GStreamer msdkvpp can output GST_VIDEO_FORMAT_RGBA. 
Currently gst msdkvpp only outputs BGRA/BGRx which matches MFX_FOURCC_RGB4 (full mapping between msdk and gst formats can be found here https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/blob/master/sys/msdk/msdk.c#L49)

**Comment by FurongZhang** [comment]
@CapOM  we have implemented MFX_FOURCC_BGR4 in Library.

**Comment by CapOM** [comment]
Nice, thx

**Comment by FurongZhang** [comment]
We have enabled BGRA input/output in https://github.com/oneapi-src/oneVPL-intel-gpu. Please use the latest version and let us know if any issues. 

Thanks a lot in advance!

**Comment by philn** [comment]
> @CapOM we have implemented MFX_FOURCC_BGR4 in Library.

In which version was this released?

**Comment by philn** [comment]
@FurongZhang ?
