### ISSUE TITLE
got corrupted stream if using MaxSliceSize for HEVC encoding on ICL

### ISSUE THREAD

**Issue by xhaihao** [Intel-Media-SDK/MediaSDK#1806]
Revert commit 195f95e due to a regression (https://github.com/Intel-Media-SDK/MediaSDK/issues/1805 ) firstly.

Run the command line below to get output.hevc
/usr/share/mfx/samples/sample_encode h265 -qsv-ff -mss 10000 -i input.yuv -o output.hevc -w 1920 -h 1080

then use a player to playback output.hevc or use video tool to check output.hevc

**Comment by dmitryermilov** [comment]
@AntonGrishin , can you take a look?

**Comment by aobolensk** [comment]
Not reproducible on latest media-driver (https://github.com/intel/media-driver/commit/7857d6bea214b755d610c1a478d4e1e23da31cdb) and latest MediaSDK (https://github.com/Intel-Media-SDK/MediaSDK/commit/9890dff6064a7f8fe738899fc0c39b33a2d181b5)
