### ISSUE TITLE
HEVC lookahead(LA) query by MFXVideoENCODE_Query requires two separate sessions 

### ISSUE THREAD

**Issue by agalin89** [Intel-Media-SDK/MediaSDK#1810]
To use lookahead for HEVC encode, we need to have h264 LA (MFX_PLUGINID_H264LA_HW) plugin and the HEVC HW encode plugin, run in separate sessions.
For simple feature query by MFXVideoENCODE_Query function it is too complicated and not transparent. 

It returns MFX_ERR_UNSUPPORTED if no h264 LA plugin loaded in separate sessions. 

Related issues: 
https://github.com/Intel-Media-SDK/MediaSDK/issues/1743
https://github.com/Intel-Media-SDK/MediaSDK/pull/1752

**Comment by ogolikov** [comment]
Hi!
RateControl MFX_RATECONTROL_LA_EXT should be used for HEVC encoder. See sample_multi_transcode as example.  Par file example:
-----------------------------------------------------------------------------------------------
-i::h265 matrix_1920x1088_300_25fps.x265 -lad 40 -join -la_ext -hw -async 1  -o::sink
-h 1088 -b 3000 -w 1920 -o::h265 0001.0.h265 -join -async 1 -hw -i::source -l 1 -u 4 
----------------------------------------------------------------------------------------------

**Comment by dmitryermilov** [comment]
@ogolikov , the request get rid of two sessions to enable LA. In your example it's still two.

**Comment by agalin89** [comment]
Exactly, in example there are two sessions.

**Comment by dmitryermilov** [comment]
@agalin89 , well, I debugged it. It's just a limitation  of current sample_multi_transcode, not MediaSDK library limitation. From MediaSDK library perspective, LA and encode should work in one session.

**Comment by dmitryermilov** [comment]
Hi @agalin89 , 

Did you get it working in your app?

**Comment by dmitryermilov** [comment]
Please see https://github.com/Intel-Media-SDK/MediaSDK/pull/2034/commits . From MSDK API perspective there is no need to additional session.
