### ISSUE TITLE
Memory leak when FadeDetection=MFX_CODINGOPTION_ON

### ISSUE THREAD

**Issue by changliwu** [Intel-Media-SDK/MediaSDK#182]
Hi,
    I have used mfxExtCodingOption3 FadeDetection=MFX_CODINGOPTION_ON in sample_encode of MediaSDK 1.25, I found that this will lead to about 1.25M bytes of memory leaks per minute for 1080p25
h264 encoding.
    I wonder the function of RunHistogram caused the memory leak.
    I have debug and disabled the function of CmEvent * CmContext::RunHistogram(DdiTask const & task,mfxU16 Width,mfxU16 Height,mfxU16 OffsetX,mfxU16 OffsetY) of MediaSDK/_studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_cm.cpp , The memory leak disappeared!

**Comment by dmitryermilov** [comment]
Hi @changliwu ,

It looks like CmEvent objects are leaking. Please try 
[cm_leak_fix.txt](https://github.com/Intel-Media-SDK/MediaSDK/files/1957881/cm_leak_fix.txt). Does it fully fix the issue or you see something else?

**Comment by changliwu** [comment]
Hi Dmitry Ermilov,
   I have changed the code like the cm_leak_fix.txt, It fully fix the issue, thanks!

**Comment by dmitryermilov** [comment]
Done: https://github.com/Intel-Media-SDK/MediaSDK/pull/190

BTW, @changliwu , thank you for preliminary investigation!
