### ISSUE TITLE
EHL/JSL: duplicated devid 0x4500

### ISSUE THREAD

**Issue by dvrogozh** [Intel-Media-SDK/MediaSDK#1820]
here:
https://github.com/Intel-Media-SDK/MediaSDK/blob/18601bea619c2119ae0c0a0cd230d302f377e857/_studio/shared/src/libmfx_core_vaapi.cpp#L331
and here:
https://github.com/Intel-Media-SDK/MediaSDK/blob/18601bea619c2119ae0c0a0cd230d302f377e857/_studio/shared/src/libmfx_core_vaapi.cpp#L337

**Comment by dmitryermilov** [comment]
Mesa says it's EHL: https://github.com/mesa3d/mesa/blob/1a32fbd48c62481cd17c6944ecd17bcb2c2b052a/include/pci_ids/i965_pci_ids.h#L240

As well as kernel:
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/include/drm/i915_pciids.h?h=v5.4.2#n584
