### ISSUE TITLE
Build ffmpeg: ERROR: libmfx not found FIX

### ISSUE THREAD

**Issue by zhiga-rsp** [Intel-Media-SDK/MediaSDK#1822]
```
ERROR: libmfx not found

Usually it happens, if you forgot to specify pkg-config path 
(default for manual build is /opt/intel/mediasdk/lib/pkgconfig, 
and for apt-get is /usr/lib/x86_64-linux-gnu/pkgconfig):

export PKG_CONFIG_PATH=/path/to/mediasdk/lib/pkgconfig
```
If you try this above, but problem still present, try to install. `apt install pkg-config.`
It helps for me on Ubuntu 19.10.
MSDK were installed from packages.

**Comment by dmitryermilov** [comment]
Is libmfx.pc somewhere available on the system?

**Comment by zhiga-rsp** [comment]
Yes
`/usr/lib/x86_64-linux-gnu/pkgconfig/libmfx.pc`

**Comment by dmitryermilov** [comment]
And what `pkg-config --modversion libmfx` outputs?

**Comment by dmitryermilov** [comment]
BTW, we have a dedicated Wiki:
https://github.com/Intel-Media-SDK/MediaSDK/wiki/Build-and-use-ffmpeg-with-MediaSDK

**Comment by dmitryermilov** [comment]
Hi @zhiga-rsp , do you have any news?

**Comment by zhiga-rsp** [comment]
# pkg-config --modversion libmfx
1.30

**Comment by zhiga-rsp** [comment]
> BTW, we have a dedicated Wiki page:
> https://github.com/Intel-Media-SDK/MediaSDK/wiki/Build-and-use-ffmpeg-with-MediaSDK
I was going  this way in the start of setup

**Comment by dmitryermilov** [comment]
Alright. What is the output of ffbuild/config.log ?

**Comment by zhiga-rsp** [comment]
> Alright. What is the output of ffbuild/config.log ?
it needs  more time for reproducing

**Comment by ConsoleYan** [comment]
I have tried some step to solve this problem:
Step1. find your mfx.pc (mediaSDK)
```
$ ls `/opt/intel/mediasdk/lib/pkgconfig/`
libmfxhw64.pc  libmfx.pc      mfx.pc 
```
Step2. vim ~/.bashrc
`export PKG_CONFIG_PATH=/opt/intel/mediasdk/lib/pkgconfig/`

Step3.source ~/.bashrc

Then this error could be fix.

**Comment by HorsonLiu** [comment]
On centos7.9, with ffmpeg 4.4, the same problem still exists.
