### ISSUE TITLE
Controlling Threads in MFXVideoDECODE

### ISSUE THREAD

**Issue by navesta** [Intel-Media-SDK/MediaSDK#1828]
Hi
Referring to https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/issues/1144 discussion, I am looking for ways to exercise finer control on decoder’s thread, i.e., their numbers and termination. From what I’ve gathered, I need to invoke MFXInitEx with par.ExternalThreads set to 1, and somehow pass worker threads to MFXDoWork. Not sure how to pass worker threads to  MFXDoWork; however, is there a sample code anywhere?
Cheers,

**Comment by dmitryermilov** [comment]
This MFXDoWork API is not supported (deprecated).

But you can control a number of internal MediaSDK threads (which belong to a scheduler) by https://github.com/Intel-Media-SDK/MediaSDK/blob/master/doc/mediasdk-man.md#mfxextthreadsparam . Please note that a min number of threads is two.

**Comment by navesta** [comment]
Thank you Dmitry. Is it possible to terminate these threads manually, e.g., is it possible to get their pid?
Cheers,

**Comment by dmitryermilov** [comment]
You're welcome. Unfortunately, app can't control them. The only way to terminate them is to close MSDK session. 
Could you share background why you're interested in manual control? Too many internal MSDK threads or ... ?

**Comment by navesta** [comment]
Thank you again Dmitry. As noted in the original post, in Gitlab, the issue is a malformed input stream that upon wrap around leaves 8 threads behind. (Even though, MFXVideoDECODE_Close is called.) Looking at gdb output, it seems that these threads are stuck at pthread_wait_cond. (I’ve also tried  MFXVideoDECODE_Reset prior to close.) Also, kindly, note that our base code is about a year old.
Cheers,

**Comment by dmitryermilov** [comment]
No problem!
I looked thru the gitlab description but didn't get: is any bug behind it or just curiosity?

**Comment by navesta** [comment]
Thank you for the followup. It's indeed a bug, as our regression test is failing on this input stream, i.e., system's memory gets exhausted after 24 hours.

**Comment by dmitryermilov** [comment]
Hmm. This doesn't seem to be related to MSDK threads, right? If so, I'd propose to track it into another issue. Is it okay for you? Please post details about the stream and ideally a reproducer.

**Comment by dmitryermilov** [comment]
Hi @navesta , 

Could you reply?

**Comment by navesta** [comment]
Hi Dmitry,
Sorry didn't have a chance to reply earlier. The reason for suggesting that these are MSDK threads was based on the discussion on the Gitlab thread, where it was asserted that decoder creates as many threads as there are number of cores. Admittedly, I have not had a chance to confirm this by InitEx and specifying a different number of threads. Once I do, I’ll update this thread.
Cheers,

**Comment by dmitryermilov** [comment]
Hi Nastooh,

Thank you. Take your time.
