### ISSUE TITLE
Please explain hevc gen11-gen9 discrepancy in code comments

### ISSUE THREAD

**Issue by onabiull** [Intel-Media-SDK/MediaSDK#1830]

**Comment by dvrogozh** [comment]
@onabiull : what do you mean? Can you, please, point to examples?

**Comment by onabiull** [comment]
Comment https://github.com/Intel-Media-SDK/MediaSDK/pull/1793#discussion_r357042482 sould appear in the code, not just in PR discussion.

**Comment by eistarov** [comment]
@onabiull , @dvrogozh , please clarify for the record, how do you want me to fix it:
1) just add comment in the code in hevcehw_disp.cpp 
2) replace _g11_ with _g9_  in file-names and Gen11 namespace with Gen9 and add comment to hevcehw_disp.cpp
3) something else...

**Comment by onabiull** [comment]
I tend to agree, w/ @dvrogozh that smth_gen9.cpp which work on Gen10 and Gen11 hardware would be much clearer, that vice-versa. Please replace g11 with g9 in both code and file names. And add a comment about platform applicability. :)

**Comment by dvrogozh** [comment]
> replace g11 with g9 in file-names and Gen11 namespace with Gen9 and add comment to hevcehw_disp.cpp

That's the general practice I observe in multiple projects. Definitions are given for the lowest platform, like gen9, and reused gen9+.
