### ISSUE TITLE
[H265]SampleEncode - not working Ubuntu/Windows

### ISSUE THREAD

**Issue by salimerko** [Intel-Media-SDK/MediaSDK#1853]
I built MSDK as per instructions,
did apt-get install intel-media-va-driver-non-free
HW is Intel NUC8I3 - i3-8109U / Ubuntu 19.10

When I run ./sample_encode h264 -i sample.yuv -o out -w 1280 -h 720; It works
When I try ./sample_encode h265 -i sample.y4m -o out -w 1280 -h 720 -hw
(with or without -hw) it always report:

libva info: VA-API version 1.6.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/local/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_4
libva info: va_openDriver() returns 0

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), AllocFrames, Query (for encoder) failed at /home/adam/ffmpeg_sources/msdk/samples/sample_encode/src/pipeline_encode.cpp:881

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), ResetMFXComponents, AllocFrames failed at /home/adam/ffmpeg_sources/msdk/samples/sample_encode/src/pipeline_encode.cpp:1893

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), Init, ResetMFXComponents failed at /home/adam/ffmpeg_sources/msdk/samples/sample_encode/src/pipeline_encode.cpp:1675

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), main, pPipeline->Init failed at /home/adam/ffmpeg_sources/msdk/samples/sample_encode/src/sample_encode.cpp:1610
Frame number: 0
Encoding fps: -nan
------------------------------

My vainfo:
libva info: VA-API version 1.6.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/local/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_4
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.6 (libva 2.5.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Coffee Lake - 2.3.0
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSliceLP
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointEncSliceLP
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointEncSliceLP
      VAProfileH264MultiviewHigh      :	VAEntrypointVLD
      VAProfileH264MultiviewHigh      :	VAEntrypointEncSlice
      VAProfileH264StereoHigh         :	VAEntrypointVLD
      VAProfileH264StereoHigh         :	VAEntrypointEncSlice
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointEncPicture
      VAProfileVP8Version0_3          :	VAEntrypointVLD
      VAProfileVP8Version0_3          :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileHEVCMain10             :	VAEntrypointEncSlice
      VAProfileVP9Profile0            :	VAEntrypointVLD
      VAProfileVP9Profile0            :	VAEntrypointEncSlice
      VAProfileVP9Profile2            :	VAEntrypointVLD

This is on fresh ubuntu and exactly same problems I am getting on Windows 1. I have no idea what is wrong and I would expect the sample to work. Is anyone else having the same problem?

**Comment by onabiull** [comment]
Looks you have both i965 an diHD driver on your system. Could you please try if setting environment variable `LIBVA_DRIVER_NAME=iHD` would solve this issue?

**Comment by salimerko** [comment]
Hi, Thank you for promt reply. 
When I set: export LIBVA_DRIVER_NAME=iHD, I get following from vainfo:
libva info: VA-API version 1.6.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /usr/local/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: va_openDriver() returns -1
vaInitialize failed with error code -1 (unknown libva error),exit

and sampleEncode returns:

libva info: VA-API version 1.6.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /usr/local/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: va_openDriver() returns -1

error, sts=MFX_ERR_MEMORY_ALLOC(-4), CreateAllocator, CreateHWDevice failed at /home/adam/ffmpeg_sources/msdk/samples/sample_encode/src/pipeline_encode.cpp:1112

error, sts=MFX_ERR_MEMORY_ALLOC(-4), Init, CreateAllocator failed at /home/adam/ffmpeg_sources/msdk/samples/sample_encode/src/pipeline_encode.cpp:1659

error, sts=MFX_ERR_MEMORY_ALLOC(-4), main, pPipeline->Init failed at /home/adam/ffmpeg_sources/msdk/samples/sample_encode/src/sample_encode.cpp:1610
Frame number: 0
Encoding fps: -0

**Comment by dmitryermilov** [comment]
Both are needed:
```
export LIBVA_DRIVER_NAME=iHD
export LIBVA_DRIVERS_PATH=/path/to/directlry/with/iHD/driver
```

**Comment by salimerko** [comment]
This helped, thank you a lot. Is this documented somewhere?
Also, One more question, how can I enable V4l2? When I did cmake .. -DENABLE_V4L2_SUPPORT=1 , compiler ignored it, thank you

**Comment by dmitryermilov** [comment]
>Is this documented somewhere?

Well, it's captured in some Wiki pages:
https://github.com/Intel-Media-SDK/MediaSDK/search?q=LIBVA_DRIVER_NAME&type=Wikis 
Probably, we need to include it in install.sh script from quarterly releases. @onabiull , what do you think? 

>Also, One more question, how can I enable V4l2? When I did cmake .. -DENABLE_V4L2_SUPPORT=1 , compiler ignored it, thank you

Let's track V4L2 in #1874 .

**Comment by onabiull** [comment]
We already do that. In MediaStack.tar.gz there are file /etc/profile.d/intel-mediasdk.sh with contents:
```
# add libva driver path/name exporting for intel media solution
export LIBVA_DRIVERS_PATH=/opt/intel/mediasdk/lib64
export LIBVA_DRIVER_NAME=iHD
```
Normally this file installed by `install_media.sh`. 

Build system look for for ENABLE_V4L2 variable. To enable V4L2 pass  `-DENABLE_V4L2=ON`
to cmake.
Looks like commit https://github.com/Intel-Media-SDK/MediaSDK/commit/0ff71e66fc6e6c8500ede212c2dcf3d997a5c784 erroneously comment out `pParams` in function signature.
