### ISSUE TITLE
MediaSDK on AMD motherboard?

### ISSUE THREAD

**Issue by Futureknows** [Intel-Media-SDK/MediaSDK#1863]
I moved a Fedora installation from an Intel system to a AMD system that doesn't have any Intel components (CPU, GPU). Can I safely remove MediaSDK? It is indicating a ton of programs are dependant on it.

**Comment by onabiull** [comment]
Hard to answer. Technically it would depend on whether application call MFXInit() during startup and how it handles errors. We can't control that. It appears to me that this question is better to be asked on some RedHat forum, given your Fedora distribution. 
Correctly written Media SDK application should depend on libva and MediaSDK dispatcher (libmfx.so.1) but I've seen implementations which directly link libmfxhw64.so.
Probably safer action is to leave Media SDK as is.
