### ISSUE TITLE
buid videoMixer_msdk error message

### ISSUE THREAD

**Issue by learnin9** [Intel-Media-SDK/MediaSDK#1866]
I have installed the intel media sdk and try to use the command " scripts/build.js -t all --check" to compile it, but i get the following errors:
make: 进入目录“/root/owt-server-4.2/source/agent/video/videoMixer/videoMixer_msdk/build”
  SOLINK_MODULE(target) Release/obj.target/videoMixer-msdk.node
/usr/bin/ld: 找不到 -lmfx
collect2: error: ld returned 1 exit status
videoMixer-msdk.target.mk:195: recipe for target 'Release/obj.target/videoMixer-msdk.node' failed
make: *** [Release/obj.target/videoMixer-msdk.node] Error 1
make: 离开目录“/root/owt-server-4.2/source/agent/video/videoMixer/videoMixer_msdk/build”
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/nodejs/node-v8.15.1-linux-x64/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.15.0-29-generic
gyp ERR! command "/usr/local/lib/nodejs/node-v8.15.1-linux-x64/bin/node" "/usr/local/lib/nodejs/node-v8.15.1-linux-x64/bin/node-gyp" "build" "-j" "8" "--loglevel=error"
gyp ERR! cwd /root/owt-server-4.2/source/agent/video/videoMixer/videoMixer_msdk
gyp ERR! node -v v8.15.1
gyp ERR! node-gyp -v v5.0.7
gyp ERR! not ok 
child_process.js:650
    throw err;
    ^

Error: Command failed: node-gyp build -j 8 --loglevel=error
    at checkExecSyncError (child_process.js:607:13)
    at execSync (child_process.js:647:13)
    at buildTarget (/root/owt-server-4.2/scripts/build.js:129:5)
    at buildList.map (/root/owt-server-4.2/scripts/build.js:153:10)
    at Array.map (<anonymous>)
    at Object.<anonymous> (/root/owt-server-4.2/scripts/build.js:152:23)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)

**Comment by onabiull** [comment]
Issue looks like some kind of mis-configuration. Could you please provide additional information? Which gstreamer code you are using, OS distribution, Media SDK installation method?
Just as a blind fix, supposing installation of MediaStack.tar.gz from https://github.com/Intel-Media-SDK/MediaSDK/releases: from please try to set `PKG_CONFIG_PATH=/opt/intel/mediasdk/lib64/pkgconfig:${PKG_CONFIG_PATH}` prior to calling build script.

**Comment by dmitryermilov** [comment]
@learnin9 , could you reply?
