### ISSUE TITLE
V4L2 in MSDK 

### ISSUE THREAD

**Issue by salimerko** [Intel-Media-SDK/MediaSDK#1874]
1.) How to properly build sample_encode via cmake to support V4L2? All I found was about build.pl which is not in MediaSDK repository, but in samples repository which is deprecated.So I did checkout master and manually defined "ENABLE_V4L2_SUPPORT" in whole sample folder and build the code.
Also I had to uncomment pParams in sample_encode/src/pipeline_encode.cpp to build it

2.) FFplay show input from /dev/video0, but when I run encode sample:
./sample_encode h264 -i::v4l2 -o out -w 1920 -h 1080 -d /dev/video0 -UYVY

it report error in sample_common/src/v4l2_util.cpp:277) : STREAMON failed: Device or resource busy
Aborted (core dumped)

Thanks for any help

**Comment by dmitryermilov** [comment]
From @onabiull :

> Build system look for for ENABLE_V4L2 variable. To enable V4L2 pass  `-DENABLE_V4L2=ON`
> to cmake.
> Looks like commit https://github.com/Intel-Media-SDK/MediaSDK/commit/0ff71e66fc6e6c8500ede212c2dcf3d997a5c784 erroneously comment out `pParams` in function signature.

**Comment by salimerko** [comment]
Thank you, that eliminated first problem, now it builded with v4l2, however, the second problem still persists. Here is the output

~/msdk-19.3.1/build/__bin/release$ ./sample_encode h264 -i::v4l2 -o output -w 1920 -h 1080 -d /dev/video0 -UYVY
libva info: VA-API version 1.6.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /opt/intel/mediasdk/lib64/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_6
libva info: va_openDriver() returns 0
Driver Caps:
  Driver: "uvcvideo"
  Card: "USB Capture HDMI+: USB Capture "
  Bus: "usb-0000:00:14.0-2"
  Version: 1.0
  Capabilities: 84a00001
G_FMT(start): width = 1280, height = 720, 4cc = YUYV, BPP = 2560 sizeimage = 1843200 field = 1
G_FMT(pre): width = 1920, height = 1080, 4cc = UYVY, BPP = 0 sizeimage = 0 field = 0
G_FMT(final): width = 1920, height = 1080, 4cc = YUYV, BPP = 3840
Encoding Sample Version 19.3.1

Input file format	YV12
Output video		HEVC
Source picture:
	Resolution	1920x1088
	Crop X,Y,W,H	0,0,1920,1080
Destination picture:
	Resolution	1920x1088
	Crop X,Y,W,H	0,0,1920,1080
Frame rate	30.00
Bit rate(Kbps)	2890
Gop size	0
Ref dist	0
Ref number	0
Idr Interval	0
Target usage	balanced
Memory type	system
Media SDK impl		hw
Media SDK version	1.30

Processing started
ERROR(/home/msdk-19.3.1/samples/sample_common/src/v4l2_util.cpp:277) : STREAMON failed: Device or resource busy
Aborted (core dumped)

**Comment by dmitryermilov** [comment]
@AntonGrishin , could you investigate?

**Comment by dmitryermilov** [comment]
Anton, the V4L2 driver requests a minimum of 3 buffers - if you look at the value in requestBuffer.count returned from VIDIOC_REQBUFS then it will be 3. In our case it's 0. 
```
    CLEAR(rqbufs);
    rqbufs.count = m_num_buffers; <------------------------
    rqbufs.type = V4L2_BUF_TYPE_VIDEO_CAPTURE;
    rqbufs.memory = V4L2_MEMORY_DMABUF;

    ret = blockIOCTL(m_fd, VIDIOC_REQBUFS, &rqbufs);
    BYE_ON(ret < 0, "VIDIOC_REQBUFS failed: %s\n", ERRSTR);
    BYE_ON(rqbufs.count < m_num_buffers, "video node allocated only "
            "%u of %u buffers\n", rqbufs.count, m_num_buffers);
```
But even if we fix it, encoded file will be corrupted - tiled picture. This should be investigated.

**Comment by AntonGrishin** [comment]
After build fix, seems that main problem is that camera capture linear, but driver expected tiled memory with yuy2,uyvy formats.
![image](https://user-images.githubusercontent.com/34107292/71622425-ae011380-2be6-11ea-9204-c2a22f7068d2.png)

When I manually disable tiling for yuy2 captured picture looks good:

![image](https://user-images.githubusercontent.com/34107292/71622665-785d2a00-2be8-11ea-8f70-fc789fd59dca.png)

So need to pass some parameters, for disable tiling. WIP.

**Comment by salimerko** [comment]
Hi Anton, could you share some details here please? Also, do you have any idea how to run v4l2 capture without involving VPP? Thanks

**Comment by AntonGrishin** [comment]
Hi @salimerko, I think, that we will fix this after holidays.
I believe, that we can use it only with VPP (because encoder doesnt support formats like yuy2 on CFL- platforms). 
First point from MediaSDK side is enabling VPP with V4L2, for example add condition here:
https://github.com/Intel-Media-SDK/MediaSDK/blob/01f937b0439cb95a350776966a0a1d16b346fffe/samples/sample_encode/src/pipeline_encode.cpp#L1585

And second one need another way to allocate surfaces (like with drm rendering)

**Comment by salimerko** [comment]
Thank you Anton, it is fine with using VPP. Any chance to share info how to get rid of the tiles?

**Comment by AntonGrishin** [comment]
Hi @salimerko,
We are working on fix.
Just for workaround you can move you camera fourcc format in media-driver [switch](https://github.com/intel/media-driver/blob/d0cbf53cd4dc23f1ef99b4b2e9bfab74172d9c9d/media_driver/linux/common/ddi/media_libva_util.cpp#L174) higher, for use `I915_TILING_NONE`, but I m not sure, that it`ll not impact something.

**Comment by dmitryermilov** [comment]
@salimerko , could you try #1987?
