### ISSUE TITLE
Clarify encoding mode (VME vs. VDENC) in sample encode and smt

### ISSUE THREAD

**Issue by dvrogozh** [Intel-Media-SDK/MediaSDK#1880]
Starting from 1.31 API implementation we started to change default encoding mode:
https://github.com/Intel-Media-SDK/MediaSDK/blob/073bf0f47ebe8dcf4221a7f1cbfa51d80aa4c161/_studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp#L1430

Here is code snippet:
```
#if (MFX_VERSION >= 1031)
    if ((platfrom == MFX_HW_JSL || platfrom == MFX_HW_EHL)
        && par.mfx.LowPower == MFX_CODINGOPTION_UNKNOWN)
    {
        par.mfx.LowPower = MFX_CODINGOPTION_ON;
        return sts;
    }
#endif
```

Can you, please, clarify:
1. Which is the default encoding mode for sample encode and smt for each platform?
2. If default mode for JSL/EHL is VDENC, how user can change it to VME? (I think there is only `-qsv-ff` which enables VDENC, but not disables it)

I recommend to print out some info clarifying the work mode of samples. Plus, I would consider changing command line option to something more sensible, like `--lowpower=on|off`

**Comment by dmitryermilov** [comment]
> Which is the default encoding mode for sample encode and smt for each platform?

In which way would you like to have it? Just a comment in current issue or ..?

> If default mode for JSL/EHL is VDENC, how user can change it to VME? (I think there is only -qsv-ff which enables VDENC, but not disables it)
I recommend to print out some info clarifying the work mode of samples. Plus, I would consider changing command line option to something more sensible, like --lowpower=on|off

@AntonGrishin , could you please follow up?

**Comment by AntonGrishin** [comment]
> > Which is the default encoding mode for sample encode and smt for each platform?
> 
> @dvrogozh , In which way would you like to have it? Just a comment in current issue or ..?

@dvrogozh any suggestions?
