### ISSUE TITLE
Sample failure

### ISSUE THREAD

**Issue by Benzez** [Intel-Media-SDK/MediaSDK#1893]
I run the folllowing sample:

~/work/MediaSDK/build/__bin/release$ ./sample_multi_transcode -i::h264 ~/work/MediaSDK/tests/content/test_stream.264 -o::h264 out.264

 

I get the following error:

Multi Transcoding Sample Version 8.4.27.

libva info: VA-API version 1.6.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_6
libva info: va_openDriver() returns 0
Session 0:

[ERROR], sts=MFX_ERR_MORE_DATA(-10), Init, pThreadPipeline->pPipeline->Init failed at /home/baseline/work/MediaSDK/samples/sample_multi_transcode/src/sample_multi_transcode.cpp:442

[ERROR], sts=MFX_ERR_MORE_DATA(-10), main, transcode.Init failed at /home/baseline/work/MediaSDK/samples/sample_multi_transcode/src/sample_multi_transcode.cpp:1169
 

Any help?

Thanks

**Comment by dmitryermilov** [comment]
Hi @Benzez , 

Which version of the sample and library do you use? I just tried https://github.com/Intel-Media-SDK/MediaSDK/releases/download/intel-mediasdk-19.3.1/MediaStack.tar.gz and https://github.com/Intel-Media-SDK/MediaSDK/releases/download/intel-mediasdk-19.4.0/MediaStack.tar.gz releases, there is no such issue:
```
/opt/intel/mediasdk/share/mfx/samples/_bin/sample_multi_transcode -i::h264 /opt/intel/mediasdk/share/mfx/samples/_bin/content/test_stream.264 -o::h264 /dev/null
Multi Transcoding Sample Version 19.3.1

libva info: VA-API version 1.6.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /opt/intel/mediasdk/lib64/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_6
libva info: va_openDriver() returns 0
Session 0:
Pipeline surfaces number (DecPool): 21
MFX HARDWARE Session 0 API ver 1.30 parameters:
Input  video: AVC
Output video: AVC

Session 0 was NOT joined with other sessions

Transcoding started
.
Transcoding finished

Common transcoding time is 0.122025 sec
-------------------------------------------------------------------------------
*** session 0 [0x55a8bd0c5070] PASSED (MFX_ERR_NONE) 0.121859 sec, 105 frames, 861.648 fps
-i::h264 /opt/intel/mediasdk/share/mfx/samples/_bin/content/test_stream.264 -o::h264 /dev/null

-------------------------------------------------------------------------------

The test PASSED

```

```
/opt/intel/mediasdk/share/mfx/samples/_bin/sample_multi_transcode -i::h264 /opt/intel/mediasdk/share/mfx/samples/_bin/content/test_stream.264 -o::h264 /dev/null
Multi Transcoding Sample Version 19.4.0

libva info: VA-API version 1.6.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /opt/intel/mediasdk/lib64/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_6
libva info: va_openDriver() returns 0
Session 0:
Pipeline surfaces number (DecPool): 21
MFX HARDWARE Session 0 API ver 1.31 parameters:
Input  video: AVC
Output video: AVC

Session 0 was NOT joined with other sessions

Transcoding started
.
Transcoding finished

Common transcoding time is 0.129128 sec
-------------------------------------------------------------------------------
*** session 0 [0x5567381296d0] PASSED (MFX_ERR_NONE) 0.128909 sec, 105 frames, 814.530 fps
-i::h264 /opt/intel/mediasdk/share/mfx/samples/_bin/content/test_stream.264 -o::h264 /dev/null

-------------------------------------------------------------------------------

The test PASSED

```

**Comment by Benzez** [comment]
I've used the following instalation guide which also installed the examples:
https://software.intel.com/en-us/articles/build-and-debug-open-source-media-stack 

Used to latest commit option.

**Comment by dmitryermilov** [comment]
Could you try Q4 release and post results? Just to check if it's a problem of a particular commit or media stack is fully broken on your system.

**Comment by dmitryermilov** [comment]
Hi @Benzez , do you have any news?

**Comment by Benzez** [comment]
Thanks Dmitry.
Didn't have time to work on it yet, will let you know once I get to it

**Comment by Benzez** [comment]
Managed to fix issues. Thanks for the help!
