### ISSUE TITLE
Intel® Media Processor SDK for evansport CPU?

### ISSUE THREAD

**Issue by th0ma7** [Intel-Media-SDK/MediaSDK#1896]
Hi,

Synology uses `intelce-utilities` and librairies in order to enable hardware media acceleration to work on evansport processors.  They provide pre-built toolkit and headers at:
https://sourceforge.net/projects/dsgpl/files/toolkit/DSM6.2/

I was wondering the following:
1. Was Intel® Media Processor SDK superseeded by Intel® Media SDK (e.g. this project) ?
2. Can the source code of Intel® Media Processor SDK be made available (which I believe being the source of `intelce-utilities` and libraries) in order to reproduce existing functionality as provided by synology?

thnx in advance!

**Comment by onabiull** [comment]
Looks like Media Processor SDK is a completely different thing from Intel Media SDK. This repo is dedicated to Media SDK - programming interface and runtime libraries for accessing [Intel® Quick Sync Video](https://en.wikipedia.org/wiki/Intel_Quick_Sync_Video) features of Intel Gen GPUs. 
Intel Evansport looks translated to [Atom D2700](https://ark.intel.com/content/www/ru/ru/ark/products/59683/intel-atom-processor-d2700-1m-cache-2-13-ghz.html), which have PowerVR (not Gen) graphics onboard. And no Quick Sync Video according to ARK.
So to answer your questions:
  1 - no they are is similar APIs for different platforms
  2 - unfortunately I don't know. I'd recommend to ask this question on Intel IDZ forums.

**Comment by th0ma7** [comment]
Thnx for the reply.
It is what I discovered as well.
I've reached out to IDZ forums, can't wait to see what answer I get.
Thnx!
