### ISSUE TITLE
Step-by-Step process described to install Intel Media SDK on Ubuntu leads to error

### ISSUE THREAD

**Issue by perydominet** [Intel-Media-SDK/MediaSDK#1898]
OK       - sudo apt-get install git cmake pkg-config
OK       - sudo apt-get install meson libdrm-dev automake libtool
OK       - git clone https://github.com/intel/libva.git
OK       - cd libva
**ERROR - git checkout tag/2.6.0.pre1**

**RESULT - error: pathspec 'tag/2.6.0.pre1' did not match any file(s) known to git.**

**Comment by dvrogozh** [comment]
Just to double check, you refer to this instruction: https://github.com/Intel-Media-SDK/MediaSDK/wiki/Build-Media-SDK-on-Ubuntu?

**Comment by AntonGrishin** [comment]
Hi @perydominet,
Sorry for mistakes in the instruction. Thanks for you report.
LibVA build section has been updated and now contains information about using recommend (latest tag) or master libva version.

**Comment by perydominet** [comment]
Hi Anton,
Thank you very much for your kind update.
Hopefully people now using your description will be able to successfully 
install the extension.
Best regards.
