### ISSUE TITLE
tutorials link not pointing to tutorials

### ISSUE THREAD

**Issue by mkwilbux** [Intel-Media-SDK/MediaSDK#1899]
**Origin:** https://github.com/Intel-Media-SDK/MediaSDK/releases/tag/intel-mediasdk-19.4.0

Tutorials link: 
>**MediaSDK tutorials published**

goes to: master/tutorials
https://github.com/Intel-Media-SDK/MediaSDK/intel-mediasdk-19.4/master/tutorials/

**Correct link:** https://github.com/Intel-Media-SDK/MediaSDK/tree/intel-mediasdk-19.4/doc/tutorials

> What's new Media SDK 19.4.0:
>API 1.31
>Added TGL, EHL, JSL platform support
>Added 12-bit color formats
>Added support for multiadapter configurations (integrated + discrete)
>Added partial bitstream output (aka slice-based encode)
>Misc
>**MediaSDK tutorials published**
>Warning-free build on gcc-9 and clang-8
>Robustness and code unification changes

**Comment by dmitryermilov** [comment]
Thank you @mkwilbux ! It's fixed.

**Comment by onabiull** [comment]
From my point of view Tutorials are code samples in the first hand :) I believe correct link should look like https://github.com/Intel-Media-SDK/MediaSDK/tree/intel-mediasdk-19.4/tutorials. But docs are also ok. And shame on me - original link was broken.
