### ISSUE TITLE
Error when building "‘VA_FOURCC_A2R10G10B10’ was not declared in this scope"

### ISSUE THREAD

**Issue by mkomarinski** [Intel-Media-SDK/MediaSDK#1903]
Debian Buster latest updates:

[...]
[  3%] Building CXX object samples/sample_common/CMakeFiles/sample_common.dir/src/vaapi_allocator.cpp.o
/home/markk/MediaSDK/samples/sample_common/src/vaapi_allocator.cpp: In member function ‘virtual mfxStatus vaapiFrameAllocator::LockFrame(mfxMemId, mfxFrameData*)’:
/home/markk/MediaSDK/samples/sample_common/src/vaapi_allocator.cpp:592:18: error: ‘VA_FOURCC_A2R10G10B10’ was not declared in this scope
             case VA_FOURCC_A2R10G10B10:
                  ^~~~~~~~~~~~~~~~~~~~~
/home/markk/MediaSDK/samples/sample_common/src/vaapi_allocator.cpp:592:18: note: suggested alternative: ‘MFX_FOURCC_A2RGB10’
             case VA_FOURCC_A2R10G10B10:
                  ^~~~~~~~~~~~~~~~~~~~~
                  MFX_FOURCC_A2RGB10
make[2]: *** [samples/sample_common/CMakeFiles/sample_common.dir/build.make:297: samples/sample_common/CMakeFiles/sample_common.dir/src/vaapi_allocator.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:239: samples/sample_common/CMakeFiles/sample_common.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
markk@plex:~/MediaSDK/build$

**Comment by AntonGrishin** [comment]
Hi @mkomarinski,

Seems that you have not last LibVA version.
Can you please provide output from `vainfo`?

**Comment by mkomarinski** [comment]
Hi @AntonGrishin,

error: can't connect to X server!
libva info: VA-API version 1.6.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /opt/intel/mediasdk/lib64/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_6
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.6 (libva 2.4.0)
vainfo: Driver version: Intel iHD driver - 19.4.0
vainfo: Supported profile and entrypoints
      VAProfileNone                   : VAEntrypointVideoProc
      VAProfileNone                   : VAEntrypointStats
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointFEI
      VAProfileH264Main               : VAEntrypointEncSliceLP
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointFEI
      VAProfileH264High               : VAEntrypointEncSliceLP
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline: VAEntrypointFEI
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointFEI
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointEncSlice
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointVLD

**Comment by AntonGrishin** [comment]
Hi @mkomarinski,

AFAIK `VA_FOURCC_A2R10G10B10` declared since 1.4.0, so maybe you use different libva during the MediaSDK build (you can try to set `PKG_CONFIG_PATH=/path/to/libva1.6.0/pkgconfig`)

**Comment by mkomarinski** [comment]
Ok. I may try with CentOS because otherwise I'm going to go down a rabbit hole of unpackaged upgrades.  Thanks for the help.

**Comment by mpalmer** [comment]
For anyone who comes up against this: I hit this problem, using the `libva` from Debian Buster, which reported "Found libva, version 1.4.0" in the build log.  Building with the `libva` currently in Debian Bullseye (2.9.0-1) worked OK.
