### ISSUE TITLE
Opencl headers should be provided in package (in-tree)

### ISSUE THREAD

**Issue by RarogCmex** [Intel-Media-SDK/MediaSDK#1908]
`/usr/bin/x86_64-pc-linux-gnu-ranlib ../../../__lib/Gentoo/libencode_hw.a
make[2]: Leaving directory '/var/tmp/portage/media-libs/intel-mediasdk-9999/work/intel-mediasdk-9999_build'
[ 90%] Built target encode_hw
[ 90%] Linking CXX executable ../../__bin/Gentoo/sample_hevc_fei_abr
cd /var/tmp/portage/media-libs/intel-mediasdk-9999/work/intel-mediasdk-9999_build/samples/sample_hevc_fei_abr && /usr/bin/cmake -E cmake_link_script CMakeFiles/sample_hevc_fei_abr.dir/link.txt --verbose=1
/usr/bin/x86_64-pc-linux-gnu-g++  -msse4.2 -std=c++11 -m64 -g -march=native -O2 -pipe -pipe -fPIC -Wall -Wformat -Wformat-security -Wnon-virtual-dtor -Wno-deprecated-declarations -Wno-unknown-pragmas -Wno-unused  -DUNIX -D__USE_LARGEFILE64 -D_FILE_OFFSET_BITS=64 -DLINUX -DLINUX32 -DLINUX64 -DMSDK_BUILD=\"\"  -DMFX_BUILD_INFO="\"Gentoo 5.4.6-ck-RarogCmex | GNU 9.2.0 | glibc 2.29"\" -DMFX_API_VERSION=\"1.31\" -DMFX_GIT_COMMIT=\"1c84cc66\"  -fPIE -pie -Wl,-O1 -Wl,--as-needed -Wl,--no-undefined,-z,relro,-z,now,-z,noexecstack -Wl,--no-as-needed -ldl  -fstack-protector   -Wl,--default-symver -Wl,--no-undefined,-z,relro,-z,now,-z,noexecstack -fstack-protector  CMakeFiles/sample_hevc_fei_abr.dir/src/abr_brc.cpp.o CMakeFiles/sample_hevc_fei_abr.dir/src/cmd_processor.cpp.o CMakeFiles/sample_hevc_fei_abr.dir/src/dso/bs_reader.cpp.o CMakeFiles/sample_hevc_fei_abr.dir/src/dso/bs_reader2.cpp.o CMakeFiles/sample_hevc_fei_abr.dir/src/dso/bs_thread.cpp.o CMakeFiles/sample_hevc_fei_abr.dir/src/dso/common_cabac.cpp.o CMakeFiles/sample_hevc_fei_abr.dir/src/dso/dll_main.cpp.o CMakeFiles/sample_hevc_fei_abr.dir/src/dso/hevc2_cabac.cpp.o CMakeFiles/sample_hevc_fei_abr.dir/src/dso/hevc2_dec.cpp.o CMakeFiles/sample_hevc_fei_abr.dir/src/dso/hevc2_headers.cpp.o CMakeFiles/sample_hevc_fei_abr.dir/src/dso/hevc2_parser.cpp.o CMakeFiles/sample_hevc_fei_abr.dir/src/dso/hevc2_ssdata.cpp.o CMakeFiles/sample_hevc_fei_abr.dir/src/dso/hevc2_trace.cpp.o CMakeFiles/sample_hevc_fei_abr.dir/src/dso/hevc_cabac.cpp.o CMakeFiles/sample_hevc_fei_abr.dir/src/dso/hevc_cabac_tables.cpp.o CMakeFiles/sample_hevc_fei_abr.dir/src/dso/hevc_sdec_ctx.cpp.o CMakeFiles/sample_hevc_fei_abr.dir/src/fei_buffer_allocator.cpp.o CMakeFiles/sample_hevc_fei_abr.dir/src/fei_utils.cpp.o CMakeFiles/sample_hevc_fei_abr.dir/src/fei_worker.cpp.o CMakeFiles/sample_hevc_fei_abr.dir/src/hevc_fei_encode.cpp.o CMakeFiles/sample_hevc_fei_abr.dir/src/hevc_sw_dso.cpp.o CMakeFiles/sample_hevc_fei_abr.dir/src/pipeline_hevc_fei.cpp.o CMakeFiles/sample_hevc_fei_abr.dir/src/sample_hevc_fei_abr.cpp.o  -o ../../__bin/Gentoo/sample_hevc_fei_abr  -Xlinker --start-group ../../__lib/Gentoo/libsample_common.a ../../__bin/Gentoo/libmfx.so.1.31 -ldl -lpthread -Xlinker --end-group -lgcc -lgcc 
make[2]: Leaving directory '/var/tmp/portage/media-libs/intel-mediasdk-9999/work/intel-mediasdk-9999_build'
[ 90%] Built target sample_hevc_fei_abr
make[1]: Leaving directory '/var/tmp/portage/media-libs/intel-mediasdk-9999/work/intel-mediasdk-9999_build'
make: *** [Makefile:130: all] Error 2
`

The complete build log:
[build.log](https://github.com/Intel-Media-SDK/MediaSDK/files/4054201/build.log)
Package manager info (using custom ebuild):
[emerge_info.txt](https://github.com/Intel-Media-SDK/MediaSDK/files/4054202/emerge_info.txt)
Build environment
[environment.txt](https://github.com/Intel-Media-SDK/MediaSDK/files/4054205/environment.txt)

Used git version of mediasdk

**Comment by dmitryermilov** [comment]
Are you sure that sample_hevc_fei build failed?
From attached log file I see rotate_opencl failed:
```

../../__bin/Gentoo/libmfx.so.1.31 -ldl -lpthread -Xlinker --end-group -lgcc -lgcc 
In file included from [01m[K/var/tmp/portage/media-libs/intel-mediasdk-9999/work/intel-mediasdk-9999/samples/sample_plugins/rotate_opencl/src/opencl_filter_va.cpp:22[m[K:
[01m[K/var/tmp/portage/media-libs/intel-mediasdk-9999/work/intel-mediasdk-9999/samples/sample_plugins/rotate_opencl/include/opencl_filter_va.h:34:10:[m[K [01;31m[Kfatal error: [m[KCL/cl_va_api_media_sharing_intel.h: No such file or directory
   34 | #include [01;31m[K<CL/cl_va_api_media_sharing_intel.h>[m[K
      |          [01;31m[K^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[m[K
compilation terminated.
make[2]: *** [samples/sample_plugins/rotate_opencl/CMakeFiles/sample_plugin_opencl.dir/build.make:102: samples/sample_plugins/rotate_opencl/CMakeFiles/sample_plugin_opencl.dir/src/opencl_filter_va.cpp.o] Error 1
make[2]: Leaving directory '/var/tmp/portage/media-libs/intel-mediasdk-9999/work/intel-mediasdk-9999_build'
make[1]: *** [CMakeFiles/Makefile2:1543: samples/sample_plugins/rotate_opencl/CMakeFiles/sample_plugin_opencl.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by RarogCmex** [comment]
No, It really seems to opencl trouble, thank you for attention.
How to fix its?

**Comment by RarogCmex** [comment]
Ok, as I investigated header https://github.com/KhronosGroup/OpenCL-Headers/blob/master/CL/cl_va_api_media_sharing_intel.h should be in-tree when its not. And also it had required even where setuped -DENABLE_OPENCL=OFF in configure stage (seems bug?).

**Comment by dmitryermilov** [comment]
@AntonGrishin , could you take a look?

**Comment by dmitryermilov** [comment]
@AntonGrishin , any news?

**Comment by AntonGrishin** [comment]
Hi @RarogCmex @dmitryermilov,

As I see, ENABLE_OPENCL uses only here: 
https://github.com/Intel-Media-SDK/MediaSDK/blob/69f22b15d085038c0ccb7ecbf313e0c0e93917ad/builder/FindPackages.cmake#L430
Also I checked both cmake configurations, and looks like all work properly.
build targets with `-DENABLE_OPENCL=ON`:
![image](https://user-images.githubusercontent.com/34107292/73630527-66e3c380-4667-11ea-8fbb-cb3d69793cc1.png)
` -DENABLE_OPENCL=OFF`:
![image](https://user-images.githubusercontent.com/34107292/73630560-8549bf00-4667-11ea-8ea9-60a47945d06a.png)

Btw,

**Comment by RarogCmex** [comment]
Hi @AntonGrishin I found that it's not checked only for x86, not x86_64. So I don't know how it actually...

**Comment by AntonGrishin** [comment]
@RarogCmex can you please share more details?
Logs w/ `-DENABLE_OPENCL=ON/OFF` ?
I don`t see any gaps for configure opencl x86/x86_64 in cmake files.

**Comment by RarogCmex** [comment]
@AntonGrishin 

[build.log](https://github.com/Intel-Media-SDK/MediaSDK/files/4147504/build.log)

**Comment by RarogCmex** [comment]
Also see build.log in thread's head

**Comment by AntonGrishin** [comment]
@RarogCmex I didn`t see error with OpenCL, but found few another errs, like:

```
/usr/bin/x86_64-pc-linux-gnu-g++ -m32 -DLINUX -DLINUX32 -DMFX_MODULES_DIR=\"/usr/lib\" -DMFX_PLUGINS_CONF_DIR=\"/usr/share/mfx\" -DUNIX -D_FILE_OFFSET_BITS=64 -D__USE_LARGEFILE64 -Dmfx_EXPORTS -I/var/tmp/portage/media-libs/intel-mediasdk-19.4.0-r1/work/MediaSDK-intel-mediasdk-19.4.0/api/mediasdk_structures -I/var/tmp/portage/media-libs/intel-mediasdk-19.4.0-r1/work/MediaSDK-intel-mediasdk-19.4.0/api/include -I. -I/var/tmp/portage/media-libs/intel-mediasdk-19.4.0-r1/work/MediaSDK-intel-mediasdk-19.4.0/api/mfx_dispatch/linux/../../include  -DNDEBUG -msse4.2 -std=c++11 -m32 -g -march=native -O2 -pipe -pipe -fPIC -Wall -Wformat -Wformat-security -Wnon-virtual-dtor -Wno-deprecated-declarations -Wno-unknown-pragmas -Wno-unused  -DUNIX -D__USE_LARGEFILE64 -D_FILE_OFFSET_BITS=64 -DLINUX -DLINUX32 -DMSDK_BUILD=\"\"  -DMFX_BUILD_INFO="\"Gentoo 5.4.15-ck-RarogCmex | GNU 9.2.0 | glibc 2.29"\" -DMFX_API_VERSION=\"1.31\" -DMFX_GIT_COMMIT=\"\" -pipe -fPIC -std=c++11 -Wall -Wformat -Wformat-security -Wno-unknown-pragmas -Wno-unused -fPIC -MD -MT api/mfx_dispatch/linux/CMakeFiles/mfx.dir/mfxparser.cpp.o -MF api/mfx_dispatch/linux/CMakeFiles/mfx.dir/mfxparser.cpp.o.d -o api/mfx_dispatch/linux/CMakeFiles/mfx.dir/mfxparser.cpp.o -c /var/tmp/portage/media-libs/intel-mediasdk-19.4.0-r1/work/MediaSDK-intel-mediasdk-19.4.0/api/mfx_dispatch/linux/mfxparser.cpp
In file included from /var/tmp/portage/media-libs/intel-mediasdk-19.4.0-r1/work/MediaSDK-intel-mediasdk-19.4.0/api/mfx_dispatch/linux/mfxloader.h:29,
                 from /var/tmp/portage/media-libs/intel-mediasdk-19.4.0-r1/work/MediaSDK-intel-mediasdk-19.4.0/api/mfx_dispatch/linux/mfxparser.cpp:28:
/var/tmp/portage/media-libs/intel-mediasdk-19.4.0-r1/work/MediaSDK-intel-mediasdk-19.4.0/api/include/mfxdefs.h:90:6: error: #error Unknown packing
   90 |     #error Unknown packing
```

**Comment by RarogCmex** [comment]
Ok, may be. 
Issue can be closed I'm sure
