### ISSUE TITLE
19.4 sample_decode error

### ISSUE THREAD

**Issue by bbao3** [Intel-Media-SDK/MediaSDK#1915]
Hi, I have seen a strange error in sample_decode of new 19.4 MSDK release: it will show a -3 error in use HW acceleration but with system memory (although the decode will proceed successfully).
sample_decode of 19.3.1 have no problem. Can you help fix the issue? Thanks.

Command and log as below: 

_root@intel-dbg:/opt/intel/mediasdk/share/mfx/samples# ./sample_decode h264 -i /video.h264 -hw
libva info: VA-API version 1.6.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /usr/local/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_6
libva info: va_openDriver() returns 0

**[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), AllocImpl, sts!=MFX_ERR_NONE error at /home/intel/vpg_env/MediaSDK-19.4.0/samples/sample_common/src/general_allocator.cpp:154
Decoding Sample Version 19.4.0**

Input video	AVC 
Output format	NV12
Input:
  Resolution	1920x1088
  Crop X,Y,W,H	0,0,1920,1080
Output:
  Resolution	1920x1080
Frame rate	50.00
Memory type		system
MediaSDK impl		hw
MediaSDK version	1.31

Decoding started
Frame number: 1679, fps: 771.409, fread_fps: 0.000, fwrite_fps: 0.000
Decoding finished_

![image](https://user-images.githubusercontent.com/44154245/72592975-cab77e00-393e-11ea-9548-f5f0b1bb50cc.png)

**Comment by dmitryermilov** [comment]
It's the same as https://github.com/Intel-Media-SDK/MediaSDK/issues/1800 
It will be a addressed by https://github.com/Intel-Media-SDK/MediaSDK/pull/1912
