### ISSUE TITLE
Output PSNR during encoding

### ISSUE THREAD

**Issue by daijh** [Intel-Media-SDK/MediaSDK#192]
Hi,
    We use mfx vpp+encoder to do video transcoding (possible scale, frc). And we use the PSNR of  the compressed video to check if low quality and trigger re-transcoding.
    So could you help to directly output PSNR after each frame encoding? Similar as other encoder x264, x265 and libvpx? 
    W/ this MSDK PSNR feature, it is also each to enable ffmpeg-qsv-encoder "-pnsr" option.
    Thank you.

**Comment by lizhong1008** [comment]
We can expose QP firstly because PSNR is support. 
But currently exposing QP is disabled now: https://github.com/Intel-Media-SDK/MediaSDK/blob/d0c68f5aa1e1c34eb6ef66c2f57a70548095da83/_studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp#L3098 
I tried to uncomment it and it works. 
So how about sending a patch to uncomment this line?

**Comment by artem-shaporenko** [comment]
@daijh Good feature request, what about SSIM requirement?
@lizhong1008 Sure, just submit PR.

**Comment by lizhong1008** [comment]
@artem-shaporenko , PR has been sent : https://github.com/Intel-Media-SDK/MediaSDK/pull/249

**Comment by artem-shaporenko** [comment]
Ok, thanks, have you checked result is right?

**Comment by adydychk** [comment]
@daijh Do you need any response in this issue from us? PR was merged.

**Comment by adydychk** [comment]
Feel free to reopen it or create new one if you have troubles.

**Comment by dvrogozh** [comment]
Folks, there were 2 requests in this issue:
1. Expose QP with which frame was encoded
2. Expose PSNR of the encoded QP

PR satisfied only 1st request, PSNR is still not exposed.

**Comment by egorovdanil** [comment]
PSNR is currently not supported in MediaSDK and media-driver.
Could you please clarify at what level you want this feature, samples or library?
You can also use our tool metrics_calc_lite to calculate PSNR: https://github.com/Intel-Media-SDK/tools

**Comment by egorovdanil** [comment]
Please reopen if still actual.
