### ISSUE TITLE
Apollo Lake LookAhead MFXVideoENCODE_Init failed

### ISSUE THREAD

**Issue by aaronovz1** [Intel-Media-SDK/MediaSDK#193]
I am using MSDK 1.2a under LibAV/QSV on Linux and I am trying to use Look Ahead BRC (MFX_RATECONTROL_LA) but MFXVideoENCODE_Init is returning MFX_ERR_UNSUPPORTED. Is there any way to get more information on what exactly is causing the error?

Is there a Linux tool like the MSDK analyzer that can display all supported features?

**Comment by aaronovz1** [comment]
Anyone have any clue? The only encoding option that seems to work without error is CQP.

**Comment by onabiull** [comment]
Could you please check this issue on one of the latest releases? Like 19.2.1.

**Comment by aaronovz1** [comment]
I'm going to wait till the 19.3 release to reduce overhead of recompiling libraries and testing.

**Comment by daleksan** [comment]
feel free to re-open the issue if it is still actual
