### ISSUE TITLE
Does MSDK support ARM?

### ISSUE THREAD

**Issue by jsunintel** [Intel-Media-SDK/MediaSDK#1957]
I'd like try MSDK on ARM, and can I build MSDK by toolchain (aarch64-ese-linux) on Linux for ARM?

**Comment by onabiull** [comment]
Short answer is no. Most likely it won't even compile.

Longer answer is it may be possible given a few assumptions.
Media SDK primary target is Intel® Gen graphics hardware platforms. But from code perspective we provide a convenience wrapper for hardware-agnostic VA API. So given that someone would write a conformant VA API implementation (say media driver) for given ARM platform, basic Media SDK functionality may turn out workable.

**Comment by jsunintel** [comment]
> 
> 
> Short answer is no. Most likely it won't even compile.
> 
> Longer answer is it may be possible given a few assumptions.
> Media SDK primary target is Intel® Gen graphics hardware platforms. But from code perspective we provide a convenience wrapper for hardware-agnostic VA API. So given that someone would write a conformant VA API implementation (say media driver) for given ARM platform, basic Media SDK functionality may turn out workable.

Thanks for the quick reply! What I need are just a few tools for testing in MSDK, such as crc calc, metrics & psnr computing. Those have nothing to do with VA API. Is there a method that I can easily build them on Linux by toolchain for ARM?

**Comment by dmitryermilov** [comment]
@jsunintel , could you say which particular tools are you interested? Please give links.

**Comment by jsunintel** [comment]
> 
> 
> @jsunintel , could you say which particular tools are you interested? Please give links.

Hi @dmitryermilov, we would like to have cocotor, ldecod, metrics_calc_lite, calc_crc & djpeg under mdp_msdk-val-tools.
