### ISSUE TITLE
MFX_ERR_INVALID_VIDEO_PARAM error code is not enough for DEBUG real issues

### ISSUE THREAD

**Issue by galinart** [Intel-Media-SDK/MediaSDK#1959]
Initialization functions like MFXVideoDECODE_Init(), MFXVideoVPP_Init(), MFXVideoEncode_Init() return MFX_ERR_INVALID_VIDEO_PARAM if some of the parameters are incorrect or could not be accepted.

MFX_ERR_INVALID_VIDEO_PARAM will be returned if one of required calls have been missed before that function call. For example: MFXVideoCORE_SetFrameAllocator() call is required if you use MFX_MEMTYPE_VIDEO_MEMORY_DECODER_TARGET type of memory as output for decoder.

It will be great to have some detailed information what is happening underneath in case if user missed some initialization parameters or even used some incorrect order of function calls.

As solution I could suggest adding trace information for Media SDK tracer as it is required only for debug stage.

**Comment by onabiull** [comment]
Not fully addressed yet, but just wanted to let you know, that https://github.com/Intel-Media-SDK/MediaSDK/pull/1975 merged, and brings Media SDK API Tracer.

**Comment by agalin89** [comment]
Great! Thanks for the update!

**Comment by daleksan** [comment]
Hi @galinart i'm going to close the issue, feel free to re-open if it still relevant for you
