### ISSUE TITLE
JPEG decoder can't ouput 422P/444P/440P format for YUV422/YUV444/YUV440 jpeg file

### ISSUE THREAD

**Issue by sunxinpeng** [Intel-Media-SDK/MediaSDK#1960]
Media SDK JPEG decoder can only ouput NV12 for YUV422/YUV444/YUV440 jpeg file decoding. For these three types of jpeg files, the ouput format(NV12) is different from the chroma format. 
Here is a relevant issue reported before:
[https://github.com/Intel-Media-SDK/MediaSDK/issues/1575](url)

**Comment by chuanli1** [comment]
the link is invalid，could you update the link? @sunxinpeng

**Comment by SofyaBalandina** [comment]
Hi
To get output stream in not NV12 fourcc, please, specify the output fourcc with options like -ayuv/-y416/etc.
For example:
`./sample_decode jpeg -i smpte_444P.jpeg -o output.yuv -hw -ayuv `

It could be used fourcc and options -ayuv/-y416 to convert stream to chroma format YUV444
It could be used fourcc and option -yuy2 to convert stream to chroma format YUV422
Unfortunately I have no information about fourcc related to format YUV440

But converting without VPP for JPEG in sample_decode is possible only to rgb4.
`From manual: Note, that NV12 is the major encoding and decoding color format. Additionally, JPEG/MJPEG decoder supports RGB32 and YUY2 output`
(so, looks like in general except rgb32 it is possible to yuy2 for JPEG, but it is not implemented in sample_decode now)

**Comment by wangyan-intel** [comment]
@sunxinpeng Could you please check @SofyaBalandina's comments? Could you please check @SofyaBalandina's comments? If OK, could we close this issue? Thanks. If OK, could we close this issue? Thanks.

**Comment by sunxinpeng** [comment]
@wangyan-intel I have not worked on it for a long time and I have no local environment to validate it. You can check this issue with @xhaihao or just close this issue.

**Comment by wangyan-intel** [comment]
@sunxinpeng Yes. I have pinged @xhaihao in #1575. Thanks.

**Comment by sunxinpeng** [comment]
@wangyan-intel OK. Close this issue.
