### ISSUE TITLE
qsv hevc quaility worse than qsv264 on the same bitrate encode? 

### ISSUE THREAD

**Issue by lion117** [Intel-Media-SDK/MediaSDK#1967]
Hi,  I had done some quaility  tests on  qsv hevc  using netflix tool : VMAF 
Here is my test Result 

![小Q截图-20200214180445](https://user-images.githubusercontent.com/3996029/74521579-8a0a4f00-4f54-11ea-9b06-b2e5a9080d26.png)

[result download](https://cdmd-1257623782.cos.ap-chengdu.myqcloud.com/mdpic/20200214181428.png) 

I used the sample_encode.exe which is in the MEDIASDK-2018R2 package. 
Here is my cmds:
```
sample_encode.exe h265 -i bigdd.yuv -o bigdd_out_265_1200.h265 -w 960 -h 720  -cbr -b 1200  -f 15  -g  30
```
I had done more test  like **X264&X264**   **NVIDIA264&NVIDIA265** . The result fit the theory . 
HEVC quaility better than H264 with the same bitrate 

#### with the same bitrate ,more complex algorithm ,   if qsv hevc encode mode quiality is worse than qsv264 , what is the meaning for qsv-hevc ?

**Comment by dvrogozh** [comment]
What was the underlying Intel GPU you've tried?

**Comment by lion117** [comment]
Cpu:I5-6500&nbsp;
Gpu:Intel(R) HD Graphics 530




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Dmitry Rogozhkin"<notifications@github.com&gt;; 
发送时间: 2020年2月14日(星期五) 晚上11:11
收件人: "Intel-Media-SDK/MediaSDK"<MediaSDK@noreply.github.com&gt;; 
抄送: "leo_nardo"<ngixpro@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Intel-Media-SDK/MediaSDK] qsv hevc quaility worse than qsv264 on the same bitrate encode?  (#1967)




What was the underlying Intel GPU you've tried?

**Comment by lion117** [comment]
> What was the underlying Intel GPU you've tried?

Any Suggestion about this issue ?

**Comment by dmitryermilov** [comment]
Hi @lion117 ,

We need a few day to reply.

Regards,
Dmitry

**Comment by ayakove** [comment]
Hi @lion117,

as a first step let me reproduce your result.
Could you share "bigdd.yuv" stream with us?

**Comment by lion117** [comment]
provide your email. I will send it to u



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ayakove"<notifications@github.com&gt;; 
发送时间: 2020年2月20日(星期四) 晚上8:42
收件人: "Intel-Media-SDK/MediaSDK"<MediaSDK@noreply.github.com&gt;; 
抄送: "leo_nardo"<ngixpro@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [Intel-Media-SDK/MediaSDK] qsv hevc quaility worse than qsv264 on the same bitrate encode?  (#1967)




Hi @lion117,
 
as a first step let me reproduce your result.
 Could you share "bigdd.yuv" stream with us?

**Comment by ayakove** [comment]
ayakove@gmail.com - you can see in my profile

**Comment by lion117** [comment]
> [ayakove@gmail.com](mailto:ayakove@gmail.com) - you can see in my profile

I am sorry that  google gmail is unable to access in china . Could u provide other emails, like microsoft email

**Comment by ayakove** [comment]
please, try andrey.yakovenko@intel.com

**Comment by ayakove** [comment]
Hi @lion117 , I posted my non google email 6 days ago but still haven't got any video.
By the way, you can see in Release Notes that HEVC on SKL system has limited features support. 
-----------------------------------------------------------------------------------
Intel® Media Software Development Kit 2016 Release Notes (Version 7.0.0.311)
HEVC Encode:
o Current support of features limited comparing to AVC encode, please
refer to limitations section.

Intel® Media Software Development Kit 2016 R2 Release Notes (Version 7.0.0.358)
HW HEVC Encode:
o Full HW HEVC encode MAIN10 profile supported on 7th Generation
Intel® Core™ and Core M platforms with limited feature coverage, please refer to limitations section.
---------------------------------------------------------------------------------

**Comment by lion117** [comment]
I am sorry to hear that . I had sent the video data to your two email . I Guess the something&nbsp; had block the email.&nbsp;I will post the video file into my cloud , you can download from there .&nbsp;
Is that Ok ?&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ayakove"<notifications@github.com&gt;; 
发送时间: 2020年2月28日(星期五) 凌晨5:13
收件人: "Intel-Media-SDK/MediaSDK"<MediaSDK@noreply.github.com&gt;; 
抄送: "leo_nardo"<ngixpro@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [Intel-Media-SDK/MediaSDK] qsv hevc quaility worse than qsv264 on the same bitrate encode?  (#1967)




Hi @lion117 , I posted my non google email 6 days ago but still haven't got any video.
 By the way, you can see in Release Notes that HEVC on SKL system has limited features support.
 
Intel® Media Software Development Kit 2016 Release Notes (Version 7.0.0.311)
 HEVC Encode:
 o Current support of features limited comparing to AVC encode, please
 refer to limitations section.
 
Intel® Media Software Development Kit 2016 R2 Release Notes (Version 7.0.0.358)
 HW HEVC Encode:
 o Full HW HEVC encode MAIN10 profile supported on 7th Generation
 Intel® Core and Core M platforms with limited feature coverage, please refer to limitations section.

**Comment by lion117** [comment]
> Hi @lion117 , I posted my non google email 6 days ago but still haven't got any video.
> By the way, you can see in Release Notes that HEVC on SKL system has limited features support.
> 
> Intel® Media Software Development Kit 2016 Release Notes (Version 7.0.0.311)
> HEVC Encode:
> o Current support of features limited comparing to AVC encode, please
> refer to limitations section.
> 
> Intel® Media Software Development Kit 2016 R2 Release Notes (Version 7.0.0.358)
> HW HEVC Encode:
> o Full HW HEVC encode MAIN10 profile supported on 7th Generation
> Intel® Core™ and Core M platforms with limited feature coverage, please refer to limitations section.

Hi , U can download the file from [Here](https://md-1257623782.cos.ap-guangzhou.myqcloud.com/video/bigdd.yuv). 
to protect provice , the link would abondan after 3 days. please don`t share it on the internet

**Comment by ayakove** [comment]
got it. thanks

**Comment by ayakove** [comment]
Hi @lion117, 

could you share which graphic driver (version)  installed on your windows system?

**Comment by ayakove** [comment]
Hi @lion117 

Pls modify your current command line for encoding (btw, for HEVC hw encoding plugin needs to be specified)
Sample_encode.exe h264  -i input.yuv -o out.h264 -w <width> -h <height> -cbr -b <bitrate> -f 15 -g 30
Sample_encode.exe h265  -i input.yuv -o out.h265 -w <width> -h <height> -cbr -b <bitrate> -f 15 -g 30 -p hevce_hw

to, updated command line such as: 
Sample_encode.exe h264 -extbrc:on  -i input.yuv -o out.h264 -w <width> -h <height> -cbr -b <bitrate> -f 15 -g 30
Sample_encode.exe h265 -extbrc:on  -i input.yuv -o out.h265 -w <width> -h <height> -cbr -b <bitrate> -f 15 -g 30 -p hevce_hw

Note that updated command line  specifies a specific bit rate controller (extBRC) which provides better results with HEVC, If you
wish even AVC hw encoding can use extBRC also, but for AVC sometimes extBrC provides better results sometimes not.
On SKL, updated curves for VMAF metric  at bitrates of interest when using extBRc vs not for AVC and HEVC are then as follows.

BdRate wrt to HW HEVC
                    | PSNR   | VMAF
AVC              | -8.99   | -7.65
AVC extBrc   | -3.40   | 6.64
HEVC extBrc | -13.07 | -13.79

**Comment by lion117** [comment]
thanks.  I Will take a try

**Comment by lion117** [comment]
Hi,  I had do some test. Here is my result . 

![image](https://user-images.githubusercontent.com/3996029/77305295-b9b92d80-6d30-11ea-88bc-1033bb3b429f.png)

**Comment by dmitryermilov** [comment]
Can it be closed?
