### ISSUE TITLE
[windows] QuickSync ICQ mode HEVC 8-bit/10-bit encoding using "fixed function" and changing quality level - API v1.30.

### ISSUE THREAD

**Issue by ukmark62** [Intel-Media-SDK/MediaSDK#1977]
Hi
Using API v1.30 and I find that changing the QuickSync ICQ quality level for HEVC 8-bit/10-bit when encoding using "fixed function" has no effect. Output files remain same size. 

It works correctly for AVC/H264 but not for HEVC. Could somebody please check if this works in the latest version? Thanks.

PS. I am using Ice Lake laptop with i7-1065G7 CPU and Intel Iris Plus graphics (driver version 26.20.100.7463). I also tried driver 26.20.100.7755 and have same problem.

**Comment by dmitryermilov** [comment]
Hi @ukmark62 ,

Are you talking about TargetUsage? Which values did you try? TU1, TU4, TU7 ?

**Comment by ukmark62** [comment]
Hi,

I'm specifically referring to the quality level (0-51). Changing that value has no impact, so ICQ 5 produces same output size as ICQ 40, when ICQ 5 should produce much larger output. Thanks.

**Comment by dmitryermilov** [comment]
Ahh. I see.

**Comment by dmitryermilov** [comment]
@vilichev , can you please reply?

**Comment by dmitryermilov** [comment]
@ukmark62 , 
could you share sample_encode command like which you can run and reproduce the issue?

**Comment by ukmark62** [comment]
Of course,

I am using the program QSVEnc (by rigaya) (https://github.com/rigaya/QSVEnc/). I have already asked him and as far as he is aware, the program is passing the correct info to the Media SDK API. This is the command run from the QSVEnc directory:-

**QSVEncC64.exe --avhw --codec hevc --quality best --profile main10 --open-gop --async-depth 4 --fixed-func --icq 23 --crop 2,140,2,140 --output-res 1280x536 -i "inputfile.mkv" -o "outputfile.hevc"**

If you then run again with for example "**--icq 30**", the output file size does not change (not for me). Thanks again.

**Comment by dmitryermilov** [comment]
@lakulako , can you give and check sample_encode command line?

**Comment by ukmark62** [comment]
I just upgraded my device driver to version 26.20.100.7870. This upgraded the Intel Media SDK API from v1.30 to v1.31, but the issue still remains.

**Comment by lakulako** [comment]
Checked with sample_encode on windows.
sample_encode.exe h265 -i foreman_352x288_300.yuv -w 352 -h 288 -hw -d3d -dump par.txt -o tmp_lp_icq10.h265  -icq 10 -qsv-ff
Confirm, that icq parameter and icq mode are set after init (see in dump), but in encoded stream cqp is used instead with default qp=26.
Used icelake with latest sw.
It is unsupported for FF.

**Comment by dmitryermilov** [comment]
Thanks @lakulako . Are you saying that low power encoder doesn't support ICQ and we internally change BRC mode to CQP?

**Comment by ukmark62** [comment]
So it is supported for AVC/H.264 FF, but not for HEVC. Are there plans to support for HEVC?

**Comment by ukmark62** [comment]
Just updated the title to denote that 8-bit HEVC has same issue as 10-bit.

**Comment by daleksan** [comment]
@vilichev can you please triage and forward the issue to the right owner?

**Comment by vilichev** [comment]
Fixed function relates to Low Power (VDENC), Hi, @thomasli21801 could you please triage or assign correct owner

**Comment by mikk9** [comment]
Same issue on my Tigerlake based i7-1165G7, different ICQ quality factor settings have no effect. With current API 1.34 drivers it is completely unavailable. H264 ICQ FF yes but no H265 ICQ FF.

**Comment by thomasli21801** [comment]
Hi
Low power HEVC encoder now doesn't support ICQ now.
I'm in discussion now with key stakeholders to collect feedback and will get back.

**Comment by mikk9** [comment]
So is this a driver limitation at the moment or the hardware does not support it? If it's driver related I hope it will come later. Let us know if there is an update, thanks.

**Comment by daleksan** [comment]
Hi @thomasli21801  do you have any updates?

**Comment by thomasli21801** [comment]
@daleksan , HEVC VDEnc ICQ functionality is enabled recently. But the Windows driver is not released to public yet. It usually takes about several weeks for internal cycle before publish.

**Comment by gitoss** [comment]
> HEVC VDEnc ICQ functionality is enabled recently

Is there any word on compatibilty with low power UHD, like in Gemini Lake Refresh (Goldmont Plus) or esp. the recently released Jasper Lake (Tremont)? The latter is said to have enhanced video encoding capability, but I didn't find any specs or reviews yet.
