### ISSUE TITLE
The file sizes are twice as big when using LA-ICQ vs ICQ for AVC/H.264

### ISSUE THREAD

**Issue by ukmark62** [Intel-Media-SDK/MediaSDK#1981]
The file sizes are still twice as big when using LA-ICQ vs ICQ for AVC/H.264 QuickSync.  Just tested this using "QSVEnc" and "Handbrake" programs. File sizes should be similar.

Do you know why issue #989 is closed??

**Comment by dmitryermilov** [comment]
Hi @ukmark62 , please specify versions of media stack components(msdk/media-driver/gmm/libva), HW type, command lines (ideally via sample or ffmpeg) so that we can reproduce it quickly.

**Comment by ukmark62** [comment]
If you refer back to the original issue #989, steps were detailed how to reproduce the problem. If somebody could verify by simply re-running that example, it would determine if the problem is still present in the 'master' branch.

**Comment by dmitryermilov** [comment]
I think it's better to ask a reporter why he closed the issue.

**Comment by ukmark62** [comment]
Using the QSVEnc CLI from rigaya on Windows 10 (https://github.com/rigaya/QSVEnc/), this is a template command how to reproduce the issue. ICQ with LA has double file size of ICQ for the same quality.

ICQ
**D:\StaxRip\Apps\Encoders\QSVEnc\QSVEncC64.exe --quality best --icq 24 -i "input.mkv" -o "output.h264"

ICQ with lookahead
D:\StaxRip\Apps\Encoders\QSVEnc\QSVEncC64.exe --quality best --la-depth 30 --la-icq 24 -i "input.mkv" -o "output.h264"**

**Comment by ukmark62** [comment]
For ffmpeg use:-
ICQ
**ffmpeg -i input.mp4 -c:v h264_qsv -global_quality 24 output.mp4**

ICQ & Lookahead 
**ffmpeg -i input.mp4 -c:v h264_qsv -global_quality 24 -look_ahead 1 -look_ahead_depth 30 output.mp4**

**Comment by dmitryermilov** [comment]
@DenWolf , any news?

**Comment by DenWolf** [comment]
@pgribov  - could you please take a look at this issue ?

**Comment by pgribov** [comment]
Hi, @ukmark62 . I have looked to this issue. At the moment, LA_ICQ gives higher quality with an increase in bitrate, so a file oversize compared to ICQ is expected.

How important is it for LA_ICQ to give a smaller file size? And in what use cases will you use it?

**Comment by ukmark62** [comment]
Thanks for looking.  I don't use AVC much - nearly always use HEVC. However, a doubling of file size seems extreme. I appreciate quality (and therfore bitrate) should be higher with lookahead enabled and it is difficult to estimate how much larger the files would be, but I would have thought that in the majority of cases the file sizes would be between 5-20% higher.  

If the current code is working as expected, then the documentation should clearly state that lookahead will increase file sizes very significantly.

**Comment by pgribov** [comment]
Normal LA is based on VBR (it controls bitrate), in this case it reduces bitrate with maintaining quality. ICQ is based on CQP (it does not control bitrate), LA_ICQ algorithm is completely different from the normal LA. So, the file size increasing in this mode is acceptable.

**Comment by pgribov** [comment]
> If the current code is working as expected, then the documentation should clearly state that lookahead will increase file sizes very significantly.

@dmitryermilov , do you think we need to add this information?
