### ISSUE TITLE
sample_decode doesn't pass vaDisplayId to MSDK session before DecodeHeader

### ISSUE THREAD

**Issue by dmitryermilov** [Intel-Media-SDK/MediaSDK#1988]
Please see https://github.com/Intel-Media-SDK/MediaSDK/pull/1982#issuecomment-591931538 . It's a bug and has to be addressed ASAP. SetHandle has to be called before any DecodeHeader, Query calls. 
See manual: https://github.com/Intel-Media-SDK/MediaSDK/blob/master/doc/mediasdk-man.md#working-with-va-api-applications :

> Because the SDK does not create internal acceleration device on Linux, the application must always share it with the SDK. This sharing should be done before any actual usage of the SDK, including capability query and component initialization.

Please check other samples, tutorials.
Once it's done, please remove this code:
https://github.com/Intel-Media-SDK/MediaSDK/blob/757ea72a2065c03942571a16c0cbe9cff51ef245/samples/sample_decode/src/pipeline_decode.cpp#L856

**Comment by dmitryermilov** [comment]
@egorovdanil , please now please remove this code:
https://github.com/Intel-Media-SDK/MediaSDK/blob/757ea72a2065c03942571a16c0cbe9cff51ef245/samples/sample_decode/src/pipeline_decode.cpp#L856 **and check MFX_FOURCC_P010 case with video memory**. It **shall** work because MSDK has to set "Shift" field in mfxVideoParams filled by DecodeHeader .

**Comment by dmitryermilov** [comment]
Also, I'm wondering if we need this:
https://github.com/Intel-Media-SDK/MediaSDK/blob/757ea72a2065c03942571a16c0cbe9cff51ef245/samples/sample_decode/src/pipeline_decode.cpp#L1143
It's 2nd priority after the request above but still, please check it by removing the code and decoding some VP9 10bit stream.

**Comment by egorovdanil** [comment]
@dmitryermilov, I checked VP9 and MFX_FOURCC_P010 with video memory, it works. And also I checked other samples and tutorials pipelines that CreateHWDevice() called right after QueryIMPL() and before Query() call, they looks right.

**Comment by dmitryermilov** [comment]
Cool! Thank you very such.
