### ISSUE TITLE
[help wanted] Errors while running sample_decode

### ISSUE THREAD

**Issue by Samuel-John** [Intel-Media-SDK/MediaSDK#20]
Hi,
I have build the application in Ubuntu 16.04 after removing -Werror flag (it caused deprecated auto_ptr error).
Now when I run __cmake/intel64.make.release/__bin/release/sample_decode, I get this error:
**[ERROR], sts=MFX_ERR_NOT_FOUND(-9), Init, m_mfxSession.Init failed at msdk/samples/sample_decode/src/pipeline_decode.cpp:285**
After checking the code i understood that there are no libraries in /opt/intel
How do I install these libraries?

The second method that i tried was by patching the kernel in Ubuntu 16.04 as given in:
http://docs.unified-streaming.com/documentation/capture/media-sdk.html

But when I tried to build the sample application in MediaSamples_Linux_2017R2.tar.gz, I got:
**CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:367 (message):
  A required package was not found**

Can you please tell me where the mistakes are in both the methods?

**Comment by onabiull** [comment]
Current master of MediaSDK compatible with open source LibVA driver. You should build and install it first if you want latest version. Alternatively you may install closed-source MSS package and replace MediaSDK binary with your own opensource version. Please refer to release notes associated with tagged releases to checkout correct version.
MediaSDK Dispatcher aka libmfx.a expect to find MediaSDK binary in default location /opt/intel/mediasdk/lib64 with name (as of time of writing) libmfxhw64-p.so.1.24. You may try run "make install" although I would not recommend it, or just setting LD_LIBRARY_PATH to folder with compiled binaries. In latter approach Dispatcher will try to load MediaSDK by short name libmfxhw64.so. Please note that Dispatcher would prefer version from /opt/intel/mediasdk/lib64 if both files exists.

**Comment by Samuel-John** [comment]
Hi @onabiull ,
I am trying to run the application like this:
$ ./sample_decode h264 -i input.mp4 -o output.yuv -sw

Now the app searches for libmfxsw64.so. Only libmfxhw64.so is created. Isn't it possible to have only software implementation?

**Comment by Samuel-John** [comment]
Actually the library is loaded into the memory. A call to MFXInitEx() in the library returns MFX_ERR_UNSUPPORTED, i.e., (-3). Now according to "https://software.intel.com/en-us/node/628429", MFXInitEx() returns MFX_ERR_UNSUPPORTED when "The function cannot find the desired SDK implementation or version". What does that mean?

**Comment by avbelova** [comment]
HI @Samuel-John, 
You're trying to run h264 in SW implementation (on CPU). SW codecs inside MediaSDK were not open sourced. If you need SW capability, please install closed source packages [Intel(R) Media SDK](https://software.intel.com/en-us/media-sdk) or [Intel(R) Media Server Studio](https://software.intel.com/en-us/intel-media-server-studio).
This github tab is mostly about bugs in Media SDK source code, If you have questions about Intel Media products, problems with running samples, etc., we would be glad to answer at the [Media SDK forum](https://software.intel.com/en-us/forums/intel-media-sdk).

Best wishes, 
Anna

**Comment by Samuel-John** [comment]
Hi Anna,
Thanks for the info about SW implementation. But what about HW implementation? It also returns the same error. Why does that happen?
The processor that I am using is Intel(R) Core(TM) i5-6400

**Comment by avbelova** [comment]
@Samuel-John, 
You give video in .mp4 container as input for sample_decode, but Media SDK samples work with elementary streams only and Media SDK itself doesn't include splitters and muxers functionality. Please extract .h264 elementary video and run sample again.

Best wishes, 
Anna

**Comment by Samuel-John** [comment]
Hi,
Actually the problem was that I was running Intel Media SDK in VMware with Windows 10 host. I found out that virtual machines cannot access GPU especially when host is windows. That is why HW implementation failed. But why doesn't SW implementation work? I get the same error with SW implementation too.

Thanks

**Comment by avbelova** [comment]
Hi @Samuel-John, did you try to work with elementary stream as input instead of video in .mp4 container as I described in my previous comment?

**Comment by onabiull** [comment]
Try to assign at least two logical cores for this VM, this should help.

**Comment by Samuel-John** [comment]
Hi @avbelova 
Yes I changed the stream to a .264 file. I got this ES from the samples given in the link which I provided in the very 1st comment.
@onabiull I was using a single core. I will try with two cores and let you know the result.

**Comment by Samuel-John** [comment]
Hi @onabiull 
Allocating 2 cores in VMware worked with SW implementation. I got the output yuv file with input .264 video.
Thus, in virtual machine:

**Comment by Samuel-John** [comment]
Hi @onabiull 
Allocating 2 cores in VMware worked with SW implementation. I got the output yuv file with input .264 video.
Thus, in virtual machine:
HW implementation: Intel Media SDK will not work unless VM has access to GPU. If host is windows, GPU cannot be accessed with hosted hypervisor.
SW implementation: Intel Media SDK will work if atleast 2 cores are allocated to Virtual Machine. The input should not be a container (like mp4).
Thank you
