### ISSUE TITLE
Enable LA with HEVC encoder in sample_encode

### ISSUE THREAD

**Issue by dmitryermilov** [Intel-Media-SDK/MediaSDK#2001]
Please enable a case of LA (as a plug-in) + HEVC encoder in sample_encode. 
It will help to demonstrate how to enable such (generally pretty basic) pipeline and unblock https://github.com/Intel-Media-SDK/MediaSDK/issues/1511, https://github.com/Intel-Media-SDK/MediaSDK/issues/1810

**Comment by agalin89** [comment]
@dmitryermilov @AntonGrishin Thanks!
