### ISSUE TITLE
[H264 Encode] slice RollingIntraRefresh doesn't work

### ISSUE THREAD

**Issue by lxx02** [Intel-Media-SDK/MediaSDK#2014]
In mediasdk-man.md document introduces that MFX_REFRESH_SLICE means horizontal refresh by slices without overlapping. However, it doesn't refresh by horizontal type when in sample_encode pipeline set -ir_type 3(slice_type) -num_slices 5.

**Comment by pgribov** [comment]
Hi @lxx02 , please specify versions of media stack components(msdk/media-driver/gmm/libva), HW type, command lines (ideally via sample or ffmpeg) so that we can reproduce it quickly.
