### ISSUE TITLE
does qsv support h264 svc protocol ? 

### ISSUE THREAD

**Issue by lion117** [Intel-Media-SDK/MediaSDK#2039]
Hi,  I wanna change the video encoder resolution dynamically  without reset qsv encoder , like the bitrate changes . 
Does qsv support h264 svc or  hevc  shvc protocol ? 
Or are  anythings I can do with qsv api?

**Comment by dmitryermilov** [comment]
Hi @lion117 ,

Unfortunately, SVC is not supported.
