### ISSUE TITLE
Sigill on CPUs without sse4 extension like AMD

### ISSUE THREAD

**Issue by sndirsch** [Intel-Media-SDK/MediaSDK#2047]
Applications are crashing with SIGILL on CPUs without sse4 extension like AMD, which offer only up to "sse2". Library can't be build with "-msse2" either. See some more details on

https://bugzilla.suse.com/show_bug.cgi?id=1167346

**Comment by dmitryermilov** [comment]
@sndirsch , what MSDK API level function call causes the crash ? mfxInit() or something else ?

**Comment by sndirsch** [comment]
@dmitryermilov Honestly I don't know. I don't know more than you can find in the referenced bug above. Did you have a look?

**Comment by dmitryermilov** [comment]
Yes, I looked but didn't find that info there. It's okay.

**Comment by dvrogozh** [comment]
As correctly pointed in the suse bug we force sse4.2 here:
https://github.com/Intel-Media-SDK/MediaSDK/blob/19d11bf1cfd4c7699d1d146d7c3e43c39ffd6038/builder/ConfTargets.cmake#L23

And we have at least the following places to take care of we will try to remove this restriction:
1. Fast copy which is a mix of SSE2 and SSE4.1: https://github.com/Intel-Media-SDK/MediaSDK/blob/master/_studio/shared/include/fast_copy.h

2. ASC has instruction set runtime dispatcher which will require adjustments to compile correctly + it has unprotected SSE4.2(?) ME path: https://github.com/Intel-Media-SDK/MediaSDK/tree/master/_studio/shared/asc

3. IPP which uses SSE4.2: https://github.com/Intel-Media-SDK/MediaSDK/tree/master/contrib/ipp

Fast Copy is a primary thing to take care of I think

**Comment by dvrogozh** [comment]
We finished code refactoring and now we are ready to remove enforced `-m<instruction-set>` from msdk build system. #2099 should take care of that, it's under testing and review now.

**Comment by sndirsch** [comment]
> We finished code refactoring and now we are ready to remove enforced `-m<instruction-set>` from msdk build system. #2099 should take care of that, it's under testing and review now.

Build doesn't work for me with that patch.

[   57s] /usr/lib64/gcc/x86_64-suse-linux/9/include/tmmintrin.h:136:1: error: inlining failed in call to always_inline '_mm_shuffle_epi8': target specific option mismatch
[   57s]   136 | _mm_shuffle_epi8 (__m128i __X, __m128i __Y)

**Comment by dvrogozh** [comment]
@sndirsch : can you, please, give us more details since our CI build works fine on gcc-9 and clang-10? Some questions I have in mind:
* What is compiler version you are using?
* What is cmake configuration command line? Did you specify any custom build flags?
* Are you trying to cherry-pick this change (from #2099) to the latest release branch? If so, there are a number of prerequisite patches you need to take as well (refactoring I was talking about) - I'll help with the list.

**Comment by sndirsch** [comment]
You're right. I just tried to use this one and only patch. I'll try the patches below later. Thanks!

**Comment by dvrogozh** [comment]
@sndirsch : I just create PR #2105 which holds all the patches we currently have to fix this issue. If you work on top of the latest release branch, I hope it will help you.

I also just spotted this issue: #2104. It eventually did not impact our CI which makes me think we have some intrinsics code in the headers which we actually don't use. Anyhow, I would like to investigate more on 2104 before deciding whether we need to apply #2105 permanently for the release branch.

**Comment by sndirsch** [comment]
Thanks a lot! That's very kind! :-)
