### ISSUE TITLE
Is MFX_EXTBUFF_VPP_SCENE_ANALYSIS option supported?

### ISSUE THREAD

**Issue by aobolensk** [Intel-Media-SDK/MediaSDK#2053]
It was discovered in #2035 that bSceneDetectionEnable field in mfxExecuteParams is not changed anywhere (except setting to 0). So what about MFX_EXTBUFF_VPP_SCENE_ANALYSIS option?

**Comment by dmitryermilov** [comment]
https://github.com/Intel-Media-SDK/MediaSDK/blob/master/doc/mediasdk-man.md:

MFX_EXTBUFF_VPP_SCENE_CHANGE | Deprecated.
-- | --

**Comment by dvrogozh** [comment]
Do we need to delete corresponding path in mediasdk library? Specifically:
https://github.com/Intel-Media-SDK/MediaSDK/blob/1f9e67b2db7b680af142376f264a61df8d5c50f1/_studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp#L6179
once #2035 will be merged this if condition will become empty.

**Comment by dmitryermilov** [comment]
I think so
