### ISSUE TITLE
For Media SDK 19.4.0, actual bitrate is a little higher than target bitrate when la

### ISSUE THREAD

**Issue by YaboWei** [Intel-Media-SDK/MediaSDK#2063]
I tested Media SDK 19.4.0 recently and find that the actual bitrate is a little higher than target bitrate. Media SDK 16.9(2018 R2) is OK.
command:
`ffmpeg -init_hw_device "qsv=hw" -filter_hw_device hw -f rawvideo -s 1920x1080 -pix_fmt yuv420p -r 30 -i chiji_Ad24DdIRwHI_60s.264.yuv -vf hwupload -c:v h264_qsv -preset:v veryslow -b:v 5000k -maxrate:v 6000.0k -bufsize:v 5000k -look_ahead 1 -look_ahead_depth 30 -no-scenecut 1 -g 90 -bf 3 -an -f h264 -y chiji_Ad24DdIRwHI_60s.h264`
which print:
`[AVHWDeviceContext @ 0x23f8d00] Unknown driver "Intel iHD driver - 19.4.0", assuming standard behaviour.

[h264_qsv @ 0x23fbce0] Using the VBR with lookahead (LA) ratecontrol method

[h264_qsv @ 0x23fbce0] MFMode:2
[AVHWDeviceContext @ 0x25784e0] Unknown driver "Intel iHD driver - 19.4.0", assuming standard behaviour.
[AVHWDeviceContext @ 0x2b57960] Unknown driver "Intel iHD driver - 19.4.0", assuming standard behaviour.
[h264_qsv @ 0x23fbce0] profile: high; level: 40
[h264_qsv @ 0x23fbce0] GopPicSize: 90; GopRefDist: 4; GopOptFlag: closed ; IdrInterval: 0
[h264_qsv @ 0x23fbce0] TargetUsage: 1; RateControlMethod: LA
[h264_qsv @ 0x23fbce0] TargetKbps: 5000; LookAheadDepth: 30
[h264_qsv @ 0x23fbce0] NumSlice: 1; NumRefFrame: 3
[h264_qsv @ 0x23fbce0] RateDistortionOpt: OFF
[h264_qsv @ 0x23fbce0] RecoveryPointSEI: OFF IntRefType: 0; IntRefCycleSize: 0; IntRefQPDelta: 0
[h264_qsv @ 0x23fbce0] MaxFrameSize: 783360; MaxSliceSize: 0;
[h264_qsv @ 0x23fbce0] BitrateLimit: ON; MBBRC: OFF; ExtBRC: OFF
[h264_qsv @ 0x23fbce0] Trellis: auto
[h264_qsv @ 0x23fbce0] RepeatPPS: ON; NumMbPerSlice: 0; LookAheadDS: 2x
[h264_qsv @ 0x23fbce0] AdaptiveI: OFF; AdaptiveB: OFF; BRefType: pyramid
[h264_qsv @ 0x23fbce0] MinQPI: 0; MaxQPI: 0; MinQPP: 0; MaxQPP: 0; MinQPB: 0; MaxQPB: 0
[h264_qsv @ 0x23fbce0] Entropy coding: CABAC; MaxDecFrameBuffering: 3
[h264_qsv @ 0x23fbce0] NalHrdConformance: OFF; SingleSeiNalUnit: ON; VuiVclHrdParameters: OFF VuiNalHrdParameters: OFF`

actual bitrate:5277
Further more, i test multi target bitrate: 2000k/3000k/4000k/5000k(bufsize==bitrate, maxrate==1.2*bitrate):
Media SDK 19.4.0 actual bitrate:2105k,3158k,4208k,5277k
Media SDK 16.9    actual bitrate:2000k,3000k,4004k,5002k

bitrate=filesize*30fps*8/nb_frames/1000)

system: 7.4.1708
kernel: 4.18
ffmpeg: Intel_ffmpeg-3.4.1.zip

**Comment by dmitryermilov** [comment]
Hi @YaboWei ,

Can you please prepare a reproducer with sample_encode?

**Comment by YaboWei** [comment]
> Hi @YaboWei ,
> 
> Can you please prepare a reproducer with sample_encode?

@dmitryermilov Sorry for my late reply.
`sudo ./MediaStack/opt/intel/mediasdk/share/mfx/samples/_bin/sample_encode h264 -i ~/chiji_Ad24DdIRwHI_60s.yuv -o a.264 -w 1920 -h 1080 -r 30 -g 90 -la -lad 30 -b 5000 -u veryslow`

outputs:
`libva info: VA-API version 1.6.0
libva info: Trying to open /opt/intel/mediasdk/lib64/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_6
libva info: va_openDriver() returns 0
Encoding Sample Version 19.4.0

Input file format	YUV420
Output video		AVC
Source picture:
	Resolution	1920x1088
	Crop X,Y,W,H	0,0,1920,1080
Destination picture:
	Resolution	1920x1088
	Crop X,Y,W,H	0,0,1920,1080
Frame rate	30.00
Bit rate(Kbps)	5000
Gop size	90
Ref dist	30
Ref number	0
Idr Interval	0
Target usage	quality
Memory type	system
Media SDK impl		hw
Media SDK version	1.31

Processing started
Frame number: 1801
Encoding fps: 182

Processing finished
$ ll a.264
-rw-rw-r-- 1 web_server web_server 39493591 Apr 13 22:49 a.264
`

calculate bitrate in kbps:
`39493591*8 / (1801/30.0) / 1000 = 5262.8`

**Comment by YaboWei** [comment]
> > Hi @YaboWei ,
> > Can you please prepare a reproducer with sample_encode?
> 
> @dmitryermilov Sorry for my late reply.
> `sudo ./MediaStack/opt/intel/mediasdk/share/mfx/samples/_bin/sample_encode h264 -i ~/chiji_Ad24DdIRwHI_60s.yuv -o a.264 -w 1920 -h 1080 -r 30 -g 90 -la -lad 30 -b 5000 -u veryslow`
> 
> outputs:
> `libva info: VA-API version 1.6.0
> libva info: Trying to open /opt/intel/mediasdk/lib64/iHD_drv_video.so
> libva info: Found init function __vaDriverInit_1_6
> libva info: va_openDriver() returns 0
> Encoding Sample Version 19.4.0
> 
> Input file format YUV420
> Output video AVC
> Source picture:
> Resolution 1920x1088
> Crop X,Y,W,H 0,0,1920,1080
> Destination picture:
> Resolution 1920x1088
> Crop X,Y,W,H 0,0,1920,1080
> Frame rate 30.00
> Bit rate(Kbps) 5000
> Gop size 90
> Ref dist 30
> Ref number 0
> Idr Interval 0
> Target usage quality
> Memory type system
> Media SDK impl hw
> Media SDK version 1.31
> 
> Processing started
> Frame number: 1801
> Encoding fps: 182
> 
> Processing finished
> $ ll a.264
> -rw-rw-r-- 1 web_server web_server 39493591 Apr 13 22:49 a.264
> `
> 
> calculate bitrate in kbps:
> `39493591*8 / (1801/30.0) / 1000 = 5262.8`

@dmitryermilov please check my sample_encode result, thanks!

**Comment by filippenkos** [comment]
Hi, @YaboWei 
In your line for sample_encode -r should be replaced with -f, as -r is for GOP distance and -f for frame rate.
I investigated your issue. In all cases where bitrate is higher with lookahead option it is no more than 10%. According to developer encoding algorithms checks that bitrate is no more than 10% higher than requested.

**Comment by YaboWei** [comment]
> Hi, @YaboWei
> In your line for sample_encode -r should be replaced with -f, as -r is for GOP distance and -f for frame rate.
> I investigated your issue. In all cases where bitrate is higher with lookahead option it is no more than 10%. According to developer encoding algorithms checks that bitrate is no more than 10% higher than requested.

Hi, @filippenkos 
I tried command:
/opt/intel/mediasdk/share/mfx/samples/_bin/sample_encode h264 -i chiji_Ad24DdIRwHI_60s.yuv -o a.264 -w 1920 -h 1080 -f 30 -g 90 -b 5000 -la -lad 30 -u veryslow
and the bitrate is 39584622*8 / (1801/30.0) / 1000 = 5275

**Comment by filippenkos** [comment]
Hi @YaboWei 
As I mentioned encoding algorithms checks that bitrate is no more than 10% higher than requested.  In your case bitrate is higher than requested by 5,5%. So this result is not an issue.
