### ISSUE TITLE
Transcode with 5.3 kernel is slower than MSS 4.14 patched kernel using the same user mode media stack

### ISSUE THREAD

**Issue by dmitryermilov** [Intel-Media-SDK/MediaSDK#2066]
This issue is a continuation of #1992 :

...
Anyway,  I moved forward and deployed this whole new software release on half our encoding farm (our farm is composed of around 180 m710x cartridges).
So it means:
- 90 cartridges running latest MSDK/ffmpeg 4.2.2/Kernel 5.3.0
- 90 cartridges running MSDK 2018R2/ffmpeg 3.4.1/Kernel 1.14 patched

=> After a week of run, and hundred of thousands of encodings, we noticed that the farm running the new  SW is still slower, by around 25/30%. It means that the farm with older SW transcodes around 30% more videos.

So I tried to rollback the kernel to 4.14 on half the farm with the new SDK, which means that have on this farm, 45 cartridges with kernel 4.14 patched and 45 with kernel 5.3.0, using the same MSDK (latest one) and ffmpeg 4.2.2.

=> the 45 cartridges with the older kernel (4.14) are transcoding 30% more videos than the one with kernel 5.3.0.

So it looks like kernel 5.3.0 is still not as good as old kernel 4.14 with patches...
I tried to encode a single file on each config, and the 5.3.0 kernel is only about 5% slower.
So maybe it becomes a problem when doing multiple concurrent transcodings ?

Thanks,
Gilles

_Originally posted by @ViGill in https://github.com/Intel-Media-SDK/MediaSDK/issues/1992#issuecomment-610260354_

**Comment by dmitryermilov** [comment]
@ViGill,
>So I tried to rollback the kernel to 4.14 on half the farm with the new SDK

Does it mean that you updated MediaSDK + media driver ? Or only MSDK?

**Comment by ViGill** [comment]
Hi @dmitryermilov, thanks for creating a new issue, it's indeed more appropriate.
Yes I use the new media driver  as well.
To sum up I compared the kernel using the following config:

FFmpeg 4.2.2
intel-gmmlib-19.4.1
intel-media-19.4.0
intel-mediasdk-19.4.0
libdrm-2.4.100
libva-2.6.1

Thanks

**Comment by onabiull** [comment]
Unfortunately this config are not consistent with 19.4.0 release. There was newer tag in media-driver since 19.4.0. Could you  please give https://github.com/intel/media-driver/releases/tag/intel-media-19.4.1 a try?
Or just switch to latest available release? Please note that Media SDK 20.1.0 should be matched with https://github.com/intel/media-driver/releases/tag/intel-media-20.1.1 . I'm going to post official release on tag https://github.com/Intel-Media-SDK/MediaSDK/releases/tag/intel-mediasdk-20.1.0 soon.

**Comment by ViGill** [comment]
Hi, thanks! when I tried I am pretty sure 19.4.0 was the latest available tag.
I ll upgrade  to 2020 release on Tuesday ! Thanks

**Comment by dmitryermilov** [comment]
Hi @ViGill , 

Yes, info from Oleg above aimed to highlight 19.4.0 is not the best anymore. Just for your information. 
Let me post more details with focus on your problem later.

**Comment by ViGill** [comment]
Hi,

so I made more tests with kernel 5.3.0.
I took 90 encoders that I cut in 3 test-farms, all running the latest userland versions (msdk 19.4.1,...)
Farm 1: kernel 5.3.0 without security patches (https://linuxreviews.org/HOWTO_make_Linux_run_blazing_fast_(again)_on_Intel_CPUs)
Farm 2: Kernel 5.3.0 vanilla, no change
Farm 3: Kernel 4.14 + qsv patches

Here are the result during 24h of transcoding:
Farm 1: 18K videos transcoded
Farm 2: 15K videos transcoded
Farm 3: 23K videos transcoded

As you can see, the security patches of 5.3.0 have a quite strong impact on transcoding performances but never reach the peformances of kernel 4.4.14 when we remove them.

BR

(I will also start the upgrade to the latest version today).

**Comment by ViGill** [comment]
Hi,

I am about to migrate to:
intel-gmmlib-20.1.1.tgz
intel-media-20.1.1.tgz
intel-mediasdk-20.1.0.tgz

Should I wait for intel-mediasdk-20.1.1 ?

Thanks

**Comment by dmitryermilov** [comment]
Hi @ViGill ,

Sorry for late reply.
Let me highlight something just to be on the same page:
4.14 kernel from MSS package was a special kernel. It had a number of custom i915 (Intel graphics kmd) patches. Some kernels were upstream, other other were not accepted by i915 maintainers. Plus, latest kernels have changes which were absent in MSS 4.14 kernel (e.g. i915 internal task scheduler, Spectre/Meltdown patches). I'm writing this to highlight that we might not be able to get a fix. But I'm not saying we should't try to root cause it.
There was useful post from @dvrogozh in https://github.com/Intel-Media-SDK/MediaSDK/issues/1466#issuecomment-498752491 about two special MSS performance features: Dynamic VDBOX balancing and Slice shutdown. There is an document in MSS package called dynamic_slice_shutdown describing slice shutdown feature. 

Plus, as you posted about security kernel patches could influence performance. I'm aware of https://www.phoronix.com/forums/forum/hardware/processors-memory/1043223-a-global-switch-to-kill-linux-s-cpu-spectre-meltdown-workarounds/page2. In the beginning of this thread there is a kernel boot params which disables S&M patches.

**Comment by ViGill** [comment]
Hi,

my turn to be sorry for the delay :) I need to fix these notifications!
Thanks for the document link, I'll read it.

I also did a test with kernel 5.3 and special kernel cmdline flags to remove motigations (basically a lot of them but only mitigations=off is need afaik on this kernel version).
Unfortunately, even if it improves a bit the perf, we are still far from this mighty kernel 4.14 with patches.
I understand that all the patches could not be mainlined, which could explain part of the performance difference.

Anway, I think we will stick on kernel 4.14 for now and re-asses in a few.

Is there a chance to add some patches to kernel 5.3.0, forking from master then, like we did on 4.14 ?

BR,
Gilles

**Comment by dmitryermilov** [comment]
Hi @ViGill ,

If you bandwidth, I'd propose dig a bit into it. Could you check performance with disabled 1) VDBOX balancing, 2) dynamic slice shutdown and 3) both ?

>Anway, I think we will stick on kernel 4.14 for now and re-asses in a few.

If it works for you, yes, it's a good option.

> Is there a chance to add some patches to kernel 5.3.0, forking from master then, like we did on 4.14 ?

Theoretically  - yes, it's opensource :) But practically - I don't think so..

Regards,
Dmitry

**Comment by daleksan** [comment]
@ViGill did you have the chance to check Dmitry's suggestion?
