### ISSUE TITLE
MFX_RATECONTROL_LA_EXT running time on version 1.26 slows 3 times than that of 1.25

### ISSUE THREAD

**Issue by changliwu** [Intel-Media-SDK/MediaSDK#207]
Hi
      I have run MFX_RATECONTROL_LA_EXT of sample_multi_transcode  in Intel(R) Core(TM) i3-6100 CPU with API 1.25 and 1.26, and found that the running time on version 1.26 slows 3 times than that of 1.25.

   Run like this:
          /opt/intel/mediasdk/samples/sample_multi_transcode -par laext.par
  and laext.par like this:
-async 10 -i::h264 /root/big.264 -o::sink -gop_size 33 -dist 4 -num_ref 2 -u 4 -la_ext -lad 33 
-async 10 -i::source -o::h264 test1.264 -gop_size 33 -dist 4 -num_ref 2 -u 4 -la_ext -lad 33 -w 1920 -h 1080 

----------------------------------- 1.25 results: ---------------------------------------------
[root@localhost ~]# /opt/intel/mediasdk/samples/sample_multi_transcode -par laext.par 
Multi Transcoding Sample Version 8.2.25.

Par file is: laext.par

libva info: VA-API version 1.0.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /usr/lib64/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_0
libva info: va_openDriver() returns 0
plugin_loader.h :172 [INFO] Plugin was loaded from GUID: { 0x58, 0x8f, 0x11, 0x85, 0xd4, 0x7b, 0x42, 0x96, 0x8d, 0xea, 0x37, 0x7b, 0xb5, 0xd0, 0xdc, 0xb4 } (Intel (R) Media SDK plugin for LA ENC)
MFX HARDWARE Session 0 API ver 1.25 parameters: 
Input  video: AVC 
Output video: To child session

MFX HARDWARE Session 1 API ver 1.25 parameters: 
Input  video: From parent session
Output video: AVC 

Pipeline surfaces number (DecPool): 63
Session 0 was NOT joined with other sessions
Session 1 was NOT joined with other sessions

Transcoding started
............
Transcoding finished

Common transcoding time is 6.65325 sec
-------------------------------------------------------------------------------
*** session 0 PASSED (MFX_ERR_NONE) 6.59019 sec, 1125 frames
-async 10 -i::h264 /root/big.264 -o::sink -gop_size 33 -dist 4 -num_ref 2 -u 4 -la_ext -lad 33 

*** session 1 PASSED (MFX_ERR_NONE) 6.6531 sec, 1125 frames
-async 10 -i::source -o::h264 test1.264 -gop_size 33 -dist 4 -num_ref 2 -u 4 -la_ext -lad 33 -w 1920 -h 1080 

-------------------------------------------------------------------------------

The test PASSED
plugin_loader.h :198 [INFO] MFXBaseUSER_UnLoad(session=0x0x15d7d30), sts=0

----------------------------------- 1.26 results: ---------------------------------------------
[root@localhost ~]# /opt/intel/mediasdk/samples/sample_multi_transcode -par laext.par 
Multi Transcoding Sample Version 8.3.26.

Par file is: laext.par

libva info: VA-API version 1.0.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /usr/lib64/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_0
libva info: va_openDriver() returns 0
plugin_loader.h :178 [INFO] Plugin was loaded from GUID: { 0x58, 0x8f, 0x11, 0x85, 0xd4, 0x7b, 0x42, 0x96, 0x8d, 0xea, 0x37, 0x7b, 0xb5, 0xd0, 0xdc, 0xb4 } (Intel (R) Media SDK plugin for LA ENC)
MFX HARDWARE Session 0 API ver 1.26 parameters: 
Input  video: AVC 
Output video: To child session

MFX HARDWARE Session 1 API ver 1.26 parameters: 
Input  video: From parent session
Output video: AVC 

Pipeline surfaces number (DecPool): 63
Session 0 was NOT joined with other sessions
Session 1 was NOT joined with other sessions

Transcoding started
............
Transcoding finished

Common transcoding time is 18.9978 sec
-------------------------------------------------------------------------------
*** session 0 PASSED (MFX_ERR_NONE) 18.9898 sec, 1125 frames
-async 10 -i::h264 /root/big.264 -o::sink -gop_size 33 -dist 4 -num_ref 2 -u 4 -la_ext -lad 33 

*** session 1 PASSED (MFX_ERR_NONE) 18.9974 sec, 1125 frames
-async 10 -i::source -o::h264 test1.264 -gop_size 33 -dist 4 -num_ref 2 -u 4 -la_ext -lad 33 -w 1920 -h 1080 

-------------------------------------------------------------------------------

The test PASSED
plugin_loader.h :204 [INFO] MFXBaseUSER_UnLoad(session=0x0x19dbc70), sts=0

**Comment by changliwu** [comment]
Hi
   I have install linux-firmware on 2a9b2cf50fb32e36e4fc1586c2f6f1421913b553
                      linux-stable in 4.16.7+
                      libva-utils on 5b10b3302502212dbf6d0710e10e2015b1e192f6
                      libva on b3be72a5a110880f70626d7c3bed953cdde124b2
                      gmmlib on 40b45bd6109a6a485b4a721686fc32ba7307a548
                      media_driver on 054a1c93a307da9fd88fc0c55fa5c71606850fd8  
                      MediaSDK on ad861f540f5ccdba6242caf6e671353731bfe5bf in Intel(R) Core(TM) i3-6320 CPU
 (1）the  MFX_RATECONTROL_LA_EXT of sample_multi_transcode run also slowly,
 (2) I have run the  MFX_RATECONTROL_LA of sample_multi_transcode but it is not slow, 
 (3) I also build MediaSDK 1.25 in this, It's very slow, too.
       so I doubt if the version of libva or media driever does not match MediaSDK.
       I look forward to your reply. Thank you！

**Comment by changliwu** [comment]
The MFX_RATECONTROL_LA_EXT of sample_multi_transcode run  normal on MediaSDK 1.25.
It install with linux-firmware on 2aa2ac2e9c09f09b0cfb6fc320c1e2d281530fa0
                     linux-stable in 4.14.16
                     libva-utils on 5b10b3302502212dbf6d0710e10e2015b1e192f6
                     libva on 6ac580c296cdbeb9a50462d280cc40d8716ffa30
                     gmmlib on 2eea1a175ab4f3388925c91c870214f36f17f20d
                     media-driver on a7de25db7bede509f6904db386740d55061019d1
                     MediaSDK on 463ab7a08b49fba70c04c169cb1e022bee8e35bf  in Intel(R) Core(TM) i3-6320 CPU

**Comment by changliwu** [comment]
# The MFX_RATECONTROL_LA_EXT of sample_multi_transcode  works normal in MediaSDK 1.25.
It install with linux-firmware on 2aa2ac2e9c09f09b0cfb6fc320c1e2d281530fa0
linux-stable in 4.14.16
libva-utils on 5b10b3302502212dbf6d0710e10e2015b1e192f6
libva on 6ac580c296cdbeb9a50462d280cc40d8716ffa30
gmmlib on 2eea1a175ab4f3388925c91c870214f36f17f20d
media-driver on a7de25db7bede509f6904db386740d55061019d1
MediaSDK on 463ab7a in Intel(R) Core(TM) i3-6320 CPU

# But it works slowly in MediaSDK 1.26.
It install lwith inux-firmware on 2a9b2cf50fb32e36e4fc1586c2f6f1421913b553
linux-stable in 4.16.7+
libva-utils on 5b10b3302502212dbf6d0710e10e2015b1e192f6
libva on b3be72a5a110880f70626d7c3bed953cdde124b2
gmmlib on 40b45bd6109a6a485b4a721686fc32ba7307a548
media_driver on 054a1c93a307da9fd88fc0c55fa5c71606850fd8
MediaSDK on ad861f5 in Intel(R) Core(TM) i3-6320 CPU

**Comment by artem-shaporenko** [comment]
Ok, thanks, is it only MFX_RATECONTROL_LA_EXT, or if try running without it, transcoding also slows down?
Also are you rebuilding LA_EXT plugin, or using the same one for both versions?

**Comment by changliwu** [comment]
I have try running without  MFX_RATECONTROL_LA_EXT, transcoding run normal
I have not rebuilding LA_EXT plugin, how can i rebuild the LA_EXT plugin?

**Comment by artem-shaporenko** [comment]
@onabiull Can you please help with this question?
@changliwu this can be a problem - it can miss compatibility due to changes in MediaSDK runtime(libmfxhw64.so)

**Comment by changliwu** [comment]
ok, Thank you for your reply.
@onabiull Look forward to your reply！

**Comment by changliwu** [comment]
Are there any updates about this question? @onabiull   @artem-shaporenko

**Comment by changliwu** [comment]
I have use the newest MediaSDK ebddee333c54f8349ae49abef9e772d7229f2f81 for testing this problem, and It still exists!

how can i rebuild the LA_EXT plugin?

**Comment by onabiull** [comment]
LA_EXT plugin is libmfx_h264la_hw64.so (plugins.cfg entry _H264la_Encoder_588f1185d47b42968dea377bb5d0dcb4_). Normally it built along with other plugins during MSDK build. Please try to replace version in /opt/intel/mediasdk/plugins/ with your custom-built version.

**Comment by changliwu** [comment]
Hi,onabiull
    How can i replace the version in /opt/intel/mediasdk/plugins/, and how can i get my custom-built version?
    According to what artem-shaporenko said, this MFX_RATECONTROL_LA_EXT running slowly is may be a problem - it can miss compatibility due to changes in MediaSDK runtime(libmfxhw64.so).
  Could you help me solve the problem?

**Comment by daleksan** [comment]
@changliwu is it still actual?

**Comment by egorovdanil** [comment]
I compared the three API versions 1.25, 1.26 and the current version of the master and found no decrease in the transcoding speed.

**MediaSDK 1.25**
```
libva info: VA-API version 1.9.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri//iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_1
libva info: va_openDriver() returns 0
plugin_loader.h :178 [INFO] Plugin was loaded from GUID: { 0x58, 0x8f, 0x11, 0x85, 0xd4, 0x7b, 0x42, 0x96, 0x8d, 0xea,                                                             0x37, 0x7b, 0xb5, 0xd0, 0xdc, 0xb4 } (Intel (R) Media SDK plugin for LA ENC)
MFX HARDWARE Session 0 API ver 1.25 parameters:
Input  video: AVC
Output video: To child session

MFX HARDWARE Session 1 API ver 1.25 parameters:
Input  video: From parent session
Output video: AVC

Pipeline surfaces number (DecPool): 66
Session 0 was NOT joined with other sessions
Session 1 was NOT joined with other sessions

Transcoding started
..
Transcoding finished

Common transcoding time is 14.006 sec
-------------------------------------------------------------------------------
*** session 0 PASSED (MFX_ERR_NONE) 13.9889 sec, 150 frames
-async 10 -i::h264 Oct2015_1.264 -o::sink -gop_size 33 -dist 4 -num_ref 2 -u 4 -la_ext -lad 33

*** session 1 PASSED (MFX_ERR_NONE) 14.0056 sec, 150 frames
-async 10 -i::source -o::h264 test1.264 -gop_size 33 -dist 4 -num_ref 2 -u 4 -la_ext -lad 33 -w 1920 -h 1080

-------------------------------------------------------------------------------

The test PASSED
```

**MediaSDK 1.26**
```
libva info: VA-API version 1.9.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /home/gta/degorov/build/media_driver/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_1
libva info: va_openDriver() returns 0
plugin_loader.h :178 [INFO] Plugin was loaded from GUID: { 0x58, 0x8f, 0x11, 0x85, 0xd4, 0x7b, 0x42, 0x96, 0x8d                                                , 0xea, 0x37, 0x7b, 0xb5, 0xd0, 0xdc, 0xb4 } (Intel (R) Media SDK plugin for LA ENC)
MFX HARDWARE Session 0 API ver 1.26 parameters:
Input  video: AVC
Output video: To child session

MFX HARDWARE Session 1 API ver 1.26 parameters:
Input  video: From parent session
Output video: AVC

Pipeline surfaces number (DecPool): 66
Session 0 was NOT joined with other sessions
Session 1 was NOT joined with other sessions

Transcoding started
..
Transcoding finished

Common transcoding time is 13.9839 sec
-------------------------------------------------------------------------------
*** session 0 PASSED (MFX_ERR_NONE) 13.9667 sec, 150 frames
-async 10 -i::h264 Oct2015_1.264 -o::sink -gop_size 33 -dist 4 -num_ref 2 -u 4 -la_ext -lad 33

*** session 1 PASSED (MFX_ERR_NONE) 13.9835 sec, 150 frames
-async 10 -i::source -o::h264 test1.264 -gop_size 33 -dist 4 -num_ref 2 -u 4 -la_ext -lad 33 -w 1920 -h 1080

-------------------------------------------------------------------------------

The test PASSED
```

**Current master**
```
libva info: VA-API version 1.9.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_9
libva info: va_openDriver() returns 0
Session 0:
plugin_loader.h :185 [INFO] Plugin was loaded from GUID: { 0x58, 0x8f, 0x11, 0x85, 0xd4, 0x7b, 0x42, 0x96, 0x8d,                                                   0xea, 0x37, 0x7b, 0xb5, 0xd0, 0xdc, 0xb4 } (Intel (R) Media SDK plugin for LA ENC)
MFX HARDWARE Session 0 API ver 1.33 parameters:
Input  video: AVC
Output video: To child session

Session 1:
MFX HARDWARE Session 1 API ver 1.33 parameters:
Input  video: From parent session
Output video: AVC

Pipeline surfaces number (DecPool): 66
Session 0 was NOT joined with other sessions
Session 1 was NOT joined with other sessions

Transcoding started
..
Transcoding finished

Common transcoding time is 1.33013 sec
-------------------------------------------------------------------------------
*** session 0 [0x563f57552d30] PASSED (MFX_ERR_NONE) 0.905437 sec, 150 frames, 165.666 fps
-async 10 -i::h264 Oct2015_1.264 -o::sink -gop_size 33 -dist 4 -num_ref 2 -u 4 -la_ext -lad 33

*** session 1 [0x563f575d55d0] PASSED (MFX_ERR_NONE) 1.32975 sec, 150 frames, 112.803 fps
-async 10 -i::source -o::h264 test1.264 -gop_size 33 -dist 4 -num_ref 2 -u 4 -la_ext -lad 33 -w 1920 -h 1080

-------------------------------------------------------------------------------

The test PASSED
```

**Comment by daleksan** [comment]
@changliwu please feel free to re-open if it is still actual
