### ISSUE TITLE
roi query of mpeg2 returns unsupported

### ISSUE THREAD

**Issue by guoyejun** [Intel-Media-SDK/MediaSDK#2076]
MFXVideoENCODE_Query is a general interface to query for mpeg2, hevc, h264 etc. It makes sense that it returns unsupported when query for mpeg2, but it is not very friendly.

- there might be many things for the query, so user does not know straightforwardly which is not supported.

- user usually uses the same code to query for mpeg2, hevc and others. It would be better that it returns ok with supported roi number to be zero, so user don't need to check the return code differently for different encoders.

**Comment by guoyejun** [comment]
any update? thanks

**Comment by guoyejun** [comment]
any update? thanks

**Comment by daleksan** [comment]
Hi @DenWolf can you take a look on this issue?

**Comment by kovakimy** [comment]
The customer declared in internal correspondence that the issue is not actual.

If you still have any questions, please, let me know. Feel free to reopen if customer impact with right justification and priority.

Thanks & Regards,
Kristina
