### ISSUE TITLE
20.1.0:  in-source version is hard to be seen

### ISSUE THREAD

**Issue by dvrogozh** [Intel-Media-SDK/MediaSDK#2078]
https://github.com/Intel-Media-SDK/MediaSDK/blob/3d6abcfb19ba2e31b6a8d32cddd1893c3e419ffc/CMakeLists.txt#L27

~~Please, bump in-source version to match release tag and provide release update fixing the issue. I.e., please, update in-source version to 20.1.1 and make corresponding release.~~

Part of in-source version is hidden here (mind 0):
https://github.com/Intel-Media-SDK/MediaSDK/blob/3d6abcfb19ba2e31b6a8d32cddd1893c3e419ffc/CMakeLists.txt#L28

**Comment by onabiull** [comment]
Media SDK version in 20.1@**intel_mediasdk-20.1.0** branch exactly **mediasdk_version: 20.1.0**

What is wrong here? If we would issue an release update it would be bumped to 20.1.1.

**Comment by dvrogozh** [comment]
Ah, I see. I overlooked 0 hiding on the next line:
https://github.com/Intel-Media-SDK/MediaSDK/blob/3d6abcfb19ba2e31b6a8d32cddd1893c3e419ffc/CMakeLists.txt#L28

Why you just didn't use this:
`set(MEDIA_VERSION 20.1.0)`
which would be simpler? or it does not work for some reason?

**Comment by onabiull** [comment]
Take a look at master version of the file:
```
   26: # Througout this project MFX_VERSION refers to uAPI version and MEDIA_VERSION refers to product version
   27: set(MEDIA_VERSION 20.2)
   28: set(MEDIA_VERSION_STR "${MEDIA_VERSION}.pre${MEDIA_VERSION_EXTRA}" CACHE STRING "" FORCE)
   29  
   30  project(mfx1
   31:   VERSION ${MEDIA_VERSION}
```

CMake project() function won't accept anything besides just numbers.

**Comment by dvrogozh** [comment]
I don't argue about "pre". But 20.1.0 should be just fine, isn't it?

**Comment by onabiull** [comment]
I kind of agree :) Two-line change looks harmless enough given better version visibility in release branches. Still  I propose to change this going forward. 20.1.0 are good enough.

**Comment by dvrogozh** [comment]
> Still I propose to change this going forward. 20.1.0 are good enough.

Definitely. No need to change this right now and go with the release update. This is not that serious issue.

**Comment by dvrogozh** [comment]
We fixed that., see #2085.
