### ISSUE TITLE
Missing x86 plug-in binaries in Windows MediaSDK 2019 R1

### ISSUE THREAD

**Issue by 3xLOGICKevinHan** [Intel-Media-SDK/MediaSDK#2083]
Hi,
"MediaSDK\tutorials\simple_2_decode" is originally used to demonstrate decoding AVC(H.264) ES file. I changed it a bit.
1) MFX_IMPL_AUTO_ANY -> MFX_IMPL_SOFTWARE // force to use software decode
2) MFX_CODEC_AVC -> MFX_CODEC_HEVC // cope with HEVC instead of AVC file

But I got MFX_ERR_UNSUPPORTED  from  "sts = mfxDEC.DecodeHeader(&mfxBS, &mfxVideoParams);". If I used "MFX_IMPL_HARDWARE" instead, then I can run the routine successfully to decode HEVC ES file.

I presume MFX_IMPL_SOFTWARE should be supported. What am I doing wrong?

Attached is log file when using MFX_IMPL_SOFTWARE.
[tracer.log](https://github.com/Intel-Media-SDK/MediaSDK/files/4496525/tracer.log)

**Comment by dmitryermilov** [comment]
Hi @3xLOGICKevinHan ,

Software codecs have been de-prioritized. They were a part of MediaServerStudio. Now they are not supported by Linux GitHub MediaSDK. Why would you like to use them?

**Comment by 3xLOGICKevinHan** [comment]
Hi @dmitryermilov ,
Thanks a lot for your reply. I have spent some time on my issue. Finally I found I have to add following code which is from "simple_decode_hevc10.cpp".

`   // 4. Load the HEVC plugin
    mfxPluginUID codecUID;
    bool success = true;
    codecUID = msdkGetPluginUID(impl, MSDK_VDECODE, mfxVideoParams.mfx.CodecId);

    if (AreGuidsEqual(codecUID, MSDK_PLUGINGUID_NULL)) {
        printf("Get Plugin UID for HEVC is failed.\n");
        success = false;
    }

    printf("Loading HEVC plugin: %s\n", ConvertGuidToString(codecUID));

    //On the success of get the UID, load the plugin
    if (success) {
        sts = MFXVideoUSER_Load(session, &codecUID, ver.Major);
        if (sts < MFX_ERR_NONE) {
            printf("Loading HEVC plugin failed\n");
            success = false;
        }
    }`

With this piece added, I can make it work. The HEVC ES file can be decoded successfully. But only for X64 configuration. X86 configuration still won't work.
Then I found it's caused folder "C:\Program Files (x86)\IntelSWTools\Intel(R) Media SDK 2019 R1\HEVC Decoder & Encoder\Plugin\15dd936825ad475ea34e35f3f54217a6" only has a file "mfxplugin64_hevcd_sw.dll" there, but NOT a "mfxplugin32_hevcd_sw.dll" there. This should be the reason for my X86 configuration won't work issue.

I'm using windows 10 OS. I downloaded "MediaSDK2019R1.exe" from intel web site. After I installed it, I got the "mfxplugin64_hevcd_sw.dll" in the folder. But why there's no "mfxplugin32_hevcd_sw.dll"?

Could you help me on this? Thanks a lot.

**Comment by dmitryermilov** [comment]
Hi @3xLOGICKevinHan ,

I've double checked. It's not by mistake. Even is release notes it's said:
_Common/general limitations:
...
This release supports only 64-bit Microsoft* Windows* applications_

**Comment by 3xLOGICKevinHan** [comment]
Hi @dmitryermilov ,
Thanks for your clarification. So if I want to use HEVC software decoding in 32bit windows app anyway, where should I get a version that supports 32bit window app?

Thanks

**Comment by dmitryermilov** [comment]
Unfortunately, there is no way to do it.

**Comment by 3xLOGICKevinHan** [comment]
Hi @dmitryermilov ,
Thanks. I have another question. According my understanding from the sample_code.cpp, no matter hw/sw decoding you are using, only NV12 image format can be used with the output surface (system/video memory surface). Is this true? How should I do to make it to be YV12/YUP420P?

Thanks

**Comment by dmitryermilov** [comment]
You're welcome. Sorry about it. 
Regarding NV12, you're right. You can do color conversion by regular MediaSDK VPP interface.

BTW, I'm still wondering, why would you like to use SW HEVC? What HW do you have?

**Comment by 3xLOGICKevinHan** [comment]
Hi @dmitryermilov ,
I'm working on a lagency code. We don't want to touch its render part of code. Also we have a limitted development timeline.
Our original code is using ffmpeg library to decode HEVC frames. We found there are performance issue with it. So what I'm doing is, I want to compare HEVC decoding performance between intel msdk and ffmpeg library.

Sure I should try HW decoding, but it's something we will work later.

**Comment by 3xLOGICKevinHan** [comment]
Hi @dmitryermilov ,
Do you have any idea on the performance comparision between ffmpeg library and intel msdk when decoding HEVC frames?

**Comment by dmitryermilov** [comment]
I see.
I don't think we made such comparison. But in general SW HEVC should demonstrate good performance. You can do quick tests by running via sample_decode.

Regards,
Dmitry

**Comment by 3xLOGICKevinHan** [comment]
Hi @dmitryermilov ,

I have a file "moredata.h265". If decoding it using ffplay.exe, then it succeeds. But if I use sample_decode.exe to test it, there's errors. 
`sts = mfxDEC.DecodeFrameAsync(&mfxBS, &pmfxSurfaces[nIndex], &pmfxOutSurface, &syncp);`
this line is returning "MFX_ERR_MORE_DATA".
Can you please help me with this issue?

**Comment by 3xLOGICKevinHan** [comment]
[moredata.zip](https://github.com/Intel-Media-SDK/MediaSDK/files/4510193/moredata.zip)

**Comment by 3xLOGICKevinHan** [comment]
Hi @dmitryermilov ,
I presume this is a intel msdk bug. If I run "ffplay.exe moredata.h265", it can decode & show the image successfully. But if I use sample_decode.exe (sw + 64bit) to test this same file, it failed with above error (MFX_ERR_MORE_DATA). This is NOT reasonable. Since ffplay.exe works, there's no reason that intel msdk fails.
Could you help me on this? Many thanks!

**Comment by 3xLOGICKevinHan** [comment]
Hi @dmitryermilov ,
Sorry, it seems my understanding of the code is incorrect. The sample_decode.exe does work. I will confirm it & come back.
Thanks

**Comment by 3xLOGICKevinHan** [comment]
Hi @dmitryermilov ,
I have made my code work. Also, I downloaded a 32bit "mfxplugin32_hevcd_sw.dll" from internet. It makes my x86 app works too.
I still have a question. Does intel msdk works if a PC is using AMD CPU? If it works, how is the performance?
FYI: I just compared the performance between ffmpeg and intel msdk. Intel msdk does have better performance even using sw decoding. It should be able to solve my issue.

**Comment by dmitryermilov** [comment]
Hi @3xLOGICKevinHan ,

>Also, I downloaded a 32bit "mfxplugin32_hevcd_sw.dll" from internet.

Interesting :)

>Does intel msdk works if a PC is using AMD CPU?

We don't support/validate such configurations.

> I just compared the performance between ffmpeg and intel msdk. Intel msdk does have better performance even using sw decoding. It should be able to solve my issue.

Great! Good to know it helped you.

**Comment by 3xLOGICKevinHan** [comment]
Hi @dmitryermilov ,
Many thanks for your help on this. You helped me clarify many things. I will just close this ticket.
:)

**Comment by dmitryermilov** [comment]
You're welcome Kevin!
