### ISSUE TITLE
sample_decode - rendering fails with libX11.so not found

### ISSUE THREAD

**Issue by jonrecker** [Intel-Media-SDK/MediaSDK#210]
After a clean installation of Ubuntu desktop 16.04.4, attempting to render the output of sample_decode in an X11 window fails with the following error:

```
./sample_decode h264 -i ../content/test_stream.264 -r
libX11.so: cannot open shared object file: No such file or directory

[ERROR], sts=MFX_ERR_MEMORY_ALLOC(-4), CreateAllocator, CreateHWDevice failed at MediaSDK/samples/sample_decode/src/pipeline_decode.cpp:1210
```
As a workaround, creating a symbolic link from /usr/lib/x86_64-linux-gnu/libX11.so --> /usr/lib/x86_64-linux-gnu/libX11.so.6 resolves the issue. This happens automatically when installing the package libx11-dev, for example.

However, I believe the library version should be specified in sample_common/src/vaapi_utils.cpp, as is done for the other libraries. e.g.

```
VA_X11Proxy::VA_X11Proxy()
    : lib("libva-x11.so.2")  <-- appends .so.2
    , SIMPLE_LOADER_FUNCTION(vaGetDisplay)
    , SIMPLE_LOADER_FUNCTION(vaPutSurface)
{
}
...

XLib_Proxy::XLib_Proxy()
    : lib("libX11.so")  <-- does not append .so.6
    , SIMPLE_LOADER_FUNCTION(XOpenDisplay)
    , SIMPLE_LOADER_FUNCTION(XCloseDisplay)
    , SIMPLE_LOADER_FUNCTION(XCreateSimpleWindow)
    , SIMPLE_LOADER_FUNCTION(XMapWindow)
    , SIMPLE_LOADER_FUNCTION(XSync)
    , SIMPLE_LOADER_FUNCTION(XDestroyWindow)
    , SIMPLE_LOADER_FUNCTION(XResizeWindow)
#if defined(X11_DRI3_SUPPORT)
    , SIMPLE_LOADER_FUNCTION(XGetGeometry)
#endif // X11_DRI3_SUPPORT
{}
```

**Comment by eero-t** [comment]
Why sample_decode is dlopening X library at run-time  instead of simply just linking at build time?   This seems very error-prone.

**Comment by onabiull** [comment]
It was implemented to allow reuse of the same sample binary on headless systems without installed X11. Initially we had something like sample_decode_x11, sample_decode_drm and sample_decode_sw. Dynamic loading introduced to pack them all into single binary.

**Comment by eero-t** [comment]
> It was implemented to allow reuse of the same sample binary on headless systems without installed X11

On Debian based systems like Ubuntu, libX11 package and its dependencies use only 3MB of disk space.  Out of curiosity, on what systems (supported by MediaSDK) that's a problem?

(As a hobby, I maintain emulator for mid-80 / early 90's computers.  On those I could understand somebody complaining loudly about 3MB. :-))

**Comment by dmitryermilov** [comment]
Fixed: https://github.com/Intel-Media-SDK/MediaSDK/blob/fe8538c74fc1d4d0049832c1314974c30d9d1cd0/samples/sample_common/src/vaapi_utils.cpp#L228
