### ISSUE TITLE
vp9 decode regression: can't support resolution > 4k

### ISSUE THREAD

**Issue by xuguangxin** [Intel-Media-SDK/MediaSDK#2101]
this issue fixed by https://github.com/Intel-Media-SDK/MediaSDK/pull/1570/files

but it's introduced again by https://github.com/Intel-Media-SDK/MediaSDK/commit/444ecb480a3918cc6faeb7662ca7492fd564f301

**Comment by dmitryermilov** [comment]
@onabiull , do you have any update?

**Comment by xuguangxin** [comment]
thanks Dima
