### ISSUE TITLE
asc: remove/hide instruction-set specific code

### ISSUE THREAD

**Issue by dvrogozh** [Intel-Media-SDK/MediaSDK#2104]
https://github.com/Intel-Media-SDK/MediaSDK/blob/99712bd1c86ea8201dcf533bfb79c694dd6a4e3c/_studio/shared/asc/include/asc_common_impl.h#L56

We need to check whether this code is actually used and if it is used need to hide it inside instuction-set specific library.

**Comment by spossos** [comment]
This particular function is used on both AVX2 and SSE4.1 optimized code, I will work on it

**Comment by dvrogozh** [comment]
I wish we had all intrinsic functions grouped in .cpp files rather than .h files. Since this completely eliminates a risk that the header file will be included in the generic code path (which is not built with required instruction set) and function accidentally used. If that's not possible, I wish we will refactor the source code placement in the folders making sure that headers with intrinsics are grouped in a dedicated folder, This would allow easier catching of problems.

**Comment by dvrogozh** [comment]
I believe we fixed that in #2107.
