### ISSUE TITLE
sample_encode h264 broken with i965 driver

### ISSUE THREAD

**Issue by nagos** [Intel-Media-SDK/MediaSDK#2108]
sample_encode h264 crashing with segfault on Ubuntu 18.04 and libva 2.7.1 on i5-3470
```
sample_encode h264 -i in.yuv -o out.h264 -u 1 -w 1920 -h 1080

libva info: VA-API version 1.7.0
libva info: Trying to open /usr/local/lib/dri/iHD_drv_video.so
libva info: va_openDriver() returns -1
libva info: Trying to open /usr/local/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_7
libva info: va_openDriver() returns 0
Encoding Sample Version 8.4.27.

Input file format	YUV420
Output video		AVC 
Source picture:
	Resolution	1920x1088
	Crop X,Y,W,H	0,0,1920,1080
Destination picture:
	Resolution	1920x1088
	Crop X,Y,W,H	0,0,1920,1080
Frame rate	30.00
Bit rate(Kbps)	3757
Gop size	0
Ref dist	4
Ref number	0
Idr Interval	0
Target usage	quality
Memory type	system
Media SDK impl		hw
Media SDK version	1.29

Processing started
Segmentation fault (core dumped)
```

Bug first appeared in 897ea5aabd1fca5c5ef3a31ff0aec21488da1192
by changes in files (if i git reset them, encoder work again):
```
samples/sample_encode/include/pipeline_encode.h
samples/sample_encode/src/pipeline_encode.cpp
samples/sample_encode/src/sample_encode.cpp
```

Segfault happening at this line
https://github.com/Intel-Media-SDK/MediaSDK/blob/897ea5aabd1fca5c5ef3a31ff0aec21488da1192/samples/sample_encode/src/pipeline_encode.cpp#L142

**Comment by dmitryermilov** [comment]
Hi @nagos , in your example the stack is using old i965 driver (not iHD). Generally this is not expected, we don't guarantee support of i965 driver. Could you check why iHD_drv_video.so is not loaded?

**Comment by dvrogozh** [comment]
Crash should not be expected either. We might have fail with the error, but we should not crash. @mpushki : can you, please, check the error handling?

**Comment by nagos** [comment]
Now i built docker image to isolate tests from my system.
Also now with intel media-driver instead of intel-vaapi-driver

> root@dd41f90ff180:/# /opt/intel/mediasdk/share/mfx/samples/sample_encode h264 -w 1920 -h 1080 -i in.yuv -o out.h264 -u 1
> libva info: VA-API version 1.7.0
> libva info: Trying to open /usr/local/lib/dri/iHD_drv_video.so
> libva info: Found init function __vaDriverInit_1_7
> libva error: /usr/local/lib/dri/iHD_drv_video.so init failed
> libva info: va_openDriver() returns 1
> libva info: Trying to open /usr/local/lib/dri/i965_drv_video.so
> libva info: Found init function __vaDriverInit_1_7
> libva info: va_openDriver() returns 0
> Encoding Sample Version 20.1.0
> 
> Input file format	YUV420
> Output video		AVC 
> Source picture:
> 	Resolution	1920x1088
> 	Crop X,Y,W,H	0,0,1920,1080
> Destination picture:
> 	Resolution	1920x1088
> 	Crop X,Y,W,H	0,0,1920,1080
> Frame rate	30.00
> Bit rate(Kbps)	3757
> Gop size	256
> Ref dist	4
> Ref number	3
> Idr Interval	0
> Target usage	quality
> Memory type	system
> Media SDK impl		hw
> Media SDK version	1.32
> 
> Processing started
> Segmentation fault (core dumped)

Next i tested same docker image on i5-8265U.
Maybe some Ivy Bridge specific bug?

I narrowed down it to -bref -nobref

> [-bref] - arrange B frames in B pyramid reference structure
> [-nobref] -  do not use B-pyramid (by default the decision is made by library)

Wtith -bref i got segfault, with -nobref everything works fine.
Current version of SDK change value of this variable from 0 to 2:
https://github.com/Intel-Media-SDK/MediaSDK/blob/897ea5aabd1fca5c5ef3a31ff0aec21488da1192/samples/sample_encode/src/sample_encode.cpp#L1371

**Comment by mpushki** [comment]
> Crash should not be expected either. We might have fail with the error, but we should not crash. @mpushki : can you, please, check the error handling?

Yes, I will check

**Comment by daleksan** [comment]
Hi @nagos is it still actual for you?

**Comment by nagos** [comment]
Not anymore, we moved to new CPU after comments by dmitryermilov.

**Comment by daleksan** [comment]
@nagos ok thanks a lot for update. i'm going to close the issue. Feel free to open the new one if help is necessary
