### ISSUE TITLE
Cheating static analysis considered harmful

### ISSUE THREAD

**Issue by fenrus75** [Intel-Media-SDK/MediaSDK#212]
inline void msdk_disp_char_cpy_s(char * to, size_t to_size, const char * from)
{
    size_t source_len = strlen(from);
    size_t num_chars = (to_size - 1) < source_len ? (to_size - 1) : source_len;
    strncpy(to, from, num_chars);
    to[num_chars] = 0;
}

really? this is tripping up compiler warnings as cheating on static analysis !

**Comment by dmitryermilov** [comment]
This is not actual with a new dispatcher implementation:
https://github.com/Intel-Media-SDK/MediaSDK/commit/a1052b1a8f888bf766a19be96e6bf6021f86892a
