### ISSUE TITLE
Error creating a QSV device (after following ffmpeg with MediaSDK wiki instructions)

### ISSUE THREAD

**Issue by malikwas** [Intel-Media-SDK/MediaSDK#2127]
I wanted to enable hardware encoding for my ffmpeg build for a project I'm working on. I followed the wiki for [building and using ffmpeg with the MediaSDK](https://github.com/Intel-Media-SDK/MediaSDK/wiki/Build-and-use-ffmpeg-with-MediaSDK). I followed the second method described using apt-get:

```
sudo apt-get install libva-dev libmfx-dev intel-media-va-driver-non-free
export LIBVA_DRIVER_NAME=iHD
```

I followed the instructions and configured then built ffmpeg. However, when I run the first decode example, I get this error message:

```
Error creating a QSV device
qsv hwaccel requested for input stream #0:0, but cannot be initialized.
[h264_qsv @ 0x55a08c6c00c0] Error initializing the MFX video decoder: invalid handle (-6)
Error while decoding stream #0:0: Invalid argument
Error creating a QSV device
qsv hwaccel requested for input stream #0:0, but cannot be initialized.
[h264_qsv @ 0x55a08c6c00c0] Error initializing the MFX video decoder: invalid handle (-6)
Error while decoding stream #0:0: Invalid argument
Error creating a QSV device
qsv hwaccel requested for input stream #0:0, but cannot be initialized.
[h264_qsv @ 0x55a08c6c00c0] Error initializing the MFX video decoder: invalid handle (-6)
Error while decoding stream #0:0: Invalid argument
Error creating a QSV device
...
```

I have the qsv codecs as a part of ffmpeg:

```
root@vm:~# ffmpeg -encoders | grep qsv
ffmpeg version N-97836-g050b72ab5e Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --arch=x86_64 --disable-yasm --enable-vaapi --enable-libmfx
  libavutil      56. 46.100 / 56. 46.100
  libavcodec     58. 86.100 / 58. 86.100
  libavformat    58. 43.100 / 58. 43.100
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 82.100 /  7. 82.100
  libswscale      5.  6.101 /  5.  6.101
  libswresample   3.  6.100 /  3.  6.100
 V..... h264_qsv             H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (Intel Quick Sync Video acceleration) (codec h264)
 V..... hevc_qsv             HEVC (Intel Quick Sync Video acceleration) (codec hevc)
 V..... mjpeg_qsv            MJPEG (Intel Quick Sync Video acceleration) (codec mjpeg)
 V..... mpeg2_qsv            MPEG-2 video (Intel Quick Sync Video acceleration) (codec mpeg2video)
 V..... vp9_qsv              VP9 video (Intel Quick Sync Video acceleration) (codec vp9)
```

I also followed the other method of building the Media SDK and getting the driver from the source, but I get the same message. I've been struggling with this for the past 3 days. I don't know what I'm doing wrong. Any help would be really appreciated.

**Comment by dvrogozh** [comment]
Please, provide output of:
`cat /proc/cpuinfo | grep "model name" | uniq`
and
`lspci -nn | grep VGA`
On the system where you try to run ffmpeg.

**Comment by malikwas** [comment]
>  `lspci -nn | grep VGA`

```
root@vm:~#  cat /proc/cpuinfo | grep "model name" | uniq
model name	: Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
root@vm:~#  lspci -nn | grep VGA
00:02.0 VGA compatible controller [0300]: Red Hat, Inc. QXL paravirtual graphic card [1b36:0100] (rev 04)
```

**Comment by malikwas** [comment]
> Please, provide output of:
> `cat /proc/cpuinfo | grep "model name" | uniq`
> and
> `lspci -nn | grep VGA`
> On the system where you try to run ffmpeg.

```
root@vm:~#  cat /proc/cpuinfo | grep "model name" | uniq
model name	: Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
root@vm:~#  lspci -nn | grep VGA```

**Comment by dvrogozh** [comment]
It seems you have Xeon without integrated GPU: https://ark.intel.com/content/www/us/en/ark/products/91767/intel-xeon-processor-e5-2650-v4-30m-cache-2-20-ghz.html. Effectively, GPU initialization fails.

**Comment by malikwas** [comment]
> It seems you have Xeon without integrated GPU: https://ark.intel.com/content/www/us/en/ark/products/91767/intel-xeon-processor-e5-2650-v4-30m-cache-2-20-ghz.html. Effectively, GPU initialization fails.

I was in a rush and did a bad copy-paste. Here's the actual output:

```

**Comment by dvrogozh** [comment]
mediasdk supports Intel GPUs only and works with iHD driver: https://github.com/intel/media-driver. You can see list of supported platforms in the driver readme. Your system does not have Intel GPU, the VGA controller you have is not supported.

**Comment by malikwas** [comment]
Gotcha, I guess my only option is to use software encoding.
