### ISSUE TITLE
How can i run MFX_RATECONTROL_LA_EXT in sample_multi_transcode?

### ISSUE THREAD

**Issue by changliwu** [Intel-Media-SDK/MediaSDK#214]
Hi
      I want to how to run one video transcoding in sample_multi_transcode with MFX_RATECONTROL_LA_EXT in MediaSDK?
Run like this:
/opt/intel/mediasdk/samples/sample_multi_transcode -par laext.par
and laext.par like this:
-async 10 -i::h264 /root/big.264 -o::sink -gop_size 33 -dist 4 -num_ref 2 -u 4 -la_ext -lad 33
-async 10 -i::source -o::h264 test1.264 -gop_size 33 -dist 4 -num_ref 2 -u 4 -la_ext -lad 33 -w 1920 -h 1080

Is it ok?

**Comment by 3703liu** [comment]
I also want to run sample_multi_transcode with MFX_RATECONTROL_LA_EXT ,I used a  similar command，but it cannot work. I tried  your command, it cannot work too. Have you find a command which can work normally ?
