### ISSUE TITLE
[APL] H264: SPS header values set to zero, once iHD driver is loaded

### ISSUE THREAD

**Issue by VUNNYSODHI** [Intel-Media-SDK/MediaSDK#2140]
There is issue in MediaSDK library for H264 stream.
If H264 stream has SPS header information with "bitstream_restriction_flag = 1" and  "max_dec_frame_buffering = 4", as H264 Spec it should use max_dec_frame_buffering, rather than using default dpzSize for frames calculation. Which is not happening currently.

**Command Used:**
 ./sample_decode h264 -hw -async 1 -vaapi -i ~/test_2880x960.h264 -n 10

**Test Environment:**
OS: Ubuntu 18.04
Hardware: APL
Latest MediaSDK Commit: 2e3dbfa7b30a1efa27e021f34dd6791f6e9447bc 
Latest MediaDriver Commit: d7061b608ad4d55fccab00f8d80b852f20eab1d7 (20.1.pre)
Latest Libva Commit: ccf3b081ff3d2b0784cd66daf04bbc317277cf8b (2.8.0.pre1)

**Comment by VUNNYSODHI** [comment]
Debugging on MediaSDK side, found function call flow as below.
main (sample_decode.cpp) -->  CDecodingPipeline::Init (pipeline_decode.cpp) --> CDecodingPipeline::InitMfxParams (pipeline_decode.cpp) --> VideoDECODEH264::DecodeHeader (umc_h264_mfx_supplier.cpp) -->  CalculateDPBSize(umc_h264_task_supplier.h)
We get dpbSize = 16 at this point based on CodecProfile: 100, CodecLevel: 51 



Later when  following function  "UMC::FillVideoParam" in "umc_h264_dec_mfx.cpp" invoked
par->mfx.MaxDecFrameBuffering =  seq->vui.bitstream_restriction_flag ? seq->vui.max_dec_frame_buffering : 0; <-- mfx.MaxDecFrameBuffering is assigned value 4 based on SPS Header inform from stream supplied (carplay_2880x960.h264)

(gdb) p par->mfx.MaxDecFrameBuffering
$6 = 4


Later on, CreateAllocator(pipeline_decode.cpp) is invoked calls --> CreateHWDevice(pipeline_decode.cpp) --> CreateVAAPIDevice (pipeline_decode.cpp) -->CVAAPIDeviceDRM(vaapi_device.cpp ) <-- This point (dri/iHD_drv_video.so) is loaded
libva info: VA-API version 1.8.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_8
libva info: va_openDriver() returns 0

Again, it will invoke "CalculateDPBSize" function 

When "VideoDECODEH264::QueryIOSurfInternal"  function in "mfx_h264_dec_decode.cpp" file invoked
if (par->mfx.MaxDecFrameBuffering && par->mfx.MaxDecFrameBuffering < dpbSize) 
    dpbSize = par->mfx.MaxDecFrameBuffering;

(gdb) p par->mfx.MaxDecFrameBuffering
$4 = 0

(gdb) p dpbSize
$5 = 16

**Comment by VUNNYSODHI** [comment]
FYI, @alariono

**Comment by dmitryermilov** [comment]
@guowillyy , could you find the right owner?

**Comment by guowillyy** [comment]
@dmitryermilov , Yan will help take a look this issue, thx Yan!

**Comment by wangyan-intel** [comment]
@VUNNYSODHI Could you please share your clip for debugging? Thanks.

**Comment by brmarkus** [comment]
We got recorded clips from our customer, which are covered under NDA and can't be shared publicly. Let us try to sync internally.
In essence, the stream header had the flag "bitstream_restriction_flag" set with "max_dec_frame_buffering==4", with a resolution of 2880x960 in h.264/AVC, as CodecProfile: 100, CodecLevel: 51.

**Comment by VUNNYSODHI** [comment]
Hi @wangyan-intel, you can use any H264 stream provided SPS header has "bitstream_restriction_flag" set and "max_dec_frame_buffering" with some value. I have tried some other 2880 clips issue is reproducible.
Thanks
