### ISSUE TITLE
mediasdk sample_decode return CreateHWDevice failed in ubuntu16.04 docker

### ISSUE THREAD

**Issue by lialin86** [Intel-Media-SDK/MediaSDK#2147]
I build and installed gmmlib libva libva-utils  media-driver  msdk(git master branch) without error in an ubuntu16.04 docker, then I try:
cd /opt/intel/mediasdk/share/mfx/samples 
./sample_decode h264 -i myvideo.h264 -vaapi -rgb4 -o ./output.yuv

I got error:
[ERROR], sts=MFX_ERR_MEMORY_ALLOC(-4), Init, CreateHWDevice failed at /home/work/msdk/samples/sample_decode/src/pipeline_decode.cpp:439

[ERROR], sts=MFX_ERR_MEMORY_ALLOC(-4), main, Pipeline.Init failed at /home/work/msdk/samples/sample_decode/src/sample_decode.cpp:745

What is wrong?  is it failed to install the media-driver or libva?

**Comment by AntonGrishin** [comment]
Hi @lialin86,
Are you sure, that you have enough rights for use gfx adapter under docker?

Btw, we have a wiki page about [access GPU under docker](https://github.com/Intel-Media-SDK/MediaSDK/wiki/Running-on-GPU-under-docker)

**Comment by uartie** [comment]
Try specifying `--device /dev/dri/renderD128` to the `docker run` options.  Additionally, depending on the user you run as in docker container, you may need to also specify `` --group-add `stat --format=%g /dev/dri/renderD128` ``.  NOTE: this is assuming `/dev/dri/renderD128` represents your Intel GPU device node... it could be different depending on your setup (e.g. `/dev/dri/renderD129`).

**Comment by uartie** [comment]
FWIW, the wiki page says to use `--privileged`.  But that option enables much more than just the host GPU access.  Thus, in my last comment, the `--device` (and `--group-add`) should be all that's necessary to expose access to the GPU in the docker container.

**Comment by lialin86** [comment]
> `--device /dev/dri/renderD128` to the `docker run` options

I add "--device /dev/dri/renderD128" to the docker run options, then I can run ./sample_decode without error, thank you.

**Comment by lialin86** [comment]
> /dev/dri

ls /dev/dri
card0  card1  renderD128  renderD129
is seems I have two device on my machine, how to enable all of them in docker run options?

**Comment by uartie** [comment]
> it seems I have two device on my machine, how to enable all of them in docker run options?

Just specify `--device /dev/dri/`

**Comment by lialin86** [comment]
@uartie thank you very much
