### ISSUE TITLE
mediasdk sample_decode init failed in centos docker

### ISSUE THREAD

**Issue by lialin86** [Intel-Media-SDK/MediaSDK#2166]
hello,
      
I build and installed gmmlib libva libva-utils media-driver msdk(git master branch) without error in an centos7 docker, then I try:
cd /opt/intel/mediasdk/share/mfx/samples
./sample_decode h264 -i myvideo.h264 -vaapi -rgb4 -o ./output.yuv

I got error:
[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), Init, m_mfxSession.Init failed at /home/IntelMediaSDK19.2.0_Install/MediaSDK-intel-mediasdk-19.2.0/samples/sample_decode/src/pipeline_decode.cpp:310

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), main, Pipeline.Init failed at /home/IntelMediaSDK19.2.0_Install/MediaSDK-intel-mediasdk-19.2.0/samples/sample_decode/src/sample_decode.cpp:701

I can run it successful in an ubuntu docker, why it is failed in centos? how to solve this problem?

**Comment by dmitryermilov** [comment]
Most likely it can't load with dispatcher (libmfx.so.1) or MediaSDK run-time library (libmfxhw64.so.1). Please try to run sample_decode under strace command to see which search paths are used. It's worth doing it in non-Docker environment (to see behavior in a workable case), then in Docker environment.

**Comment by AntonGrishin** [comment]
Hi @lialin86, 
If you install all with default paths, can you please export 

```export LD_LIBRARY_PATH=/opt/intel/mediasdk/lib64/:/usr/local/lib```

and try to run decode again?

**Comment by AntonGrishin** [comment]
Hi @lialin86,

Does the answer above resolve your problem?

**Comment by george-norton** [comment]
It is also worth remembering you need to mount `/dev/dri` inside docker (`-device /dev/dri:/dev/dri`) or run in privileged mode and that the video group id is different between Ubuntu and CentOS - so if you are running in the container as a non root user on an Ubuntu host you might find you don't have permission to access `/dev/dri/*` inside the container. You might also need to ensure that the `LIBVA_DRIVERS_PATH` and `LIBVA_DRIVER_NAME` environment variables are correctly set (you might be able to `source /etc/profile.d/intel-media.sh`). Running `vainfo` might also show up some issues (like if the wrong media-driver library is getting loaded).

**Comment by daleksan** [comment]
@lialin86 please feel free to reopen the issue if it is still actual
