### ISSUE TITLE
VPP does not reject unsupported interpolation methods

### ISSUE THREAD

**Issue by aobolensk** [Intel-Media-SDK/MediaSDK#2198]
Introduced in: 2989b1c

**Comment by FurongZhang** [comment]
I am working on that. Will file a PR within this week for this issue.

**Comment by FurongZhang** [comment]
Hi, @aobolensk, I double checked the issue you reported. When App call query or QueryIOSurf, the current MSDK implementation returns unsupported. So I think the behavior is correct from my side. 

If you think it is an issue, is it possible for you to let me know how to reproduce the issue you reported?

**Comment by FurongZhang** [comment]
BTW, is it on Windows or Linux you reported? This PR https://github.com/Intel-Media-SDK/MediaSDK/commit/2989b1cbf475c029215bd6a2b67d65fda5416c43 is only on Windows. I submitted a patch for Linux and currently it is in code review.

**Comment by aobolensk** [comment]
Hi @FurongZhang, I reported this issue for Linux

**Comment by dmitryermilov** [comment]
@FurongZhang , do you see that issue on Linux?

**Comment by FurongZhang** [comment]
https://github.com/Intel-Media-SDK/MediaSDK/commit/2989b1cbf475c029215bd6a2b67d65fda5416c43 is only for Windows. I implemented Linux and submitted code review. Also added behavior test for code review.

**Comment by dmitryermilov** [comment]
This is the point of current issue. For any feature being enabled on specific OS, specific HW type we have to make sure that on other OSes, HW types the feature returns UNSUPPORTED (not pretending to work and do nothing).

**Comment by FurongZhang** [comment]
I have fixed the issue in the latest MSDK open source code. Please feel free to let us know if any further questions or issues, thanks a lot in advance!

**Comment by dmitryermilov** [comment]
@FurongZhang , could you point to the pool request?

**Comment by FurongZhang** [comment]
2989b1cbf475c029215bd6a2b67d65fda5416c43
