### ISSUE TITLE
Remove perl wrapper for compiling

### ISSUE THREAD

**Issue by chivakker** [Intel-Media-SDK/MediaSDK#220]
Can MediaSDK remove the perl wrapper and stick to cmake as the compiler?  This can help to standardize building with dependencies like media-driver and gmmlib.

**Comment by onabiull** [comment]
Hello,

We gradually improve cmake defaults to make such scenario viable. Actually on my configuration default cmake build scenario 
```cmake 
   mkdir build && cd build
   cmake ../
   make
   sudo make install
```
already work as expected. There are some work in progress to make X11 headers optional for samples and probably relax other restrictions. After all perl wrapper just set a number of cmake options.

**Comment by dvrogozh** [comment]
@onabiull : can we switch github build scenario which we trigger during each commit check from perl to what you have described?
