### ISSUE TITLE
Segfault on Windows when using with OutputDuplication API

### ISSUE THREAD

**Issue by paniksystem** [Intel-Media-SDK/MediaSDK#2201]
I have an issue when using the encoder together with the OutputDuplication API on Windows 10

I create a D3D11 Device, and use it to capture my desktop with AcquireNextFrame and ReleaseFrame. Multithread protection is active.
I've been using this code for a long time with the Media Foundation API, but i want to migrate to the MediaSDK because dynamic bitrate does not work with the current Intel Media Transform.
I set the DEVICE_MGR_TYPE to this device, and use it to create the surface pool of my mfxFrameAllocator. As soon as i start calling EncodeFrameAsync (without even copying my desktop surface into it) i get a segfault on my next AcquireNextFrame:

`Exception levée à 0x00007FF973CB8C79 (igd10iumd64.dll): 0xC0000005 : Violation d'accès lors de la lecture de l'emplacement 0xFFFFFFFFFFFFFFFF.`

Hardware is: Iris Graphics 540
Driver is: 24.20.100.6299 (latest for my surface laptop)

Am i missing something to do in this scenario?

**Comment by dmitryermilov** [comment]
Hi @paniksystem ,

Since the crash occurs after initalization I assume there is something wrong surfaces being passed to EncodeFrameAsync. Can you please share more details here? E.g. :

1.  Do you create an instance of [D3D11 allocator](https://github.com/Intel-Media-SDK/MediaSDK/tree/master/samples/sample_common/src) or ... ?  
2. How do you initialize IOPattern of mfxVideoParams ? IN_VIDEO or something different?

Regards,
Dmitry

**Comment by paniksystem** [comment]
Hi,

1. I did not use D3D11 allocator, i started from the tutorials so used the simple allocator from common_directx11.cpp
I did not know there was another allocator example :D so i'll try to compare. From the simple allocator i just changed the BindFlags to 0 or D3D11_BIND_RENDER_TARGET because the default D3D11_BIND_DECODER option gives me an invalid arg error when using with CreateTexture2D of type DXGI_FORMAT_B8G8R8A8_UNORM (MFX_FOURCC_RGB4). 

2. The IOPattern is MFX_IOPATTERN_IN_VIDEO_MEMORY

**Comment by paniksystem** [comment]
Alright, i tried using the D3D11 Allocator from the sample, same result, crash on AcquireNextFrame after the first encoded frame...
:(

**Comment by paniksystem** [comment]
I should add that the segfault appears sometimes after 10 or so encoded frames but 90% of the times after the first one. I really don't know where to look next.

**Comment by dmitryermilov** [comment]
Is it possible to create a simple reproducer which can be shared with us?

**Comment by paniksystem** [comment]
sure, i'll get back to you (pretty big code to clear up to get a simple reproducer)

**Comment by dmitryermilov** [comment]
Thanks!

**Comment by paniksystem** [comment]
while writing the simple reproducer, the segfault is no longer happening, still investigating why...

**Comment by paniksystem** [comment]
My bad, while copying the sample, i moved the SDK initialization to a class method and did not check this part:

```
// Prepare Media SDK bit stream buffer
memset(&this->mfxBS, 0, sizeof(this->mfxBS));
this->mfxBS.MaxLength = par.mfx.BufferSizeInKB * 1000;
std::vector<mfxU8> bstData(this->mfxBS.MaxLength); // Falls out of scope
this->mfxBS.Data = bstData.data();
```

What a dumb dumb :D sorry for the inconvenience

**Comment by dmitryermilov** [comment]
Ahh. Great! I really love cases when a request to make a simple reproducer helps to reveal the issue in a production application :)
