### ISSUE TITLE
Cannot build v20.1.1 with -DBUILD_KERNELS=on

### ISSUE THREAD

**Issue by george-norton** [Intel-Media-SDK/MediaSDK#2206]
It is currently not possible to build v20.1.1 with `-DBUILD_KERNELS=on` as the latest published cm-compiler release (Release_20190717) is missing gen 12 VME support ([gen12_vme.h ](https://github.com/intel/cm-compiler/blob/master/support/include/cm/gen12_vme.h)is empty). The `genx_simple_me` and `genx_me` kernels fail to build.

**Comment by dvrogozh** [comment]
Ok, it seems we forgot about this step. Eventually we need corresponding cm compiler support. Filed https://github.com/intel/cm-compiler/issues/19.

**Comment by dvrogozh** [comment]
CM compiler added gen12 support, but it occurs there might be yet another problem - it seems we still have gen10 and CM compiler dropped the support. We need to consider to drop as well or request CM to add support back. Same for media driver.

**Comment by dmitryermilov** [comment]
Arseniy worked on Gen10 clean up and found out another problem. Please see https://github.com/intel/cm-compiler/issues/24

**Comment by daleksan** [comment]
Hi @george-norton 
Is it still actual for you? Can we close the issue?

**Comment by george-norton** [comment]
No, the issue is resolved. Thanks.
