### ISSUE TITLE
MFX_RATECONTROL_LA_EXT in sample_multi_transcode, m_pmfxENC->GetEncodeStat( &mfxStat ) return MFX_ERR_UNSUPPORTED

### ISSUE THREAD

**Issue by tongshi203** [Intel-Media-SDK/MediaSDK#2213]
Hi:
    I run sample_multi_transcode like this:
            ./sample_multi_transcode -par laext.par -p 1.perf

     laext.par is : 
            -i::h264 test.h264 -o::sink -gop_size 33 -dist 4 -num_ref 2 -u 4 -la_ext -lad 33
            -i::source -o::h265 test.h265 -gop_size 33 -dist 4 -num_ref 2 -u 4 -la_ext -lad 33 -w 1280 -h 720

    It works well and can get the encoded file test.h265,  I want to get GetEncodeStat by 
             mfxEncodeStat mfxStat;
             mfxStatus sts = m_pmfxENC->GetEncodeStat( &mfxStat );
    but  the sts is  MFX_ERR_UNSUPPORTED.
   
    why?

**Comment by daleksan** [comment]
Hi @DenWolf  can you help to clarify the question?

**Comment by kovakimy** [comment]
Hi @tongshi203,
If I understand correctly, you tried to get stat from HEVC. There is no such functionality, so the sts is MFX_ERR_UNSUPPORTED.
Thanks & Regards,
Kristina

**Comment by kovakimy** [comment]
@tongshi203 - If you still have any questions, please, let me know and reopen this ticket.
