### ISSUE TITLE
Any plan for an Alpine Build

### ISSUE THREAD

**Issue by Odianosen25** [Intel-Media-SDK/MediaSDK#2217]
Hello,

Please I will like to use this within an Alpine based docker container, but when I try to build, it gives an error for environment constraint. I guess it has to do with the fact its not designed to run within an Alpine environment (please if I am wrong let me know).

Any way there is plan for it to be supported? Of if I am just being dumb, what is the command line for the `make install` I might be missing?

Kind regards

**Comment by dvrogozh** [comment]
Just briefly trying, it builds fine for me. Docker file is below. Could you, please, be more specific what you've attempted to run and what has actually failed?

```
FROM alpine:3 AS base

ENV http_proxy=$http_proxy
ENV https_proxy=$https_proxy

RUN apk add --no-cache \
  autoconf \
  automake \
  bash \
  cmake \
  gcc \
  g++ \
  git \
  libdrm-dev \
  libpciaccess-dev \
  libtool \
  make \
  pkgconfig

ARG WORKSPACE=/opt/intel/git

RUN mkdir -p $WORKSPACE
WORKDIR $WORKSPACE

RUN git clone https://github.com/intel/libva.git
RUN git clone https://github.com/intel/libva-utils.git
RUN git clone https://github.com/intel/gmmlib.git
RUN git clone https://github.com/intel/media-driver.git
RUN git clone https://github.com/Intel-Media-SDK/MediaSDK.git

ENV PREFIX=$WORKSPACE/install
ENV BINDIR=$PREFIX/bin
ENV LIBDIR=$PREFIX/lib
ENV PKG_CONFIG_PATH=$LIBDIR/pkgconfig

RUN cd $WORKSPACE/libva \
  && ./autogen.sh --prefix=$PREFIX --libdir=$LIBDIR \
  && make -j`nproc` && make install

RUN cd $WORKSPACE/libva-utils \
  && ./autogen.sh --prefix=$PREFIX --libdir=$LIBDIR \
  && make -j`nproc` && make install

RUN cd $WORKSPACE/gmmlib && mkdir build && cd build \
  && cmake -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_INSTALL_LIBDIR=$LIBDIR .. \
  && make -j`nproc` && make install

RUN cd $WORKSPACE/media-driver && mkdir build && cd build \
  && cmake -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_INSTALL_LIBDIR=$LIBDIR .. \
  && make -j`nproc` && make install

RUN cd $WORKSPACE/MediaSDK && mkdir build && cd build \
  && cmake -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_INSTALL_LIBDIR=$LIBDIR .. \
  && make -j`nproc` && make install

ENV LIBVA_DRIVER_NAME=iHD
ENV PATH=$BINDIR:$PATH
```

Building and running as:
```
# docker build $(env | grep -E '_proxy=' | sed 's/^/--build-arg /') --file Dockerfile -t intel-media-alpine .
<...>
# docker run -it --privileged intel-media-alpine vainfo
libva info: VA-API version 1.8.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /opt/intel/git/install/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_8
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.8 (libva 2.8.0.pre1)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 20.3.pre (4ab5939a)
vainfo: Supported profile and entrypoints
      VAProfileNone                   : VAEntrypointVideoProc
      VAProfileNone                   : VAEntrypointStats
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Simple            : VAEntrypointEncSlice
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointFEI
      VAProfileH264Main               : VAEntrypointEncSliceLP
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointFEI
      VAProfileH264High               : VAEntrypointEncSliceLP
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline: VAEntrypointFEI
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointFEI
```

**Comment by Odianosen25** [comment]
Hello @dvrogozh,

Thanks for the response, and I didn't know not this docker file existed, but will try it now and get back to you. I had tried building it myself several times just following the simple instructions, but guess I was wrong.

Kind regards

**Comment by Odianosen25** [comment]
@dvrogozh,

Many thanks for the help and it did build successfully. I knew I was most likely doing something dumb, but thanks again.

If I may ask, can I assume opencl is also installed, since its about hardware acceleration? As my plan is to now build Opencv, using this image as my base image for image processing.

Kind regards

**Comment by Odianosen25** [comment]
Dumb question again, forgot it was written opencl is enabled by default :D

**Comment by dvrogozh** [comment]
No, opencl is not build. That's separate driver stack and needs separate build. The top level repo is: https://github.com/intel/compute-runtime. I would suggest to post question to them, maybe they will have some docker file for you at hand.

**Comment by Odianosen25** [comment]
Ah @dvrogozh I had thought it was. But no worries I had already put in a question there and awaiting when a docker file based on alpine will be made available. In the mean time, the built image is like 2.8GB, which to me is quite massive for an alpine image. Anyway I can shrink that down a but? I tried deleting the git downloaded file, but didn't make any difference in size.

Kind regards

**Comment by uartie** [comment]
You could optimize image size with multi-stage builds feature: https://docs.docker.com/develop/develop-images/multistage-build/

**Comment by dvrogozh** [comment]
Yes, the docker file I provided was just an attempt to build the stack. I did not care about the size. If you care about size you need staged build and bring out development packages setup (which you don't need at runtime), git clone and packages build. 

Mind also that as it occurs this is not a good idea to install packages on alpine in non-default folders. Better to install in system.

Something like this should bring runtime image size down to ~435MB:
```
FROM alpine:3 AS base

ENV http_proxy=$http_proxy
ENV https_proxy=$https_proxy

FROM base as build

RUN apk add --no-cache \
  autoconf \
  automake \
  bash \
  cmake \
  gcc \
  g++ \
  git \
  libdrm-dev \
  libpciaccess-dev \
  libtool \
  make \
  pkgconfig

ARG WORKSPACE=/opt/intel/git

RUN mkdir -p $WORKSPACE
WORKDIR $WORKSPACE

RUN git clone https://github.com/intel/libva.git
RUN git clone https://github.com/intel/libva-utils.git
RUN git clone https://github.com/intel/gmmlib.git
RUN git clone https://github.com/intel/media-driver.git
RUN git clone https://github.com/Intel-Media-SDK/MediaSDK.git

ENV PREFIX=/usr
ENV LIBDIR=/usr/lib
ENV PKG_CONFIG_PATH=$LIBDIR/pkgconfig

RUN cd $WORKSPACE/libva \
  && ./autogen.sh --prefix=$PREFIX --libdir=$LIBDIR \
  && make -j`nproc` && make install && make install DESTDIR=/opt/intel/install

RUN cd $WORKSPACE/libva-utils \
  && ./autogen.sh --prefix=$PREFIX --libdir=$LIBDIR \
  && make -j`nproc` && make install && make install DESTDIR=/opt/intel/install

RUN cd $WORKSPACE/gmmlib && mkdir build && cd build \
  && cmake -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_INSTALL_LIBDIR=$LIBDIR .. \
  && make -j`nproc` && make install && make install DESTDIR=/opt/intel/install

RUN cd $WORKSPACE/media-driver && mkdir build && cd build \
  && cmake -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_INSTALL_LIBDIR=$LIBDIR .. \
  && make -j`nproc` && make install && make install DESTDIR=/opt/intel/install

RUN cd $WORKSPACE/MediaSDK && mkdir build && cd build \
  && cmake -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_INSTALL_LIBDIR=$LIBDIR .. \
  && make -j`nproc` && make install && make install DESTDIR=/opt/intel/install

FROM base as runtime

ARG WORKSPACE=/opt/intel/git
COPY --from=build /opt/intel/install/usr /usr

RUN apk add --no-cache \
  libdrm \
  libpciaccess \
  libstdc++

ENV LIBVA_DRIVER_NAME=iHD

```

If you want to reduce size further, consider:
1. Strip down binaries you've built and installed to DESTDIR=/opt/intel/install
2. Remove all files you don't need. For example, mediasdk samples, header files, etc.

**Comment by Odianosen25** [comment]
Oh thanks @dvrogozh I will give it a shot. Wish I was that proficient in docker build, but unfortunately I am not. I don't even fully understand what was all said :(, but I know I will get there.

Thanks again

**Comment by dvrogozh** [comment]
You are welcome. @uartie gave you a link about multi-stage build. Also, consider to review docker file syntax: https://docs.docker.com/engine/reference/builder/. Everything is pretty straight forward.

With multi-stage build pay attention to FROM lines in docker file. Basically the example I gave above has the following structure:
* Base layer (called "base") is the first one and has common setup instructions, I just added http proxies in there, but you can add some packages install if needed.
* There are 2 layers which are based on "base":
  * "build" - here I clone, install development packages and build
  * "runtime" - here I create runtime environment

The trick is that final image produced by docker build is for the last layer in the docker file which happens to be a "runtime". "build" layer is just a helper one and it does not end up in the final image - that's where size saving comes from. But eventually I copy some stuff from "build" layer explicitly w/ `COPY --from=build` command.

**Comment by Odianosen25** [comment]
@dvrogozh, thanks for the explanation. I was able to later strip out ~100MB by not building samples; but I will also try the other options later.

But after everything, I later figured out I couldn't use the sdk for rtsp stream hardware accelerated video capture. So I am again trying to figure out the next step :(

Kind regards

**Comment by dvrogozh** [comment]
From the high level, which final use case you pursue? 

Neither mediasdk library nor mediasdk samples support rtsp or other streaming per-se. However, mediasdk has integration into ffmpeg (and gstreamer) which does support streaming.

Being said that you might wish to look into here: https://github.com/intel/media-delivery. I don't know your final use case, but the link above is a guide to enable content delivery use cases via nginx server which uses ffmpeg under the hood. If you don't need this case by itself, you can still look into ffmpeg building path in the docker file and the ffmpeg command line examples for cdn and edge samples. Closest to your rtsp would be here: https://github.com/intel/media-delivery/blob/70cf9abb148d24a1e381ddf632c1468c388cfa52/samples/edge/do-transcode.sh#L146

```
to_play=input.mp4
as="-c:a copy"
bitrate=3000000
  maxrate=$(python3 -c 'print(int('$bitrate' * 2))')
  bufsize=$(python3 -c 'print(int('$bitrate' * 4))')

ffmpeg \
   -hwaccel qsv -hwaccel_device $DEVICE \
    $dec_plugin -re -i $to_play \
    -c:v h264_qsv -profile:v high -preset medium \
      -b:v $bitrate -maxrate $maxrate -bufsize $bufsize \
      -extbrc 1 -b_strategy 1 -bf 7 -refs 5 -g 256 \
    $as -f flv rtmp://localhost:1935/$type/$stream
```

**Comment by Odianosen25** [comment]
@dvrogozh,

> From the high level, which final use case you pursue?

I am using OpenCV to capture and process images from cameras. I noticed that when I access a stream with abt 60 fps, my PC even though its an i7 doesn't cope so well. So I began to research into how to make the code more efficient and that's what led me to hardware acceleration. I already use hardware acceleration for recording the post processed images into a video file using `ffmpeg`; so I understand that side of things. By default I understand the `cv2.VideoCapture` uses ffmpeg at the back-end, but I don't know how to add hardware accel to it. Hope that explains it? I had thought using the MediaSDK would have solved my issue via `CAP_INTEL_MFX`.

> Neither mediasdk library nor mediasdk samples support rtsp or other streaming per-se. However, mediasdk has integration into ffmpeg (and gstreamer) which does support streaming.

My main aim here is to have it work within the `cv2.videoCapture` api, as I prefer using `openCV` to read the video frames than messing with ffmpeg to do that.

Thanks for the link, but I already use ffmpeg for delivery (HLS), and I also have hardware acceleration there too (its quite easy implementing hardware acceleration in ffmpeg, compared to openCV).  It was the desire for still hardware acceleration that got my looking into how to build openCL into my OpenCV, so I can use the Transparent api, which works great in my Windows environment strangely enough; but that's another story.

Hope I gave as clear as possible explanation?

Kind regards

**Comment by Odianosen25** [comment]
@dvrogozh,

Good day and hope you having a good weekend. I have been making some progress as been studying, but came to  another bottle neck and hoping you could help me. I will like to compile the gstreamer plugins into  the mediasdk as here https://github.com/Intel-Media-SDK/gstreamer-plugins.

Please how can I add this to the docker file?

Regards
