### ISSUE TITLE
Using OpenCV IntelMSDK accelerated to open RTSP Stream

### ISSUE THREAD

**Issue by Odianosen25** [Intel-Media-SDK/MediaSDK#2221]
@dvrogozh,

Thanks for all the help so far, and I was able to build and compile opencv to use the MSDK (MFX) to attempt to open a stream. I tried the following

```
import cv2

cap = cv2.VideoCapture("rtsp://freja.hiof.no:1935/rtplive/definst/hessdalen03.stream", cv2.CAP_INTEL_MFX)
```

And I get the following error

```
libva info: VA-API version 1.8.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /usr/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_8
libva info: va_openDriver() returns 0
MFX: Unsupported extension: rtsp://freja.hiof.no:1935/rtplive/definst/hessdalen03.stream
```

I know not why it says its an unsupported extension, or it is only for video files and not stream?

Apologises I had to open another issue,  since this is different and so making it easier for others to find in future.

Kind regards

**Comment by brmarkus** [comment]
If you choose to use the MediaSDK "backend" of OpenCV then, yes, it expects a file with an extension like ".h264" or ".h265", as the content is read-in "as-is" and provided to MediaSDK and libva.

MediaSDK doesn't implement demultiplexer or different high-level protocols.

So you might decide to use e.g. gstreamer as the backend of OpenCV, but make sure the used pipeline then contains "msdk" or "mfx" gstreamer plugins to decode, encode, transcode (and maybe also for post-processing like color-space-conversion). You would need to make sure you have them installed on your system; the installation of MediaSDK itself doesn't contain the corresponding gstreamer plugins.

**Comment by Odianosen25** [comment]
Hello @brmarkus,

Thanks for the response. I can confirm that I have built the gstreamer with some plugins into opencv, but honestly not sure which ones you  referring to; can you help with some list or something?

Also will you be kind enough to give me an example of how I can combine gstreamer and MediaSDK as backend for videocapture? I just need hardware acceleration for decoding.

Kind regards

**Comment by brmarkus** [comment]
In some of my older projects I use these "mfx" MediaSDK-gstreamer plugins: https://github.com/intel/gstreamer-media-SDK , plugins like "mfxh264dec", "mfxhevcdec".

In some of my newer projects I use the newer "msdk" MediaSDK-gstreamer plugins, which are integrated into the "bad" plugins in the meantime: https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/tree/master/sys/msdk , plugins like "msdkh264dec", "msdkh265dec".

**Comment by Odianosen25** [comment]
@brmarkus,

Thanks for the response. But please as I am actually new to  gstreamer (never used it before really), can you kindly help with an example on using the plugin with `VideoCapture`?

Regards

**Comment by brmarkus** [comment]
cv::VideoCapture() allows to give a gstreamer pipeline string, where you can specify the gstreamer pipeline, almost exactly like you wouldd call "gst-launch-1.0" in a terminal manually.
There are a few links, like:

https://stackoverflow.com/questions/46219454/how-to-open-a-gstreamer-pipeline-from-opencv-with-videowriter
https://answers.opencv.org/question/119583/how-does-the-cv2videocapture-class-work-with-gstreamer-pipelines/

Yes, something like you added to your edited post.

**Comment by Odianosen25** [comment]
Many thanks for this @brmarkus, I will give it a short and get back to you. Though I have noticed that when I use cv2.VideoCapture I get 

```
[ WARN:0] global /tmp/opencv-4.3.0/modules/videoio/src/cap_gstreamer.cpp (480) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
```

When I use the string I pasted I get

```
[ WARN:0] global /tmp/opencv-4.3.0/modules/videoio/src/cap_gstreamer.cpp (713) open OpenCV | GStreamer warning: Error opening bin: no element "rtspsrc"
[ WARN:0] global /tmp/opencv-4.3.0/modules/videoio/src/cap_gstreamer.cpp (480) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
```

**Comment by daleksan** [comment]
Hi @Odianosen25  is it still actual for you?

**Comment by Odianosen25** [comment]
@daleksan,

Apologies I really don’t understand what you saying

**Comment by daleksan** [comment]
@Odianosen25 i mean is this issue still relevant for you?

**Comment by Odianosen25** [comment]
Ah @daleksan,

Thanks for checking. Well it’s still relevant really, but I have gotten to understand it’s not what the framework was intended for I guess. 

So you can close it. But I have purchased the Movidius Stick 2 and wanting to use that instead for accelerating videocapture if I can. If you got any info on that, will be great.

But in all, you can close this, and I could reopen if I need to.

kind regards

**Comment by daleksan** [comment]
ok thanks a lot! Yes, feel free to re-open the issue if it will be relevant for you
