### ISSUE TITLE
ffmpeg-qsv encode avc some cases psnr drop on TGL

### ISSUE THREAD

**Issue by xinyudox** [Intel-Media-SDK/MediaSDK#2223]
os: ubuntu 18.04.3
kernel: 5.6.0-rc6+
platform: TGL

libva-afca400d5629
gmmlib-40c7d14fd16a
ffmpeg-cartwheel-e57905ae6125
intel-media-driver-388ea758af1f
vaapi-fits-smoke-a24b5f1caf09
vaapi-fits-6add33007b84

This issue is caused by this patch.

commit 37f26bb6850a242f6d2b549795ba31911386227b
Author: Pavel Gribov <pavel.gribov@intel.com>
Date:   Mon Mar 16 15:14:00 2020 +0300

    [h264e] Enable QPOffset by default
    
    - In CQP mode and GopRefDist 1 case
      PRefType is set to MFX_P_REF_PYRAMID by default.
    - EnableQPOffset is on by default, QPOffset is added in CQP mode.

case:
bframes=0,case=480p,gop=30,profile=main,qp=28,quality=4,slices=1

command line:
ffmpeg -init_hw_device qsv=qsv:hw -hwaccel qsv -filter_hw_device qsv -v verbose -f rawvideo -pix_fmt yuv420p -s:v 720x480 -i ./720x480p.yuv -vf 'format=nv12,hwupload=extra_hw_frames=120' -an -c:v h264_qsv -profile:v main -g 30 -q 28 -preset 4 -slices 1 -bf 0 -low_power 0 -vframes 150 -y ./test.h264

psnr:expect = [35.9774, 44.0011, 42.742, 40.9332, 46.4891, 45.4389]
psnr:actual = [35.2934, 43.8931, 42.6525, 40.5894, 46.3961, 45.3094]

**Comment by pgribov** [comment]
Hi, @xinyudox 
It's expected behavior for this patch. It drops PSNR, but improves bd-rate. We are planning to upload one or more related patches that provide further improvement. And it’s hard for me to say about the planned dates, but we expect them in the near future.

**Comment by xinyudox** [comment]
ok, thanks!
