### ISSUE TITLE
[Sandybridge] Intel MediaSDK is crashing Handbrake

### ISSUE THREAD

**Issue by DarkSwan86** [Intel-Media-SDK/MediaSDK#2230]
Hi!

I'm reporting a possible bug on the MediaSDK, on a Sandybridge platform. 

OS: Manjaro KDE x64
Kernel: 5.4.52-1-MANJARO x86_64
Processor: Intel Core Sandybridge i3-2350M
Mesa: 20.1.3
Intel Media Driver: 20.1.1-1
Intel Media SDK: 20.2.0-1
Libva: 2.8.0-1
libva-intel-driver: 2.4.1-1

Handbrake: 1.3.3 compiled with QSV support

The program seems to crash with an error on the libmfxhw64.so. Her is the coredump plus the gdb:

--------------------------
[leonardo@leonardo-pc ~]$ coredumpctl gdb 2736
           PID: 2736 (ghb)
           UID: 1000 (leonardo)
           GID: 1000 (leonardo)
        Signal: 6 (ABRT)
     Timestamp: Tue 2020-07-21 21:11:57 CEST (1min 51s ago)
  Command Line: ghb
    Executable: /usr/bin/ghb
 Control Group: /user.slice/user-1000.slice/session-2.scope
          Unit: session-2.scope
         Slice: user-1000.slice
       Session: 2
     Owner UID: 1000 (leonardo)
       Boot ID: 7d50e20c10264dd9a2112e20e97448ee
    Machine ID: 16cc0a136b2d4fa69485122dea3c9d7a
      Hostname: leonardo-pc
       Storage: /var/lib/systemd/coredump/core.ghb.1000.7d50e20c10264dd9a2112e20e97448ee.2736.1595358717000000000000.lz4
       Message: Process 2736 (ghb) of user 1000 dumped core.
                
                Stack trace of thread 2736:
                #0  0x00007f4a8a112355 raise (libc.so.6 + 0x3c355)
                #1  0x00007f4a8a0fb853 abort (libc.so.6 + 0x25853)
                #2  0x00007f4a8a0fb727 __assert_fail_base.cold (libc.so.6 + 0x25727)
                #3  0x00007f4a8a10a936 __assert_fail (libc.so.6 + 0x34936)
                #4  0x00007f4a7637fd2b n/a (libmfxhw64.so + 0x7fd2b)
                #5  0x00007f4a76379fa0 MFXVideoCORE_SetHandle (libmfxhw64.so + 0x79fa0)
                #6  0x0000563f1d3640a9 n/a (ghb + 0x2220a9)
                #7  0x0000563f1d345946 n/a (ghb + 0x203946)
                #8  0x0000563f1d31faf9 ghb_backend_init (ghb + 0x1ddaf9)
                #9  0x0000563f1d30c958 ghb_activate_cb (ghb + 0x1ca958)
                #10 0x00007f4a8b18b052 g_closure_invoke (libgobject-2.0.so.0 + 0x13052)
                #11 0x00007f4a8b1b3685 n/a (libgobject-2.0.so.0 + 0x3b685)
                #12 0x00007f4a8b1a741d g_signal_emit_valist (libgobject-2.0.so.0 + 0x2f41d)
                #13 0x00007f4a8b1a7980 g_signal_emit (libgobject-2.0.so.0 + 0x2f980)
                #14 0x00007f4a8b4d5a89 n/a (libgio-2.0.so.0 + 0xcaa89)
                #15 0x00007f4a8b4d5c0a g_application_run (libgio-2.0.so.0 + 0xcac0a)
                #16 0x0000563f1d2e9ac2 main (ghb + 0x1a7ac2)
                #17 0x00007f4a8a0fd002 __libc_start_main (libc.so.6 + 0x27002)
                #18 0x0000563f1d2ea17e _start (ghb + 0x1a817e)
                
                Stack trace of thread 2769:
                #0  0x00007f4a8a1d071d syscall (libc.so.6 + 0xfa71d)
                #1  0x00007f4a8b0e7c9b g_cond_wait_until (libglib-2.0.so.0 + 0x9ac9b)
                #2  0x00007f4a8b06f803 n/a (libglib-2.0.so.0 + 0x22803)
                #3  0x00007f4a8b0cbd5b n/a (libglib-2.0.so.0 + 0x7ed5b)
                #4  0x00007f4a8b0c7511 n/a (libglib-2.0.so.0 + 0x7a511)
                #5  0x00007f4a8a610422 start_thread (libpthread.so.0 + 0x9422)
                #6  0x00007f4a8a1d5bf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 2741:
                #0  0x00007f4a8a1cb05f __poll (libc.so.6 + 0xf505f)
                #1  0x00007f4a8b0ed168 n/a (libglib-2.0.so.0 + 0xa0168)
                #2  0x00007f4a8b09e221 g_main_context_iteration (libglib-2.0.so.0 + 0x51221)
                #3  0x00007f4a85287e5e n/a (libdconfsettings.so + 0x4e5e)
                #4  0x00007f4a8b0c7511 n/a (libglib-2.0.so.0 + 0x7a511)
                #5  0x00007f4a8a610422 start_thread (libpthread.so.0 + 0x9422)
                #6  0x00007f4a8a1d5bf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 2739:
                #0  0x00007f4a8a1cb05f __poll (libc.so.6 + 0xf505f)
                #1  0x00007f4a8b0ed168 n/a (libglib-2.0.so.0 + 0xa0168)
                #2  0x00007f4a8b09dc03 g_main_loop_run (libglib-2.0.so.0 + 0x50c03)
                #3  0x00007f4a8b50b1a8 n/a (libgio-2.0.so.0 + 0x1001a8)
                #4  0x00007f4a8b0c7511 n/a (libglib-2.0.so.0 + 0x7a511)
                #5  0x00007f4a8a610422 start_thread (libpthread.so.0 + 0x9422)
                #6  0x00007f4a8a1d5bf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 2770:
                #0  0x00007f4a8a616e32 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfe32)
                #1  0x00007f4a8a4f3c01 __gthread_cond_wait (libstdc++.so.6 + 0xc9c01)
                #2  0x00007f4a76350d76 n/a (libmfxhw64.so + 0x50d76)
                #3  0x00007f4a8a4f9b74 execute_native_thread_routine (libstdc++.so.6 + 0xcfb74)
                #4  0x00007f4a8a610422 start_thread (libpthread.so.0 + 0x9422)
                #5  0x00007f4a8a1d5bf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 2772:
                #0  0x00007f4a8a616e32 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfe32)
                #1  0x00007f4a8a4f3c01 __gthread_cond_wait (libstdc++.so.6 + 0xc9c01)
                #2  0x00007f4a76350d76 n/a (libmfxhw64.so + 0x50d76)
                #3  0x00007f4a8a4f9b74 execute_native_thread_routine (libstdc++.so.6 + 0xcfb74)
                #4  0x00007f4a8a610422 start_thread (libpthread.so.0 + 0x9422)
                #5  0x00007f4a8a1d5bf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 2738:
                #0  0x00007f4a8a1cb05f __poll (libc.so.6 + 0xf505f)
                #1  0x00007f4a8b0ed168 n/a (libglib-2.0.so.0 + 0xa0168)
                #2  0x00007f4a8b09e221 g_main_context_iteration (libglib-2.0.so.0 + 0x51221)
                #3  0x00007f4a8b09e272 n/a (libglib-2.0.so.0 + 0x51272)
                #4  0x00007f4a8b0c7511 n/a (libglib-2.0.so.0 + 0x7a511)
                #5  0x00007f4a8a610422 start_thread (libpthread.so.0 + 0x9422)
                #6  0x00007f4a8a1d5bf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 2740:
                #0  0x00007f4a8a1d071d syscall (libc.so.6 + 0xfa71d)
                #1  0x00007f4a8b0e7c9b g_cond_wait_until (libglib-2.0.so.0 + 0x9ac9b)
                #2  0x00007f4a8b06f803 n/a (libglib-2.0.so.0 + 0x22803)
                #3  0x00007f4a8b0cbd5b n/a (libglib-2.0.so.0 + 0x7ed5b)
                #4  0x00007f4a8b0c7511 n/a (libglib-2.0.so.0 + 0x7a511)
                #5  0x00007f4a8a610422 start_thread (libpthread.so.0 + 0x9422)
                #6  0x00007f4a8a1d5bf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 2773:
                #0  0x00007f4a8a616e32 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfe32)
                #1  0x00007f4a8a4f3c01 __gthread_cond_wait (libstdc++.so.6 + 0xc9c01)
                #2  0x00007f4a76350d76 n/a (libmfxhw64.so + 0x50d76)
                #3  0x00007f4a8a4f9b74 execute_native_thread_routine (libstdc++.so.6 + 0xcfb74)
                #4  0x00007f4a8a610422 start_thread (libpthread.so.0 + 0x9422)
                #5  0x00007f4a8a1d5bf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 2771:
                #0  0x00007f4a8a616e32 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfe32)
                #1  0x00007f4a8a4f3c01 __gthread_cond_wait (libstdc++.so.6 + 0xc9c01)
                #2  0x00007f4a76350d76 n/a (libmfxhw64.so + 0x50d76)
                #3  0x00007f4a8a4f9b74 execute_native_thread_routine (libstdc++.so.6 + 0xcfb74)
                #4  0x00007f4a8a610422 start_thread (libpthread.so.0 + 0x9422)
                #5  0x00007f4a8a1d5bf3 __clone (libc.so.6 + 0xffbf3)

GNU gdb (GDB) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/ghb...
(No debugging symbols found in /usr/bin/ghb)
[New LWP 2736]
[New LWP 2769]
[New LWP 2741]
[New LWP 2739]
[New LWP 2770]
[New LWP 2772]
[New LWP 2738]
[New LWP 2740]
[New LWP 2773]
[New LWP 2771]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
--Type <RET> for more, q to quit, c to continue without paging--bt
Core was generated by `ghb'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f4a8a112355 in raise () from /usr/lib/libc.so.6
[Current thread is 1 (Thread 0x7f4a8758be40 (LWP 2736))]
(gdb)

---------------------------

I've talked to the Handbrake developers and they pointed me on a possible MediaSDK library bug. 

It can be reproduced 100% of the times (also via terminal), just open Handbrake on a Sandybridge platform. 

If you need more information, i will provide them.

Thanks for your help!

**Comment by daleksan** [comment]
Hi @DarkSwan86 
Open Source Media Stack doesn't support Sandybridge, Ivybridge and Haswell platforms. Please take a look on the [system requirements](https://github.com/Intel-Media-SDK/MediaSDK/blob/master/doc/mediasdk_release_notes.md#system-requirements) section in the release notes.

**Comment by dvrogozh** [comment]
@daleksan : yes, open source msdk does not support SNB, IVB and HSW, but this should lead to error out rather than an application crash.

**Comment by dvrogozh** [comment]
@dmitryermilov Strange place to crash... How did we manage to crash in SetHandle?!

**Comment by dmitryermilov** [comment]
@dvrogozh , very easy :) :
https://github.com/Intel-Media-SDK/MediaSDK/blob/85f9cec9df7a9162c6419ad50d9a5901376290d6/_studio/shared/src/libmfx_core_vaapi.cpp#L557

SNB is not in the list of supported device ID's:
https://github.com/Intel-Media-SDK/MediaSDK/blob/85f9cec9df7a9162c6419ad50d9a5901376290d6/_studio/shared/src/libmfx_core_vaapi.cpp#L68

**Comment by dvrogozh** [comment]
They report a crash, not an assertion failure. @DarkSwan86 : can you, please, clarify: did you see a crash or assert?

@dmitryermilov : I don't think assert is properly used here. Distros enable asserts by default which would lead to apps asserting on that on the bad platform. I don't think that's a right behavior - it should be an error.

**Comment by dmitryermilov** [comment]
I agree with you.

**Comment by DarkSwan86** [comment]
Sorry for the late answer!

@dvrogozh i think it's a crash, i can't start the program even from the commandline, it always says "Aborted (core dump created)".
I've updated Manjaro to the latest version of everything and here is a new coredump and backtrace:

leonardo@leonardo-pc ~]$ coredumpctl gdb 5095
           PID: 5095 (ghb)
           UID: 1000 (leonardo)
           GID: 1000 (leonardo)
        Signal: 6 (ABRT)
     Timestamp: Fri 2020-11-13 17:27:26 CET (41s ago)
  Command Line: ghb
    Executable: /usr/bin/ghb
 Control Group: /user.slice/user-1000.slice/session-2.scope
          Unit: session-2.scope
         Slice: user-1000.slice
       Session: 2
     Owner UID: 1000 (leonardo)
       Boot ID: e1db1611df9a43d7bda0a001b5603fd0
    Machine ID: 16cc0a136b2d4fa69485122dea3c9d7a
      Hostname: leonardo-pc
       Storage: /var/lib/systemd/coredump/core.ghb.1000.e1db1611df9a43d7bda0a001b5603fd0.5095.1605284846000000.zst
       Message: Process 5095 (ghb) of user 1000 dumped core.
                
                Stack trace of thread 5095:
                #0  0x00007fe114c89615 raise (libc.so.6 + 0x3d615)
                #1  0x00007fe114c72862 abort (libc.so.6 + 0x26862)
                #2  0x00007fe114c72747 __assert_fail_base.cold (libc.so.6 + 0x26747)
                #3  0x00007fe114c81bf6 __assert_fail (libc.so.6 + 0x35bf6)
                #4  0x00007fe109126d2b n/a (libmfxhw64.so + 0x7fd2b)
                #5  0x00007fe109120fa0 MFXVideoCORE_SetHandle (libmfxhw64.so + 0x79fa0)
                #6  0x000055b3501420a9 n/a (ghb + 0x2220a9)
                #7  0x000055b350123946 n/a (ghb + 0x203946)
                #8  0x000055b3500fdaf9 ghb_backend_init (ghb + 0x1ddaf9)
                #9  0x000055b3500ea958 ghb_activate_cb (ghb + 0x1ca958)
                #10 0x00007fe115d18052 g_closure_invoke (libgobject-2.0.so.0 + 0x13052)
                #11 0x00007fe115d409c5 n/a (libgobject-2.0.so.0 + 0x3b9c5)
                #12 0x00007fe115d3459d g_signal_emit_valist (libgobject-2.0.so.0 + 0x2f59d)
                #13 0x00007fe115d34b00 g_signal_emit (libgobject-2.0.so.0 + 0x2fb00)
                #14 0x00007fe11607bb09 n/a (libgio-2.0.so.0 + 0xccb09)
                #15 0x00007fe11607bc8a g_application_run (libgio-2.0.so.0 + 0xccc8a)
                #16 0x000055b3500c7ac2 main (ghb + 0x1a7ac2)
                #17 0x00007fe114c74152 __libc_start_main (libc.so.6 + 0x28152)
                #18 0x000055b3500c817e _start (ghb + 0x1a817e)
                
                Stack trace of thread 5097:
                #0  0x00007fe114d4146f __poll (libc.so.6 + 0xf546f)
                #1  0x00007fe115c7575f n/a (libglib-2.0.so.0 + 0xa675f)
                #2  0x00007fe115c20e63 g_main_loop_run (libglib-2.0.so.0 + 0x51e63)
                #3  0x00007fe1160b0fe8 n/a (libgio-2.0.so.0 + 0x101fe8)
                #4  0x00007fe115c4ece1 n/a (libglib-2.0.so.0 + 0x7fce1)
                #5  0x00007fe1151893e9 start_thread (libpthread.so.0 + 0x93e9)
                #6  0x00007fe114d4c293 __clone (libc.so.6 + 0x100293)
                
                Stack trace of thread 5099:
                #0  0x00007fe114d4146f __poll (libc.so.6 + 0xf546f)
                #1  0x00007fe115c7575f n/a (libglib-2.0.so.0 + 0xa675f)
                #2  0x00007fe115c20121 g_main_context_iteration (libglib-2.0.so.0 + 0x51121)
                #3  0x00007fe1104e5c0e n/a (libdconfsettings.so + 0x5c0e)
                #4  0x00007fe115c4ece1 n/a (libglib-2.0.so.0 + 0x7fce1)
                #5  0x00007fe1151893e9 start_thread (libpthread.so.0 + 0x93e9)
                #6  0x00007fe114d4c293 __clone (libc.so.6 + 0x100293)
                
                Stack trace of thread 5101:
                #0  0x00007fe114d46d5d syscall (libc.so.6 + 0xfad5d)
                #1  0x00007fe115c6e8bb g_cond_wait_until (libglib-2.0.so.0 + 0x9f8bb)
                #2  0x00007fe115bf1813 n/a (libglib-2.0.so.0 + 0x22813)
                #3  0x00007fe115c51ceb n/a (libglib-2.0.so.0 + 0x82ceb)
                #4  0x00007fe115c4ece1 n/a (libglib-2.0.so.0 + 0x7fce1)
                #5  0x00007fe1151893e9 start_thread (libpthread.so.0 + 0x93e9)
                #6  0x00007fe114d4c293 __clone (libc.so.6 + 0x100293)
                
                Stack trace of thread 5103:
                #0  0x00007fe11518f6a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                #1  0x00007fe11506cc11 __gthread_cond_wait (libstdc++.so.6 + 0xc9c11)
                #2  0x00007fe1090f7d76 n/a (libmfxhw64.so + 0x50d76)
                #3  0x00007fe115072c24 execute_native_thread_routine (libstdc++.so.6 + 0xcfc24)
                #4  0x00007fe1151893e9 start_thread (libpthread.so.0 + 0x93e9)
                #5  0x00007fe114d4c293 __clone (libc.so.6 + 0x100293)
                
                Stack trace of thread 5096:
                #0  0x00007fe114d4146f __poll (libc.so.6 + 0xf546f)
                #1  0x00007fe115c7575f n/a (libglib-2.0.so.0 + 0xa675f)
                #2  0x00007fe115c20121 g_main_context_iteration (libglib-2.0.so.0 + 0x51121)
                #3  0x00007fe115c20172 n/a (libglib-2.0.so.0 + 0x51172)
                #4  0x00007fe115c4ece1 n/a (libglib-2.0.so.0 + 0x7fce1)
                #5  0x00007fe1151893e9 start_thread (libpthread.so.0 + 0x93e9)
                #6  0x00007fe114d4c293 __clone (libc.so.6 + 0x100293)
                
                Stack trace of thread 5102:
                #0  0x00007fe11518f6a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                #1  0x00007fe11506cc11 __gthread_cond_wait (libstdc++.so.6 + 0xc9c11)
                #2  0x00007fe1090f7d76 n/a (libmfxhw64.so + 0x50d76)
                #3  0x00007fe115072c24 execute_native_thread_routine (libstdc++.so.6 + 0xcfc24)
                #4  0x00007fe1151893e9 start_thread (libpthread.so.0 + 0x93e9)
                #5  0x00007fe114d4c293 __clone (libc.so.6 + 0x100293)
                
                Stack trace of thread 5105:
                #0  0x00007fe11518f6a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                #1  0x00007fe11506cc11 __gthread_cond_wait (libstdc++.so.6 + 0xc9c11)
                #2  0x00007fe1090f7d76 n/a (libmfxhw64.so + 0x50d76)
                #3  0x00007fe115072c24 execute_native_thread_routine (libstdc++.so.6 + 0xcfc24)
                #4  0x00007fe1151893e9 start_thread (libpthread.so.0 + 0x93e9)
                #5  0x00007fe114d4c293 __clone (libc.so.6 + 0x100293)
                
                Stack trace of thread 5098:
                #0  0x00007fe114d46d5d syscall (libc.so.6 + 0xfad5d)
                #1  0x00007fe115c6e8bb g_cond_wait_until (libglib-2.0.so.0 + 0x9f8bb)
                #2  0x00007fe115bf1813 n/a (libglib-2.0.so.0 + 0x22813)
                #3  0x00007fe115c51ceb n/a (libglib-2.0.so.0 + 0x82ceb)
                #4  0x00007fe115c4ece1 n/a (libglib-2.0.so.0 + 0x7fce1)
                #5  0x00007fe1151893e9 start_thread (libpthread.so.0 + 0x93e9)
                #6  0x00007fe114d4c293 __clone (libc.so.6 + 0x100293)
                
                Stack trace of thread 5104:
                #0  0x00007fe11518f6a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                #1  0x00007fe11506cc11 __gthread_cond_wait (libstdc++.so.6 + 0xc9c11)
                #2  0x00007fe1090f7d76 n/a (libmfxhw64.so + 0x50d76)
                #3  0x00007fe115072c24 execute_native_thread_routine (libstdc++.so.6 + 0xcfc24)
                #4  0x00007fe1151893e9 start_thread (libpthread.so.0 + 0x93e9)
                #5  0x00007fe114d4c293 __clone (libc.so.6 + 0x100293)

GNU gdb (GDB) 10.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/ghb...
(No debugging symbols found in /usr/bin/ghb)

warning: Can't open file /i915 (deleted) during file-backed mapping note processing

warning: Can't open file /memfd:wayland-cursor (deleted) during file-backed mapping note processing
[New LWP 5095]
[New LWP 5097]
[New LWP 5099]
[New LWP 5101]
[New LWP 5103]
[New LWP 5096]
[New LWP 5102]
[New LWP 5105]
[New LWP 5098]
[New LWP 5104]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
--Type <RET> for more, q to quit, c to continue without paging--
Core was generated by `ghb'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fe114c89615 in raise () from /usr/lib/libc.so.6
[Current thread is 1 (Thread 0x7fe111ff8980 (LWP 5095))]
(gdb) 

I also attach a report with inxi with all the specs from my laptop so maybe can help you:

System:    Host: leonardo-pc Kernel: 5.4.74-1-MANJARO x86_64 bits: 64 compiler: gcc v: 10.2.0 Desktop: KDE Plasma 5.20.2 
           tk: Qt 5.15.1 wm: kwin_wayland dm: SDDM Distro: Manjaro Linux 

CPU:       Info: Dual Core model: Intel Core i3-2350M bits: 64 type: MT MCP arch: Sandy Bridge rev: 7 L2 cache: 3072 KiB 
           flags: avx lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 18364 
           Speed: 867 MHz min/max: 800/2300 MHz Core speeds (MHz): 1: 868 2: 922 3: 880 4: 996

Graphics:  

Device-1: Intel 2nd Generation Core Processor Family Integrated Graphics vendor: ASUSTeK driver: i915 v: kernel 
           bus ID: 00:02.0 chip ID: 8086:0116 

Device-2: NVIDIA GF119M [GeForce 610M] vendor: ASUSTeK driver: nouveau v: kernel bus ID: 01:00.0 
           chip ID: 10de:1058 
           
Display: wayland server: X.Org 1.20.9 compositor: kwin_wayland driver: intel,nouveau unloaded: modesetting 
           alternate: fbdev,nv,vesa resolution: 1366x768~60Hz s-dpi: 96 

OpenGL: renderer: **Mesa DRI Intel HD Graphics 3000 (SNB GT2)** v: 3.3 Mesa 20.2.1 compat-v: 3.0 direct render: Yes

I've noticed that my HD3000 is a GT2. Reading from wikipedia there are 2 different version of GPU on Sandybridge, HD2000 and HD3000 with QSV enabled on both. Maybe it's not supported by MediaSDK?

if you need more information, just ask! Thanks!

**Comment by dvrogozh** [comment]
> I've updated Manjaro to the latest version

Can you, please, provide msdk and media-driver versions you have on Manjaro? From what I see this should be either 20.2.1 if you use Manjaro stable or 20.3.1 in case of unstable and testing.
