### ISSUE TITLE
HEVC Y210 sample decoder green frames with system memory

### ISSUE THREAD

**Issue by ngeorgis** [Intel-Media-SDK/MediaSDK#2241]
Decoding HEVC Y210 sample decoder shows green frames with system memory.
Works fine when I use D3D11.  Will try to provide a sample... 

```

./sample_decode.exe  h265  -r -i test.h265   --> green

./sample_decode.exe  h265  -d3d11 -r -i test.h265   --> works fine

```

**Comment by asmirno1** [comment]
Hi,

Could you please provide dxdiag report? We need to know platform and gfx driver version.
Have you tried to change "-r" to "-o output_file.yuv"? If so, do you see green frames in output file?
Also, is that issue specific to this bitstream or decoding of any bitstream shows green frames?
Could you also share this bitstream to us? 

Thanks,
Alexander

**Comment by ngeorgis** [comment]
sure let me work on this please...

**Comment by asmirno1** [comment]
Closing this due to aging and no answer from reporter.
@ngeorgis , please reopen and provide details if still actual.
