### ISSUE TITLE
Got MFX_ERR_UNDEFINED_BEHAVIOR when decoding AV1 clips

### ISSUE THREAD

**Issue by xhaihao** [Intel-Media-SDK/MediaSDK#2244]
MediaSDK commit: 568cb784c971d228c3162dfd9013db236dc4b9fa

$> sample_decode  av1 -hw -vaapi -i av1.ivf
...
[ERROR], sts=MFX_ERR_UNDEFINED_BEHAVIOR(-16), RunDecoding, Unexpected error!! at /home/xhh/graphics/ex/gstreamer/MediaSDK/samples/sample_decode/src/pipeline_decode.cpp:2034

[ERROR], sts=MFX_ERR_UNDEFINED_BEHAVIOR(-16), main, Pipeline.RunDecoding failed at /home/xhh/graphics/ex/gstreamer/MediaSDK/samples/sample_decode/src/sample_decode.cpp:784

**Comment by wangyan-intel** [comment]
Sure. We will check it.

**Comment by dmitryermilov** [comment]
@wangyan-intel , @xhaihao , was it fixed?

**Comment by wangyan-intel** [comment]
@dmitryermilov it seems R2R issue. We are working on it.

**Comment by dmitryermilov** [comment]
Thanks!

**Comment by xhaihao** [comment]
Any update on this issue? Thanks!

**Comment by xhaihao** [comment]
@dmitryermilov @wangyan-intel Any update for this issue?

**Comment by wangyan-intel** [comment]
@weizhu-intel  will submit patch for this soon.

**Comment by weizhu-intel** [comment]
Haihao,  we have internal  fix for it now, will cherry-pick to opensource ASAP.

**Comment by xhaihao** [comment]
@wangyan-intel @weizhu-intel Thanks for the update.

**Comment by weizhu-intel** [comment]
@xhaihao  You can cherry pick this PR(https://github.com/Intel-Media-SDK/MediaSDK/pull/2486) to have a try on local.

**Comment by xhaihao** [comment]
@weizhu-intel it works well after applying #2486

**Comment by wangyan-intel** [comment]
#2486 hase been merged. Close this issue based on @xhaihao's comments.
