### ISSUE TITLE
mfx init crash

### ISSUE THREAD

**Issue by CaseyGuanSun** [Intel-Media-SDK/MediaSDK#2249]
I encount a Intel MFX init Decoder crash:
STACK_TEXT:  
WARNING: Stack unwind information not available. Following frames may be wrong.
3334e44c 77bd8610 377addb0 78929610 3fcd59a0 ntdll+0xc6b18
3334e46c 789239bc 377addb0 3334e494 78c5b090 ntdll+0x58610
3334e478 78c5b090 377addb0 2f98622a 3334e550 igd9dxva32+0x339bc
3334e494 78bfce68 3fcd59a0 78bfcaf0 3fb53498 igd9dxva32+0x36b090
3334e4d8 7895a0ae 3334e4f4 2f9863e2 78eb9514 igd9dxva32+0x30ce68
3334e55c 7891def0 250ab5d0 3334e5c8 3fcfbf84 igd9dxva32+0x6a0ae
3334e594 69946150 3785bec0 3334e5c8 3334e618 igd9dxva32+0x2def0
3334e5ac 6985f09f 3e388040 3334e5c8 37584e40 d3d9+0x156150
3334e600 6985ec81 3334e618 0000000f 697f2aa8 d3d9+0x6f09f
3334e63c 679c563c 2a9426c0 3fcfbf84 3fcfbff8 d3d9+0x6ec81
3334e770 679c465f 08e72ca0 3fcfbf84 3fcfbff8 dxva2+0x563c
3334e7a8 7ba2615a 08e72cac 3fcfbf84 3fcfbff8 dxva2+0x465f
3334e7ec 7b9e218f 3334e830 67fd6584 2a9c9eec libmfxhw32+0x29615a
3334e954 7b9e1b13 2a9c9d20 0000000f 300f7bf0 libmfxhw32+0x25218f
3334ea04 7bac62f8 2a9c9d20 3334eb54 2a9c9eec libmfxhw32+0x251b13
3334ebc0 7b9e4b86 37546a0c 67fd6098 37546a0c libmfxhw32+0x3362f8
3334ec48 5314dea1 1878db34 37546a0c 37546808 libmfxhw32+0x254b86
3334ec5c 52ef14de 1d2e4818 37546a0c 3334f608 libspeechSpilVoip_win!MFXVideoDECODE_Init+0x21
3334ec6c 52ef36a5 37546a0c 36e4f0a0 37546880 libspeechSpilVoip_win!MFXVideoDECODE::Init+0xe [o:\baidu\speech-spil-arch\comm-sdk\source\third_party\intelmediasdk\include\mfxvideo++.h @ 116]

Is it my issue about it ?

**Comment by eero-t** [comment]
Those are rather huge offsets to the function starts, so I doubt the function names are correct.  You need to get backtrace with proper symbol information.

Does MFX / media-driver output any warnings?

**Comment by CaseyGuanSun** [comment]
> correct

how to get the MFX / media-drier output warnings?

**Comment by eero-t** [comment]
> how to get the MFX / media-drier output warnings?

I'm not sure about Windows, but on Linux you would just run it on console.

**Comment by daleksan** [comment]
Hi @CaseyGuanSun may i ask you to share more information about this crash? 
version of media stack, HW you used and traces

**Comment by asmirno1** [comment]
Closing this due to aging and no answer from reporter.
@CaseyGuanSun , please reopen and provide details if still actual.
