### ISSUE TITLE
[regression]  AV1 decoding is broken since commit 12ed7ae

### ISSUE THREAD

**Issue by xhaihao** [Intel-Media-SDK/MediaSDK#2264]
I get  MFX_ERR_UNSUPPORTED since commit 12ed7ae

$> sample_decode av1 -i av1.ivf

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), AllocFrames, m_pmfxDEC->Query failed at /home/xhh/graphics/ex/gstreamer/MediaSDK/samples/sample_decode/src/pipeline_decode.cpp:1138

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), Init, AllocFrames failed at /home/xhh/graphics/ex/gstreamer/MediaSDK/samples/sample_decode/src/pipeline_decode.cpp:557

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), main, Pipeline.Init failed at /home/xhh/graphics/ex/gstreamer/MediaSDK/samples/sample_decode/src/sample_decode.cpp:745

**Comment by wangyan-intel** [comment]
I will check it. Sorry for this.

**Comment by wangyan42164** [comment]
This is because MFX_VPX_Utility::Query() doesn't copy CodecLevel. For VP8/9, no codec level. For AV1, we need change the logic. I will submit PR for fixing it.

**Comment by dmitryermilov** [comment]
@aobolensk , can you please help to draft a simple AV1 test in Ted?

**Comment by aobolensk** [comment]
@dmitryermilov yes, I can do it
