### ISSUE TITLE
sample_decode failed when decoding hevc clips.

### ISSUE THREAD

**Issue by lizhong1008** [Intel-Media-SDK/MediaSDK#23]
H264 decoder can work well, but hevc failed seems it can't find the plugin.

To reproduce: sample_decode h265 -i ~/fate-suite/hevc-conformance/MVEDGE_A_qualcomm_3.bit -o test.yuv

plugin_loader.h :168 [ERROR] Failed to load plugin from GUID, sts=-9: { 0x33, 0xa6, 0x1c, 0x0b, 0x4c, 0x27, 0x45, 0x4c, 0xa8, 0xd8, 0x5d, 0xde, 0x75, 0x7c, 0x6f, 0x8e } (Intel (R) Media SDK HW plugin for HEVC DECODE)
Default plugin cannot be loaded (possibly you have to define plugin explicitly)

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), Init, Plugin load failed at /root/lizhong/opensource/MediaSDK/samples/sample_decode/src/pipeline_decode.cpp:379

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), main, Pipeline.Init failed at /root/lizhong/opensource/MediaSDK/samples/sample_decode/src/sample_decode.cpp:661

**Comment by lizhong1008** [comment]
After check the source code: "api/opensource/mfx_dispatch/src/mfx_plugin_hive_linux.cpp",
plugins.cfg file path is set to hard code: "const char rootPluginPath[] = "/opt/intel/mediasdk/plugins/plugins.cfg". Could it to be configurable as CMAKE_INSTALL_PREFIX?

**Comment by eero-t** [comment]
This seems a fixed issue, could it be closed?
