### ISSUE TITLE
sample_decode jpeg fail with gpu hang 

### ISSUE THREAD

**Issue by DayDaySee** [Intel-Media-SDK/MediaSDK#2311]
Platform: Centos 7.4  Kernel 5.2.4 with E3-1515M
decode gpu-hang.jpg using sample_decode, the program will get stuck for a while and then return normally, but the decoded image is invalid,  while dmesg show "i915 0000:00:02.0: Resetting vcs0 for hang on vcs0"

The attachment is gpu-hang.jpg，gpu hang  can be reproduced with decoding this image.

#dmesg -T
[Tue Aug 25 16:17:48 2020] i915 0000:00:02.0: Resetting vcs0 for hang on vcs0
[Tue Aug 25 16:25:29 2020] i915 0000:00:02.0: Resetting vcs0 for hang on vcs0

#./sample_decode jpeg -i gpu-hang.jpg -o out.yuv
pretending that aspect ratio is 1:1
libva info: VA-API version 1.4.1
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /usr/lib/dri//iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_4
libva info: va_openDriver() returns 0
Decoding Sample Version 8.3.26.

Input video	JPEG
Output format	NV12
Input:
  Resolution	352x288
  Crop X,Y,W,H	0,0,352,288
Output:
  Resolution	352x288
Frame rate	30.00
Memory type		system
MediaSDK impl		hw
MediaSDK version	1.29

Decoding started
Frame number:    1, fps: 0.128, fread_fps: 0.000, fwrite_fps: 2597.403
Decoding finished

 
[gpu-hang.tar.gz](https://github.com/Intel-Media-SDK/MediaSDK/files/5122399/gpu-hang.tar.gz)

**Comment by wangyan-intel** [comment]
@chuanli1 Could you please take a look? Thanks.

**Comment by chuanli1** [comment]
sure,I could.

**Comment by chuanli1** [comment]
The case can reproduce,use JPEGsnoop to check that the Jpeg is normal format,the next step is to use MDA and sample_decode to decode separately and compare command buffer.

**Comment by chuanli1** [comment]
The case can reproduce,use JPEGsnoop to check that the Jpeg is normal format,the next step is to use sample_decode to decode and examine command buffer.

**Comment by chuanli1** [comment]
The clip number of DC huffman codes of length is 1~13,the length supported by hw is 1~12,I will update the code to make msdk return Huffman table DC entries number is out of HW limitation，avoid gpu hang issue.

**Comment by chuanli1** [comment]
The clip number of DC huffman codes of length is 1 to13,the length supported by hw is 1to12,I will update the code to make msdk return Huffman table DC entries number is out of HW limitation，avoid gpu hang issue.

**Comment by chuanli1** [comment]
will have modified and returned hw can't support, gpu hang issue don't appear.

**Comment by wangyan-intel** [comment]
@DayDaySee Could you please confirm it? Current media-driver/MSDK will return error information. It is HW limitation. Could we close this issue?

**Comment by wangyan-intel** [comment]
This is HW limitation. Close it.
