### ISSUE TITLE
How to build 32bit msdk lib on 64 Ubuntu 20.4

### ISSUE THREAD

**Issue by LukeZheZhu** [Intel-Media-SDK/MediaSDK#2313]
I export CFLAGS=-m32 and export CXXFLAGS=-m32, then cmake and cmake log building architecture changes to 32-bit
When 'make', I get bunches of not been declared error.
I wonder is there any way to build a 32bit MSDK lib？

Thanks

**Comment by dmitryermilov** [comment]
Communicated via email.  @LukeZheZhu , please close the issue if the email answer was fine for you.
