### ISSUE TITLE
hevc temporal

### ISSUE THREAD

**Issue by lius-xjtu** [Intel-Media-SDK/MediaSDK#2316]
does the hevc encoder support temporal layer? and how to use it?

**Comment by dmitryermilov** [comment]
Hi @lius-xjtu , 

Yes it's supported. Please see [mfxExtAvcTemporalLayers](https://github.com/Intel-Media-SDK/MediaSDK/blob/master/doc/mediasdk-man.md#mfxextavctemporallayers). 'Attach' this extBuffer to encoder initialization mfxVideoParams.

**Comment by lius-xjtu** [comment]
the mfxExtAvcTemporalLayer structure configures the h265.  also support h265? I use sample_encode and the command is h265 -i test. yuv -w 1920 -h 1080 -f 30 -AvcTemporalLayers "0 1 2 4 0 0 0 0" -o out. h265 but I get the error sts=MFX_ERR_NULL_PTR(-2) , AllocFrames, Query (for encoder) failed at SRC/pipline_encode.cpp:947

**Comment by lius-xjtu** [comment]
@dmitryermilov I test it on windows,is this interface not support on wondows?

**Comment by dmitryermilov** [comment]
It's OS agnostic. Can you please debug inside encoder and say which line of code returns the error?

**Comment by lius-xjtu** [comment]
@dmitryermilov I try -AvcTemporalLayers "1 2 0 0 0 0 0 0"and is ok. but i try AvcTemporalLayers "1 2 4 0 0 0 0 0" and failed. is there any restriction on this paramenter for hevc_hw?

**Comment by dmitryermilov** [comment]
@eistarov , could you answer?

**Comment by lius-xjtu** [comment]
@dmitryermilov by the way,why sample_encode. exe not support sao in hevc_hw? the encode chroma is not good and have a lot blocking artifact

**Comment by dmitryermilov** [comment]
> @dmitryermilov I try -AvcTemporalLayers "1 2 0 0 0 0 0 0"and is ok. but i try AvcTemporalLayers "1 2 4 0 0 0 0 0" and failed. is there any restriction on this paramenter for hevc_hw?

Hi @lius-xjtu , 
We tried to pass "0 1 2 4 0 0 0 0" values to mfxExtAvcTemporalLayers and it works fine in HEVC. Can you please check that you're passing the same?

**Comment by dmitryermilov** [comment]
> @dmitryermilov by the way,why sample_encode. exe not support sao in hevc_hw? the encode chroma is not good and have a lot blocking artifact

sample_encode is just a sample app. It hardly can support all the parameters from API.

**Comment by lius-xjtu** [comment]
> > @dmitryermilov I try -AvcTemporalLayers "1 2 0 0 0 0 0 0"and is ok. but i try AvcTemporalLayers "1 2 4 0 0 0 0 0" and failed. is there any restriction on this paramenter for hevc_hw?
> 
> Hi @lius-xjtu ,
> We tried to pass "0 1 2 4 0 0 0 0" values to mfxExtAvcTemporalLayers and it works fine in HEVC. Can you please check that you're passing the same?

@dmitryermilov yes i check the value "0 1 2 4 0 0 0 0" will failed, and my cpu is intel i7-8700k. why set the first num of mfxExtAvcTemporalLayers to 0?

**Comment by dmitryermilov** [comment]
Hi @lius-xjtu , 
I misprinted. I meant to pass 0 1 2 4 0 0 0 0 0 where first 0 is BaseLayerPID. Sorry for confusion. 
Please use  AvcTemporalLayers "1 2 4 0 0 0 0 0". How did it fail on your side? Error or ? Please send full command line, log and encoded stream(if it was generated).

**Comment by dmitryermilov** [comment]
BTW, @eistarov , I noticed that seems we don't write correct layer info in SEI. Please see how analyzer complains: 
![image](https://user-images.githubusercontent.com/19732160/92929165-ca796f00-f448-11ea-8a4e-8dcab465515a.png).

Cmd line was very simple:
./sample_encode h265 -i <stream> -w - h -b 2000 -AvcTemporalLayers "1 2 4 0 0 0 0 0"
