### ISSUE TITLE
sample_vpp.exe -rotate do not work on Media SDK 2020 R1 windows version

### ISSUE THREAD

**Issue by zhaoye1** [Intel-Media-SDK/MediaSDK#2321]
test command:
sample_vpp.exe -sw 1920 -sh 1080 -scc nv12 -dw 1080 -dh 1920 -dcc nv12  -i 1nv12.data -o 1nv12Out.data -rotate 90
input data:
![image](https://user-images.githubusercontent.com/22929741/91373362-c9d9b980-e848-11ea-82ec-2f0d042943aa.png)
out put data:
![image](https://user-images.githubusercontent.com/22929741/91373405-e4ac2e00-e848-11ea-9e4e-95f90645f46f.png)

**Comment by FurongZhang** [comment]
@zhaoye1 , as we talked about, I am following up with it.

**Comment by FurongZhang** [comment]
We have reproduced it and rooted cause it. Will provide the patch once code is ready..

**Comment by FurongZhang** [comment]
Please use sample_vpp.exe -sw 1920 -sh 1080 -scc nv12 -dw 1080 -dh 1920 -dcc nv12 -i 1nv12.data -o 1nv12Out.data -rotate 90 -d3d11. We checked DX11 command, it is working.

**Comment by FurongZhang** [comment]
https://docs.microsoft.com/en-us/windows/win32/api/dxva2api/ns-dxva2api-dxva2_videoprocessbltparams does not have rotation parameters. Hence, to perform rotation, recommend to use DX11.

**Comment by FurongZhang** [comment]
It’s worked on Media SDK 2020.R1 with DX11 FLAG @zhaoye1 . Please consider to close this issue.

**Comment by FurongZhang** [comment]
Talked to @zhaoye1 , we can close this issue. @zhaoye1  will communicate with the customers if the customers would like to upgrade to MSDK 2020 R1.
