### ISSUE TITLE
[ffmpeg-qsv][gst-msdk][regression]the MediaSDK commit:e126273431b470a738e4c26896b829a6801cb455 will cause regression.

### ISSUE THREAD

**Issue by yefengxx** [Intel-Media-SDK/MediaSDK#2325]
Our CI shows that the MediaSDK commit :  e126273431b470a738e4c26896b829a6801cb455 will cause  **ffmpeg-qsv/gst-msdk avc decode** regression. 
For gst-msdk:
MediaSDK-**e126273431b47**
gst-msdk.decode.avc         total:310      pass:305     **fail:5**
MediaSDK-**995f036b7ab00e**
gst-msdk.decode.avc         total:310      pass:307     **fail:3** 
We hope to get your help.
thanks~

**Comment by dmitryermilov** [comment]
@guowillyy , please prioritize .

**Comment by guowillyy** [comment]
sure, will look into it.

**Comment by guowillyy** [comment]
@yefengxx, may I know where can I get the failed test case and how to repro the issue?

**Comment by uartie** [comment]
@guowillyy here is the mediainfo details for one failing case:

```
Video
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L5.2
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 4 frames
Duration                                 : 834 ms
Width                                    : 3 840 pixels
Height                                   : 3 840 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Variable
Frame rate                               : 59.940 (59940/1000) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Writing library                          : x264 core 148 r2643 5c65704
Encoding settings                        : cabac=1 / ref=3 / deblock=1:0:0 / analyse=0x3:0x113 / me=hex / subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=6 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=25 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=crf / mbtree=1 / crf=23.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00
```

Notice that it has 4 refs @ L5.2 (same as other failing case).  This causes an infinite loop at 
https://github.com/Intel-Media-SDK/MediaSDK/blob/1334f76f9256eab85c3e18b1878ad00082fb8028/_studio/shared/umc/codec/h264_dec/include/umc_h264_task_supplier.h#L683 
because it will never satisfy the loop terminator condition at 
https://github.com/Intel-Media-SDK/MediaSDK/blob/1334f76f9256eab85c3e18b1878ad00082fb8028/_studio/shared/umc/codec/h264_dec/include/umc_h264_task_supplier.h#L753
due to your change at
https://github.com/Intel-Media-SDK/MediaSDK/commit/e126273431b470a738e4c26896b829a6801cb455#diff-205bc80d363db7407fbe2ddd4136cb43L786-R803

**Comment by uartie** [comment]
@yefengxx can you try #2327 patch?

**Comment by yefengxx** [comment]
@uartie  I tested with[ #2327](https://github.com/Intel-Media-SDK/MediaSDK/pull/2327) patch and the results is as follows:
gst-msdk.decode.avc total:310 pass:307 fail:3
**This is the expected result**, indicating that the issue has been fixed by this patch.
