### ISSUE TITLE
Cannot compile SDK with Intel Runtime

### ISSUE THREAD

**Issue by Odianosen25** [Intel-Media-SDK/MediaSDK#2328]
Hello,

I am trying to compile the SDK with Intel runtime and I am not able to do it. The compile works great, but once I add the intel runtime, it doesn't compile. Below is my environment

**OS:** Alpine 3:12
**Environment:** DOCKER

**DOCKER File:**

```
################################################################################
##  Dockerfile to build Intel® Media SDK                                      ##
################################################################################
FROM alpine:3.12 as base

ENV http_proxy=$http_proxy
ENV https_proxy=$https_proxy

FROM base as build

RUN apk add --update --no-cache \
  autoconf \
  automake \
  bash \
  cmake \
  gcc \
  g++ \
  git \
  libdrm-dev \
  libpciaccess-dev \
  libtool \
  make \
  pkgconfig
  

ARG WORKSPACE=/opt/intel/git

RUN mkdir -p $WORKSPACE
WORKDIR $WORKSPACE

RUN git clone https://github.com/intel/libva.git
RUN git clone https://github.com/intel/libva-utils.git
RUN git clone https://github.com/intel/gmmlib.git
RUN git clone https://github.com/intel/media-driver.git
RUN git clone https://github.com/Intel-Media-SDK/MediaSDK.git

ENV PREFIX=/usr
ENV LIBDIR=/usr/lib
ENV PKG_CONFIG_PATH=$LIBDIR/pkgconfig

RUN cd $WORKSPACE/libva \
  && ./autogen.sh --prefix=$PREFIX --libdir=$LIBDIR \
  && make -j`nproc` && make install && make install DESTDIR=/opt/intel/install

RUN cd $WORKSPACE/libva-utils \
  && ./autogen.sh --prefix=$PREFIX --libdir=$LIBDIR \
  && make -j`nproc` && make install && make install DESTDIR=/opt/intel/install

RUN cd $WORKSPACE/gmmlib && mkdir build && cd build \
  && cmake -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_INSTALL_LIBDIR=$LIBDIR .. \
  && make -j`nproc` && make install && make install DESTDIR=/opt/intel/install

RUN cd $WORKSPACE/media-driver && mkdir build && cd build \
  && cmake -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_INSTALL_LIBDIR=$LIBDIR .. \
  && make -j`nproc` && make install && make install DESTDIR=/opt/intel/install
  
RUN apk add --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing \
            --update --no-cache intel-compute-runtime intel-compute-runtime-dev \
            intel-graphics-compiler intel-graphics-compiler-dev
       
RUN apk add --repository http://dl-cdn.alpinelinux.org/alpine/edge/community \
            --update --no-cache opencl-headers opencl-icd-loader opencl-icd-loader-dev

RUN cd $WORKSPACE/MediaSDK && mkdir build && cd build \
  && cmake -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_INSTALL_LIBDIR=$LIBDIR -DBUILD_SAMPLES=OFF .. \
  && make -j`nproc` && make install && make install DESTDIR=/opt/intel/install

FROM base as runtime

ARG WORKSPACE=/opt/intel/git
COPY --from=build /opt/intel/install/usr /usr

RUN apk add --no-cache \
  libdrm \
  libpciaccess \
  libstdc++

ENV LIBVA_DRIVER_NAME=iHD
```

**Errors**
```
[  8%] Building CXX object _studio/shared/umc/CMakeFiles/umc_va_hw.dir/io/umc_va/src/umc_va_video_processing.cpp.o
/opt/intel/git/MediaSDK/_studio/shared/umc/io/umc_va/src/umc_va_linux.cpp: In function 'VAProfile get_next_va_profile(uint32_t, uint32_t)':
/opt/intel/git/MediaSDK/_studio/shared/umc/io/umc_va/src/umc_va_linux.cpp:248:39: error: 'VAProfileHEVCSccMain444_10' was not declared in this scope; did you mean 'VAProfileHEVCSccMain444'?
  248 |         if (profile < 1) va_profile = VAProfileHEVCSccMain444_10;
      |                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                       VAProfileHEVCSccMain444
[  8%] Building C object contrib/ipp/CMakeFiles/ipp_sse4.dir/src/pjdecdct1.c.o
[  8%] Building C object contrib/ipp/CMakeFiles/ipp_sse4.dir/src/pjdecpred.c.o
make[2]: *** [_studio/shared/umc/CMakeFiles/umc_va_hw.dir/build.make:109: _studio/shared/umc/CMakeFiles/umc_va_hw.dir/io/umc_va/src/umc_va_linux.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[  8%] Building CXX object api/mfx_dispatch/linux/CMakeFiles/mfx.dir/mfxparser.cpp.o
....

[ 10%] Building C object contrib/ipp/CMakeFiles/ipp_sse4.dir/src/psshift.c.o
make[1]: *** [CMakeFiles/Makefile2:1747: _studio/shared/umc/CMakeFiles/umc_va_hw.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
...

[ 21%] Building ASM object contrib/ipp/CMakeFiles/ipp_sse4.dir/src/asm_intel64/pvcvc1rangemapm7as.s.o
[ 21%] Built target ipp_sse4
make: *** [Makefile:150: all] Error 2
The command '/bin/sh -c cd $WORKSPACE/MediaSDK && mkdir build && cd build   && cmake -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_INSTALL_LIBDIR=$LIBDIR -DBUILD_SAMPLES=OFF ..   && make -j`nproc` && make install && make install DESTDIR=/opt/intel
```

@dvrogozh will be nice if you could assist again please :)

Thanks and kind regards

**Comment by dmitryermilov** [comment]
Hi @Odianosen25 ,
an obvious answer is it can' find VAProfileHEVCSccMain444_10 which was checked in a few month ago by https://github.com/intel/libva/pull/390 . Could you double check that during compilation the right va.h (which you dowdloaded from https://github.com/intel/libva.git) is included ?

**Comment by Odianosen25** [comment]
@dmitryermilov,

Thanks for the quick response. Well I can confirm it sees it, as without adding intel runtime, the build works great and no issues. But once I decide to install the runtime, it then breaks. 

So it seems for some reasons,  the installation breaks it and I have no clue why. If I go based on your statement, it seems the installation of the runtime affects libva, as I had noticed that though compiling libva gives me >2.0. After installation of runtime, it seems to give me 1.7.0 for some reasons.

That was part of the reasons I moved the installation of the runtime, to after the others had been built. As if placed above them, it also prevents the build and installation of the media driver for example. As ti complains it needs >= 1.8.0 for libva, but libva at that point is at 1.7.0.

Hope this helps.

Regards

**Comment by onabiull** [comment]
It looks libva headers are taken either from pre-installed libva-dev package or from some dependency brought by compute runtime packages. Media SDK rely on a standard pkg-config to locate libva headers and binaries, I'd suggest to try figure out what `pkg-config --cflags --libs libva` would report before and after compute runtime installation.

**Comment by Odianosen25** [comment]
@onabiull,

Thanks for the response, I tried to run `pkg-config --cflags --libs libva` within console but give me just `-lva`. Is that right? As seems I am missing something.

Regards

**Comment by onabiull** [comment]
At least this means that we don't get any rogue -I pointing to the wrong headers. This essentially limits us to the /usr/include/va for LibVA headers. Could you please check from which package /usr/include/va/va.h came?

**Comment by Odianosen25** [comment]
Hello @onabiull,

I believe its `libva-dev` as can  be seen from here https://pkgs.alpinelinux.org/contents?branch=v3.12&name=libva-dev&arch=x86_64&repo=main

Regards

**Comment by dvrogozh** [comment]
Here is what's going on. You've installed intel-compute-runtime-dev package before building mediasdk. And this package brought in libva-dev package as a dependency (see https://pkgs.alpinelinux.org/package/edge/testing/x86_64/intel-compute-runtime-dev) which effectively overrode libva version you just built. Hence you got compilation error from mediasdk.

Actually, some mediasdk samples depend on opencl, but they don't depend on the opencl runtime to be compliled. So, installing opencl runtime before mediasdk does not actually make sense, you just need to install opencl dev files. So, first of all move intel opencl runtime installation below mediasdk build. Secondly, since you rebuild media stack from sources, you need to make sure that you first install opencl runtime (and bring libva-dev package as dependency) and then copy media stack you just build overriding libva-dev you got from opencl runtime dependencies. I.e. the following should work (I did not check):

```
################################################################################
##  Dockerfile to build Intel® Media SDK                                      ##
################################################################################
FROM alpine:3.12 as base

ENV http_proxy=$http_proxy
ENV https_proxy=$https_proxy

FROM base as build

RUN apk add --update --no-cache \
  autoconf \
  automake \
  bash \
  cmake \
  gcc \
  g++ \
  git \
  libdrm-dev \
  libpciaccess-dev \
  libtool \
  make \
  pkgconfig
  

ARG WORKSPACE=/opt/intel/git

RUN mkdir -p $WORKSPACE
WORKDIR $WORKSPACE

RUN git clone https://github.com/intel/libva.git
RUN git clone https://github.com/intel/libva-utils.git
RUN git clone https://github.com/intel/gmmlib.git
RUN git clone https://github.com/intel/media-driver.git
RUN git clone https://github.com/Intel-Media-SDK/MediaSDK.git

ENV PREFIX=/usr
ENV LIBDIR=/usr/lib
ENV PKG_CONFIG_PATH=$LIBDIR/pkgconfig

RUN cd $WORKSPACE/libva \
  && ./autogen.sh --prefix=$PREFIX --libdir=$LIBDIR \
  && make -j`nproc` && make install && make install DESTDIR=/opt/intel/install

RUN cd $WORKSPACE/libva-utils \
  && ./autogen.sh --prefix=$PREFIX --libdir=$LIBDIR \
  && make -j`nproc` && make install && make install DESTDIR=/opt/intel/install

RUN cd $WORKSPACE/gmmlib && mkdir build && cd build \
  && cmake -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_INSTALL_LIBDIR=$LIBDIR .. \
  && make -j`nproc` && make install && make install DESTDIR=/opt/intel/install

RUN cd $WORKSPACE/media-driver && mkdir build && cd build \
  && cmake -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_INSTALL_LIBDIR=$LIBDIR .. \
  && make -j`nproc` && make install && make install DESTDIR=/opt/intel/install
  
RUN apk add --repository http://dl-cdn.alpinelinux.org/alpine/edge/community \
            --update --no-cache opencl-headers opencl-icd-loader opencl-icd-loader-dev

RUN cd $WORKSPACE/MediaSDK && mkdir build && cd build \
  && cmake -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_INSTALL_LIBDIR=$LIBDIR -DBUILD_SAMPLES=OFF .. \
  && make -j`nproc` && make install && make install DESTDIR=/opt/intel/install

FROM base as runtime

RUN apk add --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing \
            --update --no-cache intel-compute-runtime opencl-icd-loader

ARG WORKSPACE=/opt/intel/git
COPY --from=build /opt/intel/install/usr /usr

RUN apk add --no-cache \
  libdrm \
  libpciaccess \
  libstdc++

ENV LIBVA_DRIVER_NAME=iHD
```

**Comment by Odianosen25** [comment]
@dvrogozh,

Thanks for the update. The issue I have realised earlier was that without installing the runtime first, it leads to MSDK not compiling OpenCL. Installing just the header which I had tried before and now, still doesn't compile it with MSDK.

Regards

**Comment by dvrogozh** [comment]
Ah, ok. Seems my mistake since I was describing my expectations how mediasdk build should work. Likely this happens because of this line:
https://github.com/Intel-Media-SDK/MediaSDK/blob/f46e3f8f87838b88ff89862335c1f5287a9966fd/builder/FindOpenCL.cmake#L28
where we seems to require intel opencl runtime. Which (as I noted in prev. comment) does not make sense - build does not depend on it.

**Comment by Odianosen25** [comment]
Yes build doesn't depend on it, but it helps with some extra opencl based plugin build. if the runtime doesn't forcefully install libva, i think it will be fine. I get into the same trouble, when trying to compile opencv with opencv as it keeps asking for `CL/va_ext.h`.

Will keep trying anyway.

Regards

**Comment by Odianosen25** [comment]
Thanks everyone, as my issue been fixed. There was a recent re-compile of the runtime and I moved the installation of the runtime to the beginning of the build.

SO these two things must have fixed and all good now.

Kind regards
