### ISSUE TITLE
I messed up in the publishing of our npm package, so have to bump to a new release to publish once again. Say hello to v4.2.1!

### ISSUE THREAD

**Issue by Melearn867** [Intel-Media-SDK/MediaSDK#2343]
I messed up in the publishing of our npm package, so have to bump to a new release to publish once again. Say hello to v4.2.1!

__Originally posted by @mdo in https://github.com/twbs/bootstrap/pull/27892__

**Comment by onabiull** [comment]
Looks some automation gone rogue. I'm going to ban this account for a while.
