### ISSUE TITLE
build fail with gcc10

### ISSUE THREAD

**Issue by tjaalton** [Intel-Media-SDK/MediaSDK#2369]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=957365

tutorials/common/common_vaapi.cpp: In function 'int open_intel_adapter()':
tutorials/common/common_vaapi.cpp:100:10: error: 'string' is not a member of 'std'
  100 |     std::string adapterPath = DRI_PATH;
      |          ^~~~~~
tutorials/common/common_vaapi.cpp:27:1: note: 'std::string' is defined in header '<string>'; did you forget to '#include <string>'?
   26 | #include "common_vaapi.h"
  +++ |+#include <string>
   27 | 
[  9%] Building C object contrib/ipp/CMakeFiles/ipp.dir/src/pccyuvmsw7.c.o
tutorials/common/common_vaapi.cpp:101:5: error: 'adapterPath' was not declared in this scope
  101 |     adapterPath += DRI_NODE_RENDER;
      |     ^~~~~~~~~~~
cd build/contrib/ipp && /usr/bin/cc  -Iapi/mediasdk_structures -Iapi/include -Ibuild -I/contrib/ipp/include -I_studio/shared/include -I_studio/shared/umc/core/umc/include  -DMFX_TRACE_ENABLE_STAT -DMFX_TRACE_ENABLE_TEXTLOG -msse4.2 -m64 -g -g -O2 -fdebug-prefix-map=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -pipe -fPIC -Wall -Wformat -Wformat-security -Wno-deprecated-declarations -Wno-unknown-pragmas -Wno-unused  -DUNIX -D__USE_LARGEFILE64 -D_FILE_OFFSET_BITS=64 -DLINUX -DLINUX32 -DLINUX64 -DMSDK_BUILD=\"\"  -DMFX_BUILD_INFO="\"Linux-4.19.0-6-cloud-amd64 4.19.0-6-cloud-amd64 | GNU 10.0.1 | glibc 2.29"\" -DMFX_API_VERSION=\"1.31\" -DMFX_GIT_COMMIT=\"\" -D_Y8 -D_ARCH_EM64T      -o CMakeFiles/ipp.dir/src/pccyuvmsw7.c.o   -c contrib/ipp/src/pccyuvmsw7.c
tutorials/common/common_vaapi.cpp:107:14: error: 'string' is not a member of 'std'
  107 |         std::string curAdapterPath = adapterPath + std::to_string(nodeIndex + i);
      |              ^~~~~~
tutorials/common/common_vaapi.cpp:107:14: note: 'std::string' is defined in header '<string>'; did you forget to '#include <string>'?
tutorials/common/common_vaapi.cpp:109:23: error: 'curAdapterPath' was not declared in this scope
  109 |         int fd = open(curAdapterPath.c_str(), O_RDWR);
      |                       ^~~~~~~~~~~~~~
make[3]: *** [tutorials/common/CMakeFiles/tutorials_common.dir/build.make:105: tutorials/common/CMakeFiles/tutorials_common.dir/common_vaapi.cpp.o] Error 1
make[3]: Leaving directory 'build'
make[2]: *** [CMakeFiles/Makefile2:1929: tutorials/common/CMakeFiles/tutorials_common.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....

**Comment by dvrogozh** [comment]
@tjaalton : original issue on debian side is reported against 19.4.0 version. Can you, please, clarify:
1. Do you see the issue on the latest master/release?
2. Are you looking for the fix for 19.4.x release series or you need a fix in latest master/release?
```
Package: src:intel-mediasdk
Version: 19.4.0-1
Severity: normal
Tags: sid bullseye
User: debian-gcc@lists.debian.org
Usertags: ftbfs-gcc-10
```

**Comment by tjaalton** [comment]
20.2 still fails, and the file hasn't changed in master

getting a fix in master is good enough, I'll just patch the package until there's a new release

**Comment by dvrogozh** [comment]
@eponomar : I don't get it why this issue was not caught by CI? we have gcc-10 compiler configuration... Do we need to update to latest gcc-10.2 (from current gcc-10.0) to see it?

**Comment by dvrogozh** [comment]
Actually this issue means that `#include <string>` is missed, but it was already added in this commit:
https://github.com/Intel-Media-SDK/MediaSDK/commit/c7d40371eb0c2042261fe1f91a364f69a1457235

which should be available in this releases:
```
git tag --contains c7d40371eb0c2042261fe1f91a364f69a1457235
intel-mediasdk-20.1.0
intel-mediasdk-20.1.1
intel-mediasdk-20.1.pre1
intel-mediasdk-20.1.pre2
intel-mediasdk-20.1.pre3
intel-mediasdk-20.2.0
intel-mediasdk-20.2.1
intel-mediasdk-20.2.pre1
intel-mediasdk-20.2.pre2
intel-mediasdk-20.2.pre3
intel-mediasdk-20.3.pre1
intel-mediasdk-20.3.pre2
intel-mediasdk-20.3.pre3
intel-mediasdk-20.3.pre4
intel-mediasdk-20.3.pre5
intel-mediasdk-20.3.pre6
```

@tjaalton : I believe that master branch and releases >=20.1.0 has this issue fixed. Can you, please, double check that you updated a code base and really build one of the later releases?

**Comment by tjaalton** [comment]
hum, ok.. yes, looks like my testing local testing was outdated, it does built with 20.2.0, but the tests segfault but that's something else then

**Comment by dvrogozh** [comment]
> but the tests segfault but that's something else then

You gave us heads up on that some time ago, but we failed to reproduce:(. If these failures will persist, please, open another issue and attach detailed logs. Rough logs and output from strace might be needed. gdb results appreciated.

**Comment by tjaalton** [comment]
so I did.. I'll test a CI build on salsa.debian.org first, to verify it's not something on the chroot/sbuild on my own system
