### ISSUE TITLE
Wrong adapter check in multiGPUs/connections HW setup

### ISSUE THREAD

**Issue by maximd33** [Intel-Media-SDK/MediaSDK#2385]
In reference to implementation details:
https://github.com/Intel-Media-SDK/MediaSDK/blob/90993883519abd3d2955dc097e4f749602d30fe2/api/mfx_dispatch/windows/src/mfx_dispatcher.cpp#L480
especially `adapter_n - 1`

it can be wrong under conditions:  

- IA GPU is not connected to monitor 
- other IHV GPU has two monitors connected

 Adapters list for such HW setup:

> MFXQueryAdaptersNumber:651 VendorID:4318
MFXQueryAdaptersNumber:651 VendorID:4318
MFXQueryAdaptersNumber:651 VendorID:32902

Summary: MFXQueryAdapters() should return no error and correct list as mfxAdaptersInfo* adapters with such configuration.

**Comment by maximd33** [comment]
according to MSFT:

> Note  Do not mix the use of DXGI 1.0 (IDXGIFactory) and DXGI 1.1 (IDXGIFactory1) in an application. Use IDXGIFactory or IDXGIFactory1, but not both in an application.

from https://docs.microsoft.com/en-us/windows/win32/api/dxgi/nf-dxgi-createdxgifactory

MFX_Dispatcher and samples implementations advised to follow recommendation

**Comment by asmirno1** [comment]
Prepared repro scenario based on sample_decode to check behavior for QueryAdapterInfo function.
Figured out that inside QueryAdapterInfo, values for VendorID and DeviceID are always received from dxvaDevice.InitD3D9(adapter_n) call (not InitDXGI1).

One the most appropriate solutions for this is to make MFXQueryAdapter* functions DX11 only:
* Remove DX9 related code from these functions
* Add a special note into msdk-man that the result of these function corresponds only to DX11 adapters enumeration

Fix is merged: https://github.com/Intel-Media-SDK/MediaSDK/pull/2400
Additional doc change: https://github.com/Intel-Media-SDK/MediaSDK/pull/2407
