### ISSUE TITLE
VPP cropping doesn't work

### ISSUE THREAD

**Issue by HermanMolinder** [Intel-Media-SDK/MediaSDK#239]
Cropping falsely results in nothing at all or a resized frame, depending on settings.

I wish to perform a "pan and scan" to convert 16:9 aspect ratio to 4:3 aspect ratio, by cropping the left and right borders of the video frames. First I decode the video and then perform the VPP and output the raw frames on HDMI. I tried a few different settings explained in the examples below. Unfortunately none of them works as expected.

Example 1:
vpp_par.vpp.In.Width = 720
vpp_par.vpp.In.Height = 576
vpp_par.vpp.In.CropW = 540
vpp_par.vpp.In.CropX = 90
vpp_par.vpp.In.CropH = 576
vpp_par.vpp.In.CropY = 0

vpp_par.vpp.Out.Width = 720
vpp_par.vpp.Out.Height = 576
vpp_par.vpp.Out.CropW = 720
vpp_par.vpp.Out.CropX = 0
vpp_par.vpp.Out.CropH = 576
vpp_par.vpp.Out.CropY = 0

With these settings I would expect the input to be cropped and then resized, removing left and right borders but keeping the width and height (thus stretching the cropped picture to cover the complete output frame). However the input and output frames look identical.

Example 2:
vpp_par.vpp.In.Width = 720
vpp_par.vpp.In.Height = 576
vpp_par.vpp.In.CropW = 544
vpp_par.vpp.In.CropX = 88
vpp_par.vpp.In.CropH = 576
vpp_par.vpp.In.CropY = 0

vpp_par.vpp.Out.Width = 544
vpp_par.vpp.Out.Height = 576
vpp_par.vpp.Out.CropW = 544
vpp_par.vpp.Out.CropX = 0
vpp_par.vpp.Out.CropH = 576
vpp_par.vpp.Out.CropY = 0

With these settings I would expect the input to be cropped and copied to the output surface, which has a smaller width equal to the cropped width. However the output frame is just a resized version of the input frame. No cropping occurs.

The same problems are reported and discussed in the following thread:
https://software.intel.com/en-us/forums/intel-media-sdk/topic/501508

And to clarify, I set these settings before query and init of decoder and VPP.

Additional info:
-Video memory is used through vaapi.
-Tested on Apollolake.
-Open source msdk from following commits:
libva: b3be72a5a110880f70626d7c3bed953cdde124b2
media-driver: 1c2b0615d749c45c07f9aee6586774816989c5b3
gmmlib: 247673f8e487d62b818876dc1905036e477986c1
MediaSDK: 7c2b069

**Comment by dmitryermilov** [comment]
Hi @HermanMolinder ,

According to MSDK manual cropping settings in mfxVideoParam are ignored at VPP::Init(). Actual cropping settings are applied from mfxFrameSurface1::Info::CropX/CropY/CropW/CropH values at run-time. It's described at the Appendix A of the manual. So please check which cropping values VPP input and output surfaces have. I hope this info is what you were looking for. If not, please let me know and continue discussion.

**Comment by HermanMolinder** [comment]
Hi @dmitryermilov ,

Thank you! I had missed that part and will try to set these parameters during runtime. I'll get back to you with the results.

**Comment by HermanMolinder** [comment]
Setting cropping params at runtime works as expected.
Thank you! You can close this issue now.

**Comment by dmitryermilov** [comment]
You're welcome.
