### ISSUE TITLE
vainfo needs sudo on Ubuntu20.04

### ISSUE THREAD

**Issue by ymaskina** [Intel-Media-SDK/MediaSDK#2394]
I faced an issue using libva functions on Ubuntu20.04 (OpenVINO package). Without sudo the output of vainfo will be follow:
libva info: VA-API version 1.8.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /opt/intel/mediasdk/lib64/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_8
libva error: /opt/intel/mediasdk/lib64/iHD_drv_video.so init failed
libva info: va_openDriver() returns 18
vaInitialize failed with error code 18 (invalid parameter),exit
I found workaround to change owner group of renderD128 from 'render' to 'video'
Maybe there should be some kind of notification for Ubuntu 20 about this during installation 
Thanks,
Yuliya

**Comment by onabiull** [comment]
Looks https://github.com/intel/libva/issues/444 would be better place to discuss.
