### ISSUE TITLE
Can´t set look_ahead on 9th intel gen

### ISSUE THREAD

**Issue by Classsic** [Intel-Media-SDK/MediaSDK#2404]
Hi, I follow the steps for compile and install ffmpeg on ubuntu 20.04. 
[https://github.com/Intel-Media-SDK/MediaSDK/wiki/Build-FFmpeg-QSV](url)
When try to use look_ahead, whit this command:
`ffmpeg -loglevel info -init_hw_device qsv=hw  -filter_hw_device hw -rtsp_transport tcp -i rtsp://localhost/lasheras   -c:v h264_qsv  -vf  hwupload=extra_hw_frames=120  -look_ahead 1    -g 90 -bf 3  -rtsp_transport tcp -f rtsp -an rtsp://localhost:9088/3mp`
I get this error:

`[h264_qsv @ 0x55919ca8bdc0] Error initializing the encoder: unsupported (-3)
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!
`

If I setup look_ahead 0, works perfectly.
What I´m missing?
Thanks.

This is my cpu:
`model name      : Intel(R) Core(TM) i3-9100 CPU @ 3.60GHz
`

**Comment by dvrogozh** [comment]
Look ahead path requires cmrt library which is built during media driver build. On Ubuntu it will be /usr/lib/x86_64-linux-gnu/libigfxcmrt.so.7. Can you, please, check whether it is available? If you use Ubuntu 20.04 packages make sure to install:
```
apt-get install libigfxcmrt7
```

**Comment by Classsic** [comment]
Now works great!
Maybe this have to go in the tutorial, is very important.
Thanks.
Close this issue.-
