### ISSUE TITLE
Linux kernel 4.19 EOL date on Wiki page looks wrong

### ISSUE THREAD

**Issue by Mr-Clam** [Intel-Media-SDK/MediaSDK#2405]
This page say Linux kernel 4.19 will EOL Dec 2020:
https://github.com/Intel-Media-SDK/MediaSDK/wiki/Intel-Graphics-Support-in-Linux-Kernels

The upstream page says Dec 2024:
https://www.kernel.org/category/releases.html

I suppose this is an error and should be fixed in both places on the Wiki page.

**Comment by dvrogozh** [comment]
Thank you for pointing this out. Actually this is not a mistake, but not updated wiki page. Initially 4.19 was announced with the shorter support period (and you saw it on the wiki page), later on (in about ~half a year) support period was extended. I aligned dates with the official kernel documentation and added a note that dates needs to be checked against it.

**Comment by daleksan** [comment]
wiki page was updated. i'm going to close the issue
