### ISSUE TITLE
vp9 encode failed!

### ISSUE THREAD

**Issue by syjml** [Intel-Media-SDK/MediaSDK#2421]
OS:win10 2004
GPU：Intel UHD 630

After compiling the sample_encode project, execute the following command:

sample_encode.exe vp9 -hw -i yuv420p.yuv -o yuv420p.vp9 -w 1920 -h 1080

return error message:
ERROR: No suitable adapters found for this workload

![image](https://user-images.githubusercontent.com/8069021/97262216-6590a180-185b-11eb-8d30-741eb2d79dfe.png)

I want to know if the cause of the error is msdk does not support VP9 encoding or my command is wrong?

**Comment by onabiull** [comment]
UHD 630 translates to Coffee Lake and Gen9 Intel Graphics. VP9 encode introduced since Icelake (Gen 11).
