### ISSUE TITLE
Decoders are broken since PR #2363

### ISSUE THREAD

**Issue by dmitryermilov** [Intel-Media-SDK/MediaSDK#2432]
#2363 introduced not backward compatibility. If system doesn't have very latest UMD, then decoders since #2363 return MFX_ERR_UNSUPPORTED from DecodeFrameAsync . It's a regression because GPU priority support is an optional feature. MSDK should query driver caps and not try to enable if a particular UMD instance doesn't have corresponding support.

**Comment by dvrogozh** [comment]
@dylanintel : fyi

And I was warning about this behavior, but thought we took care about that. Looks like I overlooked something in review. @dmitryermilov : did we revert the feature already?

**Comment by dmitryermilov** [comment]
Let's allow 24h (per policies) for a fix?

**Comment by dvrogozh** [comment]
ok

**Comment by dmitryermilov** [comment]
I observe the same issue with AVC encoder.

**Comment by dmitryermilov** [comment]
Dylan and I chatted and did some debug in parallel. PR from Dylan indeed introduced Query support so sorry for pressure, Dylan! It’s not a MSDK problem, it’s driver issue. There is a short range of drivers where driver being compiled against libva <1.10 reports GPU priority is supported but the real support is not included in the build. I was lucky to have such driver.
