### ISSUE TITLE
[ERROR], sts=MFX_ERR_UNSUPPORTED(-3),MediaSDK2018 Q4@@ CentOS Linux release 7.5.1804

### ISSUE THREAD

**Issue by kevinchen1223** [Intel-Media-SDK/MediaSDK#2463]
cpu:i5-7200U
[root@localhost samples]# ./sample_decode h264 -i cars_1920x1080.h264 -o out.yuv
libva info: VA-API version 1.4.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'i965'
libva info: Trying to open /opt/intel/mediasdk/lib64/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_4
libva info: va_openDriver() returns 0
[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), AllocFrames, m_pmfxDEC->QueryIOSurf failed at /home/MediaSDK-intel-mediasdk-18.4.0/samples/sample_decode/src/pipeline_decode.cpp:1036
[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), Init, AllocFrames failed at /home/MediaSDK-intel-mediasdk-18.4.0/samples/sample_decode/src/pipeline_decode.cpp:429
[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), main, Pipeline.Init failed at /home/MediaSDK-intel-mediasdk-18.4.0/samples/sample_decode/src/sample_decode.cpp:666

[root@localhost lib64]# vainfo
error: can't connect to X server!
libva info: VA-API version 1.4.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'i965'
libva info: Trying to open /opt/intel/mediasdk/lib64/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_4
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.4 (libva 2.4.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Kaby Lake - 2.4.1
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSliceLP
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointEncSliceLP
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointEncSliceLP
      VAProfileH264MultiviewHigh      :	VAEntrypointVLD
      VAProfileH264MultiviewHigh      :	VAEntrypointEncSlice
      VAProfileH264StereoHigh         :	VAEntrypointVLD
      VAProfileH264StereoHigh         :	VAEntrypointEncSlice
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointEncPicture
      VAProfileVP8Version0_3          :	VAEntrypointVLD
      VAProfileVP8Version0_3          :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileHEVCMain10             :	VAEntrypointEncSlice
      VAProfileVP9Profile0            :	VAEntrypointVLD
      VAProfileVP9Profile0            :	VAEntrypointEncSlice
      VAProfileVP9Profile2            :	VAEntrypointVLD

[root@localhost lib64]# uname -r
3.10.0-862.el7.x86_64

**Comment by kevinchen1223** [comment]
[root@localhost mediasdk]# cd lib64/
[root@localhost lib64]# ll
总用量 53816
-rwxr-xr-x. 1 root root      989 11月  9 15:44 i965_drv_video.la
-rwxr-xr-x. 1 root root  8694744 11月  9 15:44 i965_drv_video.so
lrwxrwxrwx. 1 root root       15 11月  9 15:52 libmfxhw64.so -> libmfxhw64.so.1
lrwxrwxrwx. 1 root root       18 11月  9 15:52 libmfxhw64.so.1 -> libmfxhw64.so.1.28
-rwxr-xr-x. 1 root root 45979088 11月  9 15:52 libmfxhw64.so.1.28
lrwxrwxrwx. 1 root root       11 11月  9 15:52 libmfx.so -> libmfx.so.1
lrwxrwxrwx. 1 root root       14 11月  9 15:52 libmfx.so.1 -> libmfx.so.1.28
-rwxr-xr-x. 1 root root   417048 11月  9 15:48 libmfx.so.1.28
drwxr-xr-x. 2 root root     4096 11月  9 15:52 mfx
drwxr-xr-x. 2 root root     4096 11月  9 15:52 pkgconfig

**Comment by onabiull** [comment]
Take a look at wiki page: https://github.com/Intel-Media-SDK/MediaSDK/wiki/Intel-media-stack-on-Ubuntu
Your environment looks erroneously pick up i965 instead of iHD driver.

**Comment by onabiull** [comment]
And according to https://github.com/Intel-Media-SDK/MediaSDK/wiki/Intel-Graphics-Support-in-Linux-Kernels Kabylake (i7-7200U) support introduced in kernel version 4.9. While some distributions do backport HW support changes, so from i915 KMD driver perspective your kernel almost certainly newer than 3.10, I'd recommend to give 4.9 a try.

**Comment by daleksan** [comment]
Hi @kevinchen1223
Is it still actual?

**Comment by daleksan** [comment]
Hi @kevinchen1223 i'm going to close the issue, but feel free to re-open if it still actual for you!
