### ISSUE TITLE
[HEVCe_LP][Regression] one commit breaks HEVCe LP on ffmpeg-qsv and gst-msdk at target usage 7 on Gen12

### ISSUE THREAD

**Issue by zhangyuankun-star** [Intel-Media-SDK/MediaSDK#2475]
https://github.com/Intel-Media-SDK/MediaSDK/pull/2440 .this commit breaks HEVCe LP on ffmpeg-qsv and gst-msdk at target usage 7 on Gen12.
**for example**:
gst-launch-1.0 -vf filesrc location=<input> num-buffers=240 ! rawvideoparse format=i420 width=1280 height=720 framerate=30 ! videoconvert dither=0 ! video/x-raw,format=NV12 ! msdkh265enc rate-control=vbr hardware=true gop-size=256 target-usage=7 num-slices=1 b-frames=7 max-vbv-bitrate=4000 bitrate=2000 ref-frames=5 low-power=1 ! video/x-h265,profile=main ! h265parse ! filesink location=<output>
**Log**:
ERROR: from element /GstPipeline:pipeline0/GstMsdkH265Enc:msdkh265enc0: Encode frame failed.
Additional debug info:
../sys/msdk/gstmsdkenc.c(1023): gst_msdkenc_encode_frame (): /GstPipeline:pipeline0/GstMsdkH265Enc:msdkh265enc0:
MSDK encode error (null pointer)
ERROR: pipeline doesn't want to preroll.
ERROR: from element /GstPipeline:pipeline0/GstRawVideoParse:rawvideoparse0: Internal data stream error.
Additional debug info:
../libs/gst/base/gstbaseparse.c(3679): gst_base_parse_loop (): /GstPipeline:pipeline0/GstRawVideoParse:rawvideoparse0:
streaming stopped, reason error (-5)
ERROR: pipeline doesn't want to preroll.
ERROR: from element /GstPipeline:pipeline0/GstMsdkH265Enc:msdkh265enc0: Encode frame failed.
Additional debug info:
../sys/msdk/gstmsdkenc.c(1097): gst_msdkenc_flush_frames (): /GstPipeline:pipeline0/GstMsdkH265Enc:msdkh265enc0:
MSDK encode error (the HW acceleration device is busy)
ERROR: pipeline doesn't want to preroll.
Setting pipeline to NULL ...
ERROR: from element /GstPipeline:pipeline0/GstMsdkH265Enc:msdkh265enc0: Encode frame failed.
Additional debug info:
../sys/msdk/gstmsdkenc.c(1097): gst_msdkenc_flush_frames (): /GstPipeline:pipeline0/GstMsdkH265Enc:msdkh265enc0:
MSDK encode error (the HW acceleration device is busy)
ERROR: pipeline doesn't want to preroll.
Freeing pipeline ...

**Comment by uartie** [comment]
Reverted in #2476

**Comment by JeremyShang** [comment]
Hi @zhangyuankun-star , if you are still meeting the same issue. I suggests you update the intel media driver to the latest version.  
Thanks!
