### ISSUE TITLE
error after running '/opt/intel/mediasdk/bin/vainfo'

### ISSUE THREAD

**Issue by niuwenju** [Intel-Media-SDK/MediaSDK#2477]
environments:

1. OS:ubuntu18.04
2. kernel:Linux version 5.4.0-52-generic (buildd@lcy01-amd64-022) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #57~18.04.1-Ubuntu SMP Thu Oct 15 14:04:49 UTC 2020
3. CPU:Intel® Core™ i7-4790 CPU @ 3.60GHz 
4. openvino:2020.1

i have successfully installed openvino2020.1, but after running `/opt/intel/mediasdk/bin/vainfo` got errors as follows

```
libva info: VA-API version 1.6.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /opt/intel/mediasdk/lib64/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_6
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
libva error: /opt/intel/mediasdk/lib64/iHD_drv_video.so init failed
libva info: va_openDriver() returns 18
vaInitialize failed with error code 18 (invalid parameter),exit
```

**Comment by daleksan** [comment]
Hi @niuwenju what media driver version you used?

**Comment by dvrogozh** [comment]
`i7-4790` is HSW. It is not supported neither by mediasdk nor by iHD driver.

You might get HW acceleration support thru i965 driver by installing (mediasdk won't work however):
```
apt-get install i965-va-driver
```

If you will continue to use vainfo and libva from openvino installation (but I would advice not doing that and rely on system version), you might need to expose:
```
export LIBVA_DRIVER_NAME=i965
export LIBVA_DRIVERS_PATH=/usr/lib/x86_64-linux-gnu/dri
```
