### ISSUE TITLE
ERROR], sts=MFX_ERR_UNSUPPORTED(-3),MediaSDK2018 - sample_camera.exe WINDOWS 10

### ISSUE THREAD

**Issue by vladi14** [Intel-Media-SDK/MediaSDK#2481]
hi , i try to prefrom simple actions on jpeg file ( i have managed successfully make rotation with multi_transcode.exe ) and i getting that error after i put the following command line :

command line :         sample_camera.exe -3DLUT_gamma -i sample.jpeg -o test.jpeg
error :

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), CCameraPipeline::Init, m_mfxSession.Init failed at C:\Users\vpikovsk\Desktop\MediaSDK\samples\sample_camera\src\pipeline_camera.cpp:867

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), wmain, Pipeline.Init failed at C:\Users\vpikovsk\Desktop\MediaSDK\samples\sample_camera\src\sample_camera.cpp:684

tried various of parameters and getting the same issue.

**Comment by dmitryermilov** [comment]
@mvmaximov , is it expected ?

**Comment by mvmaximov** [comment]
@vladi14 , could you please provide additional information: 

- which platform it is (CPU/GPU) 
- version of graphics driver installed on the system

**Comment by vladi14** [comment]
hi , i managed to use decode , sampe_vpp ,
now i am trying to use sample encode , with the following command line :

sample_encode.exe jpeg -i out_modified.yuv -o my_file.jpg -w 352 -h 192 -angle 180 -q 100
and facing the following erros:
C:\Users\vladi\Desktop\decoder\bin> sample_encode.exe jpeg -i out_modified.yuv -o my_file.jpg -w 352 -h 192 -angle 180 -q 100

[ERROR], sts=MFX_ERR_NULL_PTR(-2), CSmplYUVReader::Init, f pointer is NULL at C:\Users\vpikovsk\Desktop\MediaSDK\samples\sample_common\src\sample_utils.cpp:142

[ERROR], sts=MFX_ERR_NULL_PTR(-2), CUserPipeline::Init, m_FileReader.Init failed at C:\Users\vpikovsk\Desktop\MediaSDK\samples\sample_encode\src\pipeline_user.cpp:184

[ERROR], sts=MFX_ERR_NULL_PTR(-2), wmain, pPipeline->Init failed at C:\Users\vpikovsk\Desktop\MediaSDK\samples\sample_encode\src\sample_encode.cpp:1627

i am using intel UHD Graphic adapter 630
with driver version : 26.20.100.7642

**Comment by asmirno1** [comment]
@vladi14 , could you please also provide samples version that you are using?

**Comment by asmirno1** [comment]
Closing this due to aging and no answer from reporter.
@vladi14 , please reopen and provide details if still actual.
