### ISSUE TITLE
DecodeFrameAsync access violation

### ISSUE THREAD

**Issue by lzfgnu** [Intel-Media-SDK/MediaSDK#2493]
Does media sdk have limits on the number of decode sessions in a single process?
In my project, I use media sdk to decode h264 file. I find  when I create more than 12 decoders, the access violation occures in function DecodeFrameAsync.
However, if I create two processes, one of each creates 6 decoders. the access violation won't happen.
I also tried to use ffmpeg h264_qsv, the same problem occured

Platform:        win10 1909
cpu:                Intel core i7-8700
gpu:                Intel UHD Graphics 630 (**driver version: 26.20.100.7642**)

**Comment by dmitryermilov** [comment]
@wangyan-intel , @asmirno1 , could you investigate it?

**Comment by wangyan-intel** [comment]
Sure. We will take a look.

**Comment by daleksan** [comment]
Hi @wangyan-intel  do you have any updates?

**Comment by wangyan-intel** [comment]
@lzfgnu Sorry for slow response. It this issue still existed?

**Comment by wangyan-intel** [comment]
@lzfgnu Because no response, I will close this issue at first. If it is still existed, please free to reopen it. Thanks.
