### ISSUE TITLE
Sample_encode output for h265 is corrupted if using system memory with p016 input raw video.

### ISSUE THREAD

**Issue by SiewHoon** [Intel-Media-SDK/MediaSDK#2556]
![image](https://user-images.githubusercontent.com/7076622/103519580-bbfc0b00-4eb0-11eb-9c6c-6d347874a41e.png)

Without -vaapi & -hw the encode output, playback the output is color corrupted. We can see corrupted issue by  using VQ Analyzer to check encode output stream.
 ./sample_encode h265 -i /home/root/output_1920x1080_p016.yuv -p016 -w 1920 -h 1080 -o /home/root/video.265

With -vaapi & -hw the encode output playback is good.
 ./sample_encode h265 -i /home/root/output_1920x1080_p016.yuv -p016 -hw -vaapi -w 1920 -h 1080 -o /home/root/video.265

Environment:
MediaSDK tag: intel-mediasdk-20.5.1
Media-driver tag: intel-media-20.4.5 
libva : libva-intel_2.10.0.bb
Platform: TGL-U

**Comment by AntonGrishin** [comment]
Hi @SiewHoon,
Can you please add "-msb10" to your command line and try again?

**Comment by SiewHoon** [comment]
Hi @AntonGrishin,

By add "-msb10", I can't the corruption anymore.
