### ISSUE TITLE
sample_encode encode h265 with intra refresh failed

### ISSUE THREAD

**Issue by wenbinc-Bin** [Intel-Media-SDK/MediaSDK#2571]
I try to use sample_encode to encode h265 with intra refresh, and it failed.

```
platform GEN 9
MediaSDK 77f673853c23a91241
```

command line:
`sample_encode h265 -i 1920x1080.yuv -o sample_output.265 -ir_type 1 -ir_cycle_size 4 -ir_qp_delta -20 -ir_cycle_dist 20 -w 1920 -h 1080`
error:
```
ERROR: Hardware device was lost or returned an unexpected error. Recovering...

[ERROR], sts=MFX_ERR_DEVICE_FAILED(-17), SynchronizeFirstTask, SyncOperation failed at /home/wenbin/software/media/src/MediaSDK/samples/sample_encode/src/pipeline_encode.cpp:168

[ERROR], sts=MFX_ERR_DEVICE_FAILED(-17), GetFreeTask, m_TaskPool.SynchronizeFirstTask failed at /home/wenbin/software/media/src/MediaSDK/samples/sample_encode/src/pipeline_encode.cpp:2193

[ERROR], sts=MFX_ERR_DEVICE_FAILED(-17), Run, m_pmfxENC->EncodeFrameAsync failed at /home/wenbin/software/media/src/MediaSDK/samples/sample_encode/src/pipeline_encode.cpp:2497
```
if i change ir_qp_delta to 0:
`sample_encode h265 -i 1920x1080.yuv -o sample_output.265 -ir_type 1 -ir_cycle_size 4 -ir_qp_delta 0 -ir_cycle_dist 20 -w 1920 -h 1080`
error:
sample_encode: 
```
/home/wenbin/software/media/src/MediaSDK/_studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_legacy_defaults.cpp:1258: static std::tuple<unsigned char, unsigned char> GetDefault::RPL(MfxFeatureBlocks::CallChain<std::tuple<unsigned char, unsigned char>, const HEVCEHW::Base::Defaults::Param&, const HEVCEHW::Base::_DpbFrame (&)[15], short unsigned int, short unsigned int, const HEVCEHW::Base::FrameBaseInfo&, unsigned char (&)[2][15]>::TExt, const HEVCEHW::Base::Defaults::Param&, const HEVCEHW::Base::_DpbFrame (&)[15], mfxU16, mfxU16, const HEVCEHW::Base::FrameBaseInfo&, mfxU8 (&)[2][15]): Assertion `!"L0 is empty - reordering issue?"' failed.
Aborted (core dumped)
```

**Comment by xhaihao** [comment]
@dmitryermilov @daleksan any update about this issue?

**Comment by dmitryermilov** [comment]
@SofyaBalandina , @DenWolf , please share an update.

**Comment by vilichev** [comment]
@yskuridi please take a look from HEVCe side

**Comment by yskuridi** [comment]
Hi @xhaihao ,
I found out that the device fail error is a driver issue. Investigation from driver side is required.

Regarding the issue with empty L0, the investigation is in progress.

**Comment by xhaihao** [comment]
@yskuridi Thanks for the update.

**Comment by yskuridi** [comment]
Hi @xhaihao 

There are 2 issues.
The first relates to gpu hang. Investigation from media driver is required. 
The second error occurred due to default GopRefDist (=4) and it leads to encoding with B-frames. But IntraRefresh feature doesn't work with B-frames. Check for GopRefDist with Intra Refresh will be added from msdk side. In order to set GopRefDist=1 sample_encode have -r 1 option.

Thanks,
Yuri.

**Comment by xhaihao** [comment]
@yskuridi thanks for the update, should we file a driver issue for the GPU hang?

**Comment by yskuridi** [comment]
@xhaihao Indeed, I've created one https://github.com/intel/media-driver/issues/1179.
