### ISSUE TITLE
Ice Lake HEVC 10-bit fixed-function encoding (vs Tiger Lake)

### ISSUE THREAD

**Issue by ukmark62** [Intel-Media-SDK/MediaSDK#2574]
I am using "fixed-function" HEVC 10-bit encoding on Ice Lake CPU i7-1065G7 and I am unable to make use of b-frames and b-pyramid functionality - they are disabled by the driver during encoding. I have heard that Tiger Lake does allow b-frames and b-pyramid to be used with HEVC 10-bit "fixed-function" encoding. 

Can somebody please confirm, that Ice Lake does or does not support fixed-function HEVC 10-bit encoding with use of b-frames and b-pyramid? Is there any documentation that covers this area?

Many thanks.

**Comment by JeremyShang** [comment]
Hi @ukmark62 , yes, Ice Lake does not support fixed-function encoding with use of b-frames and b-pyramid (8bit or 10bit). Fixed function supports that starting from Tiger Lake.

**Comment by ukmark62** [comment]
Thanks for the clarification.
