### ISSUE TITLE
H265 decode with SFC from NV12->RGB4 failed

### ISSUE THREAD

**Issue by joojler** [Intel-Media-SDK/MediaSDK#2580]
Checked the code, one restriction added to avoid CSC in SFC.  in _studio/mfx_lib/decode/h265/src/mfx_h265_dec_decode.cpp

![image](https://user-images.githubusercontent.com/3134283/105948802-9b396680-60a6-11eb-8c2e-3b76bccd4ede.png)

Can this restriction be removed right now?

**Comment by wangyan-intel** [comment]
@shawnli2 Could you please take a look?

**Comment by shawnli2** [comment]
I will update a patch soon to remove this check
