### ISSUE TITLE
ffmpeg-qsv crash on Ubuntu 20.10 (driver intel-media-va-driver, not intel-media-va-driver-non-free)

### ISSUE THREAD

**Issue by mikhail-nikolskiy** [Intel-Media-SDK/MediaSDK#2595]
Steps to reproduce:
```
docker run -it --privileged --net=host ubuntu:20.10
# apt update
# apt install ffmpeg
# ffmpeg -hwaccel qsv -c:v h264_qsv -i [INPUT] -vf hwdownload,format=nv12 output.yuv
```

Output
```
/build/intel-mediasdk-UBsAHl/intel-mediasdk-20.1.0/_studio/shared/src/mfx_vpp_vaapi.cpp:239: mfxStatus MfxHwVideoProcessing::VAAPIVideoProcessing::Init(void**, mfxVideoParam*): Assertion `0x00000000 == vaSts' failed.
Aborted (core dumped)
```

Note that same command-line for decoding into .yuv file works ok if `apt install intel-media-va-driver-non-free`

MediaSDK crashes inside MFXVideoVPP_Init. VPP operation not available in intel-media-va-driver, only in intel-media-va-driver-non-free. If VPP not available, MFXVideoVPP_Init should gracefully return error code, not crash.
![Screenshot from 2021-02-10 15-44-49](https://user-images.githubusercontent.com/48696869/107596602-19305e00-6bcd-11eb-9e60-7cf00fbecc28.png)

**Comment by dmitryermilov** [comment]
Yes, we need to clean up code from MFX_CHECK_WITH_ASSERT . Or enable underlying assert inside MFX_CHECK_WITH_ASSERT only for debug build . 
@aobolensk , can you please fix at first the issue Mikhail reported (just replace MFX_CHECK_WITH_ASSERT with MFX_CHECK) for VPP Query/QueryIOSurf/Init calls? Then, we'll think what to do with with the rest MFX_CHECK_WITH_ASSERT. I personally think it's better to remove all of them and enable MFX_DEBUG_TRACE for debug build. It's required some discussion. 
BTW, it's expected that intel-media-va-driver doesn't well support VPP. It's described in UMD github page.
