### ISSUE TITLE
avc/vdenc: not available BRC modes causes msdk abort with assertion

### ISSUE THREAD

**Issue by dvrogozh** [Intel-Media-SDK/MediaSDK#2614]
https://github.com/Intel-Media-SDK/MediaSDK/blob/8c1d3dfe48529df141d0e014d9c8c4227664e371/_studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp#L73

This assert will be triggered if BRC mode is not available. I use "not available" since this very well might be the case on SKL/KBL/TGL if kernel was not loaded with not enabled huc (which is actually a default). As a result VDENC AVC encoder will step into this assert and program will be terminated w/o a chance to fallback to VME.

I believe we better change this assert into runtime error.

**Comment by kovakimy** [comment]
HI @dvrogozh,
Thank you for your note.
I added PR with removing of assert.
