### ISSUE TITLE
sample_decode not able to play on Weston

### ISSUE THREAD

**Issue by vcheah** [Intel-Media-SDK/MediaSDK#2657]
Platform-impacted: ADL-S, EHL, TGL
BSP: core-image-sato-sdk-intel-corei7-64-20210312172429.wic.bz2
BIOS: IOTG_TGL_UR01_B0B0-XXXXXLP_RPSF_SEP5_55049A_25Mhz_2021WW10.5.01_SATA.bin
CPU: QVD5
Weston version: weston 9.0.0 (Build: 9.0.0-46-gf5eeaa4) & (Build: 9.0.0-48-gacb16b7)
Kernel: 5.10.21-intel-ese-standard-lts & 5.4.102-intel-ese-standard-lts

Execution command:   ./sample_decode h265 -i Puppies_3840x2160.265 -rwld -rgb4

Execution errors: 
libva info: VA-API version 1.10.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /usr/lib64/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_10
libva info: va_openDriver() returns 0

[07:31:49.108] libwayland: error in client communication (pid 7432)
wl_drm@5: error 0: authenticate failed
[ERROR], sts=MFX_ERR_UNKNOWN(-1), CreateHWDevice, m_hwdev->Init failed at /usr/src/debug/intel-mediasdk/21.1.1-r0/git/samples/sample_decode/src/pipeline_decode.cpp:1105
[ERROR], sts=MFX_ERR_UNKNOWN(-1), Init, CreateHWDevice failed at /usr/src/debug/intel-mediasdk/21.1.1-r0/git/samples/sample_decode/src/pipeline_decode.cpp:439
[ERROR], sts=MFX_ERR_UNKNOWN(-1), main, Pipeline.Init failed at /usr/src/debug/intel-mediasdk/21.1.1-r0/git/samples/sample_decode/src/sample_decode.cpp:778

**Comment by wangyan-intel** [comment]
IMHO, iHD_drv_video.so hasn't supported Wayland/Weston so far.

**Comment by vcheah** [comment]
MR: https://github.com/Intel-Media-SDK/MediaSDK/issues/2657

**Comment by dmitryermilov** [comment]
Hi @vcheah , 

Could you confirm that #2658 fixes this issue?

**Comment by vcheah** [comment]
> Hi @vcheah ,
> 
> Could you confirm that #2658 fixes this issue?
recheck on TGL. Issue seems to be fix.
