### ISSUE TITLE
Device 8086:4C8A was not found?

### ISSUE THREAD

**Issue by tongshi203** [Intel-Media-SDK/MediaSDK#2670]
Hi，
   I want to download GPU Drivers for centos8.3, my device PCI ID is 8086:4C8A, but the result is:
"Device 8086:4C8A was not found".
 where can i find this drivers?
    Thanks!

**Comment by tongshi203** [comment]
CPU：Rocket Lake 11th Gen Intel(R) Core(TM) i5-11500 @ 2.70GHz
Base Board:  H510M-ITX/ac

**Comment by dmitryermilov** [comment]
Hi @tongshi203 ,

MediaSDK and media-driver support it:
https://github.com/Intel-Media-SDK/MediaSDK/blob/510d19dcace1d8c57567fdd40b557155ab11ab8e/_studio/shared/src/libmfx_core_vaapi.cpp#L385 

https://github.com/intel/media-driver/blob/9d78ff3082a7878e11f03be6bc161dcac2482c89/media_driver/linux/gen12/ddi/media_sysinfo_g12.cpp#L298  : 
```
static bool rklGt1Device4C8A = DeviceInfoFactory<GfxDeviceInfo>::
    RegisterDevice(0x4C8A, &rklGt1Info);
```

Please try to update to latest version of code.

**Comment by tongshi203** [comment]
Thanks
