### ISSUE TITLE
sample_decode zero copy to renderer possible w/ NV12?

### ISSUE THREAD

**Issue by gsilva2016** [Intel-Media-SDK/MediaSDK#2675]
Does sample_decode support zero-copy path from decoding to rendering for each frame where the decoded NV12 frame is passed directly to a DRM (primary) plane? 

The issue [1622](https://github.com/Intel-Media-SDK/MediaSDK/issues/1622) shows that sample_decode with -rdrm requires -rgb4 which I'd like to avoid and use NV12 instead. 

I haven't tried with -rwld because issue [2657](https://github.com/Intel-Media-SDK/MediaSDK/issues/2657) seems to indicate -rgb4 is needed again.

**Comment by dmitryermilov** [comment]
Hi @gsilva2016 ,

The rdrm support was added into sample_decode long time ago. That time drm renderer (linux kernel) supported RGB only, NV12 didn't work. Perhaps, latest kernels can render NV12. 
@SofyaBalandina , do you have bandwidth to try?

**Comment by SofyaBalandina** [comment]
@dmitryermilov , hi, I can try on new platforms on this week

**Comment by VUNNYSODHI** [comment]
Hi @dmitryermilov and @SofyaBalandina, 

I have tried on Tigerlake in 4k(3840x2160) drm/console mode with latest media stack + 5.12.0-rc7 drm-tip Kernel.

$sample_decode h265 -hw -vaapi -i Bunny_3840x2160.265 -rdrm -nv12
libva info: VA-API version 1.10.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_10
libva info: va_openDriver() returns 0
drmrender: trying connection: DisplayPort
drmrender: selected crtc already attached to connector
drmrender: succeeded...
drmrender: connected via DisplayPort to 3840x2160@60 capable display
[ERROR], sts=MFX_ERR_UNKNOWN(-1), AllocImpl, sts!=MFX_ERR_NONE error at /home/tgl-deb/github/latest-media-stack-22-april/msdk/samples/sample_common/src/general_allocator.cpp:148

[ERROR], sts=MFX_ERR_UNKNOWN(-1), AllocFrames, m_pGeneralAllocator->Alloc failed at /home/tgl-deb/github/latest-media-stack-22-april/msdk/samples/sample_decode/src/pipeline_decode.cpp:1261

[ERROR], sts=MFX_ERR_UNKNOWN(-1), Init, AllocFrames failed at /home/tgl-deb/github/latest-media-stack-22-april/msdk/samples/sample_decode/src/pipeline_decode.cpp:561

[ERROR], sts=MFX_ERR_UNKNOWN(-1), main, Pipeline.Init failed at /home/tgl-deb/github/latest-media-stack-22-april/msdk/samples/sample_decode/src/sample_decode.cpp:782

**Comment by VUNNYSODHI** [comment]
Also found above failure is coming from:
https://github.com/Intel-Media-SDK/MediaSDK/blob/master/samples/sample_common/src/vaapi_utils_drm.cpp#L423

**IOCTL is failing with -22 error** --> in dmesg can see [drm:drm_internal_framebuffer_create] bad pitch 3840 for plane 0

 ret = m_drmlib.drmModeAddFB(m_fd,
              vmid->m_image.width, vmid->m_image.height,
              24, 32, vmid->m_image.pitches[0],
              flink_open.handle, &fbhandle);

24,32 magic numbers looks okay for RGB4, not for NV12 I think.
Not sure for NV12  format do we need to change from legacy FB calling drmModeAddFB to drmModeAddFB2

**Comment by dmitryermilov** [comment]
Thanks, Vunny.
I'll check next week what's going on.

**Comment by VUNNYSODHI** [comment]
Hi @dmitryermilov  and @SofyaBalandina 

Please help to review.

**Comment by gsilva2016** [comment]
Introduced patch resolves direct NV12 rendering.
