### ISSUE TITLE
Use SetThreadErrorMode 

### ISSUE THREAD

**Issue by Antr2005** [Intel-Media-SDK/MediaSDK#2680]
Hi,

https://docs.microsoft.com/en-us/windows/win32/api/errhandlingapi/nf-errhandlingapi-setthreaderrormode

Minimum supported client | Windows 7 [desktop apps \| UWP apps]

https://docs.microsoft.com/ru-ru/cpp/porting/modifying-winver-and-win32-winnt

#define _WIN32_WINNT_WIN7                   0x0601 // Windows 7

mfx_load_dll.cpp, mfx_dxva2_device.cpp

Best regards

**Comment by daleksan** [comment]
Hi @mvmaximov can you take a look?

**Comment by npletnev** [comment]
The issue has been fixed in mentioned pr.
