### ISSUE TITLE
Memory leak during full HD HEVC encoding.

### ISSUE THREAD

**Issue by avstrakhov** [Intel-Media-SDK/MediaSDK#2681]
Looks like a small memory leak exists in HEVC encoding pipeline. It was found using the application which runs an encoding of long stream of full HD NV12 frames and confirmed using MedisSDK sample_encode application.
No any memory leaks were observed running AVC encoding, so looks like this memory leak is HEVC encoding specific.
The issue was investigated on Centos Linux 7 running on i7-8809G CPU using 21.1.3 MediaSDK stack and the latest sources from GitHub. 

Output from top demonstrates the issue: 
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
14665 astrakh+  20   0  382468  93428  32448 S  56.3  0.3   0:32.76 sample_encode
14665 astrakh+  20   0  382468 116216  32448 S  55.3  0.4  15:58.03 sample_encode
14665 astrakh+  20   0  382468 129676  32448 S  59.5  0.4  29:59.69 sample_encode
14665 astrakh+  20   0  382468 143932  32448 R  70.1  0.4  45:01.65 sample_encode
14665 astrakh+  20   0  382468 158188  32448 S  55.8  0.5  60:06.15 sample_encode

**Comment by vilichev** [comment]
Reproduced the issue.
According to valgrind log it looks we have memory growth issue but not real memory leak. 
More debugging is needed to understand whether memory growth relates to MSDK or to media driver.
