### ISSUE TITLE
The QP value for I P B frame is inverted for HEVC encode by MFX_RATECONTROL_LA_EXT

### ISSUE THREAD

**Issue by tongshi203** [Intel-Media-SDK/MediaSDK#2694]
Hi,
For normal encoding, the QPI<QPP<QPB, but the QP value for I P B frame is inverted for HEVC encode by MFX_RATECONTROL_LA_EXT.

I add the print qp in _studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_ext_brc.cpp,like this:

static mfxStatus GetFrameCtrl(mfxHDL pthis, mfxBRCFrameParam* par, mfxBRCFrameCtrl* ctrl)
{
MFX_CHECK_NULL_PTR3(pthis, par, ctrl);

ctrl->QpY = ((TBRC*)pthis)->GetQP(par->EncodedOrder);
printf("FrameType:%d    QpY:%d \n", par->FrameType, ctrl->QpY);
return MFX_ERR_NONE;

}

and then run the sample_encode,by like this:
./sample_encode h265 -i 1.yuv -o 1.h265 -w 1920 -h 1080 -hw -nv12 -la_ext -CodecProfile 1 -async 1 -lad 5 -f 25 -u 4 -g 65 -r 8 -b 5000

the result is:
[root@localhost release]# ./sample_encode h265 -i 1.yuv -o 1.h265 -w 1920 -h 1080 -hw -nv12 -la_ext -CodecProfile 1 -async 1 -lad 5 -f 25 -u 4 -g 65 -r 8 -b 5000
plugin_loader.h :185 [INFO] Plugin was loaded from GUID: { 0x58, 0x8f, 0x11, 0x85, 0xd4, 0x7b, 0x42, 0x96, 0x8d, 0xea, 0x37, 0x7b, 0xb5, 0xd0, 0xdc, 0xb4 } (Intel (R) Media SDK plugin for LA ENC)
libva info: VA-API version 1.12.0
libva info: Trying to open /usr/lib64/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_12
libva info: va_openDriver() returns 0
Encoding Sample Version 8.4.27.0

Input file format NV12
Output video HEVC
Source picture:
Resolution 1920x1088
Crop X,Y,W,H 0,0,1920,1080
Destination picture:
Resolution 1920x1088
Crop X,Y,W,H 0,0,1920,1080
Frame rate 25.00
Bit rate(Kbps) 5000
Gop size 65
Ref dist 8
Ref number 4
Idr Interval 0
Target usage balanced
Memory type system
Media SDK impl hw
Media SDK version 1.35

Processing started
FrameType:193 QpY:29
FrameType:68 QpY:31
FrameType:4 QpY:33
FrameType:4 QpY:35
FrameType:4 QpY:37
FrameType:4 QpY:39
FrameType:4 QpY:38
FrameType:4 QpY:37
FrameType:4 QpY:37
FrameType:68 QpY:38
FrameType:4 QpY:36
FrameType:4 QpY:36
FrameType:4 QpY:35
FrameType:4 QpY:35
FrameType:4 QpY:33
FrameType:4 QpY:33
FrameType:4 QpY:34
FrameType:68 QpY:35
FrameType:4 QpY:33
FrameType:4 QpY:33
FrameType:4 QpY:32
FrameType:4 QpY:33
FrameType:4 QpY:31
FrameType:4 QpY:31
FrameType:4 QpY:32
FrameType:68 QpY:33
FrameType:4 QpY:31
FrameType:4 QpY:31
FrameType:4 QpY:31
FrameType:4 QpY:32
FrameType:4 QpY:30
FrameType:4 QpY:30
FrameType:4 QpY:31
FrameType:68 QpY:31
FrameType:4 QpY:29
FrameType:4 QpY:29
FrameType:4 QpY:29
FrameType:4 QpY:30
FrameType:4 QpY:29
FrameType:4 QpY:29
FrameType:4 QpY:30
FrameType:68 QpY:31
FrameType:4 QpY:29
FrameType:4 QpY:29
FrameType:4 QpY:29
FrameType:4 QpY:30
FrameType:4 QpY:28
FrameType:4 QpY:28
FrameType:4 QpY:29
FrameType:68 QpY:30
FrameType:4 QpY:28
FrameType:4 QpY:28
FrameType:4 QpY:28
FrameType:4 QpY:29
FrameType:4 QpY:27
FrameType:4 QpY:27
FrameType:4 QpY:28
FrameType:68 QpY:28
FrameType:4 QpY:26
FrameType:4 QpY:25
FrameType:4 QpY:25
FrameType:4 QpY:27
FrameType:4 QpY:29
FrameType:4 QpY:31
FrameType:4 QpY:33
FrameType:193 QpY:34
FrameType:68 QpY:32
FrameType:4 QpY:30
FrameType:4 QpY:28
FrameType:4 QpY:27
FrameType:4 QpY:29
FrameType:4 QpY:31
FrameType:4 QpY:32
FrameType:4 QpY:32
FrameType:68 QpY:32
FrameType:4 QpY:30
FrameType:4 QpY:28
FrameType:4 QpY:26
FrameType:4 QpY:27
FrameType:4 QpY:27
FrameType:4 QpY:27
FrameType:4 QpY:28
FrameType:68 QpY:29
FrameType:4 QpY:28
FrameType:4 QpY:28
FrameType:4 QpY:28
FrameType:4 QpY:29
FrameType:4 QpY:27
FrameType:4 QpY:27
FrameType:4 QpY:28
FrameType:68 QpY:28
FrameType:4 QpY:27
FrameType:4 QpY:27
FrameType:4 QpY:27
FrameType:4 QpY:28
FrameType:4 QpY:27
FrameType:4 QpY:27
FrameType:4 QpY:28
FrameType:68 QpY:29
FrameType:4 QpY:28
FrameType:4 QpY:28
FrameType:4 QpY:28
FrameType:4 QpY:28
FrameType:4 QpY:27
FrameType:4 QpY:27
FrameType:4 QpY:27
FrameType:68 QpY:28
FrameType:4 QpY:26
FrameType:4 QpY:26
FrameType:4 QpY:26
FrameType:4 QpY:28
FrameType:4 QpY:27
FrameType:4 QpY:27
FrameType:4 QpY:28
FrameType:68 QpY:29
FrameType:4 QpY:27
FrameType:4 QpY:27
FrameType:4 QpY:27
FrameType:4 QpY:28
FrameType:4 QpY:27
FrameType:4 QpY:26
FrameType:4 QpY:27
FrameType:68 QpY:28
FrameType:4 QpY:27
FrameType:4 QpY:27
FrameType:4 QpY:27
FrameType:4 QpY:29
FrameType:4 QpY:31
FrameType:4 QpY:33
FrameType:4 QpY:33
FrameType:193 QpY:33

My development environment are:
OS: Centos8.2
CPU：Rocket Lake 11th Gen Intel(R) Core(TM) i5-11500 @ 2.70GHz
Base Board: H510M-ITX/ac

**Comment by ogolikov** [comment]
Hi! This LA mode is targeted for long LA. Could you check this test case with -lad 40?

**Comment by changliwu** [comment]
yes ,it works well with -lad 40, thanks!
