### ISSUE TITLE
How to monitor Intel GPU resources used by MediaSDK...

### ISSUE THREAD

**Issue by htartisan** [Intel-Media-SDK/MediaSDK#27]
My company has asked me to create an application that can monitor Intel GPU resources that are used by the Intel Media SDK / MFX / QuickSync.  We run Intel QuickSync based transcoding software on our Intel E3 servers, and need to monitor how much of the system resources are currently being used on each server.

I have looked in the Media SDK for an API to get this information, but couldn't find one.  I then came across the Intel PAL / Intel Metrics Framework, and that seemed to have what I need.  I developed a metrics framework based application that monitored all of the "metrics" that seem to be related to MFX/QuickSync, and when I ran it on Windows 10, it seemed to work fine.  Unfortunately, when I ran it on one of our Intel E3 servers (which run Windows 2012 Server OS), it said that none of the "metrics" related to QuickSync were detected.

NOTE: I used to work at Intel, and sometimes interfaced with the Media SDK dev team.  I know that what I am trying to do is possible, because I saw one of the Media SDK developers running something like what I'm developing.

Anyone have any idea where I can go for help with this?  My company is willing to pay for support.

**Comment by avbelova** [comment]
HI @htartisan , 
What exact metrics are you interested in? Please check that Xeon E3 has proper graphics driver installed. 

Best wishes, 
Anna

**Comment by htartisan** [comment]
The specific metrics that I am looking for are:
"com.intel.gpu.gpu_busy"
"com.intel.media.gpu_usage"
"com.intel.media.mfx_usage"

Yes, I have verified that there is an Intel graphics driver loaded (driver version on production system is: 21.20.16.4860).

These metrics are loaded just fine on my development systems, but when I try to run the same software on the production systems, the software gets an error that these metrics can not be loaded.

As mentioned above, my goal is to poll our production servers to find out what (how much) Intel GPU resources are currently being used by the Intel Media SDK / MFX / QuickSync software.

NOTE:  Intel provides the Intel Media SDK (MFX / QuickSync) SDK, that allows applications to accelerate H.264 encoding.  However, each Intel GPU provides a limited number of GPU resources that are used to do this, so only a limited number of video files can be encoded in parallel.  Unfortunately Intel does not seem to offer any way to determine how much of the GPU resources are currently being used, so there is no way to know when a server is "fully loaded".

**Comment by artem-shaporenko** [comment]
@abelova Most likely there is an issue with new drivers installing files into driver store, as a result Metrics framework probably just can't find out driver .dll reporting metrics, most likely update for Metrics Framework is required. Can you please check with Metrics Framework team if they can provide fixes?

**Comment by avbelova** [comment]
Hi @htartisan ,
As I checked with PAL team, it's not expected to work on servers.

Best wishes, 
Anna

**Comment by adydychk** [comment]
If there are no more questions here I will close it but feel free to open new one in case of new questions or troubles.
