### ISSUE TITLE
Compile error on Ubuntu

### ISSUE THREAD

**Issue by turingyao** [Intel-Media-SDK/MediaSDK#270]
Hardware: N3450
System: 4.13.0-43-generic #48~16.04.1-Ubuntu SMP Thu May 17 12:56:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Branch: 1.3a

Error:

/home/box/MediaSDK/_studio/mfx_lib/shared/src/mfx_h264_fei_vaapi.cpp: In member function ‘virtual mfxStatus MfxHwH264Encode::VAAPIFEIPREENCEncoder::Execute(mfxHDL, const MfxHwH264Encode::DdiTask&, mfxU32, const MfxHwH264Encode::PreAllocatedVector&)’:
/home/box/MediaSDK/_studio/mfx_lib/shared/src/mfx_h264_fei_vaapi.cpp:331:5: error: ‘VAPictureFEI’ was not declared in this scope
     VAPictureFEI past_ref, future_ref;
     ^
/home/box/MediaSDK/_studio/mfx_lib/shared/src/mfx_h264_fei_vaapi.cpp:436:23: error: ‘l0surfs’ was not declared in this scope
         VAPictureFEI* l0surfs = &past_ref;
                       ^
/home/box/MediaSDK/_studio/mfx_lib/shared/src/mfx_h264_fei_vaapi.cpp:436:34: error: ‘past_ref’ was not declared in this scope
         VAPictureFEI* l0surfs = &past_ref;
                                  ^
/home/box/MediaSDK/_studio/mfx_lib/shared/src/mfx_h264_fei_vaapi.cpp:442:30: error: ‘VA_PICTURE_FEI_TOP_FIELD’ was not declared in this scope
             l0surfs->flags = VA_PICTURE_FEI_TOP_FIELD;
                              ^
/home/box/MediaSDK/_studio/mfx_lib/shared/src/mfx_h264_fei_vaapi.cpp:445:30: error: ‘VA_PICTURE_FEI_BOTTOM_FIELD’ was not declared in this scope
             l0surfs->flags = VA_PICTURE_FEI_BOTTOM_FIELD;
                              ^
/home/box/MediaSDK/_studio/mfx_lib/shared/src/mfx_h264_fei_vaapi.cpp:448:30: error: ‘VA_PICTURE_FEI_PROGRESSIVE’ was not declared in this scope
             l0surfs->flags = VA_PICTURE_FEI_PROGRESSIVE;
                              ^
/home/box/MediaSDK/_studio/mfx_lib/shared/src/mfx_h264_fei_vaapi.cpp:453:31: error: ‘VA_PICTURE_FEI_CONTENT_UPDATED’ was not declared in this scope
             l0surfs->flags |= VA_PICTURE_FEI_CONTENT_UPDATED;
                               ^
/home/box/MediaSDK/_studio/mfx_lib/shared/src/mfx_h264_fei_vaapi.cpp:471:23: error: ‘l1surfs’ was not declared in this scope
         VAPictureFEI* l1surfs = &future_ref;
                       ^
/home/box/MediaSDK/_studio/mfx_lib/shared/src/mfx_h264_fei_vaapi.cpp:471:34: error: ‘future_ref’ was not declared in this scope
         VAPictureFEI* l1surfs = &future_ref;
                                  ^
/home/box/MediaSDK/_studio/mfx_lib/shared/src/mfx_h264_fei_vaapi.cpp:477:30: error: ‘VA_PICTURE_FEI_TOP_FIELD’ was not declared in this scope
             l1surfs->flags = VA_PICTURE_FEI_TOP_FIELD;
                              ^
/home/box/MediaSDK/_studio/mfx_lib/shared/src/mfx_h264_fei_vaapi.cpp:480:30: error: ‘VA_PICTURE_FEI_BOTTOM_FIELD’ was not declared in this scope
             l1surfs->flags = VA_PICTURE_FEI_BOTTOM_FIELD;
                              ^
/home/box/MediaSDK/_studio/mfx_lib/shared/src/mfx_h264_fei_vaapi.cpp:483:30: error: ‘VA_PICTURE_FEI_PROGRESSIVE’ was not declared in this scope
             l1surfs->flags = VA_PICTURE_FEI_PROGRESSIVE;
                              ^
/home/box/MediaSDK/_studio/mfx_lib/shared/src/mfx_h264_fei_vaapi.cpp:488:31: error: ‘VA_PICTURE_FEI_CONTENT_UPDATED’ was not declared in this scope
             l1surfs->flags |= VA_PICTURE_FEI_CONTENT_UPDATED;
                               ^
/home/box/MediaSDK/_studio/mfx_lib/shared/src/mfx_h264_fei_vaapi.cpp:538:47: error: ‘VA_PICTURE_FEI_TOP_FIELD’ was not declared in this scope
         statParams.stats_params.input.flags = VA_PICTURE_FEI_TOP_FIELD;
                                               ^
/home/box/MediaSDK/_studio/mfx_lib/shared/src/mfx_h264_fei_vaapi.cpp:542:47: error: ‘VA_PICTURE_FEI_BOTTOM_FIELD’ was not declared in this scope
         statParams.stats_params.input.flags = VA_PICTURE_FEI_BOTTOM_FIELD;
                                               ^
/home/box/MediaSDK/_studio/mfx_lib/shared/src/mfx_h264_fei_vaapi.cpp:546:47: error: ‘VA_PICTURE_FEI_PROGRESSIVE’ was not declared in this scope
         statParams.stats_params.input.flags = VA_PICTURE_FEI_PROGRESSIVE;
                                               ^
/home/box/MediaSDK/_studio/mfx_lib/shared/src/mfx_h264_fei_vaapi.cpp:551:48: error: ‘VA_PICTURE_FEI_CONTENT_UPDATED’ was not declared in this scope

**Comment by adydychk** [comment]
Hi @turingyao ,
Which version of libva do you use and from which source? How do you install it?

Current HEAD works well with libva compiled from: https://github.com/intel/libva.git

**Comment by turingyao** [comment]
Hi using both the master branch works! Thanks.

**Comment by adydychk** [comment]
My pleasure :)
