### ISSUE TITLE
Running sample_multi_transcode to composite 8x8 tiled 64ch streams results fail in TGL

### ISSUE THREAD

**Issue by UngTengEn** [Intel-Media-SDK/MediaSDK#2702]
Running the par file with sample_muti_transcode will result fail
[n64_d1_1080p.zip](https://github.com/Intel-Media-SDK/MediaSDK/files/6530237/n64_d1_1080p.zip)
There are 2 par file in the attachment, one for DP display and anther for HDMI display.

Here is the fail case :
root@tgl-rvp12:/mnt/persistent/home/root/hsd# LD_LIBRARY_PATH=/usr/local/share/mfx/samples:$LD_LIBRARY_PATH /usr/local/share/mfx/samples/sample_multi_transcode -par n64_d1_1080p_hdmi.par 2>&1 > n64_d1_1080p_hdmi_kernel_5.4.0.log
libva info: VA-API version 1.11.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /usr/local/lib64/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_11
libva info: va_openDriver() returns 0

[ERROR], sts=MFX_ERR_GPU_HANG(-21), Encode, VPP: SyncOperation failed at /usr/local/src/MediaSDK/samples/sample_multi_transcode/src/pipeline_transcode.cpp:1284

[ERROR], sts=MFX_ERR_ABORTED(-12), Run, CTranscodingPipeline::Run::Encode() [0x560279812ca0] failed at /usr/local/src/MediaSDK/samples/sample_multi_transcode/src/pipeline_transcode.cpp:4567

[ERROR], sts=MFX_ERR_ABORTED(-12), main, transcode.ProcessResult failed at /usr/local/src/MediaSDK/samples/sample_multi_transcode/src/sample_multi_transcode.cpp:1255

Here is the fail log.
[ubuntu_n64_d1_1080p_hdmi_kernel_5.4.0.log](https://github.com/Intel-Media-SDK/MediaSDK/files/6530156/ubuntu_n64_d1_1080p_hdmi_kernel_5.4.0.log)

If reduce the streams to 63 or have a 640x360 resolution video stream, the the issue seems goen.  But customer require 64 video streams with 640x480 resolution.

**Comment by UngTengEn** [comment]
The issue can be seen on Yocto and Ubuntu 18.04.

On ubuntu side build the [MediaSDK 21.1.3 stack](https://github.com/Intel-Media-SDK/MediaSDK/releases/tag/intel-mediasdk-21.1.3), and then boot into [console mode](https://askubuntu.com/questions/859630/how-to-start-ubuntu-in-console-mode#:~:text=Start%20Ubuntu%20from%20a%20virtual%20console%20Open%20a,prompt%20type%20your%20user%20password%20and%20press%20Enter.) to run the script.

**Comment by UngTengEn** [comment]
Running on Yocto ca see GPU Hung and reset back, and VAAPI trace seems mention 

Command :
LIBVA_TRACE=va LD_LIBRARY_PATH=/usr/share/mfx/samples /usr/share/mfx/samples/sample_multi_transcode -par n64_d1_1080p_hdmi.par

Kernel log :
[  740.461283] i915 0000:00:02.0: [drm] GPU HANG: ecode 12:1:85dcfffb, in sample_multi_tr [3939]
[  740.470883] i915 0000:00:02.0: [drm] Resetting rcs0 for stopped heartbeat on rcs0
[  740.478402] i915 0000:00:02.0: [drm] sample_multi_tr[3939] context reset due to GPU hang

VAAPI trace :
root@intel-corei7-64:~/hsd# grep HW_BUSY va*
va.180915.thd-0x0000118f:[6903.154808][ctx       none]=========vaSyncSurface ret = VA_STATUS_ERROR_HW_BUSY, HW busy now

**Comment by dmitryermilov** [comment]
@FurongZhang m any news?

**Comment by FurongZhang** [comment]
@UngTengEn , from the below log, it is rcs0. Right? In decoding or encoding? I will take a look at this issue.

[ 740.461283] i915 0000:00:02.0: [drm] GPU HANG: ecode 12:1:85dcfffb, in sample_multi_tr [3939]
[ 740.470883] i915 0000:00:02.0: [drm] Resetting rcs0 for stopped heartbeat on rcs0
[ 740.478402] i915 0000:00:02.0: [drm] sample_multi_tr[3939] context reset due to GPU hang

**Comment by UngTengEn** [comment]
It decode 64 videos and composite into single image.

**Comment by UngTengEn** [comment]
Hi @FurongZhang,

    Have try to modify the par script to use lowpower mode, but still seeing the issue.

-i::h264 test.h264 -join -hw  -async 1 -o::sink -vpp_comp_dst_x 720 -vpp_comp_dst_y 405 -vpp_comp_dst_w 240 -vpp_comp_dst_h 135 -ext_allocator _-scaling_mode lowpower_
-i::h264 test.h264 -join -hw  -async 1 -o::sink -vpp_comp_dst_x 960 -vpp_comp_dst_y 405 -vpp_comp_dst_w 240 -vpp_comp_dst_h 135 -ext_allocator _-scaling_mode lowpower_
-i::h264 test.h264 -join -hw  -async 1 -o::sink -vpp_comp_dst_x 1200 -vpp_comp_dst_y 405 -vpp_comp_dst_w 240 -vpp_comp_dst_h 135 -ext_allocator _-scaling_mode lowpower_
-i::h264 test.h264 -join -hw  -async 1 -o::sink -vpp_comp_dst_x 1440 -vpp_comp_dst_y 405 -vpp_comp_dst_w 240 -vpp_comp_dst_h 135 -ext_allocator -scaling_mode lowpower
... ...

**Comment by UngTengEn** [comment]
Try adding below options on the par script for the 64 session seems solve the problem.

-i::h264 test.h264 **-dec_postproc -w 240 -h 135** -join -hw  -async 1 -o::sink -vpp_comp_dst_x 0 -vpp_comp_dst_y 0 -vpp_comp_dst_w 240 -vpp_comp_ds t_h 135 -ext_allocator
-i::h264 test.h264 **-dec_postproc -w 240 -h 135** -join -hw  -async 1 -o::sink -vpp_comp_dst_x 240 -vpp_comp_dst_y 0 -vpp_comp_dst_w 240 -vpp_comp_ dst_h 135 -ext_allocator
-i::h264 test.h264 **-dec_postproc -w 240 -h 135** -join -hw  -async 1 -o::sink -vpp_comp_dst_x 480 -vpp_comp_dst_y 0 -vpp_comp_dst_w 240 -vpp_comp_ dst_h 135 -ext_allocator
-i::h264 test.h264 **-dec_postproc -w 240 -h 135** -join -hw  -async 1 -o::sink -vpp_comp_dst_x 720 -vpp_comp_dst_y 0 -vpp_comp_dst_w 240 -vpp_comp_ dst_h 135 -ext_allocator


Thanks
Teng

[n64_d1_1080p_hdmi-fine.zip](https://github.com/Intel-Media-SDK/MediaSDK/files/6690273/n64_d1_1080p_hdmi-fine.zip)
