### ISSUE TITLE
The kernel version for Comet Lake in  intel-mediasdk-19.4.0

### ISSUE THREAD

**Issue by HankWong-guangdong** [Intel-Media-SDK/MediaSDK#2703]
I want to ask if the intel-mediasdk-19.4.0 require the kernel version to be 5.3 or later for Comet Lake?

**Comment by HankWong-guangdong** [comment]
> Generally MediaSDK doesn't have direct dependencies from specific linux kernel. Media-driver has.
> I just checked git log of linux kernel. It seems first CML support appeared in 5.2: [torvalds/linux@a7b4dee](https://github.com/torvalds/linux/commit/a7b4deeb02b978bc59808cb13c93ba84f01023a4)
> 
> But searching more by "cometlake", "cml", "i915/cml" I see that there were several cometlake related fixed appeared in later linux kernels.

Thank you very much!

**Comment by dmitryermilov** [comment]
Welcome!
