### ISSUE TITLE
MFX_ERR_INCOMPATIBLE_VIDEO_PARAM error when implement adding source session dynamically  by reset mfxvpp in sink session to let it work

### ISSUE THREAD

**Issue by nickifu** [Intel-Media-SDK/MediaSDK#2721]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/fuqiaoni/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/fuqiaoni/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/fuqiaoni/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>

<p class=MsoNormal>We reference the sample MediaSDK Sample_multi_transcode to
implement the NVR use case, we meet MFX_ERR_INCOMPATIBLE_VIDEO_PARAM error
when<span style='mso-spacerun:yes'>  </span>implement the adding source session
dynamically <span style='mso-spacerun:yes'> </span>and try to reset mfxvpp in
sink session to let it work(removing source session dynamically works well), below
are the details:<o:p></o:p></p>

<p class=MsoNormal><b>The detail of the use case:<o:p></o:p></b></p>

<ol style='margin-top:0in' start=1 type=1>
 <li class=MsoListParagraphCxSpFirst style='margin-left:0in;mso-add-space:auto;
     mso-list:l0 level1 lfo1'>The pipeline including multiple input streaming from
     IP cameras and corresponding multiple decode + vpp sessions and then
     composition to one channel and encode it.<o:p></o:p></li>
</ol>

<p class=MsoListParagraphCxSpLast><o:p>&nbsp;</o:p></p>

<p class=MsoNormal style='margin-left:.5in'>N source sessions to 1 sink
session:<o:p></o:p></p>

<p class=MsoNormal style='margin-left:.5in'>Source sessions:<span
style='mso-spacerun:yes'>   </span>Ip cameras with encoded video data input
-&gt; decode -&gt; vpp(scaling) -&gt; buffer<o:p></o:p></p>

<p class=MsoNormal style='margin-left:.5in'>Sink session:<span
style='mso-spacerun:yes'>    </span>Buffers data from source sessions -&gt;
vpp(composition)<span style='mso-spacerun:yes'>  </span>-&gt; encode<o:p></o:p></p>

<p class=MsoNormal style='margin-left:.5in'><o:p>&nbsp;</o:p></p>

<ol style='margin-top:0in' start=2 type=1>
 <li class=MsoListParagraph style='margin-left:0in;mso-add-space:auto;
     mso-list:l0 level1 lfo1'>The ip camera(decode session) can be dynamically
     added or removed during running, and the adding or removing will not
     impact other sessions.<o:p></o:p></li>
</ol>

<p class=MsoNormal><b>Our implementation:<o:p></o:p></b></p>

<p class=MsoNormal>(Based on MediaSDK sample Sample_multi_transcode)<o:p></o:p></p>

<p class=MsoNormal>Adding decode session dynamically:<o:p></o:p></p>

<ol style='margin-top:0in' start=1 type=1>
 <li class=MsoListParagraphCxSpFirst style='margin-left:0in;mso-add-space:auto;
     mso-list:l1 level1 lfo2'>Initial/create new decode session.<o:p></o:p></li>
 <li class=MsoListParagraphCxSpMiddle style='margin-left:0in;mso-add-space:
     auto;mso-list:l1 level1 lfo2'>Add the created SafetySurfaceBuffer of the
     new decode session to the chain and make sure the encode session can
     access it by looping the chain in encode(). <o:p></o:p></li>
 <li class=MsoListParagraphCxSpMiddle style='margin-left:0in;mso-add-space:
     auto;mso-list:l1 level1 lfo2'>make sure the new decode session has joined
     to the joined sessions and assign the right parentpipeline for it.<o:p></o:p></li>
 <li class=MsoListParagraphCxSpMiddle style='margin-left:0in;mso-add-space:
     auto;mso-list:l1 level1 lfo2'>Update the mfx VPP Param for
     mfxExtVPPComposite<o:p></o:p></li>
 <li class=MsoListParagraphCxSpLast style='margin-left:0in;mso-add-space:auto;
     mso-list:l1 level1 lfo2'>Reset the mfx VPP in the encode session.<o:p></o:p></li>
</ol>

<p class=MsoNormal><b>The issue and our analysis:<o:p></o:p></b></p>

<p class=MsoNormal>We process it as above, but we meet an issue when reset the
mfx vpp(step 5) with the error MFX_ERR_INCOMPATIBLE_VIDEO_PARAM, after looking
into the MediaSDK code, we found below logic in ConfigureExecuteParams and it
will be called when mfx_vpp Reset in mfx_vpp_hw.cpp:<o:p></o:p></p>

mfxStatus ConfigureExecuteParams(
--
  | mfxVideoParam & videoParam, // [IN]
  | mfxVppCaps & caps,          // [IN]
  | mfxExecuteParams & executeParams, //   [OUT]
  | Config & config)                  // [OUT]

<p class=MsoNormal><i><span style='font-size:9.0pt;line-height:106%'>{<o:p></o:p></span></i></p>

<p class=MsoNormal><i><span style='font-size:9.0pt;line-height:106%'>…<o:p></o:p></span></i></p>

<p class=MsoNormal style='text-indent:.5in'><i><span style='font-size:9.0pt;
line-height:106%'>case MFX_EXTBUFF_VPP_COMPOSITE:<o:p></o:p></span></i></p>

<p class=MsoNormal><i><span style='font-size:9.0pt;line-height:106%'>…<o:p></o:p></span></i></p>

<p class=MsoNormal><i><span style='font-size:9.0pt;line-height:106%'><span
style='mso-spacerun:yes'>            </span>{if
(!executeParams.dstRects.empty())<o:p></o:p></span></i></p>

<p class=MsoNormal><i><span style='font-size:9.0pt;line-height:106%'><span
style='mso-spacerun:yes'>                        </span>{<o:p></o:p></span></i></p>

<p class=MsoNormal><b><i><span style='font-size:9.0pt;line-height:106%'><span
style='mso-spacerun:yes'>                            </span>if
(executeParams.dstRects.size() &lt; StreamCount)<o:p></o:p></span></i></b></p>

<p class=MsoNormal><b><i><span style='font-size:9.0pt;line-height:106%'><span
style='mso-spacerun:yes'>                                </span>return MFX_ERR_INCOMPATIBLE_VIDEO_PARAM;<o:p></o:p></span></i></b></p>

<p class=MsoNormal><b><i><span style='font-size:9.0pt;line-height:106%'><span
style='mso-spacerun:yes'>                        </span>}<o:p></o:p></span></i></b></p>

<p class=MsoNormal><i><span style='font-size:9.0pt;line-height:106%'><o:p>&nbsp;</o:p></span></i></p>

<p class=MsoNormal><i><span style='font-size:9.0pt;line-height:106%'><span
style='mso-spacerun:yes'>                        </span>if
(executeParams.dstRects.size() != StreamCount)<o:p></o:p></span></i></p>

<p class=MsoNormal><i><span style='font-size:9.0pt;line-height:106%'><span
style='mso-spacerun:yes'>                        </span>{<o:p></o:p></span></i></p>

<p class=MsoNormal><i><span style='font-size:9.0pt;line-height:106%'><span
style='mso-spacerun:yes'>                           
</span>executeParams.dstRects.clear();<o:p></o:p></span></i></p>

<p class=MsoNormal><i><span style='font-size:9.0pt;line-height:106%'><span
style='mso-spacerun:yes'>                            </span>executeParams.dstRects.resize(StreamCount);<o:p></o:p></span></i></p>

<p class=MsoNormal><i><span style='font-size:9.0pt;line-height:106%'><span
style='mso-spacerun:yes'>                        </span>}<o:p></o:p></span></i></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal>For adding decode session case, the executeParams.dstRects.size()
is smaller than StreamCount because we have updated the streamCount +1 for the
new decode session, so it will return MFX_ERR_INCOMPATIBLE_VIDEO_PARAM. <b><o:p></o:p></b></p>

<p class=MsoNormal>It can be resolved if we do not run <b>the code in bold</b> and
run its below code to resize the<b> </b>executeParams.dstRects to StreamCount
size instead.<o:p></o:p></p>

<p class=MsoNormal><span style='mso-spacerun:yes'>                       
</span>if (executeParams.dstRects.size() != StreamCount)<o:p></o:p></p>

<p class=MsoNormal><span style='mso-spacerun:yes'>                       
</span>{<o:p></o:p></p>

<p class=MsoNormal><span style='mso-spacerun:yes'>         </span><span
style='mso-spacerun:yes'>                   </span>executeParams.dstRects.clear();<o:p></o:p></p>

<p class=MsoNormal><span style='mso-spacerun:yes'>                           
</span>executeParams.dstRects.resize(StreamCount);<o:p></o:p></p>

<p class=MsoNormal><span style='mso-spacerun:yes'>                       
</span>}<o:p></o:p></p>

<p class=MsoNormal><b>Suggest:<o:p></o:p></b></p>

<p class=MsoNormal>So can we change the logic that if the ConfigureExecuteParams
is called by mfx_vpp_hw.Reset(), do not return MFX_ERR_INCOMPATIBLE_VIDEO_PARAM
but resize the executeParams.dstRects instead<b>?<o:p></o:p></b></p>

<p class=MsoNormal><span style='mso-spacerun:yes'>                     
</span>if (executeParams.dstRects.size() &lt; StreamCount <b>&amp;&amp;
!isReset</b>) //isReset is new added param<o:p></o:p></p>

<p class=MsoNormal><span
style='mso-spacerun:yes'>                                </span>return
MFX_ERR_INCOMPATIBLE_VIDEO_PARAM;<o:p></o:p></p>

<p class=MsoNormal><span style='mso-spacerun:yes'>                       
</span>}<o:p></o:p></p>

<p class=MsoNormal>We have verified that it can fix the issue that adding
source session dynamically works well.<o:p></o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal>FYI, For Removing decode session dynamically, it can work
well with blow process.<o:p></o:p></p>

<ol style='margin-top:0in' start=1 type=1>
 <li class=MsoListParagraphCxSpFirst style='margin-left:0in;mso-add-space:auto;
     mso-list:l2 level1 lfo3'>Exit the decode loop in decode() to stop the
     decode session which you want to stop.<o:p></o:p></li>
 <li class=MsoListParagraphCxSpMiddle style='margin-left:0in;mso-add-space:
     auto;mso-list:l2 level1 lfo3'>Skip the buffer of the decode session when
     loop the SafetySurfaceBuffers chain in encode(), <o:p></o:p></li>
 <li class=MsoListParagraphCxSpLast style='margin-left:0in;mso-add-space:auto;
     mso-list:l2 level1 lfo3'>Update the mfx VPP Param for mfxExtVPPComposite
     and reset the VPP in encode.<o:p></o:p></li>
</ol>

</body>

</html>

**Comment by FurongZhang** [comment]
@nickifu , do you have a PR link?

**Comment by Nicki-fu** [comment]
> @nickifu , do you have a PR link?

@FurongZhang  No, I did not submit PR.

**Comment by dmitryermilov** [comment]
Basically your suggestion makes sense to me . However I looked at git history in internal repo (before Linux opensource happened) and found this code internationally was added there:
```
                        StreamCount = extComp->NumInputStream;
+
+                        if (!executeParams.dstRects.empty())
+                        {
+                            if (executeParams.dstRects.size() < StreamCount)
+                                return MFX_ERR_INCOMPATIBLE_VIDEO_PARAM;
+                        }
+
                        if (executeParams.dstRects.size() != StreamCount)
                        {
```

We have to understand why. I'll try to find out. If no success, we can proceed with check-in.

**Comment by dmitryermilov** [comment]
[MSDK spec  ](https://github.com/Intel-Media-SDK/MediaSDK/blob/master/doc/mediasdk-man.md#mfxextvppcomposite)says:
 
<html>
<body>


NumInputStream | Number of input surfaces to compose one output. May be changed dynamically at runtime through Reset. Number of surfaces can be decreased or increased, but should not exceed number specified during initialization. Query mode 2 should be used to find maximum supported number.
-- | --



</body>
</html>

I assume this change in code was motivated by this wording. BUT, https://github.com/Intel-Media-SDK/MediaSDK/blob/edd272aa26ad13c614917bf96bfc9cb661c5160d/_studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp#L5874 is still an incorrect check because it compares latest params (before Reset) with reset params, not original Init params . By spec it’s a valid scenario:
Init (10 channels) -> Reset (5 channels) -> Reset (10 channels). But code forbids and it’s a bug. @FurongZhang , please find an owner from VP scrum to fix it.

**Comment by MicroYY** [comment]
Hi @Nicki-fu Submitted PR. Could you pls have a try? Thanks!
https://github.com/Intel-Media-SDK/MediaSDK/pull/2758

**Comment by dmitryermilov** [comment]
> Hi @Nicki-fu Submitted PR. Could you pls have a try? Thanks!
> #2758

The fix is not ready yet .   No need to check it because it won't be merged in current version.

**Comment by dmitryermilov** [comment]
The fix is ready for verification now.

**Comment by Nicki-fu** [comment]
> The fix is ready for verification now.

Hi Dmitry,
    MFX_CHECK(StreamCount <= executeParams.initialStreamNum, MFX_ERR_INCOMPATIBLE_VIDEO_PARAM);
Currently, I have no the environment to verify the fix, but from the code, I think it doesn't work for the case if user **reduce** the Num of the input channels at runtime by reset.

**Comment by MicroYY** [comment]
> > The fix is ready for verification now.
> 
> Hi Dmitry,
> MFX_CHECK(StreamCount <= executeParams.initialStreamNum, MFX_ERR_INCOMPATIBLE_VIDEO_PARAM);
> Currently, I have no the environment to verify the fix, but from the code, I think it doesn't work for the case if user **reduce** the Num of the input channels at runtime by reset.

Hi Nicki
It should work because the initial number of layers is recorded and it's compared to current count when reset.

**Comment by Nicki-fu** [comment]
> > > The fix is ready for verification now.
> > 
> > 
> > Hi Dmitry,
> > MFX_CHECK(StreamCount <= executeParams.initialStreamNum, MFX_ERR_INCOMPATIBLE_VIDEO_PARAM);
> > Currently, I have no the environment to verify the fix, but from the code, I think it doesn't work for the case if user **reduce** the Num of the input channels at runtime by reset.
> 
> Hi Nicki
> It should work because the initial number of layers is recorded and it's compared to current count when reset.

Hi MicroYY,
The same case as Dmitry mentioned：
10 -> 5
If the user wants to remove some input channels for composition at runtime, user may reduce the value of extComp->NumInputStream which is streamCount, the streamCount <=executeParams.initialStreamNum is expected, but in the code, it will return MFX_ERR_INCOMPATIBLE_VIDEO_PARAM that the case runs to be Interrupted. 
Please correct me if I am wrong.

**Comment by MicroYY** [comment]
> > > > The fix is ready for verification now.
> > > 
> > > 
> > > Hi Dmitry,
> > > MFX_CHECK(StreamCount <= executeParams.initialStreamNum, MFX_ERR_INCOMPATIBLE_VIDEO_PARAM);
> > > Currently, I have no the environment to verify the fix, but from the code, I think it doesn't work for the case if user **reduce** the Num of the input channels at runtime by reset.
> > 
> > 
> > Hi Nicki
> > It should work because the initial number of layers is recorded and it's compared to current count when reset.
> 
> Hi MicroYY,
> The same case as Dmitry mentioned：
> 10 -> 5
> If the user wants to remove some input channels for composition at runtime, user may reduce the value of extComp->NumInputStream which is streamCount, the streamCount <=executeParams.initialStreamNum is expected, but in the code, it will return MFX_ERR_INCOMPATIBLE_VIDEO_PARAM that the case runs to be Interrupted.
> Please correct me if I am wrong.

Hi Nicki

`MFX_CHECK(EXPR, ERR)` expands to  `{ if (!(EXPR)) MFX_RETURN(ERR); }` so no error will be returned.

**Comment by Nicki-fu** [comment]
> > > The fix is ready for verification now.
> > 
> > 
> > Hi Dmitry,
> > MFX_CHECK(StreamCount <= executeParams.initialStreamNum, MFX_ERR_INCOMPATIBLE_VIDEO_PARAM);
> > Currently, I have no the environment to verify the fix, but from the code, I think it doesn't work for the case if user **reduce** the Num of the input channels at runtime by reset.
> 
> Hi Nicki
> It should work because the initial number of layers is recorded and it's compared to current count when reset.

Oh, Sorry for the mistake, So the adjustment is because of  "but should not exceed number specified during initialization" , could you tell that why it has this limitation? thanks very much!

**Comment by Nicki-fu** [comment]
If user wants to increase the input channels than first time, what's the BKM to achieve this? thanks!
10 ->11

**Comment by MicroYY** [comment]
Hi Nicki
I guess in such cases (10 -> 11), we may not have so many surfaces allocated. Possibly we try to allocate enough surfaces (maximum count of layers) rather than the initial count.
@dmitryermilov Could you comment on this?

**Comment by dmitryermilov** [comment]
> If user wants to increase the input channels than first time, what's the BKM to achieve this? thanks!
> 10 ->11



> Hi Nicki
> I guess in such cases (10 -> 11), we may not have so many surfaces allocated. Possibly we try to allocate enough surfaces (maximum count of layers) rather than the initial count.
> @dmitryermilov Could you comment on this?

Hi @Nicki-fu  and @MicroYY ,

The right way in this case to initialize with higher num of channels, then immediately make a Reset call with currently desired num of channels. Please comment if it works for you.

**Comment by Nicki-fu** [comment]
> > If user wants to increase the input channels than first time, what's the BKM to achieve this? thanks!
> > 10 ->11
> 
> > Hi Nicki
> > I guess in such cases (10 -> 11), we may not have so many surfaces allocated. Possibly we try to allocate enough surfaces (maximum count of layers) rather than the initial count.
> > @dmitryermilov Could you comment on this?
> 
> Hi @Nicki-fu and @MicroYY ,
> 
> The right way in this case to initialize with higher num of channels, then immediately make a Reset call with currently desired num of channels. Please comment if it works for you.

Hi Dmitry,
Now there is no environment to verify this, but it sounds work, and the fixed looks good if there is the limitation "but should not exceed number specified during initialization".

**Comment by dmitryermilov** [comment]
Hi Nicky,

Okay. Let us merge the PR.
