### ISSUE TITLE
issues when transcode from h264 to h265

### ISSUE THREAD

**Issue by guoyejun** [Intel-Media-SDK/MediaSDK#273]
msdk: ebddee333c54f8349ae49abef9e772d7229f2f81, build with Debug option.
libva: b3be72a5a110880f70626d7c3bed953cdde124b2
media-driver: 7c241661b333516b1c6698163b6c979319506fc3

sample_multi_transcode is able to transcode from h265 to h265, from h265 to h264, from h264 to h264, but, when transcode from h264 to h265, the video with 1920x1080 is transcoded to video with 1920x540, with the following command:
$ ./sample_multi_transcode -hw -i::h264 ~/xxx.264 -o::h265 ./test.265

**Comment by otsirule** [comment]
Hello,

If your h264 stream is interlaced, then sample_multi_transcode enables interlace encoding for h265 by default. For that, VPP field splitting is enabled that produces field pair (top and bottom) with resolution 1920x540 each and encoder inserts picture timing SEI with picstruct type for every field picture in the bitstream.

**Comment by guoyejun** [comment]
thanks otsirule,  i'll check my stream. Just assume it is interlaced, from end user's perspective, what commands (or command options) should I use to convert this h264 to h265 without resolution change.

**Comment by otsirule** [comment]
The only way to disable interlace encoding (both h264 and h265) in sample_multi_transcode (SMT) is enabling deinterlacer in the command line (-deinterlace::ADI/ADI_SCD/ADI_NO_REF/BOB).

**Comment by guoyejun** [comment]
got it, thanks.
