### ISSUE TITLE
Sample - CEncodingPipeline::InitMfxPreEncParams does not validate pInParams parameter properly

### ISSUE THREAD

**Issue by CarlG12** [Intel-Media-SDK/MediaSDK#2735]
In the sample sample_encode, the method "CEncodingPipeline::InitMfxPreEncParams" implements parameter validation. However, pInParams->bEnableExtLA is validate before ensuring that pInParams is not null. This behaviors might cause segmentation fault.

Current implementation:
`mfxStatus CEncodingPipeline::InitMfxPreEncParams(sInputParams *pInParams)
{
    MSDK_CHECK_ERROR(pInParams->bEnableExtLA, false, MFX_ERR_INVALID_VIDEO_PARAM);
    MSDK_CHECK_POINTER(pInParams,  MFX_ERR_NULL_PTR);
`

Suggested implementation:
`mfxStatus CEncodingPipeline::InitMfxPreEncParams(sInputParams *pInParams)
{
    MSDK_CHECK_POINTER(pInParams,  MFX_ERR_NULL_PTR);
    MSDK_CHECK_ERROR(pInParams->bEnableExtLA, false, MFX_ERR_INVALID_VIDEO_PARAM);
`

**Comment by SofyaBalandina** [comment]
Hi, PR with fix is made #2738
