### ISSUE TITLE
HEVC hardware encoder worked well in Gen11 i3, not in Gen10 and Gen11 i7 

### ISSUE THREAD

**Issue by jiangjianping** [Intel-Media-SDK/MediaSDK#2756]
The same windows 10 app got the difference result in the different kind of computers, why?

The MSDK HEVC hardware encoder worked well:
 
![WechatIMG31](https://user-images.githubusercontent.com/14144270/129471643-6e2c7aac-4b87-4cc7-b67f-5b8b988b8327.jpeg)

Sometime works, but often return the -17 error:
 
![WechatIMG33](https://user-images.githubusercontent.com/14144270/129471733-313dcfef-204b-4f80-85cd-72eca7b45e4f.jpeg)

Always get the -3 when init the encoder:
![屏幕快照 2021-08-15 下午3 46 42](https://user-images.githubusercontent.com/14144270/129471796-e4f12330-fd97-4ee9-a356-44afaf9f4671.png)

**Comment by dmitryermilov** [comment]
Hi @jiangjianping ,

What app are you running? Propriety one or sample_encode ? Please try to reproduce via sample_encode and share cmd line and console output.

**Comment by jiangjianping** [comment]
@dmitryermilov 

My own app which is using media sdk.  I will try to reproduce this via sample_encode. Thanks.

**Comment by jiangjianping** [comment]
this issue can be closed.
