### ISSUE TITLE
HEVC software encoder cannot output timecode SEI correctly during interlace encoding

### ISSUE THREAD

**Issue by IKEZOET-GVKOBE-DEV** [Intel-Media-SDK/MediaSDK#2766]
In the case of the software encoder, since it encodes frame, set two timecode SEI payloads in mfxEncodeCtrl.Payload, two timecode SEIs will be output in both fields.
I expect the first timecode SEI to be output to the 1st field and the second timecode SEI to be output to the 2nd field.

In the case of Hardware encoder, since it encodes for each field, only one timecode SEI needs to be set, so the output is correct.

Confirmed with MSDK 2019R1 and 2021R1. (Windows)

**Comment by daleksan** [comment]
Hi @thomasli21801  can you take a look on this request?

**Comment by thomasli21801** [comment]
There is no interlace support commitment for HEVC VDEnc currently.
May I know what is the usage that you need to use interlace content for HEVC?
