### ISSUE TITLE
ffmpeg h264_qsv encoder 'forced_idr' option bug?

### ISSUE THREAD

**Issue by steven8274** [Intel-Media-SDK/MediaSDK#2776]
I use qsv hardware H.264 encoder from ffmpeg.I need the encoder to output IDR frames when I set AVFrame's 'key_frame' property to 1 and 'pict_type' to AV_PICTURE_TYPE_I, and it to output none-IDR frames when I set AVFrame's 'key_frame' property to 0 and 'pict_type' to AV_PICTURE_TYPE_P.So I set the private data of encoder as:
`av_opt_set(m_ctx->priv_data, "forced_idr", "1", 0);`
 But once I set an AVFrame's 'key_frame' property to 1 and 'pict_type' to AV_PICTURE_TYPE_I, all subsequent frames output are IDR frames.
How can I output frames as my expectation?
Thanks in advance!

**Comment by dmitryermilov** [comment]
@xhaihao , can you please help to comment?

**Comment by xhaihao** [comment]
@steven8274 could you please have a try with http://ffmpeg.org/pipermail/ffmpeg-devel/2021-January/274342.html ?

**Comment by steven8274** [comment]
> @steven8274 could you please have a try with http://ffmpeg.org/pipermail/ffmpeg-devel/2021-January/274342.html ?

Thanks very much, it seems to work.I'll try it.

**Comment by steven8274** [comment]
Yes!http://ffmpeg.org/pipermail/ffmpeg-devel/2021-January/274342.html  works!

**Comment by xhaihao** [comment]
@steven8274 the patch was merged into FFmpeg master, you may use the latest FFmpeg now.

**Comment by steven8274** [comment]
> @steven8274 the patch was merged into FFmpeg master, you may use the latest FFmpeg now.

That's great!Thank you very much!
