### ISSUE TITLE
Why HEVC HW encoder performance varied much in different motherboard?

### ISSUE THREAD

**Issue by jiangjianping** [Intel-Media-SDK/MediaSDK#2781]
I test the i3/i5 hw encoder performance and found that the performance varied very much in different main motherboard. Both testing computers have the same SSD and memory. Why? Thank you.

**Comment by jiangjianping** [comment]
The real problem is memory, close now.

**Comment by dmitryermilov** [comment]
@jiangjianping , just wondering, was it about dual channel memory ?

**Comment by jiangjianping** [comment]
@dmitryermilov 

That's right. memory located some sockets did not provide real dual channel performance.
