### ISSUE TITLE
[TGL] segfaults in "sample_multi_transcode" when they run in parallel

### ISSUE THREAD

**Issue by eero-t** [Intel-Media-SDK/MediaSDK#2822]
## System information
- 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
- Intel Corporation TigerLake GT2 [Iris Xe Graphics] [8086:9a60] (rev 01)
- Whole GPU stack built from git, starting from drm-tip kernel
- VT-d enabled from BIOS (i.e. GFX IOMMU is active) [1]

## Issue behavior

Run 50 parallel instances of this:
`sample_multi_transcode -i::h264 1280x720p_29.97_10mb_h264_cabac.264 -o::h264 0030_HD22_1.0.h264 -b 800 -u 4 -n 1200 -f 15 -w 352 -h 240 -FRC::PT -async 4 -hw`

And 13 parallel instances of this:
`sample_multi_transcode -i::h264 1280x720p_29.97_10mb_h264_cabac.264 -o::h264 0027_HD20_1.0.h264 -b 2000 -u 4 -n 1200 -async 4 -hw`

### Current behavior

With the first test-case, there are random crashes in 0-2 of the 50 instances, with dmesg from the automated testing showing "sample_multi_transcode" crash to happen somewhere in libc:
```
 6929.748524] sample_multi_tr[171059]: segfault at c ip 00007fccb3c836ff sp 00007fcca95beaf8 error 6 in libc-2.31.so[7fccb3b1a000+178000]
[ 6929.748544] Code: 80 fa 01 77 3b 72 05 0f b6 0e 88 0f c3 c5 fa 6f 06 c5 fa 6f 4c 16 f0 c5 fa 7f 07 c5 fa 7f 4c 17 f0 c3 48 8b 4c 16 f8 48 8b 36 <48> 89 4c 17 f8 48 89 37 c3 8b 4c 16 fc 8b 36 89 4c 17 fc 89 37 c3
```
This started around 26th of August (plus/minus couple of days).  Only thing that changed should be the media stack.

Second test-case crashes much more rarely, but it crashes in the same place in libc, so  it's likely to have started at same time from the same cause.

### The expected behavior

No crashes.

There are no crashes on GEN9 HW with the same tests, and there no crashes on TGL when doing similar operation using FFmpeg QSV or VA-API backends, so this seems more likely a bug in the tool than the driver, if that is possible.

My assumption is that kernel sometimes returns an error for the transcode operation in this kind of heavily contended cases [1], and tool does not handle such error properly any more.

[1] Kernel has had earlier problems with these kind of cases, but it handles them nowadays better.  There may still be issues with VT-d / GFX / IOMMU though, see: https://gitlab.freedesktop.org/drm/intel/-/issues/4082

**Comment by dmitryermilov** [comment]
I've been working on "another" crash reproduced  in a high density usage case on TGL . In my issue, crash most likely was introduced by https://github.com/intel/media-driver/commit/976b1035d34a34da7bd2e6b7b8ff45634dd93373#diff-e7c132d1e16b5abc85b439f6bed0e226e72a2fc183b91670ab4d2934d327cb48 . Time of check-in fits your description. @eero-t , do you  have a call stack of the crash so that I can compare?

**Comment by eero-t** [comment]
Unfortunately not.  I only see the crashes from dmesg hours later (these tests are run as part of much larger test-set, and I do not have time to debug them myself).  They happen always at the same offset in libc i.e. in same function.  This is from last evening build:
```
[ 9703.324785] Iteration 1/3: 13x sample_multi_transcode -i::h264 1280x720p_29.97_10mb_h264_cabac.264 -o::h264 0027_HD20_1.0.h264 -b 2000 -u 4 -n 1200 -async 4 -hw
[ 9708.173419] sample_multi_tr[56541]: segfault at c ip 00007f1de22226ff sp 00007f1dd7353af8 error 6 in libc-2.31.so[7f1de20b9000+178000]
[ 9708.173432] Code: 80 fa 01 77 3b 72 05 0f b6 0e 88 0f c3 c5 fa 6f 06 c5 fa 6f 4c 16 f0 c5 fa 7f 07 c5 fa 7f 4c 17 f0 c3 48 8b 4c 16 f8 48 8b 36 <48> 89 4c 17 f8 48 89 37 c3 8b 4c 16 fc 8b 36 89 4c 17 fc 89 37 c3
...
[ 9886.608558] Iteration 3/3: 50x sample_multi_transcode -i::h264 1280x720p_29.97_10mb_h264_cabac.264 -o::h264 0030_HD22_1.0.h264 -b 800 -u 4 -n 1200 -f 15 -w 352 -h 240 -FRC::PT -async 4 -hw
[ 9897.181146] sample_multi_tr[61577]: segfault at d ip 00007f6aa5aab71d sp 00007f6a9bbdeae8 error 6 in libc-2.31.so[7f6aa5942000+178000]
[ 9897.181158] Code: 4c 17 f0 c3 48 8b 4c 16 f8 48 8b 36 48 89 4c 17 f8 48 89 37 c3 8b 4c 16 fc 8b 36 89 4c 17 fc 89 37 c3 0f b7 4c 16 fe 0f b7 36 <66> 89 4c 17 fe 66 89 37 c3 48 81 fa 00 10 00 00 0f 87 6c ff ff ff
```
I do not see any exported functions near that crash offset:
```
$ readelf -s /lib/x86_64-linux-gnu/libc-2.31.so | grep 001[6-8a-b] | sort -k2
...
  1859: 00000000001663f0    17 FUNC    GLOBAL DEFAULT   16 __nss_database_lookup@GLIBC_2.2.5
   525: 00000000001b7405     5 OBJECT  GLOBAL DEFAULT   18 _libc_intl_domainname@@GLIBC_2.2.5
```
So I assume media crash is happening in some static (or dynamically generated) libc function, that gets bad data from  "sample_multi_transcode" or media driver, although in latter it's probably some unique way in which the tool uses MediaSDK / media-driver compared to FFmpeg + QSV (as that combo does not crash with the same test setup).

**Comment by dmitryermilov** [comment]
Fixed by https://github.com/intel/media-driver/commit/6b8bf2f2a88a05aa16f48077688104176da2c204

**Comment by eero-t** [comment]
From builds before that commit there are crashes in dmesg, with builds after it, they're gone => VERIFIED

PS. It was odd that this showed in dmesg only with "sample_multi_transcode", considering that I'm running same parallel tests also with FFmpeg, using the same Python script (with same Popen() options etc). Maybe FFmpeg catches the crashes so kernel does not report them?

Or maybe   "sample_multi_transcode"  does threading differently from FFmpeg? (I know that FFmpeg QSV & VA-API backends thread differently, which can sometimes result in noticeable perf differences)
