### ISSUE TITLE
deinterlace double frame rate

### ISSUE THREAD

**Issue by fut33v** [Intel-Media-SDK/MediaSDK#2834]
## System information
Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz

### Describe the current behavior
can't set options for VPP double frame rate deinterlacing:

```
        mfxParams.vpp.Out.FrameRateExtN = mfxParams.vpp.In.FrameRateExtN * 2;
        extVppDeinterlacing->Mode = MFX_DEINTERLACING_AUTO_DOUBLE;
```
m_MFXVideoVPP_Query returns MFX_ERR_UNSUPPORTED

## Debug information
libva info: VA-API version 1.11.0
[vainfo.log](https://github.com/Intel-Media-SDK/MediaSDK/files/7624628/vainfo.log)

**Comment by dmitryermilov** [comment]
Such mode isn't supported. Please use MFX_DEINTERLACING_ADVANCED or  MFX_DEINTERLACING_ADVANCED_SCD instead.

**Comment by fut33v** [comment]
Thank you, it is not obvious why this mode is still in enum.

**Comment by dmitryermilov** [comment]
Even something is not supported anymore by current version of run-time library, it remains in API. Overwise re-compilation of legacy applications will be broken.

**Comment by fut33v** [comment]
strange, with MFX_DEINTERLACING_ADVANCED
m_MFXVideoVPP_RunFrameVPPAsync returns MFX_ERR_UNDEFINED_BEHAVIOR

**Comment by fut33v** [comment]
Strange, MFXVideoVPP_RunFrameVPPAsync returns MFX_ERR_NONE each 2 time and MFX_ERR_MORE_SURFACE another instead of returning MFX_ERR_MORE_SURFACE every time.

**Comment by fut33v** [comment]
Unfortunately my program fails to start with tracer with seg fault
91038 segmentation fault (core dumped)  LD_PRELOAD=libmfx-tracer.so.1.35

91038 2021-12-14 17:15:32     mfx_tracer: dll_init() +
91038 2021-12-14 17:15:32     mfx_tracer: lib=libmfxhw64.so.1
91038 2021-12-14 17:15:32     mfx_tracer: dll_init() - 


91038 2021-12-14 17:15:32 function: MFXInitEx(mfxInitParam par={.Implementation=MFX_IMPL_HARDWARE_ANY, .Version=0x7ffc182a5494}, mfxSession *session=0x1f974d0) +
91038 2021-12-14 17:15:32     par.Implementation=MFX_IMPL_HARDWARE_ANY
91038 2021-12-14 17:15:32     par.Version.Major=1
91038 2021-12-14 17:15:32     par.Version.Minor=34
91038 2021-12-14 17:15:32     par.Version.Version=65570
91038 2021-12-14 17:15:32     par.ExternalThreads=0
91038 2021-12-14 17:15:32     par.NumExtParam=0
91038 2021-12-14 17:15:32     par.ExtParam=0000000000000000
91038 2021-12-14 17:15:32     par.reserved2[]={ 0, 0, 0, 0, 0 }
91038 2021-12-14 17:15:32     par.GPUCopy=0
91038 2021-12-14 17:15:32     par.reserved[]={ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }

91038 2021-12-14 17:15:32     mfxSession session=0
91038 2021-12-14 17:15:32 >> MFXInitEx called
91038 2021-12-14 17:15:32     par.Implementation=MFX_IMPL_HARDWARE_ANY
91038 2021-12-14 17:15:32     par.Version.Major=1
91038 2021-12-14 17:15:32     par.Version.Minor=34
91038 2021-12-14 17:15:32     par.Version.Version=65570
91038 2021-12-14 17:15:32     par.ExternalThreads=0
91038 2021-12-14 17:15:32     par.NumExtParam=0
91038 2021-12-14 17:15:32     par.ExtParam=0000000000000000
91038 2021-12-14 17:15:32     par.reserved2[]={ 0, 0, 0, 0, 0 }
91038 2021-12-14 17:15:32     par.GPUCopy=0
91038 2021-12-14 17:15:32     par.reserved[]={ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }

91038 2021-12-14 17:15:32     mfxSession session=0x1f7e4e8
91038 2021-12-14 17:15:32 function: MFXInitEx(0.527 msec, status=MFX_ERR_NONE) -

**Comment by dmitryermilov** [comment]
Weird. I can't double check how you call MFXVideoVPP_RunFrameVPPAsync but I assume you do it correctly. Deinterlace takes one input interlaced surface and produced two progressive surfaces. So the statuses, you get, are correct.
```
input = GetFromSomewhere()
output = FindFreeSurface();
sts = MFXVideoVPP_RunFrameVPPAsync (input, output, &syncp); // MFX_ERR_MORE_SURFACE - need more output surfaces to make DI
if (syncp)
{
  SyncOperation(syncp);
  MakeSomethingWith(output)
}
if (sts == MFX_ERR_MORE_SURFACE)
{
  output1 = FindFreeSurface();
  MFXVideoVPP_RunFrameVPPAsync (input, output1, &syncp); // MFX_ERR_NONE- 2nd surface provided, DI for current input frame is done
  if (syncp)
  {
    SyncOperation(syncp);
    MakeSomethingWith(output1)
  }
}
```
