### ISSUE TITLE
Support for H.264 High10 Profile?

### ISSUE THREAD

**Issue by softworkz** [Intel-Media-SDK/MediaSDK#2845]
Hi,

I'm wondering whether MFX_PROFILE_AVC_HIGH10 is meant to be supported.

At this place in CheckVideoParam() it is included in the switch for supported profiles:

https://github.com/Intel-Media-SDK/MediaSDK/blob/bdc576c121e19018c20dab30d5b3c821695d93f4/_studio/shared/umc/codec/h264_dec/src/umc_h264_mfx_supplier.cpp#L1535-L1550

But further up in Query(), it is missing:

[MFX_PROFILE_AVC_HIGH10
](https://github.com/Intel-Media-SDK/MediaSDK/blob/bdc576c121e19018c20dab30d5b3c821695d93f4/_studio/shared/umc/codec/h264_dec/src/umc_h264_mfx_supplier.cpp#L1066-L1079)

Probably one of the two places is wrong, but which one...could it possibly work? 

I mean, when MFX_PROFILE_AVC_HIGH_422 is supported, it doesn't seem unlikely that High10 could work either?

Thanks,
softworkz

**Comment by dmitryermilov** [comment]
Hi @softworkz ,

Is the request for decoder or encode?

**Comment by softworkz** [comment]
decode only

**Comment by wangyan-intel** [comment]
@chuanli1 will check it. Thanks.

**Comment by dmitryermilov** [comment]
Unfortunately HW AVC doesn't support 10 bit. This code above is leftover from SW AVC decoder. @chuanli1, it would be great to remove this code to avoid confusion. The same is for VPL.

**Comment by softworkz** [comment]
OK thanks.
What about the MFX_PROFILE_AVC_HIGH_422 profile? I suppose it's not supported in HW either?

**Comment by chuanli1** [comment]
Hi @dmitryermilov,
According to this open driver code:https://github.com/intel/media-driver/blob/master/media_driver/linux/common/ddi/media_libva_caps.cpp#L3130-L3137, the hw seems to only support VAProfileH264ConstrainedBaseline, VAProfileH264Main and VAProfileH264High.

**Comment by softworkz** [comment]
@chuanli1 - Thanks a lot for looking it up. 

The above is for Linux/VAAPI - can you find out how the situation is for Windows?

**Comment by chuanli1** [comment]
Hi @softworkz ,
HW AVC doesn't support MFX_PROFILE_AVC_HIGH10 and MFX_PROFILE_AVC_HIGH_422, I will remove them, thanks for your reminder.

**Comment by softworkz** [comment]
Great, thanks!
