### ISSUE TITLE
About Limitation of composition filter

### ISSUE THREAD

**Issue by APrashant** [Intel-Media-SDK/MediaSDK#2853]
Hi 

We have noticed the following limitation in the https://github.com/Intel-Media-SDK/MediaSDK/blob/master/doc/samples/readme-multi-transcode_linux.md document as:

**Sample may crash if composition filter is used with more than 10 sources (because of limitations in MSDK library).**

As we are using 16 inputs and each input has 1 to N pipeline, also N to 1 display is needed for all the 16 inputs.

Whether intel media sdk supports only for max of 10 or we can use this for 16 inputs also.

Thanks in advance

**Comment by brmarkus** [comment]
No problems with huge video-walls (like with 8, 16, 32 or 64) on my side seen so far with respect to composition-filters.

**Comment by dmitryermilov** [comment]
It's old (most likely) out-of-date limitation of sample_multi_transcode app. It's not related to MediaSDK.
