### ISSUE TITLE
Is it possible to make hardware acceleration effective without display attached

### ISSUE THREAD

**Issue by cloudjiang2** [Intel-Media-SDK/MediaSDK#2870]
There are two graphics cards in a windows 10 host, one is UHD, another is Geforce 1030, I found that MSDK hardware acceleration (HEVC decode/encode) works only when there is display attached to UHD graphics. My requirements:
1. two 4K displays attached to Geforce
2. UHD do video encode/decode acceleration without display attached

**Comment by wangyan-intel** [comment]
If your UHD is enabled, it should be media driver related. Media driver can use drm directly instead of X display. You could confirm    it in https://github.com/intel/media-driver/issues. Thanks.

**Comment by cloudjiang2** [comment]
@wangyan-intel ,
Thanks for you quick response. I test it in windows 10, I will check with media-driver.

**Comment by dmitryermilov** [comment]
There's a Windows limitation (not MSDK or Intel driver) on DirectX9 that HW accelerated processing works only if a target GPU has attached display. To mitigate this please switch to DirectX11.
