### ISSUE TITLE
how to verify ROI feature with sample_multi_transcode on hardware encoder

### ISSUE THREAD

**Issue by guoyejun** [Intel-Media-SDK/MediaSDK#290]
i tried with the following:

to make the roi file simple, i firstly modify the sample source code.
--- a/samples/sample_multi_transcode/src/pipeline_transcode.cpp
+++ b/samples/sample_multi_transcode/src/pipeline_transcode.cpp
@@ -1711,8 +1711,8 @@ void CTranscodingPipeline::SetEncCtrlRT(ExtendedSurface& extSurface, bool bInser
             m_extBuffPtrStorage[keyId].push_back((mfxExtBuffer *)&m_bufExtMBQP[keyId]);
 #endif
         } else {

FROM:
-            if (m_ROIData.size() > m_nSubmittedFramesNum)
-                m_extBuffPtrStorage[keyId].push_back((mfxExtBuffer *)&m_ROIData[m_nSubmittedFramesNum]);
TO:
+            //if (m_ROIData.size() > m_nSubmittedFramesNum)
+                m_extBuffPtrStorage[keyId].push_back((mfxExtBuffer *)&m_ROIData[0]);

         }

And the roi file contains:
1; 0; 0; 500; 500; -20;

the command line is:
./sample_multi_transcode -i::h265 ./f.265 -o::h265 ./out.roi.265  -roi_file ./roi

I verified that the flag has been transferred into the driver correctly at media_driver/agnostic/gen9/codec/hal/codechal_encode_hevc_g9.cpp Line 
6789|     curbe->DW2.ROIEnable               = (m_hevcPicParams->NumROI > 0);

but, when i play the video f.265 and out.roi.265, i do not see the difference with my eyes.

thanks.

**Comment by artem-shaporenko** [comment]
Hi @guoyejun what rate control method and bitrate or QP values are you using? Also what is resolution?

**Comment by guoyejun** [comment]
thanks for the reply, all my changes are described above, i do not change any other default settings of rate control method and bitrate or QP values.

$ mediainfo ./f.265 
General
Complete name                            : ./f.265
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
File size                                : 1.51 MiB

Video
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Width                                    : 1 280 pixels
Height                                   : 720 pixels
Display aspect ratio                     : 16:9
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits


btw, my media driver is built from https://github.com/intel/media-driver.git 7c241661b333516b1c6698163b6c979319506fc3

**Comment by dmitryermilov** [comment]
@AntonGrishin , can you please take a look?

**Comment by AntonGrishin** [comment]
Hi @guoyejun,
When I checked streams which encoded w/ and w/o RoI setting, usually I didn`t see any difference that can be discerned by eye. But if you want to check this, you can try to look the QP map.

**Comment by guoyejun** [comment]
thanks for the reply.

i see, looking the QP map is another method, did you check the QP map method? 

And, i think that the difference should be seen easily by human eyes with the roi file that described above.  I also copy here for your convenient.
1; 0; 0; 500; 500; -20;

Did you see any problem in my command line? thanks.  If no, i'd think it is an issue within msdk, thanks.

**Comment by AntonGrishin** [comment]
hi @guoyejun,
Yes we checked this. RoI works. Based on your cmd (added bitrate option; roi file contains `1; 0; 0; 400; 400; -20;`
)
**Note:** your file specified RoI only for first frame (check SMT help).
```
-roi_file <roi-file-name>
                Set Regions of Interest for each frame from <roi-file-name>
```
cmd:
```
~# ./sample_multi_transcode -i::h265 str720x480.h265 -o::h265 ./str.roi720x480.h265 \
-roi_file roi -b 3000000
```
QP map for source vs RoI stream (you can see the border)
<img width="657" alt="compare" src="https://user-images.githubusercontent.com/34107292/66319190-5a539680-e925-11e9-9c9f-9434e5d26478.png">

**Comment by guoyejun** [comment]
thanks, reproduced with latest libva, media dirver and msdk.

**Comment by guoyejun** [comment]
Hi @AntonGrishin 

sorry for the late, i just have time to look at again. 

Looks that it goes into the software path of the encoder, actually, what i want is the hardware path (GPU).

Could you share the command line to try the hw x264, hw x265 and hw vp9 encoders? thanks a lot.
