### ISSUE TITLE
Error opening the internal VPP session when running on non igpu attached display

### ISSUE THREAD

**Issue by caioavidal** [Intel-Media-SDK/MediaSDK#2906]
## System information
- CPU information (link to ark.intel.com): https://ark.intel.com/content/www/us/en/ark/products/126687/intel-core-i58400-processor-9m-cache-up-to-4-00-ghz.html
- GPU information (link to ark.intel.com):  https://ark.intel.com/content/www/br/pt/ark/products/graphics/126790/intel-uhd-graphics-630.html
- Driver version: 26.20.100.7642

### Describe the current behavior
My Windows 10 (x64) computer has two video devices:

- an nVidia video card (GT1030) as the main display adapter (ID: 0)
- and intel iGPU used as extended display (ID: 1)

When running this FFMPEG command below it simply doesn't work:
`ffmpeg -init_hw_device qsv=hw_any -filter_hw_device hw_any -f gdigrab -offset_x 0 -offset_y 0 -video_size 1920x1080 -framerate 60 -i desktop -an -vf "format=nv12,hwupload=extra_hw_frames=64" -c:v h264_qsv -preset veryfast record.mp4 -y -v verbose`

And returns: 
[AVHWFramesContext @ 000001c96ee500c0] Error opening the internal VPP session.Surface upload/download will not be possible

It works fine if I set the igpu attached display as my main display on windows settings.
Note that I have one single display for each gpu (igpu and nvidia gpu)

### Describe the expected behavior
I'd like the encoder to work independent of the main display setting.

**Comment by dmitryermilov** [comment]
@xhaihao , can you please take a look?

**Comment by caioavidal** [comment]
> @caioavidal , can you please try a similar scenario using sample_encode? e.g. sample_encode h264 -i -w <> -h <> -b 3000 -o o.264

h264: process but got a corrupted output file 
h265: works well

@dmitryermilov The interested part is that it works well when I don't initialize the device on ffmpeg command:
`./ffmpeg -f gdigrab -offset_x 0 -offset_y 0 -video_size 1920x1080 -framerate 60 -i desktop -an -c:v h264_qsv -preset veryfast record.mp4 -y -v verbose`
Unfortunately I notice performance impact using the above command. Is this due to hw frames vs sw frames?

**Comment by xhaihao** [comment]
Could you please use '-init_hw_device qsv=intel,child_device=1, filter_hw_device intel' to initialize your hw device ? You may use  `child_device` to specify your HW adapter in your machine.

**Comment by caioavidal** [comment]
@xhaihao That works fine. Thank you very much
