### ISSUE TITLE
Color is not right after jpeg decoding to rgb4

### ISSUE THREAD

**Issue by cvidkal** [Intel-Media-SDK/MediaSDK#2958]
## System information
- CPU information(model name	: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz):
- GPU information(`00:02.0 VGA compatible controller [0300]: Intel Corporation UHD Graphics 620 [8086:5917] (rev 07)`):
- Display server if rendering to display(X or wayland):

### Describe the current behavior

I use media sdk sample_decode to decode jpg to rgb4, when I dump the rga4 bytes to png, the color is not same as the original jpg 
./sample_decode jpeg -jpeg_rgb -rgb4 -i ~/2.jpeg -gpucopy::on -o test.rgb
And I Use OpenCV to load test.rgb, then use imwrite to write png file.

original jpg
![2](https://user-images.githubusercontent.com/5698123/178463997-90938af7-1d2e-48c2-8aef-c5de2c760656.jpg)
decoded rgb4 png
![test](https://user-images.githubusercontent.com/5698123/178463971-e5a7b6f0-44f4-4977-a76f-baa28fdda06a.png)

## Debug information
- What's libva/libva-utils/gmmlib/media-driver/Media SDK version?
- Could you confirm whether GPU hardware exist or not by `ls /dev/dri`?
- Could you attach dmesg log if it's GPU hang by `dmesg >dmesg.log 2>&1`?
- Could you provide vainfo log if possible by `vainfo -a >vainfo.log 2>&1`?
- Could you provide strace log if possible by `strace YOUR_CMD >strace.log 2>&1`?
- Could you provide libva trace log if possible? Run cmd `export LIBVA_TRACE=/tmp/libva_trace.log` first then execute the case.
- Media SDK tracer output (https://github.com/Intel-Media-SDK/MediaSDK/blob/master/tools/tracer/README.md)?
- Do you want to contribute a PR? (yes/no):

**Comment by brmarkus** [comment]
Can you maybe share the original file `2.jpeg` and the dumped file `test.rgb`, please?
Can you confirm the decoded (and converted to RGB4) input is what you expect (e.g. by rendering on the screen)?

**Comment by cvidkal** [comment]
[test.zip](https://github.com/Intel-Media-SDK/MediaSDK/files/9099650/test.zip)
2.jpg and test.rgb are in test.zip above.

The decoded file (test.rgb) I think is 4 channel image (RGBA or BGRA) , I loaded it and use opencv to show, didn't get the same image as the original encoded one (2.jpeg). I don't know what's the problem is. Could you please some advice ?

**Comment by brmarkus** [comment]
When using the "test.rgb" and display in one of my "raw content viewer" tools then I can see the correct picture when selecting the color-format like "AYUV 4:4:4:4".
Are you sure your OpenCV code interprets the raw data in "test.rgb" correctly?

**Comment by cvidkal** [comment]
Thanks for you reply. I got right result after  I removed -jpeg_rgb in command line parameters
