### ISSUE TITLE
Filed to Run transcode sample

### ISSUE THREAD

**Issue by cvidkal** [Intel-Media-SDK/MediaSDK#2969]
I run the folllowing sample:

release ./sample_multi_transcode -i::h264 /home/yogo/thirdparty/msdk/tests/content/test_stream.264 -o::h264 test.h264   

I get the following error:

Multi Transcoding Sample Version 8.4.27.0

libva info: VA-API version 1.16.0
libva info: Trying to open /usr/local/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_15
libva info: va_openDriver() returns 0
Session 0:

[ERROR], sts=MFX_ERR_MORE_DATA(-10), Init, pThreadPipeline->pPipeline->Init failed at /home/yogo/MediaSDK-intel-mediasdk-22.4.4/samples/sample_multi_transcode/src/sample_multi_transcode.cpp:533

[ERROR], sts=MFX_ERR_MORE_DATA(-10), main, transcode.Init failed at /home/yogo/MediaSDK-intel-mediasdk-22.4.4/samples/sample_multi_transcode/src/sample_multi_transcode.cpp:1251

I compile code from this
https://github.com/Intel-Media-SDK/MediaSDK/releases/tag/intel-mediasdk-22.4.4

Any help?

Thanks

**Comment by brmarkus** [comment]
Can you provide as much information as possible about your environment?

Would it be possible, for reproduction and deeper analysis, if you could share your used file `test_stream.264`?
Is decoding of your file possible with `sample_decode`, like `./sample_decode h264 -hw -vaapi -i test_stream.264`?

You can align with the bug-issue-template below:

> ## System information
> - CPU information(`cat /proc/cpuinfo | grep "model name" | uniq`):
> - GPU information(`lspci -nn | grep -E 'VGA|isplay`):
> - Display server if rendering to display(X or wayland):
> 
> ## Issue behavior
> ### Describe the current behavior
> 
> ### Describe the expected behavior
> 
> ## Debug information
> - What's libva/libva-utils/gmmlib/media-driver/Media SDK version?
> - Could you confirm whether GPU hardware exist or not by `ls /dev/dri`?
> - Could you attach dmesg log if it's GPU hang by `dmesg >dmesg.log 2>&1`?
> - Could you provide vainfo log if possible by `vainfo -a >vainfo.log 2>&1`?
> - Could you provide strace log if possible by `strace YOUR_CMD >strace.log 2>&1`?
> - Could you provide libva trace log if possible? Run cmd `export LIBVA_TRACE=/tmp/libva_trace.log` first then execute the case.
> - Media SDK tracer output (https://github.com/Intel-Media-SDK/MediaSDK/blob/master/tools/tracer/README.md)?
> - Do you want to contribute a PR? (yes/no):

**Comment by cvidkal** [comment]
System information

CPU information(cat /proc/cpuinfo | grep "model name" | uniq): model name      : Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
GPU information(lspci -nn | grep -E 'VGA|isplay):
00:02.0 VGA compatible controller [0300]: Intel Corporation UHD Graphics 620 [8086:5917] (rev 07)
02:00.0 Display controller [0380]: Advanced Micro Devices, Inc. [AMD/ATI] Topaz XT [Radeon R7 M260/M265 / M340/M360 / M440/M445] [1002:6900] (rev c3)
Display server if rendering to display(X or wayland):
Issue behavior

Debug information
[vainfo.log
[dmesg.log](https://github.com/Intel-Media-SDK/MediaSDK/files/9233083/dmesg.log)
](https://github.com/Intel-Media-SDK/MediaSDK/files/9233082/vainfo.log)
[strace.log](https://github.com/Intel-Media-SDK/MediaSDK/files/9233084/strace.log)
[test_stream.264.zip](https://github.com/Intel-Media-SDK/MediaSDK/files/9233105/test_stream.264.zip)


What's libva/libva-utils/gmmlib/media-driver/Media SDK version? 2.15.0/ 22.1.4 /22.4.4/ 22.4.4
Could you confirm whether GPU hardware exist or not by ls /dev/dri? by-path  card0  card1  renderD128  renderD129
Could you attach dmesg log if it's GPU hang by dmesg >dmesg.log 2>&1?
Could you provide vainfo log if possible by vainfo -a >vainfo.log 2>&1?
Could you provide strace log if possible by strace YOUR_CMD >strace.log 2>&1?
Could you provide libva trace log if possible? Run cmd export LIBVA_TRACE=/tmp/libva_trace.log first then execute the case.
Media SDK tracer output (https://github.com/Intel-Media-SDK/MediaSDK/blob/master/tools/tracer/README.md)?
Do you want to contribute a PR? (yes/no):

**Comment by cvidkal** [comment]
libva info: Open new log file /tmp/libva_trace.log.103139.thd-0x00005bca for the thread 0x00005bca
libva info: LIBVA_TRACE is on, save log into /tmp/libva_trace.log.103139.thd-0x00005bca
libva info: VA-API version 1.16.0
libva info: Trying to open /usr/local/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_15
libva info: va_openDriver() returns 0

[ERROR], sts=MFX_ERR_MORE_DATA(-10), InitMfxParams, m_FileReader->ReadNextFrame failed at /home/yogo/MediaSDK-intel-mediasdk-22.4.4/samples/sample_decode/src/pipeline_decode.cpp:814

[ERROR], sts=MFX_ERR_MORE_DATA(-10), Init, InitMfxParams failed at /home/yogo/MediaSDK-intel-mediasdk-22.4.4/samples/sample_decode/src/pipeline_decode.cpp:572

[ERROR], sts=MFX_ERR_MORE_DATA(-10), main, Pipeline.Init failed at /home/yogo/MediaSDK-intel-mediasdk-22.4.4/samples/sample_decode/src/sample_decode.cpp:807

**Comment by brmarkus** [comment]
Can you double-check the video-file, please?
Your attached ZIP-file has a size of 291Bytes, the video-file in it has a size of 131bytes.
It's a text-file with the following content:

> version https://git-lfs.github.com/spec/v1
> oid sha256:e26d061df2876fe52b216fe330d44857b390c2a5772c56cb6537238d2e623ec3
> size 267554

Do you locally have a correct-file or also such a small file?

Is GIT-LFS installed and working in your environment?

**Comment by cvidkal** [comment]
Thanks, It run successfully after using the right file.
