### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [Intel-Media-SDK/MediaSDK#3]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [CBitStreamOutput::Init](https://github.com/Intel-Media-SDK/MediaSDK/blob/1ec49c728ede53d813cc13da086d8436edcfc9d7/lib/_studio/shared/umc/codec/jpeg_common/src/bitstreamout.cpp#L77 "CBitStreamOutput::Init function")
- [HeaderSet::AddHeader](https://github.com/Intel-Media-SDK/MediaSDK/blob/1ec49c728ede53d813cc13da086d8436edcfc9d7/samples/sample_common/include/avc_headers.h#L44 "HeaderSet::AddHeader function")
- [MFXHEVCEncoderPlugin::PluginClose](https://github.com/Intel-Media-SDK/MediaSDK/blob/1ec49c728ede53d813cc13da086d8436edcfc9d7/lib/_studio/mfx_lib/plugin/src/mfx_hevc_enc_plugin.cpp#L94 "MFXHEVCEncoderPlugin::PluginClose function")

**Comment by amaslenn** [comment]
Thanks! For this and for #2 too.
What do you use for searching issues like this?

**Comment by elfring** [comment]
How do you think about any more results from the GitHub search interface?

**Comment by amaslenn** [comment]
Yes, please report any issues you found.

**Comment by elfring** [comment]
Would you like to continue related software improvements with your own source code searches?

**Comment by amaslenn** [comment]
Yes, sure
