### ISSUE TITLE
How to make media player use Media SDK in Linux?

### ISSUE THREAD

**Issue by jwang11** [Intel-Media-SDK/MediaSDK#301]
There are a bunch of popular media players -vlc, mpv, totem in Linux, which are based on gst or ffmpeg.  To   make them use Media SDK, one approach per my understanding is by msdk gstreamer-plugin, is that right? Is there a preferred media player which is directly on top of Media SDK?

**Comment by maximd33** [comment]
MediaSDK support exists at difference media frameworks: ffmpeg/libav/gstreamer
so your understanding is correct.

**Comment by adydychk** [comment]
@jwang11 Do you need any response concerning this issue?

**Comment by dmitryermilov** [comment]
@jwang11 , please look at https://software.intel.com/en-us/articles/get-started-with-the-intel-media-accelerator-reference-software
