### ISSUE TITLE
Downloading a Windows build

### ISSUE THREAD

**Issue by lathonez** [Intel-Media-SDK/MediaSDK#3024]
Hello,

Apologies for raising this issue, but I was hoping someone here may be able to help me get a Windows Build.

It seems that Intel's download centre has been broken as part of a migration to single sign on, and the media-sdk is no longer available to download from the link afoot the README.

I have raised an issue with the download centre but have been advised that I need to use OneVPL instead, which I can't use on Windows 7.

I have used Media-SDK for years to enable QuickSync on my processor. I have no other usecase. I have tried to build from source from this repo, but after several hours decided it was beyond my capabilities and tooling

I wonder if someone could help me to do one of the following:
- Access a windows build of media SDK. It doesn't even need to be a new version, though I would prefer it was
- Let me know what I can install from this repo to enable QuickSync, I think there are a couple of DLL but I haven't found solid information.

Thanks

**Comment by daleksan** [comment]
Hello @lathonez,

you may download driver from https://www.intel.com/content/www/us/en/search.html#sort=relevancy&f:@operatingsystem_en=[Windows%207%2C%2064-bit*]&f:@tabfilter=[Downloads]&f:@stm_10385_en=[Graphics] 

and pick the library *libmfxhw64(32).dll" from driver package

Please let me know if that solution is suitable for you

**Comment by lathonez** [comment]
Thank you!
