### ISSUE TITLE
0053-android-sync-Improved-debug-dump-to-dmesg.patch makes the compilation to fail.

### ISSUE THREAD

**Issue by lp35** [Intel-Media-SDK/MediaSDK#327]
Using GCC 5.5.0 + Intel MediaSDK2018R1, applying the patch 0053-android-sync-Improved-debug-dump-to-dmesg.patch to kernel 4.4.111 is introducing a dependency to sync_dump_timeline function that is breaking the kernel build while not compiling in debug.

Another question: why all these patches are not merged to the mainstream kernel?

``
drivers/android/sync.c: In function ‘sync_timeline_destroy’:
drivers/android/sync.c:91:3: error: implicit declaration of function ‘sync_dump_timeline’ [-Werror=implicit-function-declaration]
   sync_dump_timeline(obj);
   ^
``

Workaround is to modify the patch and comment line 47.

**Comment by fruitboy1226** [comment]
pls open this config: CONFIG_DEBUG_FS, and have a try. thanks.

**Comment by onabiull** [comment]
@lp35 is this issue still actual?

**Comment by asaechnx** [comment]
No, it's not actual

**Comment by dmitryermilov** [comment]
Let's wait for a while for a reply from the submitter.

**Comment by lp35** [comment]
Hi,

I've updated to more recent version of my kernel (4.14) and it seems that you upstreamed all the patches. So I would say I don't have the issue anymore because of my use case, but still this patch might fail against 4.4 kernel.

**Comment by dmitryermilov** [comment]
Good. Thank you for confirmation.

**Comment by lp35** [comment]
Simply downloading the latest 4.4 sources and apply the patches will help you to reproduce the issue very quickly of course ;)
