### ISSUE TITLE
ffmpeg vp8/vc1 decoding failure due to MFX_FRAMETYPE is uninitialized

### ISSUE THREAD

**Issue by lizhong1008** [Intel-Media-SDK/MediaSDK#333]
Reproduce: 
Using the latest ffmpeg( commit_id: deb9a04d54045c8021816cfe019bf2bba0e9595d) 

./ffmpeg -hwaccel qsv -init_hw_device qsv -c:v vp8_qsv -i /root/lizhong/Videos/fate-suite/vp8-test-vectors-r1/vp80-00-comprehensiv
e-001.ivf -vf "hwdownload,format=nv12" -pix_fmt yuv420p -f md5 -
ffmpeg version N-91336-gdeb9a04 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.9) 20160609
  configuration: --enable-libmfx --enable-libx264 --enable-gpl --disable-optimizations --enable-debug=3
  libavutil      56. 18.102 / 56. 18.102
  libavcodec     58. 20.103 / 58. 20.103
  libavformat    58. 17.101 / 58. 17.101
  libavdevice    58.  4.101 / 58.  4.101
  libavfilter     7. 25.100 /  7. 25.100
  libswscale      5.  2.100 /  5.  2.100
  libswresample   3.  2.100 /  3.  2.100
  libpostproc    55.  2.100 / 55.  2.100
Input #0, ivf, from '/root/lizhong/Videos/fate-suite/vp8-test-vectors-r1/vp80-00-comprehensive-001.ivf':
  Duration: 00:00:00.97, start: 0.000000, bitrate: 131 kb/s
    Stream #0:0: Video: vp8 (VP80 / 0x30385056), yuv420p(progressive), 176x144, 30 tbr, 30 tbn, 30 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (vp8 (vp8_qsv) -> rawvideo (native))
Press [q] to stop, [?] for help
Assertion 0 failed at libavcodec/qsv.c:219
Aborted (core dumped)

It is failed in ff_qsv_map_pictype() checking frame_type and found it is uninitialized(return a value of MFX_FRAMETYPE_UNKNOWN).  Other codes (h264/vc1/hevc) looks good except vp8.

**Comment by lizhong1008** [comment]
[vp80-00-comprehensive-001.zip](https://github.com/Intel-Media-SDK/MediaSDK/files/2122511/vp80-00-comprehensive-001.zip)

**Comment by lizhong1008** [comment]
Any comment? All vp8 decoding cases failed in ffmpeg right now.

**Comment by dvrogozh** [comment]
@lizhong1008 : do you need the same feature supported for Jpeg decoder?

**Comment by lizhong1008** [comment]
@dvrogozh , yes, it is needed. Basically speaking,  we should keep internal implementation compatibility with same API. If not, then we should expose such limitation with query interface. 
As tested with my mjpeg decoding enabling patch (though it is not merged now), JPEG frame_type is also FRAMETYPE_UNKNOWN reported from MSDK.

**Comment by dvrogozh** [comment]
@akokoshn : we need the same patch for jpeg decoder... and please, check vp9 as well.

**Comment by lizhong1008** [comment]
@dvrogozh , confirmed with vp9 decoder,  it is FRAMETYPE_UNKNOWN too.

**Comment by akokoshn** [comment]
hi @lizhong1008, as far I know for JPEG not actual frame types I/P/B (in my understanding all frames may be named as I), so could you please explain why need ask MSDK about JPEG frame type?
We can report all frames as I, but I'm not sure it's make sense or not.

**Comment by lizhong1008** [comment]
@akokoshn , good question.  It is similar issue for ffmpeg software jpeg/mjpeg decoding/encoding.  Currently software is taken is as Keyframe (I frame).  See: https://github.com/FFmpeg/FFmpeg/blob/master/libavcodec/mjpegdec.c#L708.

I believe MSDK can follow this too, set all frame as I frame. 
FRAMETYPE_UNKNOWN as my understanding it means something is broken.

**Comment by lizhong1008** [comment]
Give a quick testing, I haven't found anything wrong for MJPEG/VP8/VP9, except VC1.

Applied a patch as
```
diff --git a/libavcodec/qsv.c b/libavcodec/qsv.c
index 7dcfb04316..e7683ffd27 100644
--- a/libavcodec/qsv.c
+++ b/libavcodec/qsv.c
@@ -245,6 +245,8 @@ enum AVPictureType ff_qsv_map_pictype(int mfx_pic_type)
         av_assert0(0);
     }

+    printf("mfx decoding type is %d\n", mfx_pic_type);
+    printf("qsv decoding type is %d\n", type);
     return type;
 }

diff --git a/libavcodec/vc1_parser.c b/libavcodec/vc1_parser.c
index 493ffde611..3f49657da8 100644
--- a/libavcodec/vc1_parser.c
+++ b/libavcodec/vc1_parser.c
@@ -90,6 +90,7 @@ static void vc1_extract_header(AVCodecParserContext *s, AVCodecContext *avctx,
         else
             s->pict_type = vpc->v.s.pict_type;

+        printf("picture type is %d\n",vpc->v.s.pict_type);
         if (avctx->ticks_per_frame > 1){
             // process pulldown flags
             s->repeat_pict = 1;

```
./ffmpeg -hwaccel qsv -c:v vc1_qsv -i /root/Videos/fate-suite/vc1/SA00040.vc1 -vf 'scale_qsv=format=rgb32, hwdownload,format=rgb32' -f sdl -

All of frames which are not I frames are reported as B frame by ffmpeg software parser, but MSDK return a picture_type unknown.
 
Then I checked the code: https://github.com/Intel-Media-SDK/MediaSDK/blob/af248638256501f4edad3abc097909a4c2fffdd5/_studio/mfx_lib/decode/vc1/src/mfx_vc1_decode.cpp#L50 
Only I frame is handled here.  

AFAIK, VC1 picture type are I-picture, P-picture, skipped picture, B/BI-picture. Why only I frames are handled here?

**Comment by dvrogozh** [comment]
@akokoshn : please, comment.

**Comment by akokoshn** [comment]
Hi @lizhong1008 , sorry for delay response.
Current implementation of MSDK VC1d ignore P/B types: frame defines as skip or I-Frame: https://github.com/Intel-Media-SDK/MediaSDK/blob/a14166bd60890c89b174686d68238f6972898b47/_studio/shared/umc/codec/vc1_dec/include/umc_vc1_video_decoder_hw.h#L160
PR: https://github.com/Intel-Media-SDK/MediaSDK/pull/1229 should fix it, but still see reported frame type unknown on test with ffmpeg  (stream 
SA00040.vc1)

**Comment by akokoshn** [comment]
Hi @lizhong1008 , I have found root cause issue - MSDK specific handling skipped frames leads rewrite real frame type by VC1_SKIPPED_FRAME.
https://github.com/Intel-Media-SDK/MediaSDK/pull/1229 was updated

**Comment by lizhong1008** [comment]
@akokoshn Patch LGTM and will give an updated testing.

**Comment by lizhong1008** [comment]
Tested SA00040.vc1 and  SA10091.vc1 (you can get all of them from ffmpeg suite: http://ffmpeg.org/fate.html).  Two issue found:
1. No I frame exposed for SA00040.vc1.  All frames B frames. 
2. some last frames of SA10091.vc1 are still reported as Unknown.

**Comment by dvrogozh** [comment]
@lizhong1008, @akokoshn : Let's continue VC1 debug in issue #1239. This issue was about mediasdk decoders not reporting frame types at all - it was fixed. Now, we observe that some decoders don't properly recognize stream and, hence, don't report frame type correctly. Let's deal with these kind of issues separately.
