### ISSUE TITLE
Fails to build with ITT support when using IntelSEAPI

### ISSUE THREAD

**Issue by dbermond** [Intel-Media-SDK/MediaSDK#338]
The default [IntelSEAPI](https://github.com/intel/IntelSEAPI/) build system builds a library called `libittnotify64.a` in 64-bit systems, but the MediaSDK cmake build system is expecting to find `libittnotify.a`, as seen here:

https://github.com/Intel-Media-SDK/MediaSDK/blob/master/builder/FindITT.cmake#L33

As a result, MediaSDK fails build with ITT support when using IntelSEAPI  and `-DENABLE_ITT:BOOL='ON'` because it cannot find the correct library.

Caused by commit: 5e6b710c7ebd30a013c51313280d9a53fc9dc2c5

**Comment by dvrogozh** [comment]
Thank you for noting. VTune and SEAPI are eventually not in an agreement on how to name ITT library. I filed https://github.com/intel/IntelSEAPI/issues/21 for that. Rather than guessing what is the correct name (which I probably still implement, sigh...) I would better request support for the normal pkg-config from them. Here is a request for SEAPI: https://github.com/intel/IntelSEAPI/issues/20.

**Comment by dbermond** [comment]
Thank you for the reply and for filling these requests on IntelSEAPI.

I hope they can implement them.

**Comment by dvrogozh** [comment]
As of now I would just improve FindITT.cmake to look for both variants of itt library name. Problem is that I can't test this because of this build issue in SEAPI: https://github.com/intel/IntelSEAPI/issues/22 and I have no bandwidth to install/try another operating system.

**Comment by dbermond** [comment]
@dvrogozh  Thank you for working on this issue.

cmake correctly finds ITT from IntelSEAPI after applying this patch. The configuration summary shows `ENABLE_ITT : ON`.

But it still fails to build during the compile time, giving me multiple occurrences of this error:
```
/usr/bin/ld: cannot find -littnotify
collect2: error: ld returned 1 exit status
```

I'm on Arch Linux x86_64. Building with gcc 8.1.1.

**Comment by dvrogozh** [comment]
That was stupid me. I forgot to change library name to link with, I just detected it. Please, try https://github.com/dvrogozh/MediaSDK/commit/cd9108bd86eaab108fd0764ded6e9ca00deca813.

**Comment by dbermond** [comment]
> Please, try dvrogozh/MediaSDK@cd9108b.

It works. I can confirm that MediaSDK builds fine with ITT support when using SEAPI after applying this patch.

Thank you for fixing this.

**Comment by dvrogozh** [comment]
ok, cool, thank you for the confirmation. I have just created a pull request.
