### ISSUE TITLE
Download an exe?

### ISSUE THREAD

**Issue by EddieOne** [Intel-Media-SDK/MediaSDK#346]
I'm having issues with quick sync causing red glitches in videos. One page mentions using the media sdk as there seems no way to disable quick sync. Is there a simple way to install it?

**Comment by avbelova** [comment]
Hi @EddieOne, 
Quick Sync is HW technology that offloads video coding computation to the Intel(R) Processor Graphics. Media SDK is programming API to access Quick Sync.
It looks like you're using some application that uses Quick Sync. Which application do you use? 

Best wishes, 
Anna

**Comment by EddieOne** [comment]
Hi @avbelova,

If I render any 4k footage on adobe cs6 slightly older Intel chips, I get Quick Sync crashes that show in the render as solid color glitches, red or green. Not sure if buying new software is the only option or if new hardware will also fix it?

Thanks, Eddie

**Comment by avbelova** [comment]
@EddieOne ,
Which concrete Intel chip do you use, and which video decoder (AVC, HEVC,..)?

Best wishes, 
Anna

**Comment by EddieOne** [comment]
It's the i7-4790k and it happens with the h264 codec. I use another application that offers gpu quick sync and I can render down to 1440p. It's then possible to render those via Intel inside Adobe.

**Comment by avbelova** [comment]
@EddieOne , on the QuickSync/Media SDK side we don't have limitations with 4K AVC decode. We advice you to address the issue to Adobe.

Best wishes, 
Anna
