### ISSUE TITLE
VP8 decode failure due to alignment issue

### ISSUE THREAD

**Issue by sreerenjb** [Intel-Media-SDK/MediaSDK#360]
Take a video sample of size 36x36 .
set, 
mfxFrameInfo.Width = 64; // 32 bit alingment
mfxFrameInfo.Width = 64; // 32 bit alingment
mfxFrameInfo.CropW = 36;
mfxFrameInfo.CropH = 36;

Then MFXVideoDECODE_DecodeFrameAsync() is failing with MFX_ERR_INVALID_VIDEO_PARAM error code. But if I use 16bit alignment (Width=48, Height=48),it works fine. 
Other codecs like h264 and vp9 have no issue like this.

Is there any hard restriction in vp8 decoder such that "width must be aligned to **immediate next** 16 bit rounded value "??

**Comment by dmitryermilov** [comment]
@lakulako , can you please take a look?

**Comment by lakulako** [comment]
Need to check the standard.

**Comment by lakulako** [comment]
@sreerenjb , there are no such restrictions. Thank you for catching. Could you please provide info how to reproduce the case. Where and when do you set size and crops?

**Comment by dmitryermilov** [comment]
@chivakker , can you please provide a reproducer via sample_decode?

**Comment by chivakker** [comment]
@dmitryermilov I think we saw it also with sample_decode and a ivf stream.  I'll share the command line later today.

**Comment by dmitryermilov** [comment]
Thanks!

**Comment by Alexandr-Konovalov** [comment]
In what related to msdkvpp, one is used for conversion from NV12 that is output of msdkvp8dec (and other plugins like msdkmjpegdec) to RGB4 that is expected as input by glimagesink. I.e., you can run

`gst-launch-1.0 -v filesrc location=FOO.webm ! matroskademux ! msdkvp8dec ! filesink location=test.nv12`

and get decoded NV12 stream in the file. Alternatively, negotiation may be done via

`gstreamer-1.0 filesrc location=FOO.webm ! matroskademux ! msdkvp8dec ! 'video/x-raw,format=NV12' ! glimagesink`

**Comment by Alexandr-Konovalov** [comment]
@chivakker , hope we answered all you questions. Fill free to re-open the issue or file a new one.
