### ISSUE TITLE
MFX_RATECONTROL_LA_EXT run slowly on version 1.27  same as 1.26

### ISSUE THREAD

**Issue by changliwu** [Intel-Media-SDK/MediaSDK#381]
Hi
   I have run MFX_RATECONTROL_LA_EXT of sample_multi_transcode with API 1.27, It runed as slow as the 1.26, please see https://github.com/Intel-Media-SDK/MediaSDK/issues/207
    Eagerly looking forward to your help, thanks very much!!!

It install with linux-firmware on d1147327232ec4616a66ab898df84f9700c816c1
linux-stable in 4.18.0-rc1+
libva-utils on 1bea64e12144fce74363538232c1a94ee9c98446
libva on b3be72a5a110880f70626d7c3bed953cdde124b2
gmmlib on 41dbe28e6891deec97fcee3bf8fa56fa84137549
media-driver on 2b6c2a625373df973098bd8105a8744782402e5d
MediaSDK on e0e56532cb4c1a3f75688d5a2a4ffe6b08727d75

**Comment by egorovdanil** [comment]
I compared the three API versions 1.25, 1.26 and the current version of the master in #207 and found no decrease in the transcoding speed. So I think it's the same for 1.27

**Comment by daleksan** [comment]
@changliwu please feel free to re-open if it is still actual
