### ISSUE TITLE
Proper support for placing .so files in paths other than MFX_MODULES_DIR

### ISSUE THREAD

**Issue by russelltg** [Intel-Media-SDK/MediaSDK#389]
Right now it seems that there is no flexibility of where to load `.so` files from, it's configure during the build process: 
https://github.com/Intel-Media-SDK/MediaSDK/blob/a01ef319b5e96fe9ae2b63b67e1f1a30011829b0/api/opensource/mfx_dispatch/CMakeLists.txt#L61-L65

and then used staticly when finding the `.so`s:

https://github.com/Intel-Media-SDK/MediaSDK/blob/a01ef319b5e96fe9ae2b63b67e1f1a30011829b0/api/opensource/mfx_dispatch/src/mfx_library_iterator_linux.cpp#L311-L314

This is a totally acceptable default, but it may be nice to have a environment variable like `MFX_SOPATH` to be able to change this at runtime.

Is there interest in this feature? I'm willing to implement if there is interest.

**Comment by russelltg** [comment]
Would this be useful? Is there interest in a PR? Help-wanted seems interesting considering I'm willing to implement it.

**Comment by onabiull** [comment]
Hello,
  Thank you for proposal! Still I hardly see how this would be useful. 
  Dispatcher part already complicated enough and often confuse even experienced users. Considering that there are "standard search path", "default search path", and specific logic tailored to search of suitable runtime for plugins. Developers of specific software are free to change dispatcher behavior to suit their specific needs, but adding new environment variable would just add another layer of complexity and most likely won't play nice with already-built software, which essentially use outdated dispatcher.

**Comment by vvkalinin24** [comment]
Linux dispatcher and build system now allow such configuration
