### ISSUE TITLE
How to use Hevc FEI

### ISSUE THREAD

**Issue by TVUbrucesun** [Intel-Media-SDK/MediaSDK#39]
Hello, 
I have a question. 
I have installed MediaServerStudioEssentials2017R3 to cpu 6500u Linux.
can i use this MediaSDK hevc fei encoder on it ?

**Comment by artem-shaporenko** [comment]
No, there is no HEVC FEI support in graphics driver distributed with 2017 R3 release. So far current Open Source Media SDK master head is not compatible with R3 release due to differences in libva.

**Comment by TVUbrucesun** [comment]
Thank you very much.
Is that means that i only must install this vaapi (https://github.com/intel/media-driver) ?

**Comment by artem-shaporenko** [comment]
VAAPI itself stored in [https://github.com/01org/libva](https://github.com/01org/libva), so you need to get it from there(see version 2.1)
And, yes, compatible driver is [https://github.com/intel/media-driver](https://github.com/intel/media-driver)

**Comment by onabiull** [comment]
My two cents :) To enable this new functionality one need to pass --api=latest to build_mfxp.pl. Please be warned, that unless given specific API version, any piece of API considered unstable. This is current work in progress and would receive updates including source and binary incompatible ones.

**Comment by artem-shaporenko** [comment]
@TVUbrucesun are your questions/concerns closed? If so we can close the issue?
