### ISSUE TITLE
Dispatcher may initialize few mediasdk sessions in a single MFXInit call

### ISSUE THREAD

**Issue by dvrogozh** [Intel-Media-SDK/MediaSDK#425]
https://github.com/Intel-Media-SDK/MediaSDK/blob/fecddbead79d7a5a14b81edaf289556677e11522/api/opensource/mfx_dispatch/src/mfx_dispatcher.cpp#L250

Combined with the code in main.cpp (to load all possible mediasdk libraries into a collection), we may initialize mediasdk session few times and dispose of all of them except one:
https://github.com/Intel-Media-SDK/MediaSDK/blob/fecddbead79d7a5a14b81edaf289556677e11522/api/opensource/mfx_dispatch/src/main.cpp#L368

**Comment by vvkalinin24** [comment]
With modern dispatcher this issue is obsolete, maybe this issue should be closed?
