### ISSUE TITLE
Ubuntu test Error

### ISSUE THREAD

**Issue by kweisamx** [Intel-Media-SDK/MediaSDK#438]
I use Ubuntu 16.04 to build MediaSDK, when I test the file mat some problem
```
/opt/intel/mediasdk/samples$ ./sample_encode h264 -i ../content/test_stream_176x96.yuv -o test.264 -w 196 -h 96 -angle 0
[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), Init, m_mfxSession.InitEx failed at /home/sam/msdk/samples/sample_encode/src/pipeline_encode.cpp:1268

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), main, pPipeline->Init failed at /home/sam/msdk/samples/sample_encode/src/sample_encode.cpp:1189

```
LD_LIBRARY_PATH I change to /opt/intel/mediasdk/lib , and the error still existd
can anyone tell me how to fix it ?

kernel version:4.15.0-29-generic
os : ubuntu 16.04

**Comment by kixiro** [comment]
+1

**Comment by vvkalinin24** [comment]
Please, try pre-built release tarball. Issue looks like a configuration problem
