### ISSUE TITLE
why metrics_monitor show some number above 100% for Intel Media SDK 2018R1

### ISSUE THREAD

**Issue by andrewmabc** [Intel-Media-SDK/MediaSDK#475]
Hi,

I has installed Intel Media SDK 2018R1, and use metrics_monitor to check GPU usage. I found some number above 100%. I think it is a bug.

How to fix it?

Thanks!

Regards

Andrew

**Comment by dvrogozh** [comment]
metrics monitor shows % in a range of 0-100 for each gpu engine. Thus, yes, this looks like a bug. However, metrics_monitor don't create a load by itself. Thus, please, provide a use case where you noted this behavior. What exactly you've ran? metrics_monitor tests or some real workload (provide/describe it) and used metrics_monitor?

**Comment by andrewmabc** [comment]
The use case is that, ffmpeg is used to do 5-9 transcoding tasks simultaneously。And RENDER usage sometimes is above 100%。

**Comment by lizhong1008** [comment]
@andrewmabc ，please provide more details about how to reproduce it. For example. FFmpeg version/ MSDK version, hardware platform, testing clips and so on.

**Comment by andrewmabc** [comment]
MSDK version : MediaServerStudioEssentials2018R1
FFmpeg version : 4.0

any test clip can reproduce the issue.

The way to reproduce the issue is to run multiple 1080p transcoding tasks long enough. Then, metrics monitor program will show incorrect number that is over 100.

**Comment by vvkalinin24** [comment]
@andreyor Could you please confirm if this was addresed w/ latest version of metrics_monitor

**Comment by daleksan** [comment]
Algorithm was corrected some time ago please feel free to re-open if issue still persist
