### ISSUE TITLE
Installation failed missing environment variable

### ISSUE THREAD

**Issue by easychizy** [Intel-Media-SDK/MediaSDK#486]
I build the new release 2018Q2.1 according to the following article:
https://software.intel.com/en-us/articles/build-and-debug-open-source-media-stack

I did manually build and completed the build process, everything else is OK but I got following error when I run sample_multi_transcode:
```
./sample_multi_transcode -i::h264 ../content/test_stream.264 -o::h264 out.264
Multi Transcoding Sample Version 8.2.25.982

libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_1
libva info: va_openDriver() returns 0

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), Init, m_pmfxSession->InitEx failed at /home/lab_msdk/buildAgentDir/buildAgent_MediaSDK3/git/mdp_msdk-lib/samples/sample_multi_transcode/src/pipeline_transcode.cpp:3474

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), Init, pThreadPipeline->pPipeline->Init failed at /home/lab_msdk/buildAgentDir/buildAgent_MediaSDK3/git/mdp_msdk-lib/samples/sample_multi_transcode/src/sample_multi_transcode.cpp:348

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), main, transcode.Init failed at /home/lab_msdk/buildAgentDir/buildAgent_MediaSDK3/git/mdp_msdk-lib/samples/sample_multi_transcode/src/sample_multi_transcode.cpp:916
```
I can set the following environment to work around it,`export LD_LIBRARY_PATH=/opt/intel/mediasdk/lib/` but I don't think this is the root cause. This reminds me an old issue related to dispatcher. 

Where did I missed?

Thanks.

Mark

**Comment by Brainiarc7** [comment]
Hello there, 

You will need to add a library entry file (under` /etc/ld.so.conf.d/*`) and update the cache via:

`sudo ldconfig -vvv`

Sample library file (create this with a text editor of choice /etc/ld.so.conf.d/imsdk.conf)

**Content:**

```
/opt/intel/mediasdk/lib
/opt/intel/mediasdk/plugins

```
Then run:

`sudo ldconfig -vvvv`

And retest.

**Comment by onabiull** [comment]
Dispatcher was unable to find fresh HW binary.
Without
```bash
sudo make install
```
you'll need either copy libmfxhw64.so to /opt/intel/mediasdk/lib64/libmfxhw64-p.so.1.26 or make dynamic loader aware of your libmfxhw64.so by setting LD_LIBRARY_PATH or adding libmfxhw64.so location to text file in /etc/ld.so.conf.d/

**Comment by dmitryermilov** [comment]
@Brainiarc7 , were you able to get it working?

**Comment by Brainiarc7** [comment]
Yes. Zero issues.
