### ISSUE TITLE
Question: which rate controls are supported under linux?

### ISSUE THREAD

**Issue by andreasunterhuber** [Intel-Media-SDK/MediaSDK#492]
Are the advanced rate controls like 
- ICQ
- LA_ICQ
- QVR 

supported under CentOS 7.2? 

If yes - Is there a way to use these RC with ffmpeg (currently probably not, because of the `#if defined(_WIN32)` switch in https://github.com/FFmpeg/FFmpeg/blob/7ceec9c5ec511fd75116ab94ac132159f8d97edc/libavcodec/qsvenc.h - but generally possible?

Thanks

**Comment by aaronovz1** [comment]
Is ICQ supported for both H.264 and H.265?

**Comment by andreasunterhuber** [comment]
@aaronovz1 currently , it's only support AVC

**Comment by Brainiarc7** [comment]
Hello there,
Using this version of the Media SDK and the current ffmpeg git head, the following RC modes are supported by the VAAPI-based hevc and h264 encoders:

```
     CQP                          E..V..... Constant-quality
     CBR                          E..V..... Constant-bitrate
     VBR                          E..V..... Variable-bitrate
     ICQ                          E..V..... Intelligent constant-quality
     QVBR                         E..V..... Quality-defined variable-bitrate
     AVBR                         E..V..... Average variable-bitrate

```

However, to use the QVBR mode, the [`iHD` driver](https://github.com/intel/media-driver) must be in use in the session.

**Comment by andreasunterhuber** [comment]
@Brainiarc7 correct, and the BRC of `LA_ICQ` (Intelligent constant-quality with look ahead) is also part of this.

**Comment by Brainiarc7** [comment]
The reason I omitted mentioning `LA_ICQ` is that as a quality-based mode, its' only available on the QSV runtime, and is auto-selected when both `global_quality` and `look_ahead` options are set.

By default, its' masked from the QSV session unless explicitly enabled as such: http://www.ffmpeg.org/ffmpeg-codecs.html#QSV-encoders

The same also applies to the rate control mode `LA`.
`vcm` mode also seems to be [deprecated](http://git.videolan.org/?p=ffmpeg.git;a=commit;h=8e789d244cc946bc350672eeb02453918b21a09f) (as at ffmpeg git head).

**Comment by vvkalinin24** [comment]
@gkrivor Could you please comment?

**Comment by eero-t** [comment]
Note that on newer HW, rate controls require also HuC firmware to be loaded ("i915.enable_guc=2" kernel option to enable HuC firmware upload for GuC, while still keeping GuC submission disabled).

**Comment by daleksan** [comment]
we consider that this fixed, please feel free to file the new one if rate control doesn't match expectations
