### ISSUE TITLE
Whether LA_ICQ will support the HEVC encoding in the future or needs to be implemented with FEI by self？

### ISSUE THREAD

**Issue by changliwu** [Intel-Media-SDK/MediaSDK#504]
Hi,
         I have run HEVC encoding with LA_ICQ of sample_encode in MediaSDK 1.27, It shows error MFX_ERR_UNSUPPORTED.

Run like this:
# ./sample_encode h265 -i out.yuv -o out.h265 -w 176 -h 96 -la_icq
plugin_loader.h :186 [INFO] Plugin was loaded from GUID: { 0x6f, 0xad, 0xc7, 0x91, 0xa0, 0xc2, 0xeb, 0x47, 0x9a, 0xb6, 0xdc, 0xd5, 0xea, 0x9d, 0xa3, 0x47 } (Intel (R) Media SDK HW plugin for HEVC ENCODE)
libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /usr/lib64/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_1
libva info: va_openDriver() returns 0
[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), AllocFrames, Query (for encoder) failed at /root/Desktop/MediaSDK_e0e56532cb4c1a3f75688d5a2a4ffe6b08727d75/samples/sample_encode/src/pipeline_encode.cpp:792

Whether LA_ICQ will support the HEVC encoding in the future, or it need to be implemented with FEI by ourself?
             thanks!

**Comment by vilichev** [comment]
There are no plans to support LA_ICQ for HEVCe. @thomasli21801 could you please confirm this?

**Comment by thomasli21801** [comment]
Yes, you are right. There is no plan to support LA_ICQ for HEVC VDEnc.

**Comment by DoS007** [comment]
@vilichev @thomasli21801 Ok, good that this is here cleared up. So i used CQP, ICQ and VBR with i5 1035g4.

VBR: Bad quality at the same Bitrate.

CQP and ICQ are much better. And ICQ is better than CQP, because it has less weird motion artifacts (at least on my tests).

So ICQ is for transcoding to file best imo (using ICQ at quality level 35 which results in good file sizes), BUT I don't understand:

I have a presentation recording: And every time the slide changes the new slide is blurry at first and then after a second or so gets sharpend. Shouldn't qsv allow higher bitrate for very short time at slide change, so that it's sharp immediatly (and after that for next frames use the previous frame information for less bitrate usage)?

Is there an option i forgot to set?

Greets

**Comment by thomasli21801** [comment]
@DoS007 , can you help to confirm that blur happens when scene change is happening in ICQ quality level 35 with presentation content (Microsoft PPT with titles/sentences/pics)?
May I know if you can try with lower quality level to see how it goes?
Is there a chance for you to help share the cmd line?
I'll ask team to try to reproduce.

Thanks,
Thomas

**Comment by thomasli21801** [comment]
BTW, may I know if you are using HEVC VME or VDEnc in this case?

**Comment by DoS007** [comment]
@thomasli21801 

> can you help to confirm that blur happens when scene change is happening in ICQ quality level 35 with presentation content (Microsoft PPT with titles/sentences/pics)?

Yes, exactly (scene change in ICQ 35). This happend after i minimized a window (so OneNote was visible as a "new scene").

![grafik](https://user-images.githubusercontent.com/11618958/124124746-19949d00-da79-11eb-89df-9caa84505c67.png)
And after a second or so: 
![grafik](https://user-images.githubusercontent.com/11618958/124124828-3335e480-da79-11eb-8aeb-9b6d266e2ab2.png)

Also during presentation slides. From a slide change:
![grafik](https://user-images.githubusercontent.com/11618958/124125496-f3bbc800-da79-11eb-84fc-1eb882346102.png)

![grafik](https://user-images.githubusercontent.com/11618958/124125573-10580000-da7a-11eb-977b-1db1d4aafc65.png)

> May I know if you can try with lower quality level to see how it goes?
? When i go lower the overall quality gets better?

> Is there a chance for you to help share the cmd line / driver version / kernel version / env details?

I'm using `ffmpeg version 4.4-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.2.0 (Rev6, Built by MSYS2 project)` on Windows 64 bit
![grafik](https://user-images.githubusercontent.com/11618958/124125966-7775b480-da7a-11eb-82ca-32e79a2634cb.png)

and the command line is
`ffmpeg -init_hw_device qsv=hw -hwaccel qsv -c:v h264_qsv -i "file.mkv" -c:v hevc_qsv -global_quality:v 35 -look_ahead:v 1 -c:a libopus -cutoff:a 8000 -application:a 'voip' -frame_duration:a 40 -compression_level:a 10 -vbr:a 'on' -b:a 24K -ac 1 "file_converted.mkv"`

I now know that look_ahead does not work with hevc, but ffmpeg told me anyway that it will ignore it. The first init_hw_device is unnessecary but also should do no harm. So the relevant part for you is `-hwaccel qsv -c:v h264_qsv -i "file.mkv" -c:v hevc_qsv -global_quality:v 35` (the two lasts for output).

This the ffmpeg doc I found about QSV: https://www.ffmpeg.org/ffmpeg-codecs.html#QSV-encoders , https://trac.ffmpeg.org/wiki/Hardware/QuickSync . Using global_quality will use ICQ according to first page.

Greets

**Comment by DoS007** [comment]
> 
> 
> BTW, may I know if you are using HEVC VME or VDEnc in this case?

How can I see this?

**Comment by dmitryermilov** [comment]
> > BTW, may I know if you are using HEVC VME or VDEnc in this case?
> 
> How can I see this?

You can find out it by GPU utilization. VME involves execution units (render engine aka "rcs") and VDBOX (aka "vcs"), VDEnc  involves only VDBOX. Please refer to https://github.com/Intel-Media-SDK/MediaSDK/wiki/Performance-monitoring-and-debug. You can use' metrics_monitor' or 'intel_gpu_top' or 'perf' tools.

**Comment by dmitryermilov** [comment]
> > BTW, may I know if you are using HEVC VME or VDEnc in this case?
> 
> How can I see this?

You can take MSDK API tracer (https://github.com/Intel-Media-SDK/MediaSDK/tree/master/tools/tracer), collect logs and check value for 'mfxVideoParams::LowPower' (ON or OFF). ON means VDEnc.

**Comment by DoS007** [comment]
@dmitryermilov Where are the releases for Windows? I don't have a compiling suite for c++ here.

**Comment by dmitryermilov** [comment]
> @dmitryermilov Are there releases for Windows? I don't have a compiling suite for c++ here.

Windows version of the tracer is provided by regular Windows Media SDK dev kit.

**Comment by vilichev** [comment]
I have tried ffmpeg on ICL Windows using the similar command. MSDK is initialized with par->mfx.LowPower = 32 so it is VME. 
Hi @nlu5, could you please continue the investigation from VME side?

**Comment by DoS007** [comment]
@vilichev Sorry, I haven't answered yet, I' quite busy at the moment. Do you still need confirmation from my side?

**Comment by vilichev** [comment]
@DoS007 I think no confirmation is required from your side. I have confirmed the encoding is done using HEVCe VME
