### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by Zeranoe** [Intel-Media-SDK/MediaSDK#515]
I'm trying to compile mfx_dispatch to use in FFmpeg, but it seems like Windows support has either been dropped or forgotten.

For example, all the *_linux.cpp sources are being included in ${sources}: https://github.com/Intel-Media-SDK/MediaSDK/blob/master/api/opensource/mfx_dispatch/CMakeLists.txt#L103

This causes MingGW-w64 to fail building since sched.h is not a header on Windows.

If that issue is fixed another one comes up with including dlfcn.h: https://github.com/Intel-Media-SDK/MediaSDK/blob/master/api/opensource/mfx_dispatch/src/mfx_dispatcher.cpp#L28

There might be other issues as well, as I stopped looking after finding these two.

It appears there need to be some changes to support Windows platforms again. I can create PRs for these, but I wanted to make sure Windows is still supposed to be supported as a possible target.

**Comment by lp35** [comment]
Hi Zeranoe,

May I ask which version of the Media SDK you are using in official Zeranoe builds?

**Comment by zhoub** [comment]
Bump, this is really needed.

**Comment by mvmaximov** [comment]
Windows support for mfx_dispatch was added in https://github.com/Intel-Media-SDK/MediaSDK/pull/1277

As for Media SDK library, open source version doesn't have Windows support for now (see https://github.com/Intel-Media-SDK/MediaSDK#known-limitations)

**Comment by daleksan** [comment]
Samples also supported on Windows. Release notes reference applicable driver version. Currently no plan to upstream Windows version of code.
