### ISSUE TITLE
How can I check if my processor supports the codecs I need?

### ISSUE THREAD

**Issue by kixiro** [Intel-Media-SDK/MediaSDK#550]
```
# ./sample_decode h264 -i 1.mp4 -o 1.raw -p vp8d_hw

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), Init, m_mfxSession.Init failed at /root/src/msdk/samples/sample_decode/src/pipeline_decode.cpp:296

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), main, Pipeline.Init failed at /root/src/msdk/samples/sample_decode/src/sample_decode.cpp:666
```

**Comment by brmarkus** [comment]
Calling "vainfo" gives a good overview about "low level drivers" supporting certain codecs (encoders and decoders) in your environment - which doesn't mean that when libva supports a certain codec that MediaSDK also supports it.
Your example above shows that you try to decode a "MP4 container" "1.mp4".
However, MediaSDK is not a "media player" like gstreamer or ffmpeg.
You would need to demux the contained video elementary stream first (e.g. by using ffmpeg, e.g. "ffmpeg -i 1.mp4 -an -vcodec copy -bsf h264_mp4toannexb -f h264 1.h264").
And then do e.g. "./sample_decode h264 -hw -i 1.h264 -nv12 -o 1.nv12".
