### ISSUE TITLE
FFMPEG: need transcoding example against 2018Q2.2

### ISSUE THREAD

**Issue by lp35** [Intel-Media-SDK/MediaSDK#557]
Hi,

I currenlty compiled and installed MediaSDK 2018Q2.2 with all dependencies on my system (libva, mediadriver, etc).
The multiple transcode sample code is working fine.

I have compiled ffmpeg 3.4.2 with libmfx support and I cannot find any good example on the Internet showing how to transcode a simple .mp4 file (I get the unsupported format error -3) using ffmpeg.

Is there any minimum version of ffmpeg required to make the latest sdk work with the 2018Q2.2?

Thank you, BR

**Comment by maximd33** [comment]
try to compile ffmpeg from master
