### ISSUE TITLE
Don’t allocate internal memory via external allocator (+ don’t allocate via a WA)

### ISSUE THREAD

**Issue by dvrogozh** [Intel-Media-SDK/MediaSDK#559]
Initially filed and discussed here: https://github.com/Intel-Media-SDK/samples/issues/13. Since this is not samples issue (at least not only), moved to track in Media SDK library repo.

As of now we need to:
1. Make sure that no mediasdk codecs allocate internal memory via external allocator. Suspected codec is HEVC encoder
2. Consider deletion of external memory allocation for bitstreams.

**Comment by lizhong1008** [comment]
FFmpeg hevc works!  Thanks a lot for your support!
One question, how about the status of other codecs? For example, vp9 hw encoder (though hasn't implemented in ffmpeg, I will add it soon).

**Comment by artem-shaporenko** [comment]
VP9 still need to be updated.

**Comment by lizhong1008** [comment]
So, would you please create a new issue to check vp9 encoder since this one has been closed? @artem-shaporenko @dvrogozh

**Comment by dvrogozh** [comment]
Let's track vp9e in https://github.com/Intel-Media-SDK/MediaSDK/issues/762.
