### ISSUE TITLE
Decoder render failed

### ISSUE THREAD

**Issue by qiushics** [Intel-Media-SDK/MediaSDK#60]
Both H264/H265 sample_decode render failed, but output to yuv file is ok.

machine:
```
Linux ubuntu 4.10.0-28-generic #32~16.04.2-Ubuntu SMP Thu Jul 20 10:19:48 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
intel i7 6700
```
---
Output:
```
Decoding started
Frame number:    0, fps: 0.000, fread_fps: 0.000, fwrite_fps: 0.000
DeliverOutput return error = -1
Frame number:    1, fps: 0.527, fread_fps: 0.000, fwrite_fps: 1526.718
```
---

After debug, I have fould [render frame return 18(invalid params)](https://github.com/Intel-Media-SDK/MediaSDK/blob/6ae24f64826339367028867e265fb018ebc5efb4/samples/sample_common/src/vaapi_device.cpp#L200)

Maybe API changed?

**Comment by qiushics** [comment]
Besides, I found the h264 decoder test failed on the build bot
[172](http://mediasdk.intel.com/buildbot/#/builders/2/builds/172)

**Comment by adydychk** [comment]
@qiushics Buildbot`s tests fail were because of infrastructure reasons.  
You can see that last tests are green: http://mediasdk.intel.com/buildbot/#/console

**Comment by onabiull** [comment]
I believe this fixed a long ago.
