### ISSUE TITLE
msdk didn't support 4Kx2K vp9 decode

### ISSUE THREAD

**Issue by ewanglong** [Intel-Media-SDK/MediaSDK#639]
MSDK sample decode return error when decoding 4Kx2K vp9 format. Seems it only support 1080p vp9 format decoding.

plugin_loader.h :186 [INFO] Plugin was loaded from GUID: { 0xa9, 0x22, 0x39, 0x4d, 0x8d, 0x87, 0x45, 0x2f, 0x87, 0x8c, 0x51, 0xf2, 0xfc,
0x9b, 0x41, 0x31 } (Intel (R) Media SDK HW plugin for VP9 DECODE)
pretending that stream is 30fps one
libva info: VA-API version 1.2.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /usr/lib64/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_2
libva info: va_openDriver() returns 0

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), AllocFrames, m_pmfxDEC->Query failed at /home/clr/work/gst/msdk/samples/sample_decode/src/pipeline_decode.cpp:1004

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), Init, AllocFrames failed at /home/clr/work/gst/msdk/samples/sample_decode/src/pipeline_decode.cpp:429

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), main, Pipeline.Init failed at /home/clr/work/gst/msdk/samples/sample_decode/src/sample_decode.cpp:666
plugin_loader.h :212 [INFO] MFXBaseUSER_UnLoad(session=0x0x5576917d9290), sts=0

**Comment by vshampor** [comment]
Greetings, @ewanglong!

Could you please provide the exact command line that produces this error?

**Comment by vshampor** [comment]
This is a [driver](https://github.com/intel/media-driver) problem - at [libmfx_core_vaapi.cpp:1294](https://github.com/Intel-Media-SDK/MediaSDK/blob/4f76d2166dcb8a887f313d2a241a4774937db3d8/_studio/shared/src/libmfx_core_vaapi.cpp#L1294-L1296) the driver returns 1920x1920 as its highest supported resolution, while in fact it can support larger resolution.

**Comment by dmitryermilov** [comment]
@vshampor , do we already have an issue at driver gitbug repo?

**Comment by dmitryermilov** [comment]
@vshampor , do we already have an issue at driver github repo?

**Comment by dmitryermilov** [comment]
@ewanglong , driver [fix](https://github.com/intel/media-driver/pull/341) has been merged. Can you please confirm that it fixes the issue?
