### ISSUE TITLE
The sample code sample_vpp cannot support yv12 to nv12 in MediaSDK 2018Q2.2 ?

### ISSUE THREAD

**Issue by 289801922** [Intel-Media-SDK/MediaSDK#658]
I run the command:

/opt/intel/mediasdk/samples/samples/__cmake/intel64.make.debug/__bin/debug/sample_vpp -sw 640 -sh 480 -dw 640 -dh 480 -scc yv12 -dcc nv12 -denoise 32 -i input.yv12 -o out.nv12

But I found the out.nv12 has the wrong colour, looks like greenish colour.
So, does the sample code sample_vpp cannot support yv12 to nv12 in MediaSDK 2018Q2.2 ?
Thanks

**Comment by dmitryermilov** [comment]
Yes, it does.
Please attach input YUV  file you used to check on our side. One frame is enough. BTW, are you sure that the input YUV is in YV12, not I420 ?

**Comment by dmitryermilov** [comment]
@289801922 , can you please reply?

**Comment by chivakker** [comment]
I'm seeing a core dump with a similar example, yv12 -> nv12 conversion

mplayer plays fine my yv12

mplayer ~/Videos/input_yv12.yuv -demuxer rawvideo -rawvideo w=176:h=144:yv12

Then MediaSDK

./sample_vpp -i ~/Videos/input_yv12.yuv -o ~/Videos/output_sample_i420.yuv -lib hw -sh 144 -sw 176 -dh 144 -dw 176 -scc yv12 -dcc nv12



#0  KernelDll_FindRule (pState=<optimized out>, pSearchState=0x55555567a128) at /usr/src/debug/media-driver-intel-media-19.1.0/media_driver/agnostic/common/vp/kdll/hal_kerneldll.c:1885
#1  0x00007ffff360a349 in KernelDll_SearchKernel (pSearchState=0x55555567a128, pState=0x7ffff21fc010) at /usr/src/debug/media-driver-intel-media-19.1.0/media_driver/agnostic/common/vp/kdll/hal_kerneldll.c:3620
#2  KernelDll_SearchKernel (pState=0x7ffff21fc010, pSearchState=0x55555567a128) at /usr/src/debug/media-driver-intel-media-19.1.0/media_driver/agnostic/common/vp/kdll/hal_kerneldll.c:3565
#3  0x00007ffff35f2973 in CompositeState::RenderPhase (this=this@entry=0x555555679de8, pCompParams=pCompParams@entry=0x7ffff6f986f0) at /usr/src/debug/media-driver-intel-media-19.1.0/media_driver/agnostic/common/vp/hal/vphal_render_composite.cpp:5949
#4  0x00007ffff35f33ed in CompositeState::RenderMultiPhase (this=this@entry=0x555555679de8, pcRenderParams=pcRenderParams@entry=0x7ffff6fa1410, ppSources=ppSources@entry=0x7ffff6f9cb60, iSources=iSources@entry=1, pOutput=pOutput@entry=0x5555556a9ae0) at /usr/src/debug/media-driver-intel-media-19.1.0/media_driver/agnostic/common/vp/hal/vphal_render_composite.cpp:2009
#5  0x00007ffff35f3ca2 in CompositeState::Render (this=<optimized out>, pcRenderParams=0x7ffff6fa1410, pRenderPassData=<optimized out>) at /usr/src/debug/media-driver-intel-media-19.1.0/media_driver/agnostic/common/vp/hal/vphal_render_composite.cpp:2341
#6  0x00007ffff360204b in VphalRenderer::RenderComposite (pRenderPassData=0x7ffff6fa1020, pRenderParams=0x7ffff6fa1410, this=0x555555670680) at /usr/src/debug/media-driver-intel-media-19.1.0/media_driver/agnostic/common/vp/hal/vphal_renderer.cpp:932
#7  VphalRenderer::RenderPass (this=0x555555670680, pRenderParams=0x7ffff6fa1410) at /usr/src/debug/media-driver-intel-media-19.1.0/media_driver/agnostic/common/vp/hal/vphal_renderer.cpp:759
#8  0x00007ffff36015a1 in VphalRenderer::Render (this=0x555555670680, pcRenderParams=<optimized out>) at /usr/src/debug/media-driver-intel-media-19.1.0/media_driver/agnostic/common/vp/hal/vphal_renderer.cpp:1183
#9  0x00007ffff35e6094 in VphalState::Render (this=0x55555564dbe0, pcRenderParams=0x5555556a7140) at /usr/src/debug/media-driver-intel-media-19.1.0/media_driver/agnostic/common/vp/hal/vphal.cpp:562
#10 0x00007ffff3827322 in DdiVp_EndPicture (pVaDrvCtx=pVaDrvCtx@entry=0x555555602af0, vaCtxID=vaCtxID@entry=1073741824) at /usr/src/debug/media-driver-intel-media-19.1.0/media_driver/linux/common/vp/ddi/media_libva_vp.c:3249
#11 0x00007ffff37f7ddb in DdiMedia_EndPicture (ctx=0x555555602af0, context=1073741824) at /usr/src/debug/media-driver-intel-media-19.1.0/media_driver/linux/common/ddi/media_libva.cpp:3324
#12 0x00007ffff6fba72d in vaEndPicture (context=1073741824, dpy=0x555555602980) at ../va/va.c:1519
#13 vaEndPicture (dpy=0x555555602980, context=1073741824) at ../va/va.c:1506
#14 0x00007ffff7015032 in MfxHwVideoProcessing::VAAPIVideoProcessing::Execute (this=0x555555619140, pParams=0x7ffff6fa1c90) at /usr/src/debug/MediaSDK-intel-mediasdk-19.1.0/_studio/shared/src/mfx_vpp_vaapi.cpp:1254
#15 0x00007ffff71c1b03 in MfxHwVideoProcessing::VideoVPPHW::SyncTaskSubmission (this=0x5555556c23f0, pTask=0x5555556c7710) at /usr/include/c++/9/bits/unique_ptr.h:357
#16 0x00007ffff6ff7306 in mfxSchedulerCore::call_pRoutine (call=..., this=0x5555555e6d60) at /usr/src/debug/MediaSDK-intel-mediasdk-19.1.0/_studio/mfx_lib/scheduler/include/mfx_scheduler_core.h:467
#17 mfxSchedulerCore::ThreadProc (this=0x5555555e6d60, pContext=0x5555556010a8) at /usr/src/debug/MediaSDK-intel-mediasdk-19.1.0/_studio/mfx_lib/scheduler/src/mfx_scheduler_core_thread.cpp:80
#18 0x00007ffff7e7d7b4 in execute_native_thread_routine () at ../../../../../gcc-9.1.0/libstdc++-v3/src/c++11/thread.cc:80
#19 0x00007ffff7f9d84e in start_thread (arg=<optimized out>) at pthread_create.c:486
#20 0x00007ffff7b56623 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

**Comment by ekislyuk** [comment]
@chivakker Could you please attach your input yuv file?  if the issue is still actual for you
