### ISSUE TITLE
sample_encode not working with sw

### ISSUE THREAD

**Issue by vashishkumar93** [Intel-Media-SDK/MediaSDK#664]
I have installed Media sdk-2018-Q2 according to the steps given in mediasdk guide.
I am using Ubuntu 18.04.1 LTS and kernel -> 4.16.0-041600-generic

I am trying to run sample_encode with hw , it is working fine but with sw it is giving error. I ran this command - 
./sample_encode h264 -i ../content/test_stream_176x96.yuv -o /tmp/1.h264 -w 176 -h 96 -sw 

I am getting this error- 
[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), Init, m_mfxSession.InitEx failed at /localdisk/bb/worker/build-master-branch/build_dir/repos/MediaSDK/samples/sample_encode/src/pipeline_encode.cpp:1265

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), main, pPipeline->Init failed at /localdisk/bb/worker/build-master-branch/build_dir/repos/MediaSDK/samples/sample_encode/src/sample_encode.cpp:1182

Can you please help me out?

Thanks

**Comment by otsirule** [comment]
Hello @vashishkumar93 !
Open source Media SDK doesn't have the software implementation of the library, that's why using -sw in command line leads to error.
