### ISSUE TITLE
class_wayland.h produces a handful of warnings

### ISSUE THREAD

**Issue by chivakker** [Intel-Media-SDK/MediaSDK#673]
[ 93%] Building CXX object samples/sample_misc/wayland/CMakeFiles/mfx_wayland.dir/src/class_wayland.cpp.o
In file included from /builddir/build/BUILD/MediaSDK-intel-mediasdk-18.3.pre2/samples/sample_misc/wayland/src/class_wayland.cpp:32:
/builddir/build/BUILD/MediaSDK-intel-mediasdk-18.3.pre2/samples/sample_misc/wayland/include/class_wayland.h: In constructor 'Wayland::Wayland()':
/builddir/build/BUILD/MediaSDK-intel-mediasdk-18.3.pre2/samples/sample_misc/wayland/include/class_wayland.h:135:25: warning: 'Wayland::m_shm_pool' will be initialized after [-Wreorder]
         struct ShmPool *m_shm_pool;
                         ^~~~~~~~~~
/builddir/build/BUILD/MediaSDK-intel-mediasdk-18.3.pre2/samples/sample_misc/wayland/include/class_wayland.h:133:32: warning:   'wl_event_queue* Wayland::m_event_queue' [-Wreorder]
         struct wl_event_queue *m_event_queue;
                                ^~~~~~~~~~~~~
/builddir/build/BUILD/MediaSDK-intel-mediasdk-18.3.pre2/samples/sample_misc/wayland/src/class_wayland.cpp:46:1: warning:   when initialized here [-Wreorder]
 Wayland::Wayland()
 ^~~~~~~
In file included from /builddir/build/BUILD/MediaSDK-intel-mediasdk-18.3.pre2/samples/sample_misc/wayland/src/class_wayland.cpp:32:
/builddir/build/BUILD/MediaSDK-intel-mediasdk-18.3.pre2/samples/sample_misc/wayland/include/class_wayland.h:137:13: warning: 'Wayland::m_fd' will be initialized after [-Wreorder]
         int m_fd;
             ^~~~
/builddir/build/BUILD/MediaSDK-intel-mediasdk-18.3.pre2/samples/sample_misc/wayland/include/class_wayland.h:136:13: warning:   'int Wayland::m_display_fd' [-Wreorder]
         int m_display_fd;
             ^~~~~~~~~~~~
/builddir/build/BUILD/MediaSDK-intel-mediasdk-18.3.pre2/samples/sample_misc/wayland/src/class_wayland.cpp:46:1: warning:   when initialized here [-Wreorder]
 Wayland::Wayland()
 ^~~~~~~
In file included from /builddir/build/BUILD/MediaSDK-intel-mediasdk-18.3.pre2/samples/sample_misc/wayland/src/class_wayland.cpp:32:
/builddir/build/BUILD/MediaSDK-intel-mediasdk-18.3.pre2/samples/sample_misc/wayland/include/class_wayland.h:140:15: warning: 'Wayland::m_device_name' will be initialized after [-Wreorder]
         char *m_device_name;
               ^~~~~~~~~~~~~
/builddir/build/BUILD/MediaSDK-intel-mediasdk-18.3.pre2/samples/sample_misc/wayland/include/class_wayland.h:134:22: warning:   'volatile int Wayland::m_pending_frame' [-Wreorder]
         volatile int m_pending_frame;
                      ^~~~~~~~~~~~~~~
/builddir/build/BUILD/MediaSDK-intel-mediasdk-18.3.pre2/samples/sample_misc/wayland/src/class_wayland.cpp:46:1: warning:   when initialized here [-Wreorder]

**Comment by dvrogozh** [comment]
I believe this was fixed and should be available in the next round of 18.3 pre-release/release. @onabiull : can you, please, consider set 18.3.pre3 tag?

**Comment by dvrogozh** [comment]
@chivakker : can you, please, switch to https://github.com/Intel-Media-SDK/MediaSDK/releases/tag/intel-mediasdk-18.3.pre3 and try again? I believe that warnings should be gone.

**Comment by chivakker** [comment]
Yes, confirming these warnings go away with given pre-release intel-mediasdk-18.3.pre3
