### ISSUE TITLE
sample_decode freezes system when running X11 mode

### ISSUE THREAD

**Issue by chivakker** [Intel-Media-SDK/MediaSDK#674]
This might be particular to the configuration given.  I am enabling wayland and x11 at the same time.  This is the configuration output:

I have not hooked up GDB yet.

********************** Media SDK Configuration Summary **********************
MediaSDK:
  API (request to use this version)       :
  API_VERSION                             : 1.27
  API_FLAGS                               :
  MFX_CONFIG_FILE                         :
  See detailed per-component mediasdk configuration in the auto-generated file:
    /builddir/build/BUILD/MediaSDK-intel-mediasdk-18.3.pre2/clr-build/mfxconfig.h
Cmake:
  CMAKE_VERSION                           : 3.12.2
  CMAKE_GENERATOR                         : Unix Makefiles
  CMAKE_BUILD_TOOL                        : /usr/bin/gmake
Target:
  CMAKE_SYSTEM_NAME                       : Linux
  CMAKE_SYSTEM_VERSION                    : 4.18.9-635.native
  CMAKE_SYSTEM_PROCESSOR                  : x86_64
General:
  CMAKE_BUILD_TYPE                        : Release
  CMAKE_TOOLCHAIN_FILE                    :
  CMAKE_C_COMPILER                        : /usr/lib64/ccache/bin/gcc
  CMAKE_CXX_COMPILER                      : /usr/lib64/ccache/bin/g++
  Building architecture                   : 64-bit
Flags:
  CMAKE_C_FLAGS                           : -msse4.2 -m64 -g -O2 -fPIC -g -feliminate-unused-debug-types -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=32 -Wformat -Wformat-security -Wl,--copy-dt-needed-entries,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -ftree-vectorize -Wl,--enable-new-dtags -m64 -march=westmere -mtune=haswell -fasynchronous-unwind-tables -fno-omit-frame-pointer -Wp,-D_REENTRANT -pipe -fPIC -Wall -Wformat -Wformat-security -Wno-deprecated-declarations -Wno-unknown-pragmas -Wno-unused
  CMAKE_CXX_FLAGS                         : -msse4.2 -std=c++11 -m64 -g -O2 -fPIC -g -feliminate-unused-debug-types -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=32 -Wformat -Wformat-security -Wl,--copy-dt-needed-entries,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -ftree-vectorize -Wl,--enable-new-dtags -m64 -march=westmere -mtune=haswell -fasynchronous-unwind-tables -fno-omit-frame-pointer -Wp,-D_REENTRANT -pipe -fPIC -Wall -Wformat -Wformat-security -Wnon-virtual-dtor -Wno-deprecated-declarations -Wno-unknown-pragmas -Wno-unused
Release flags:
  CMAKE_C_FLAGS_RELEASE                   : -O3 -DNDEBUG
  CMAKE_CXX_FLAGS_RELEASE                 : -O3 -DNDEBUG
Debug flags:
  CMAKE_C_FLAGS_DEBUG                     : -g -D_DEBUG
  CMAKE_CXX_FLAGS_DEBUG                   : -g -D_DEBUG
Install:
  CMAKE_INSTALL_PREFIX                    : /usr
  CMAKE_INSTALL_FULL_INCLUDEDIR           : /usr/include
  CMAKE_INSTALL_FULL_LIBDIR               : /usr/lib64
  CMAKE_INSTALL_FULL_DATADIR              : /usr/share
Enable:
  ENABLE_OPENCL                           : ON
  ENABLE_X11_DRI3                         : OFF
  ENABLE_WAYLAND                          : true
  ENABLE_ITT                              : OFF
  ENABLE_TEXTLOG                          : OFF
  ENABLE_STAT                             : OFF
Build:
  BUILD_RUNTIME                           : ON
  BUILD_DISPATCHER                        : ON
  BUILD_SAMPLES                           : ON
  BUILD_TOOLS                             : OFF
*****************************************************************************
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:
    LIB_INSTALL_DIR
    LIB_SUFFIX
-- Build files have been written to: /builddir/build/BUILD/MediaSDK-intel-mediasdk-18.3.pre2/clr-build
+ make -j4

**Comment by dvrogozh** [comment]
This looks not to be a system freeze, but X server freeze. System is responsible via SSH and even via CTRL+ALT+FN switching to console mode. I don't have a clue why this can be happening yet. 

@chivakker:
1. Do you build on the same system which you later on run?
2. If not, what are host and client systems? 
3. If not, can you try to run on a host system instead of a client (if it has compatible GPU of course)?

**Comment by dvrogozh** [comment]
@chivakker: still, would that be possible to run the test case on the same system where code was built?
