### ISSUE TITLE
mediasdk build system not honoring user settings

### ISSUE THREAD

**Issue by chivakker** [Intel-Media-SDK/MediaSDK#678]
CMake Warning:
  Manually-specified variables were not used by the project:
    LIB_INSTALL_DIR
    LIB_SUFFIX

This are provided during configure like this:

cmake .. -G 'Unix Makefiles' -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_SHARED_LIBS:BOOL=ON -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DCMAKE_AR=/usr/bin/gcc-ar -DLIB_SUFFIX=64 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_RANLIB=/usr/bin/gcc-ranlib -DENABLE_WAYLAND=true -DENABLE_X11=true

**Comment by dvrogozh** [comment]
What are these variables and why you expect mediasdk to use them? Media SDK uses these variables to configure installation directories: https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html. Briefly looking I do not see any informative description on how LIB_INSTALL_DIR and LIB_SUFFIX are expected to be used.

**Comment by chivakker** [comment]
Exactly, you're using GNUInstallDirs without checking if the user  defined LIB_SUFFIX and LIB_INSTALL_DIR; and that needs fixing. 

This is an example I could find

https://github.com/intel/metrics-discovery/pull/8/files

**Comment by dvrogozh** [comment]
`set (LIB_INSTALL_DIR "${CMAKE_INSTALL_PREFIX}/lib${LIB_SUFFIX}")`

This looks to be equivalent of CMAKE_INSTALL_LIBDIR. Why you don't use this variable?

@chivakker : cmake supports passing arbitrary variables and I can imagine a lot of names for the same thing. For example, LIB_INSTALL_DIR or MFX_LIB_INSTALL_DIR or INSTALL_LIBDIR, etc. Why you believe that we should support some variable if it is not documented in cmake? CMAKE_INSTALL_LIBDIR is documented, LIB_INSTALL_DIR - is not (or I did not find it). We can not support individual different settings per-convenience of each project which tries to build mediasdk.

So, I am not convinced that we need to support this. We use https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html to configure things. I am ok to consider something else, but you need to provide a reason for that. This can be cmake documentation that such variables should be honored, or a reference to some community-accepted packaging tool which uses these settings, etc. As of now you did not provide such reason.

**Comment by uartie** [comment]
The problem is not GNUInstallDirs.  LIB_INSTALL_DIR is not a cmake builtin variable.  We should be using CMAKE_INSTALL_LIBDIR in cmake files instead.  And user should use that variable to override library install path.

https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html

**Comment by uartie** [comment]
And if user does not override CMAKE_INSTALL_LIBDIR, then GNUInstallDirs will generate it base on platform and CMAKE_INSTALL_PREFIX

**Comment by uartie** [comment]
respectfully, I have to agree with @dvrogozh

**Comment by chivakker** [comment]
@dvrogozh yes, I am looking for the reasoning behind this, will provide asap.

**Comment by chivakker** [comment]
After some investigation on this, there's indeed not specific rule for defining those variables.  As mentioned by @uartie this shouldn't be expected to be honored by this package.  Closing this issue; I hope this doesn't cause further confusion
