### ISSUE TITLE
About 25% slower than windows

### ISSUE THREAD

**Issue by qiushics** [Intel-Media-SDK/MediaSDK#69]
CPU: i7 6700

command:
`sample_multi_transcode -i::h264 a.h264 -o::h264 b.h264
`
Ubuntu16.04.3 X64
`*** session 0 PASSED (MFX_ERR_NONE) 554.268 sec, 92583 frames
`
Win7 X64
`*** session 0 PASSED (MFX_ERR_NONE) 450.646 sec, 92583 frames`

Should I change some parameters?

**Comment by artem-shaporenko** [comment]
Any details what resolution/etc you are running? Is it open source linux?

**Comment by qiushics** [comment]
@artem-shaporenko 
The resolution is  1080P.
On linux I use the opensource version MediaSDK, and compile the libva/gmmlib/media driver(git master)
On windows I use Intel_Media_SDK_2017_R1.

**Comment by artem-shaporenko** [comment]
libva/gmmlib/media driver? SO it is not https://github.com/intel/media-driver?

**Comment by qiushics** [comment]
@artem-shaporenko 
I've tried 3 methods:
Windows Media SDK > Linux Media SDK/media driver(iHD) >= vaapi driver(i915) through ffmpeg
Windows Media SDK(https://github.com/Intel-Media-SDK/samples compiled with Intel_Media_SDK_2017_R1) is 25% faster than Linux Media SDK with iHD (this repo) using `sample_multi_transcode`.

So may I change some parameters to import the performance on linux?

vainfo output:
```
vainfo
error: can't connect to X server!
libva info: VA-API version 1.0.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /usr/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_0
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.0 (libva 2.0.1.pre1)
vainfo: Driver version: Intel iHD driver - 2.0.0
vainfo: Supported profile and entrypoints
      VAProfileNone                   : VAEntrypointVideoProc
      VAProfileNone                   : VAEntrypointStats
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Simple            : VAEntrypointEncSlice
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointFEI
      VAProfileH264Main               : VAEntrypointEncSliceLP
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointFEI
      VAProfileH264High               : VAEntrypointEncSliceLP
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline: VAEntrypointFEI
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointFEI
```

**Comment by artem-shaporenko** [comment]
@qiushics Are you seeing difference in performance with ffmpeg?
About samples - latest good samples for linux currently placed in https://github.com/Intel-Media-SDK/MediaSDK/ samples folder, I'm not sure if issue is in samples, but that can be a case.
What KMD are you using? Upstream KMD has non optimal performance, there are patches for KMD required. @dvrogozh @onabiull do we have patches available somewhere in public?
To verify - you can try to install our closed source release in binary form from https://software.intel.com/en-us/intel-media-server-studio, select community addition for free download. There is an instruction how to install it.

**Comment by dvrogozh** [comment]
@qiushics 
-  You may wish to play with the **-async N**, N=1,2,3,4,5 option of sample_multi_transcode both on Windows and Linux. This will set asynchronous level where N=1 will by just synchronous mode and should be the slowest if you have single transcoding. Appreciate if you will provide a comparison table between Windows and Linux. Optimal operation point (fastest) should be N=2 or 3, it can be different between Windows/Linux.
- And I have a question regarding your configuration: do you run on Linux in a headless mode (no display attached)? if display is attached, which connector do you use?

**Comment by qiushics** [comment]
Thanks for reply. I'll do more tester to dig into the performace issue.

**Comment by adydychk** [comment]
@qiushics It seems like the questions is answered. I will close this issue but you can open new one or reopen this if you want. You are always welcome.
