### ISSUE TITLE
No MediaStack download link in version 18.3.0

### ISSUE THREAD

**Issue by dbermond** [Intel-Media-SDK/MediaSDK#698]
There is no download link for `MediaStack.tar.gz` binary package in version 18.3.0 as in previous versions. There are only links for the pdf release notes and for source code.

Is this intentional?

**Comment by chivakker** [comment]
It doesn't seem to be the final release. @alariono can you clarify?

**Comment by dmitryermilov** [comment]
Yes, it's not a final version yet.

**Comment by onabiull** [comment]
Yes, this is intentional. Once val cycle completed, and all required checks passed, I'll upload tarball along with release promotion to "release" state.

**Comment by dbermond** [comment]
Ok. The previous releases are also not final versions and they contain the binary package `MediaStack.tar.gz`. That's why I'm asking, because it's different from previous pre-releases.

**Comment by dmitryermilov** [comment]
[18.3.0/MediaStack.tar.gz](https://github.com/Intel-Media-SDK/MediaSDK/releases/download/intel-mediasdk-18.3.0/MediaStack.tar.gz ) been uploaded.
