### ISSUE TITLE
the output of h264 sample decode  has some garbage in some case

### ISSUE THREAD

**Issue by fulinjie** [Intel-Media-SDK/MediaSDK#715]
Issue description:
https://trac.ffmpeg.org/ticket/7397

Tested with the latest version of MSDK： c083a2724b99851af6d69bbb35e3130b39a1f702

$ ffmpeg -i crop-to-container-dims-canon.mov -c:v copy src.h264
$ ./sample_decode h264 -i src.h264 -i420 -o msdk.yuv

$ ffmpeg -hwaccel qsv -hwaccel_device /dev/dri/renderD128 -v verbose -y -c:v h264_qsv -i crop-to-container-dims-canon.mov -vf hwdownload,format=nv12 -pix_fmt yuv420p -f rawvideo -y dump.yuv -vsync 0

Both msdk.yuv and dump.yuv have garbage in my test. 
The same file could be decoded correctly using ffmpeg vaapi or ffmpeg software.

**Comment by ekislyuk** [comment]
still actual

**Comment by weizhu-intel** [comment]
Hi fulinjie:
Raw video src.h264 don't have actual  video size information, it is contained in mov container.
So when decode raw video, you can only use actual decode surface size 1920*1088 for check.  

It is not a bug.
