### ISSUE TITLE
QSV encoding using avcodec (issue w/ 640x480 MFX encoding, FFMPeg 4.0.2)

### ISSUE THREAD

**Issue by lp35** [Intel-Media-SDK/MediaSDK#716]
Hi all,

Using FFMpeg 4.0.2 for Windows from Zeranoe (https://ffmpeg.zeranoe.com/builds/), I am encountering an issue while encoding in 640x480. It seems that the video stream is going backward each 3~5 frames. (see this attached file: 
[mv-test-new-0007-2018_10_5-19_17_36.zip](https://github.com/Intel-Media-SDK/MediaSDK/files/2459620/mv-test-new-0007-2018_10_5-19_17_36.zip) )

Context:

I am developing an application that makes use of FFMpeg libraries (libavcodec, libavformat, etc.). I inspired myself to a unfortunately non-merged patch from Zhong Li: [FFMpeg example qsv encoding](https://ffmpeg.org/pipermail/ffmpeg-devel/2017-August/214425.html).
Following are the parameters I pass to AvCodec:

    vCodecCtx->bit_rate = 400000;
    vCodecCtx->gop_size = 10;					//TODO: add parameter for that?
    // vCodecCtx->max_b_frames = 0; // Working if uncommented
    vCodecCtx->width = 640;
    vCodecCtx->height = 480;
    vCodecCtx->pix_fmt = AV_PIX_FMT_NV12;
    vCodecCtx->hw_device_ctx = av_buffer_ref(mEncode_device); // Hw context

Not setting max_b_frames to 0 seems to make the bug appears. So I would like to know why this parameter is changing the way Intel QSV works compared to other encoders (tried x264 and NvEnc, no issues so far). Please not that using a stream in 800x600, this "reward bug" is not present.

Also note that re-encoding a file using a FFMpeg binary directly does not make this bug to appear.

Thank you for your lights.

**Comment by maximd33** [comment]
I need to clarify a couple of things:
what is your command line when you use ffmpeg.exe directly? 
or the problem happens in your implementation only?

> Also note that re-encoding a file using a FFMpeg binary directly does not make this bug to appear.


in the sense of: using QSV path or a CPU encode ?

> Not setting max_b_frames to 0 seems to make the bug appears. 

we might want to add enforcing default values.

does it happen in your case for both: release and debug builds?
