### ISSUE TITLE
Remove warning with clang

### ISSUE THREAD

**Issue by chivakker** [Intel-Media-SDK/MediaSDK#729]
Compiling with clang brings a lot of warnings, please fix:

i.e.

clang-7: warning: -Wl,--copy-dt-needed-entries,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code: 'linker' input unused [-Wunused-command-line-argument]
clang-7: warning: -Wl,--enable-new-dtags: 'linker' input unused [-Wunused-command-line-argument]
[ 30%] Building CXX object _studio/shared/umc/CMakeFiles/umc.dir/core/umc/src/umc_frame_data.cpp.o
clang-7: warning: -Wl,--copy-dt-needed-entries,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code: 'linker' input unused [-Wunused-command-line-argument]
clang-7: warning: -Wl,--enable-new-dtags: 'linker' input unused [-Wunused-command-line-argument]
[ 30%] Building CXX object _studio/shared/umc/CMakeFiles/umc_va_hw.dir/io/umc_va/src/umc_va_video_processing.cpp.o
clang-7: warning: -Wl,--copy-dt-needed-entries,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code: 'linker' input unused [-Wunused-command-line-argument]
clang-7: warning: -Wl,--enable-new-dtags: 'linker' input unused [-Wunused-command-line-argument]
[ 31%] Building CXX object _studio/shared/umc/CMakeFiles/umc.dir/core/umc/src/umc_media_data.cpp.o
clang-7: warning: -Wl,--copy-dt-needed-entries,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code: 'linker' input unused [-Wunused-command-line-argument]
clang-7: warning: -Wl,--enable-new-dtags: 'linker' input unused [-Wunused-command-line-argument]
[ 31%] Building CXX object _studio/shared/umc/CMakeFiles/umc.dir/core/umc/src/umc_va_base.cpp.o
clang-7: warning: -Wl,--copy-dt-needed-entries,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code: 'linker' input unused [-Wunused-command-line-argument]
clang-7: warning: -Wl,--enable-new-dtags: 'linker' input unused [-Wunused-command-line-argument]
[ 31%] Building CXX object _studio/shared/umc/CMakeFiles/umc.dir/core/umc/src/umc_video_data.cpp.o
clang-7: warning: -Wl,--copy-dt-needed-entries,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code: 'linker' input unused [-Wunused-command-line-argument]
clang-7: warning: -Wl,--enable-new-dtags: 'linker' input unused [-Wunused-command-line-argument]
[ 31%] Building CXX object _studio/shared/umc/CMakeFiles/umc.dir/core/umc/src/umc_video_decoder.cpp.o

**Comment by mgonchar** [comment]
@dvrogozh can we close this one now?

**Comment by dvrogozh** [comment]
@chivakker : We recently closed a lot of warnings for clang and we hoped we achieved 0-level warning with clang-8. At least we were able to introduce -Werror for clang CI build path. Could you, please, check warnings status on your side and give us feedback? Most recent fixes:
* https://github.com/Intel-Media-SDK/MediaSDK/pull/1678
* https://github.com/Intel-Media-SDK/MediaSDK/pull/1676
* https://github.com/Intel-Media-SDK/MediaSDK/pull/1659
* https://github.com/Intel-Media-SDK/MediaSDK/pull/1660
* https://github.com/Intel-Media-SDK/MediaSDK/pull/1636

**Comment by chivakker** [comment]
I tried ToT SHA and clang-9, still see a few linker warnings

fwiw, reference sha is 44cec624dc91f86b0b9a559467a9fb820d96807b

these warnings don't seem to affect actual functionality when compiling with clang.  Also I see they're considerably less but still present.

**Comment by dvrogozh** [comment]
@chivakker : can you, please, post part of the log with warnings which you see?

As of now we use clang-8 in the CI, but plan to switch to clang-9 in the next few weeks.

**Comment by dvrogozh** [comment]
By the way, you might need to set `-DCMAKE_ASM_COMPILER=clang-9` since we have few files with assembler code... This might be reason why you still see some warnings.

**Comment by chivakker** [comment]
The logs are in the first comment, so in this case "--enable-new-dtags" is given by user on compiler/linker flags.  Then in some cases, I'd assume mediasdk uses such parameter and the warning doesn't come up.  In some cases mediasdk won't use it and linker prints a warning.  I also think the ASM_COMPILER is defaulting to clang, it happens that my clang is clang-9 but that shouldn't matter.

**Comment by dvrogozh** [comment]
I believe that mediasdk build system does not specify those flags which you see in warnings. For example, `--copy-dt-needed-entries` is definitely missing. Thus, I believe that they are coming externally, i.e. these flags are specified as configuration input by your scripts.

Can you, please, check that you set these flags only to the linker, for example via `LINK_FLAGS` and they don't go into `CMAKE_C_FLAGS` and `CMAKE_CXX_FLAGS` kind of variables?

**Comment by egorovdanil** [comment]
I tried to build msdk on clang-9 by adding these flags to the `LINK_FLAGS` and did not get any warnings.

**Comment by dvrogozh** [comment]
If this issue persists, please, reopen specifying the full cmake configuration command line with all custom compile/linker flags being passed during the build.
