### ISSUE TITLE
Open-source Intel Media SDK stack doesn't work with Apollo Lake platform Intel Celeron J3455

### ISSUE THREAD

**Issue by ishmael1985** [Intel-Media-SDK/MediaSDK#74]
I built and installed Intel Media SDK (MSDK) on an Intel Celeron J3455 system (https://ark.intel.com/products/95594/Intel-Celeron-Processor-J3455-2M-Cache-up-to-2_3-GHz) which is based on the Apollo Lake platform. I followed the build instructions according to the following link:

https://software.intel.com/en-us/articles/build-and-debug-open-source-media-stack

When building and testing the Intel media driver, everything looks fine.

```
ishmael@ishmael-desktop /opt/intel/mediasdk/samples $ vainfo
libva info: VA-API version 1.0.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_0
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.0 (libva 2.0.1.pre1)
vainfo: Driver version: Intel iHD driver - 2.0.0
vainfo: Supported profile and entrypoints
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileNone                   :	VAEntrypointStats
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointFEI
      VAProfileH264Main               :	VAEntrypointEncSliceLP
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointFEI
      VAProfileH264High               :	VAEntrypointEncSliceLP
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointFEI
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointFEI
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileVP9Profile0            :	VAEntrypointVLD
```

However, after installing the open-source stack and testing with the sample_decode application I get the following:

```
ishmael@ishmael-desktop /opt/intel/mediasdk/samples $ ./sample_decode h264 -i /home/ishmael/Videos/bbb.h264

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), Init, m_mfxSession.Init failed at /home/ishmael/msdk/MediaSDK/samples/sample_decode/src/pipeline_decode.cpp:293

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), main, Pipeline.Init failed at /home/ishmael/msdk/MediaSDK/samples/sample_decode/src/sample_decode.cpp:674
```

I made sure that the I built the open-source MSDK stack by specifying `--target=BXT` in the Perl build command as specified by the guide given on the link I provided. I am using the 4.14.16 Linux kernel version with the BXT firmware included as recommended by the mentioned guide. I am providing the processor details as follows:

```
ishmael@ishmael-desktop /opt/intel/mediasdk/samples $ cat /proc/cpuinfo processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 92
model name	: Intel(R) Celeron(R) CPU J3455 @ 1.50GHz
stepping	: 9
microcode	: 0x20
cpu MHz		: 1390.211
cache size	: 1024 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 21
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology tsc_reliable nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg cx16 xtpr pdcm sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave rdrand lahf_lm 3dnowprefetch cpuid_fault cat_l2 pti retpoline tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust smep erms mpx rdt_a rdseed smap clflushopt intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts
bugs		: monitor cpu_meltdown spectre_v1 spectre_v2
bogomips	: 2995.20
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 92
model name	: Intel(R) Celeron(R) CPU J3455 @ 1.50GHz
stepping	: 9
microcode	: 0x20
cpu MHz		: 1299.581
cache size	: 1024 KB
physical id	: 0
siblings	: 4
core id		: 1
cpu cores	: 4
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 21
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology tsc_reliable nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg cx16 xtpr pdcm sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave rdrand lahf_lm 3dnowprefetch cpuid_fault cat_l2 pti retpoline tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust smep erms mpx rdt_a rdseed smap clflushopt intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts
bugs		: monitor cpu_meltdown spectre_v1 spectre_v2
bogomips	: 2995.20
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 2
vendor_id	: GenuineIntel
cpu family	: 6
model		: 92
model name	: Intel(R) Celeron(R) CPU J3455 @ 1.50GHz
stepping	: 9
microcode	: 0x20
cpu MHz		: 1356.676
cache size	: 1024 KB
physical id	: 0
siblings	: 4
core id		: 2
cpu cores	: 4
apicid		: 4
initial apicid	: 4
fpu		: yes
fpu_exception	: yes
cpuid level	: 21
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology tsc_reliable nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg cx16 xtpr pdcm sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave rdrand lahf_lm 3dnowprefetch cpuid_fault cat_l2 pti retpoline tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust smep erms mpx rdt_a rdseed smap clflushopt intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts
bugs		: monitor cpu_meltdown spectre_v1 spectre_v2
bogomips	: 2995.20
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 3
vendor_id	: GenuineIntel
cpu family	: 6
model		: 92
model name	: Intel(R) Celeron(R) CPU J3455 @ 1.50GHz
stepping	: 9
microcode	: 0x20
cpu MHz		: 1425.584
cache size	: 1024 KB
physical id	: 0
siblings	: 4
core id		: 3
cpu cores	: 4
apicid		: 6
initial apicid	: 6
fpu		: yes
fpu_exception	: yes
cpuid level	: 21
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology tsc_reliable nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg cx16 xtpr pdcm sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave rdrand lahf_lm 3dnowprefetch cpuid_fault cat_l2 pti retpoline tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust smep erms mpx rdt_a rdseed smap clflushopt intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts
bugs		: monitor cpu_meltdown spectre_v1 spectre_v2
bogomips	: 2995.20
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:
```

The system configuration is based from this product:

https://www.amazon.com/Compact-Channel-Bluetooth-Pre-Assembled-ITX/dp/B0755KPNYR

I tried the latest media driver, libva, gmmlib versions from the master branch, as well as the specific commits as given by the guide, and all give the same result as described. What did I miss?

**Comment by dvrogozh** [comment]
This error usually means that mediasdk library just was not loaded, not that you have some issue in the media support. To verify this theory, please, locate libmfxhw64.so library, it should be available at /opt/intel/mediasdk/lib64 and try to export the path:
`export LD_LIBRARY_PATH=/opt/intel/mediasdk/lib64`
Then rerun sample_decode. Will it run? If this will succeed, please, specify which commitid you've built? Was that the latest master? I thought that this installation issue is actually already solved.

**Comment by ishmael1985** [comment]
Well, you're right, I did miss that step carelessly! I will report what I get tomorrow after that simple export command.

**Comment by dvrogozh** [comment]
Well, I would say this is not a proper installation step, that's a workaround or development solution. The proper step to see mediasdk installed should be
`make install`
which I think you performed (please confirm) since otherwise I don't understand how you got mediasdk at the /opt/intel location:). I know this issue, but I hoped it is already resolved. A pity if it is not. So, once we confirm that LD_LIBRARY_PATH works, I will ping the team to see the issue addressed.

**Comment by ishmael1985** [comment]
The resulting /opt/intel/mediasdk directories were created by the following commands after the build step as mentioned in the README file.

```
cd __cmake/intel64.make.release
sudo make install
```

Those commands were not mentioned in the README but was used as part of the installation process in the guide - https://software.intel.com/en-us/articles/build-and-debug-open-source-media-stack. But a better solution would be to provide a proper `make install` step and update the README accordingly.

**Comment by dvrogozh** [comment]
I completely agree.

**Comment by ishmael1985** [comment]
The LD_LIBRARY_PATH export works, but is still required with the latest version in the MediaSDK master branch. The commit IDs I used are:

https://github.com/intel/libva/commit/f2f9956f1dd871af59f2fd9bc6fdfc6c0992f0d1
https://github.com/intel/gmmlib/commit/6f565367e87c2c6628efd8d60b357b5ffb1a54e8
https://github.com/intel/media-driver/commit/43a84e7a893ebf0433a8efc6bb7ab6a3e325a3fa
https://github.com/Intel-Media-SDK/MediaSDK/commit/c2ad93af671190ac5b9ba224eced65b0dd73c601

For now I resorted to custom shell and conf files to export libva-related environmental variables and the custom libmfxhw64.so in `/opt/intel/mediask/lib`. It would be more convenient if these shell and conf files were created automatically during the install process, but it would require a `make uninstall` step to remove these files which cmake does not trivially support.
Thanks for catching my careless mistake!

**Comment by uartie** [comment]
If you specify `--prefix=/usr` to `build_mfx.pl` then everything should be installed into system paths... and you wouldn't have to deal with the env var mess.

**Comment by ishmael1985** [comment]
Thanks @uartie for the tip. I prefer the default install path as is for now (/opt/intel/mediasdk) for  development purposes, in case I need to do a clean reinstall of MSDK. Any idea how to achieve something similar to a `make uninstall` if I installed to system paths?

**Comment by uartie** [comment]
I wrote a script long ago that ran `make install` and then `make install DESTDIR=<some temp dir>`.  Then, the script walks the contents of DESTDIR and saves a manifest of all the files (replacing DESTDIR with actual install prefix in the manifest).  Then later, you can use the manifest to uninstall the correct files.  Yes, it's hackish and requires make install twice!

I know autotools-enabled projects look for the `INSTALL` environment variable which can be set to any custom script you want... and it will be called for every file its installing during `make install`.  That custom script could save a manifest of each file it sees and `make install` would only need to run once.  But unfortunately, I don't think cmake supports `INSTALL` variable.

Therefore, I'm not aware of any solution beyond one-off hacks that support simple uninstall (other than incorporating a package manager (e.g. rpm) into your workflow).

Nonetheless, in the past, I always used isolated custom, non-system build/install directories with `LD_LIBRARY_PATH`, `PKG_CONFIG_PATH`, `LDFLAGS` and etc. variables to avoid system pollution during development.  Nowadays, it's easier to just use Docker containers to isolate development and prevent host system pollution.

**Comment by ishmael1985** [comment]
+1 for Docker.
