### ISSUE TITLE
vp9e: do not allocate internal resources via external allocator

### ISSUE THREAD

**Issue by dvrogozh** [Intel-Media-SDK/MediaSDK#762]
Please, switch vp9 encoder to use internal mediasdk core and avoid any external allocations for internal resources.

**Comment by xhaihao** [comment]
@dvrogozh @onabiull @DmitryMalishev is D3DDDIFMT_INTELENCODE_MBSEGMENTMAP (MFX_FOURCC_VP9_SEGMAP)  an internal resource ?  According to https://github.com/Intel-Media-SDK/MediaSDK/blob/f290d47574a35152d057d5d19e8df5080d4072d3/_studio/shared/src/libmfx_core_vaapi.cpp#L528, MediaSDK still tries to use the external frame allocator for D3DDDIFMT_INTELENCODE_MBSEGMENTMAP on linux

**Comment by DmitryMalishev** [comment]
Hi @xhaihao,
MFX_FOURCC_VP9_SEGMAP surface has MFX_MEMTYPE_INTERNAL_FRAME flag when inited:
https://github.com/Intel-Media-SDK/MediaSDK/blob/b1c624e14660e3fa33302f98f84915cef4fee4e3/_studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw.cpp#L226
https://github.com/Intel-Media-SDK/MediaSDK/blob/b1c624e14660e3fa33302f98f84915cef4fee4e3/_studio/mfx_lib/encode_hw/vp9/include/mfx_vp9_encode_hw_utils.h#L75
It means that internal frame allocator should be used for this surface allocation:
https://github.com/Intel-Media-SDK/MediaSDK/blob/b1c624e14660e3fa33302f98f84915cef4fee4e3/_studio/shared/src/libmfx_core_vaapi.cpp#L560-L563
Do you see in debug that it is not the case? Please let us know if so.

@eshiryae, could you please track this request if more help required?

**Comment by xhaihao** [comment]
@DmitryMalishev @eshiryae  No, it is not the case because m_Display is not NULL. 

Maybe MFX_FOURCC_VP9_SEGMAP should go into the else block too.

https://github.com/Intel-Media-SDK/MediaSDK/blob/b1c624e14660e3fa33302f98f84915cef4fee4e3/_studio/shared/src/libmfx_core_vaapi.cpp#L612-L623

**Comment by DmitryMalishev** [comment]
@xhaihao, thank you for the clarification.
Before solving it out we(@eshiryae) would like to ask you a couple of things:
[1] What is the impacted usage scenario? Do you have workaround?
[2] Is it urgent change request?
[3] Is it possible to make it work by returning an UNSUPPORTED status from the external allocator on this request to make it use the internal allocator then?
https://github.com/Intel-Media-SDK/MediaSDK/blob/b1c624e14660e3fa33302f98f84915cef4fee4e3/_studio/shared/src/libmfx_core_vaapi.cpp#L572-L577

**Comment by xhaihao** [comment]
@DmitryMalishev we are enabling vp9 encode in both ffmpeg/qsv and gst-msdk which have an external allocator. We may workaround it by returning an UNSUPPORTED status however we have to provide the workaround in both ffmpeg/qsv and gst-msdk, another thing is we failed to find MFX_FOURCC_VP9_SEGMAP in mfx header files, so we have to define it in ffmpeg/qsv and gst-msdk. Hence I think it would be better to fix it in MediaSDK.

**Comment by eshiryae** [comment]
Hi @xhaihao, thank you for the details, we understand the problem and will work to solve it.

**Comment by eshiryae** [comment]
Hi @xhaihao, it is expected behavior for hw library and in this case you should return an unsupported error(MFX_ERR_UNSUPPORTED) for segmentation map allocation try. All resources which unsupported by external allocator are allocated by internal allocator.
According MFX_FOURCC_VP9_SEGMAP, you can define it as it's done here:
https://github.com/Intel-Media-SDK/MediaSDK/blob/fcc342685c1809b2f3d83d3cb70ed9868e62ad52/_studio/mfx_lib/encode_hw/vp9/include/mfx_vp9_encode_hw_vaapi.h#L34
