### ISSUE TITLE
VP9 decode plugin doesn't get built for Intel Media SDK with Apollo Lake platforms

### ISSUE THREAD

**Issue by ishmael1985** [Intel-Media-SDK/MediaSDK#77]
Even though the Intel media driver (https://github.com/intel/media-driver) specifies VP9 Profile 0 decode support for BXT / APL, the VP9 decode plugin for MSDK doesn't seem to get included when building MSDK. Intel MSDK 2017 for Embedded Linux seems to have VP9 decode support (https://software.intel.com/sites/default/files/managed/9b/7b/mediasdkembedded_release_notes.pdf), so I would assume the open-source MSDK stack would have VP9 decode support as well ever since BXT / APL support was introduced. Did I miss a flag to enable this feature apart from `--target=BXT` when building MSDK?

**Comment by ishmael1985** [comment]
I've checked the source and seen that there is no indication of VP9 decode support, so that's why it wasn't built.

**Comment by artem-shaporenko** [comment]
it'll be merged later
