### ISSUE TITLE
samples: consider adding O_CLOEXEC if code can be used as a library or plugin

### ISSUE THREAD

**Issue by dvrogozh** [Intel-Media-SDK/MediaSDK#794]
Please, consider the following:
* Add 'e' for fopen (O_CLOEXEC for open) in multithreaded libraries and/or plugins
* Avoid std::fstream in multithreaded applications

**Comment by egorovdanil** [comment]
@dvrogozh I talked with @onabiull . He believes this is a low-level flag, and we do not need it.
[https://mail.gnome.org/archives/gtk-devel-list/2015-March/msg00038.html](https://mail.gnome.org/archives/gtk-devel-list/2015-March/msg00038.html)

**Comment by egorovdanil** [comment]
We do not test samples on fork-workflow.
