### ISSUE TITLE
can mediasdk support Geminilake?

### ISSUE THREAD

**Issue by malei1987** [Intel-Media-SDK/MediaSDK#798]
i use（Intel） NUC7PJYH j5005,  centos7.4 os , mediasdk can not work ok?  i see MediaSDK 2018 Q3.0 only support  Broadwell, Skylake, Kabylake, Coffeelake, Icelake and Apollo Lake families. i want to known if  it support Geminilake(j5005)

**Comment by dmitryermilov** [comment]
Hi,

Officially Gemini Lake is not supported. We don't validate such systems. 
On the other hand, Gemini Lake is a low power version of Kaby Lake. It has GPU media support. Moreover Windows versions of media driver and MediaSDK support Gemini Lake.  Please address the question about Gemini Lake support at https://github.com/intel/media-driver/. If driver start supporting it, MediaSDK will also do.

**Comment by malei1987** [comment]
> Hi,
> 
> Officially Gemini Lake is not supported. We don't validate such systems.
> On the other hand, Gemini Lake is a low power version of Kaby Lake. It has GPU media support. Moreover Windows versions of media driver and MediaSDK support Gemini Lake. Please address the question about Gemini Lake support at https://github.com/intel/media-driver/. If driver start supporting it, MediaSDK will also do.

**Comment by malei1987** [comment]
> Hi,
> 
> Officially Gemini Lake is not supported. We don't validate such systems.
> On the other hand, Gemini Lake is a low power version of Kaby Lake. It has GPU media support. Moreover Windows versions of media driver and MediaSDK support Gemini Lake. Please address the question about Gemini Lake support at https://github.com/intel/media-driver/. If driver start supporting it, MediaSDK will also do.

thanks so much, i will try new media-dirver.

**Comment by zcwang** [comment]
Hi All,
Does MSDK 19.4.0 (or the latest upstream of MSDKr) support GLK in Linux?
https://github.com/Intel-Media-SDK/MediaSDK/releases/tag/intel-mediasdk-19.4.0

Thanks!
Gary
