### ISSUE TITLE
[Question] HEVC 10bit decode support

### ISSUE THREAD

**Issue by codeathon** [Intel-Media-SDK/MediaSDK#8]
The open source LibVA from 01.org does not support HEVC 10bit HW decode on SKL. Does the Media SDK provide that support for SKL? I was able to get 8bit fixed function HEVC decode going with the 2017 SDK. Want to understand what is supported for the 10bit decode. Is it Software only or is it a hybrid implementation?

What about KBL support for 10bit fixed function HEVC decode in the latest SDK?

**Comment by VladimirPlichkoIntel** [comment]
Hi Rohit, thanks for your questions.

There is no 10bit HEVC support on Skylake hardware and we have no immediate plans to support Kabylake in the Media Server Studio or respective open source Media SDK version.

I'm not aware of any Intel graphics-accelerated 10bit HEVC decode solutions, but there is a number of the 10bit encoders from the leading compression technology vendors optimized for Intel, few examples are:
Beamr: http://media2.beamrvideo.com/pdf/Beamr_Intel_NAB_2017_PR.pdf
GigPeak: http://www.gigpeak.com/press-release/gigpeak-to-demonstrate-industry-first-encoding-solution-at-nab-2017/
Ittiam: http://www.ittiam.com/newsroom/news/2017-2/ittiam-hpe-announce-highly-efficient-scalable-hevc-hdr10-solutions-nab-2017/

Let me know if you have any other questions.

BR,
Vladimir Plichko, Intel
