### ISSUE TITLE
video wall issue of sample_multi_transcode

### ISSUE THREAD

**Issue by bbao3** [Intel-Media-SDK/MediaSDK#803]
Hi,
I installed the latest 18.3 media SDK together with 18.3 media driver from https://github.com/intel/media-driver/tree/intel-media-18.3, and found the sample_multi_transcode can not run correctly in video wall mode: it will only show the last row of the content, and all the rows on top of last one will be blank.
The issue can be replicated by: "**_./sample_multi_transcode -par -64_4k_DP.par_**" or "**_./sample_multi_transcode -par -64_1080_DP.par_**".
And further debugging shows if change the height of the picture a little bit, the whole picture can be seen, but the performance is very slow. The command is "**_./sample_multi_transcode -par -64_4k_DP_2.par_**" or "**_./sample_multi_transcode -par -64_1080_DP_2.par_**".

**Comment by bbao3** [comment]
Upload my par files here.
[parfiles.zip](https://github.com/Intel-Media-SDK/MediaSDK/files/2503952/parfiles.zip)

**Comment by alariono** [comment]
Hello @bbao3,
Related to performance… Which HW do you use? Is it Atom base (like APL family) or Core (like SKL, KBL)
Try following:
1. Increase “-async 1” => “-async 3”
2. Use Tiles in VPP Composition (because you use rectangles). See attached par files as example.
[64_1080p_DP_2.Tiles.par.txt](https://github.com/Intel-Media-SDK/MediaSDK/files/2510913/64_1080p_DP_2.Tiles.par.txt)

**Comment by bbao3** [comment]
Hi Alariono,
Thank you for the reply. I tested on SKL, APL and CFL three platforms, all of them can replicate the issue.
I've tried your new Tile based par file, but still failed. The last line should remove the -vpp_comp_tile_id parameter.

Can you please do a local replication and let me know if I miss anything? thank you.

Regards,
Bruce

**Comment by bbao3** [comment]
BTW, all these three platforms (APL, SKL, CFL) I am using Ubuntu 16.04 with 4.18 kernel.

**Comment by IlyaSergeyev** [comment]
Flag to disable colorfill in TiledVideWall added. Platform dependency code removed, 
VA_PROC_PIPELINE_SUBPICTURES and VA_FILTER_SCALING_HQ are works with APL, CFL, SKL now.

**Comment by alariono** [comment]
Fix merged into master
https://github.com/Intel-Media-SDK/MediaSDK/pull/825

**Comment by bbao3** [comment]
Thank you so much! I've confirmed it had been fixed on SKL.
