### ISSUE TITLE
What is minimal required gtest/gmock version?

### ISSUE THREAD

**Issue by dvrogozh** [Intel-Media-SDK/MediaSDK#836]
I was trying to build mediasdk on CentOS 7 with:
`cmake -DBUILD_TESTS=ON -DRUN_TESTS=ON`
And used system available versions of gtest/gmock. I did not get any configuration issues, but got compile issues:
```
In file included from /usr/include/gmock/gmock-generated-function-mockers.h:43:0,
                 from /usr/include/gmock/gmock.h:61,
                 from /home/dvrogozh/git/github/MediaSDK/tests/mfx_dispatch/linux/mfx_dispatch_test_mocks.h:26,
                 from /home/dvrogozh/git/github/MediaSDK/tests/mfx_dispatch/linux/mfx_dispatch_test_main.h:25,
                 from /home/dvrogozh/git/github/MediaSDK/tests/mfx_dispatch/linux/mfx_dispatch_test_cases_plugins.cpp:21:
/home/dvrogozh/git/github/MediaSDK/tests/mfx_dispatch/linux/mfx_dispatch_test_fixtures.h: In member function ‘void DispatcherPluginsTest::SetupForGoodLibInit(MockCallObj&)’:
/home/dvrogozh/git/github/MediaSDK/tests/mfx_dispatch/linux/mfx_dispatch_test_fixtures.h:91:9: error: invalid use of member function ‘testing::internal::MockSpec<void*(const char*, int)>& MockCallObj::gmock_dlopen(const testing::Matcher<const char*>&, const testing::Matcher<int>&)’ (did you forget the ‘()’ ?)
         EXPECT_CALL(mock, dlopen).Times(AtLeast(1)).WillRepeatedly(Return(MOCK_DLOPEN_HANDLE));
         ^
/home/dvrogozh/git/github/MediaSDK/tests/mfx_dispatch/linux/mfx_dispatch_test_fixtures.h:92:9: error: invalid use of member function ‘testing::internal::MockSpec<void*(void*, const char*)>& MockCallObj::gmock_dlsym(const testing::Matcher<void*>&, const testing::Matcher<const char*>&)’ (did you forget the ‘()’ ?)
         EXPECT_CALL(mock, dlsym).Times(AtLeast(1)).WillRepeatedly(Invoke(&mock, &MockCallObj::EmulateAPI));
         ^
/home/dvrogozh/git/github/MediaSDK/tests/mfx_dispatch/linux/mfx_dispatch_test_fixtures.h:93:9: error: invalid use of member function ‘testing::internal::MockSpec<mfxStatus(mfxInitParam, _mfxSession**)>& MockCallObj::gmock_MFXInitEx(const testing::Matcher<mfxInitParam>&, const testing::Matcher<_mfxSession**>&)’ (did you forget the ‘()’ ?)
         EXPECT_CALL(mock, MFXInitEx).Times(AtLeast(1)).WillRepeatedly(DoAll(SetArgPointee<1>(MOCK_SESSION_HANDLE), Return(MFX_ERR_NONE)));
         ^
/home/dvrogozh/git/github/MediaSDK/tests/mfx_dispatch/linux/mfx_dispatch_test_fixtures.h:94:9: error: invalid use of member function ‘testing::internal::MockSpec<mfxStatus(_mfxSession*, int*)>& MockCallObj::gmock_MFXQueryIMPL(const testing::Matcher<_mfxSession*>&, const testing::Matcher<int*>&)’ (did you forget the ‘()’ ?)
         EXPECT_CALL(mock, MFXQueryIMPL).Times(AtLeast(1)).WillRepeatedly(Return(MFX_ERR_NONE));
         ^
/home/dvrogozh/git/github/MediaSDK/tests/mfx_dispatch/linux/mfx_dispatch_test_fixtures.h:95:9: error: invalid use of member function ‘testing::internal::MockSpec<mfxStatus(_mfxSession*, mfxVersion*)>& MockCallObj::gmock_MFXQueryVersion(const testing::Matcher<_mfxSession*>&, const testing::Matcher<mfxVersion*>&)’ (did you forget the ‘()’ ?)
         EXPECT_CALL(mock, MFXQueryVersion).Times(AtLeast(1)).WillRepeatedly(Invoke(&mock, &MockCallObj::ReturnEmulatedVersion));
```

I guess system available gmock/gtest version is not enough:
```
[dvrogozh@dvrscl build]$ yum info gtest | grep Version
Version     : 1.6.0
[dvrogozh@dvrscl build]$ yum info gmock | grep Version
Version     : 1.6.0
```

We need to fix gtest/gmock configuration issues. At least we need to check minimal required version (and I am not sure whether we check gmock at all). And probably we need to consider puling in gtest/gmock sources inside as other projects do.

**Comment by uartie** [comment]
When we integrated gtest (release-1.8.0) into libva-utils, intel-vaapi-driver and libyami we had weird issues with system packaged gtest.  Also, some distros do not provide gtest packages.  IIRC, gtest docs indicate that it should be compiled on a per-project basis, otherwise you may see strange behavior with a shared installation.  That is, user-configurable #define's are shared between public headers and compilation units... and you don't know what those were set to when the library was compiled.  Hence, directly pulling in and tracking the source inside the project and compiling it would be the ideal thing to do.

**Comment by dmitry-gurulev** [comment]
J4I, one of the recommended approach is [ExternalProject_Add], see details at [Generic Build Instructions](https://github.com/google/googletest/blob/master/googletest/README.md)

**Comment by vshampor** [comment]
https://github.com/Intel-Media-SDK/MediaSDK/pull/842

Somehow, my CMake 2.8.12.2 won't configure it:

`[100%] Built target googletest
CMake Error at /usr/share/cmake/Modules/WriteBasicConfigVersionFile.cmake:39 (message):
  No VERSION specified for WRITE_BASIC_CONFIG_VERSION_FILE()
Call Stack (most recent call first):
  /usr/share/cmake/Modules/CMakePackageConfigHelpers.cmake:152 (write_basic_config_version_file)
  build/googletest-src/googletest/CMakeLists.txt:96 (write_basic_package_version_file)
`

CMake 3.12.1 works well, though.

**Comment by dvrogozh** [comment]
@uartie : can you, please, look into #842? Will this trick do? It adds automated git-clone fetching for gtest within mediasdk cmake build procedure.
