### ISSUE TITLE
HEVC 10 bit decoder is broken with the latest driver

### ISSUE THREAD

**Issue by dmitryermilov** [Intel-Media-SDK/MediaSDK#859]
driver: e0227fae06ccf9aaadd16543fd84817b485e1986
msdk: b284aaf032d130256dd57301361aaa39208f5b0c

```

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), Init, m_pmfxDEC->Init failed at /localdisk/bb/worker/build-api-next/build_dir/repos/MediaSDK/samples/sample_decode/src/pipeline_decode.cpp:437

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), main, Pipeline.Init failed at /localdisk/bb/worker/build-api-next/build_dir/repos/MediaSDK/samples/sample_decode/src/sample_decode.cpp:666
plugin_loader.h :212 [INFO] MFXBaseUSER_UnLoad(session=0x0x55647effa1e0), sts=0

```

**Comment by dmitryermilov** [comment]
It's broken since this commit : https://github.com/intel/media-driver/commit/d40ce38d40da34e06fd2003d31b9be99d323046d

**Comment by dmitryermilov** [comment]
+ @XinfengZhang, + @xhaihao

**Comment by xhaihao** [comment]
@dmitryermilov I am still experiencing this issue with the latest media driver and msdk

media driver: e0227fae06ccf9aaadd16543fd84817b485e1986
msdk: 7ca2c5bf72eb822b0fe32b3a1680abbce1d8fe51

**Comment by dmitryermilov** [comment]
Hi @xhaihao ,

I'm sure it worked fine with the fix. Let me double check tomorrow.

**Comment by xhaihao** [comment]
@dmitryermilov yes, it works.
The install path for samples was changed from {prefix}/samples/ to {prefix}/share/mfx/samples, but I still used the stale one for testing, sorry for the noise.

**Comment by dmitryermilov** [comment]
Ahh. I see. Thanks for confirmation!
