### ISSUE TITLE
30-40% performance regression on GT2 machines compared to old MediaSDK

### ISSUE THREAD

**Issue by eero-t** [Intel-Media-SDK/MediaSDK#869]
Test setup:
* Ubuntu 18.04
* BDW GT2 or SKL GT2 HW
* drm-tip git kernel from FDO
* git versions of gmmlib, libva, media-driver, MediaSDK from Github Intel repos
  * instrumentation & trace options are *not* enabled

Test-case:
* Input file: AVC, 1280x720, Progressive, Frame rate: 29.97, Bit rate: 10 Mbps
* Output: AVC, 352x240, Progressive, Frame rate: 15, Bit rate: 800 Kbps
* VPP: RS, FRC (dither)
* Command line:
`sample_multi_transcode  -o::h264 <output>.h264 -b 800 -u 4 -n 600 -i::h264 <input>.h264 -async 1 -hw  -w 352 -h 240 -FRC::PT`

Expected outcome:
* performance same (or better) as with the proprietary MediaSDK from (early) 2017
* both when single and multiple streams are used

Actual outcome:
* 30-40% lower performance on GT2 devices

With SKL GT3e:
* Performance drops 10-20% with a single stream
* Performance increases 3-5% with ~50 streams

**Comment by lizhong1008** [comment]
"old MediaSDK", if you were using MediaSeverStudio, could you please give which version of MediaServerStudio?

If you were using open source MSDK, could you please help to use git bisect to find the regression commit?

**Comment by eero-t** [comment]
I don't exactly know what the old version is.  I think it's built from open source version, what was available around September 2017 (as files have such dates), but I think getting it working required some components also from the proprietary MediaSDK (issue tracker here also lists problems with that until end of 2017).

Performance of that is in the other few pipelines we've tested is about same as with the latest Git version of the open source MediaSDK stack, it's only this case where there's a noticeably change.

**Comment by eero-t** [comment]
intel_gpu_top (for i-g-t v1.23) reports following...

Old MediaSDK:
* 60% -> 85% Video pipeline (increases while it's running)
* 100% Render pipeline

New MediaSDK:
* 100% Video pipeline
* 60-70% Render pipeline

When looking at the RAPL reported power usage, old MediaSDK used slightly more power for UnCore, and 2x more power for CPU cores.

(With v4.20-rc kernel, CPU power usage of both increased significantly, so with git version of drm-tip kernel, the difference itself isn't anymore 2x.)

Potential conclusion one could draw from these is that MediaSDK moved activity from CPU to video pipeline, but this particular use-case bottlenecks more on Video pipeline than it did on CPU, at least on GT2.

(When looking at the OA HW counters counters for new MediaSDK Render pipeline with GpuTop, Render pipeline / compute utilization spikes a bit more for few seconds at the beginning, so I guess initially Video engine isn't "full".)

**Comment by eero-t** [comment]
> If you were using open source MSDK, could you please help to use git bisect to find the regression commit?

Not if it regressed before everything started to build fine without patching/hacking, or if it doesn't build on Ubuntu 18.04.  Aren't you able to reproduce the perf drop?

Btw. which components could affect this?  MediaSDK & media-driver?  Or also libva and gmmlib?

**Comment by eero-t** [comment]
> With v4.20-rc kernel, CPU power usage of both increased significantly, so with git version of drm-tip kernel, the difference itself isn't anymore 2x

Filed kernel bug about this regression: https://bugs.freedesktop.org/show_bug.cgi?id=108700

> Potential conclusion one could draw from these is that MediaSDK moved activity from CPU to video pipeline, but this particular use-case bottlenecks more on Video pipeline than it did on CPU, at least on GT2.

Potential other reasons for the changed load numbers:
* Some of the load was moved from Render compute to fixed Video pipeline
* Just the Video pipeline work increased

(And CPU load dropped just because CPU needs to wait more when feeding Video batches)

**Comment by onabiull** [comment]
With several performance-improvement patches introduces last year and upstream of many kernel patches which affect media performance, we consider this as closed. Please feel free to reopen, or better, submit new issue, if there are any noticeable gap.

**Comment by eero-t** [comment]
I haven't noticed any performance improvements during this year in this test-case (there was one noticeable perf regression, that was later fixed) i.e. since I started measuring it.

Note that I'm using nowadays -async 4 instead of -async 1 which has much better perf.   I don't have old MediaSDK anymore to test -async 4 with it, so closing this is fine.
