### ISSUE TITLE
Build failures with GCC 6

### ISSUE THREAD

**Issue by vanvugt** [Intel-Media-SDK/MediaSDK#9]
The code fails to build with modern g++-6/gcc-6 releases. I had to revert to gcc-5/g++5 to make progress.

**Comment by GoAlexander** [comment]
@vanvugt Can you share your output?

**Comment by vanvugt** [comment]
I can't, sorry. It's been two months and I am no longer attempting to use MSDK. But it's a trivial problem description so no doubt someone will fix it, if not already.

**Comment by GoAlexander** [comment]
Ok, but which version of gcc did you try exactly? 6.4? I want to try to reproduce your problem.

**Comment by vanvugt** [comment]
It was Ubuntu 17.10 at the time, so on 14 Jun I estimate that would have been 6.3 ...
https://launchpad.net/ubuntu/artful/+source/gcc-6

**Comment by GoAlexander** [comment]
Thanks @vanvugt for your feedback.
Before I waited your answer I tried to reproduce your bug with fresh compiled from source gcc 6.4 - building *successfully* finished.

I will try to reproduce it with gcc version 6.3

**Comment by ishmael1985** [comment]
Maybe this commit had something to do with this :)
https://github.com/Intel-Media-SDK/MediaSDK/pull/11

**Comment by GoAlexander** [comment]
@ishmael1985 thanks for the comment.

About gcc 6.4:  
I understood that I installed latest version of gcc not correct so cmake used my 4.8.5 version of gcc.
I will set up my environment correctly and then will try to reproduce your problem again.

**Comment by GoAlexander** [comment]
@vanvugt We have finally reproduced your bug with gcc 6. 
That was errors with deprecated `auto_ptr`. Isn`t it?  
  
We will think about possible way of fixing it.

**Comment by vanvugt** [comment]
No hurry. We have decided we don't need MSDK support in Ubuntu any time soon.

**Comment by adydychk** [comment]
We switched to gcc 6.3.1 in our CI. @onabiull I think we can close this issue if @vanvugt is ok with it :)

**Comment by adydychk** [comment]
@vanvugt Thanks for your feedback!
