### ISSUE TITLE
Sample parameters are not in the same style

### ISSUE THREAD

**Issue by artem-shaporenko** [Intel-Media-SDK/MediaSDK#900]
https://github.com/Intel-Media-SDK/MediaSDK/blob/0e24aefb6076c73526cda71caac65436e3cbac3a/samples/sample_multi_transcode/src/transcode_utils.cpp#L1949

"-extbrc::on", but "-ExtBrcAdaptiveLTR:on", need to align to the same style to simplify .

**Comment by daleksan** [comment]
won't fix
