### ISSUE TITLE
VA RT format and fourcc are mixed in MediaSDK

### ISSUE THREAD

**Issue by xhaihao** [Intel-Media-SDK/MediaSDK#906]
When creating a surface with fourcc setting to VA_FOURCC_P010, the format is expected to VA_RT_FORMAT_YUV420_10. However the format is actually set to VA_FOURCC_P010 in MSDK.

**Comment by xhaihao** [comment]
Below is the related code in libmfx_allocator_vaapi.cpp

197                 attrib.value.value.i = va_fourcc;                                                                                                                                                                                    
198                 format               = va_fourcc;

**Comment by egorovdanil** [comment]
The problem no longer reproduce.
