### ISSUE TITLE
dec/enc failed on centos 7

### ISSUE THREAD

**Issue by YaboWei** [Intel-Media-SDK/MediaSDK#92]
Hi,
I try to build msdk and run samples on CentOS 7, encode sample and decode sample both failed:

- encode failed
`sample_encode h264 -i ~/assassin_st4_1080p30fps.flv.yuv -o out.264 -w 1920 -h 1080 -hw
[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), Init, m_mfxSession.InitEx failed at /home/web_server/weiyabo/msdk/samples/sample_encode/src/pipeline_encode.cpp:1242

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), main, pPipeline->Init failed at /home/web_server/weiyabo/msdk/samples/sample_encode/src/sample_encode.cpp:1174`

- decode failed
`sample_decode h264 -i ~/assassin_st4_1080p30fps.264  -hw
[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), Init, m_mfxSession.Init failed at /home/web_server/weiyabo/msdk/samples/sample_decode/src/pipeline_decode.cpp:293

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), main, Pipeline.Init failed at /home/web_server/weiyabo/msdk/samples/sample_decode/src/sample_decode.cpp:667`

environment：
CPU：E3-1585 v5
OS：CentOS 7.4
kernel：upgrade to 4.15.7-1.el7.elrepo.x86_64

**Comment by lizhong1008** [comment]
Add "libmfxhw64_d.so" to lib search path should can fix your issue: 
export LD_LIBRARY_PATH= "${LIBMSDK_PREFIX}/lib/lin_x64/:$LD_LIBRARY_PATH"
But would better MSDK can provide a patch (or update the wiki page?) to fix this issue.

**Comment by YaboWei** [comment]
@lizhong1008 
thanks
My problem resolved!

**Comment by colin130** [comment]
> @lizhong1008
> thanks
> My problem resolved!

Hi, How did you solve this problem?
