### ISSUE TITLE
H264 Compress problem with OpenCV

### ISSUE THREAD

**Issue by yiyunluo07** [Intel-Media-SDK/MediaSDK#944]
##### System information (version)

- OpenCV => 3.4.3-openvino
- Operating System / Platform => Linux Ubuntu 16.04

##### Detailed description
Hello, I'm using Intel Up-Board Squared to develop a programm which needs to compress video by using INTEL_MFX apiPreference to speed up the process.
I've compiled OpenCV with Intel Media SDK backend, and the compiler didn't give any errors to my code. 
 `int fourcc = cv::VideoWriter::fourcc('H','2','6','4');`
 `cv::VideoWriter writer("filename.mp4", cv::INTEL_MFX, fourcc, 30, cv::Size(1280,720), true);`
What interesting is,  when I run the code, it will show a line with `MFX: unsupported extension: /dev/video0`, but the video could be written in a new file.
The video file which was written is very large. A video about 30 seconds can be 70 MB large. I think that the video has been written without compressing with H264. 

I also installed Intel Quick Sync Video for ffmpeg.
```bash
up-board@upboard-UP-APL01:~$ ffmpeg -codecs | grep 'qsv'ffmpeg version n3.4-dev-2711-g587fada Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 20160609
  configuration: --enable-libmfx
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
 DEV.LS h264                 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (decoders: h264 h264_v4l2m2m h264_qsv h264_vdpau h264_cuvid ) (encoders: h264_nvenc h264_qsv h264_v4l2m2m h264_vaapi nvenc nvenc_h264 )
 DEV.L. hevc                 H.265 / HEVC (High Efficiency Video Coding) (decoders: hevc hevc_qsv hevc_cuvid ) (encoders: nvenc_hevc hevc_nvenc hevc_qsv hevc_vaapi )
 DEV.L. mpeg2video           MPEG-2 video (decoders: mpeg2video mpegvideo mpegvideo_vdpau mpeg2_v4l2m2m mpeg2_qsv mpeg2_cuvid ) (encoders: mpeg2video mpeg2_qsv mpeg2_vaapi )
 D.V.L. vc1                  SMPTE VC-1 (decoders: vc1 vc1_vdpau vc1_qsv vc1_v4l2m2m vc1_cuvid )
 DEV.L. vp8                  On2 VP8 (decoders: vp8 vp8_v4l2m2m vp8_cuvid vp8_qsv ) (encoders: vp8_v4l2m2m vp8_vaapi )
```
I think that it's correctly installed.
Is there anyone who has experience with Media SDK backend for OpenCV? Hope someone can help me.

Greetings,
Yiyun

**Comment by yiyunluo07** [comment]
Hello, I have solved the problem by changing a file of opencv for mfx_writer: /modules/videoio/src/cap_mfx_writer.cpp

After I changed the code params.mfx.TargetKbps = (mfxU16)cvRound(frameSize.area() * fps / 500); to params.mfx.TargetKbps = (mfxU16)cvRound(**4000000**);, the video file which was written by the VideoWriter has now only 15 MB large for 1 min instead of 300 MB large for 1 min. (The resolution is Full HD.)

I also tested with other bit rates and I post the results here: (with Full HD)
With 10000 for 1 min 70MB
With 1000000 for 1 min 118MB
With 4000000 for 1 min 15,2MB
With 8000000 for 1 min 36MB

**Comment by Odianosen25** [comment]
@yiyunluo07,

I am trying to run the following

```
import cv2
cap = cv2.VideoCapture("/config/test-high-res2.mp4", cv2.CAP_INTEL_MFX)
```

But getting
```
libva info: VA-API version 1.8.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /usr/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_8
libva info: va_openDriver() returns 0
MFX: Unsupported extension: /config/test-high-res2.mp4
```
Please any assistance on how to solve this?

Regards

**Comment by brmarkus** [comment]
The MediaSDK "backend" is not a media-player, but expects local files with a file extension of e.g. "*.h264" or "*.h265", i.e. a local file as an elementary stream, which is read-in and provided "as-is" to MediaSDK and libva. You could use e.g. a gstreamer pipeline with MediaSDK-plugins.

**Comment by Odianosen25** [comment]
@brmarkus, 

Ah now that makes so much more sense, thanks for the clarification. Now I have decided to make use of the gstreamer plugin, but I am failing to figure out how to compile the gstreamer mediasdk plugins into my mediasdk build (not like I did the build myself anyway), but still can't figure it out. As simply installing the bad plugins doesn't seem to cut it

Regards
