### ISSUE TITLE
VP8 encode  support in MediaSDK

### ISSUE THREAD

**Issue by xhaihao** [Intel-Media-SDK/MediaSDK#947]
According to https://github.com/intel/media-driver#supported-codecs, VP8 encode is supported.  I also see vp8e_hw in the supported plugin list in the help doc for sample_encode, however I failed to find the corresponding plugin info in plugins.cfg, could you confirm whether msdk supports vp8 encoding? If not, could you add support for VP8 encode in MediaSDK?

**Comment by xhaihao** [comment]
Any comment?

**Comment by artem-shaporenko** [comment]
@xhaihao MSDK Doesn't support VP8 at a moment

**Comment by lizhong1008** [comment]
@artem-shaporenko Do you have any plan to support it?

**Comment by zhoub** [comment]
Bump, this is critical.

**Comment by dvrogozh** [comment]
@onabiull : what are our plans around that?

**Comment by onabiull** [comment]
Unfortunately currently it is hard to justify efforts on enabling and validating VP8e. For now this not going to be implemented.
