### ISSUE TITLE
How to dump log message in msdk libarbary at runtime?

### ISSUE THREAD

**Issue by lizhong1008** [Intel-Media-SDK/MediaSDK#948]
Dumping log message is quite benefit  to report issue and debug. 
I see there is an option to dump log message of samples. E.g:  sample_encode -dump fileName 

Is there any option (or other configuration such as environment variable  setting) to dump log message in MSDK core library at run time?

**Comment by lizhong1008** [comment]
Found the log at /tmp/mfxlib.log. Looks like it is hard-coded.

**Comment by daleksan** [comment]
@lizhong1008 would you mind closing this issue?

**Comment by fulinjie** [comment]
@fulinjie useful tool :D.
