### ISSUE TITLE
ffmpeg mjpeg encode: set FrameType to MFX_FRAMETYPE_I 

### ISSUE THREAD

**Issue by fulinjie** [Intel-Media-SDK/MediaSDK#970]
In mjpeg_qsv: 
pict_type was decided by bs->FrameType and it equals AV_PICTURE_TYPE_NONE.

In native mjpeg encode:
pict_type was set to AV_PICTURE_TYPE_I in avcodec_encode_video2() after calling ff_mpv_encode_picture();

So, I think it may be better to set bs Frame Type to MFX_FRAMETYPE_I in MSDK than setting pict_type to AV_PICTURE_TYPE_NONE in ff_qsv_encode()?

Details in https://trac.ffmpeg.org/ticket/7593

**Comment by dvrogozh** [comment]
@Alexandr-Konovalov: I thought, maybe you will take a look since you work with jpeg now?
