### ISSUE TITLE
FindOpenCL.cmake will not find the right intel opencl driver

### ISSUE THREAD

**Issue by liyuming1978** [Intel-Media-SDK/MediaSDK#98]
I change the cmake to 

find_path( OPENCL_INCLUDE CL/opencl.h PATHS /opt/intel/opencl/include /usr/include NO_DEFAULT_PATH)
find_library( OPENCL_LIBRARY libOpenCL.so PATHS /opt/intel/opencl/ /usr/lib NO_DEFAULT_PATH)

it's ok now.  since opencl.h and libopencl.so also exist in /usr folder

**Comment by adydychk** [comment]
@liyuming1978 Is your problem still relevant?
We have some documentation how to install it [here](https://github.com/Intel-Media-SDK/infrastructure#deploy-build-box-worker-buildbot):

```
sudo yum install libpciaccess libpciaccess-devel opencl-headers

#Enable epel repository
sudo yum install gtest gtest-devel ocl-icd ocl-icd-devel

#Compile OpenCL from these cources: https://github.com/intel/compute-runtime/releases/tag/2018ww18-010782
#By using these instructions: https://github.com/intel/compute-runtime/blob/master/documentation/BUILD_Centos.md
sudo rpm -ihv intel-opencl-1.0-0.x86_64-igdrcl.rpm
```

**Comment by liyuming1978** [comment]
fix it with NO_DEFAULT_PATH

**Comment by adydychk** [comment]
Issue will be tested. Thanks for suggestion

**Comment by ekislyuk** [comment]
No interest from customer for more than a year - closing for now. In case of facing  any new issues-feeel free to open new issue against  most fresh release
