### ISSUE TITLE
LA_ICQ creates output twice as big as ICQ

### ISSUE THREAD

**Issue by andreasunterhuber** [Intel-Media-SDK/MediaSDK#989]
### Issue
BRC LA_ICQ creates files **twice** as big as BRC ICQ with same quality settings. 

### How to proof
The current version (master branch) of MediaSDK does create the following output with sample_encode tool: 

* **ICQ**
   * `sample_encode h264 -i soccer.yuv -o encode-test-icq.h264 -w 704 -h 576 -icq 30 -f 60`
   * Output filesize: _2.1 MB_
   * [Download output file](https://we.tl/t-ci3ao8YV5T)
* **LA_ICQ**
   *  `sample_encode h264 -i soccer.yuv -o encode-test-laicq.h264 -w 704 -h 576 -icq 30 -lad 100 -f 60`
   * Output filesize: _5.1 MB_
   * [Download output file](https://we.tl/t-CJlUB88em7)

Download input file: [soccer.yuv](https://we.tl/t-P2HOwiWFBU)
The same behavior is mesaured with ffmpeg.

## Wanted behavior
File size not twice as big just because of using LA_ICQ bitrate control rate.

### Test environment
* Latest master checkout [libva](https://github.com/intel/libva)
* Latest master checkout [libva-utils](https://github.com/intel/libva-utils)
* Latest master checkout [media-driver](https://github.com/intel/media-driver)
* Latest master checkout [gmmlib](https://github.com/intel/gmmlib)
* Latest master checkout [MediaSDK](https://github.com/Intel-Media-SDK/MediaSDK)

**Comment by andreasunterhuber** [comment]
@dvrogozh just as quick feedback. Even with #969 it does not change the behavior.

**Comment by andreasunterhuber** [comment]
@dvrogozh PING ;) is there any update?

**Comment by dvrogozh** [comment]
Russia is on big holidays. Will be back in a couple of days. I will ping folks once they are back to look into these issues.

**Comment by andreasunterhuber** [comment]
@dvrogozh PING 🔔

**Comment by dvrogozh** [comment]
@ogolikov : could you, please, comment on the difference between ICQ and ICQ_LA modes?
